export const fixtures = {
    'Get category transformer Возвращает трансформированную категорию': {
        CATEGORY_ATTRIBUTES: {
            urlPart: 'news',
            service: 'autoru',
            title: 'Новости',
            draftTitle: 'Новости (draft)',
            shortTitle: 'Ньюс',
            draftShortTitle: 'Ньюс (draft)',
            isArchived: false,
            metaTitle: 'Новости (мета тайтл)',
            metaDescription: 'Новости (мета дескрипшен)',
            blocks: [],
            draftBlocks: [],
            createdAt: '2021-06-03T16:25:54.000Z',
            lastEditedAt: '2021-06-03T16:25:54.000Z',
        },
    },
    'Get category transformer Возвращает трансформированную категорию с тегами': {
        CATEGORY_ATTRIBUTES: {
            urlPart: 'news',
            service: 'autoru',
            title: 'Новости',
            draftTitle: 'Новости (draft)',
            shortTitle: 'Ньюс',
            draftShortTitle: 'Ньюс (draft)',
            isArchived: false,
            metaTitle: 'Новости (мета тайтл)',
            metaDescription: 'Новости (мета дескрипшен)',
            blocks: [],
            draftBlocks: [],
            createdAt: '2021-06-03T16:25:54.000Z',
            lastEditedAt: '2021-06-03T16:25:54.000Z',
        },
        TAG_ATTRIBUTES_1: {
            urlPart: 'conceptcar',
            service: 'autoru',
            title: 'Концепты',
            draftTitle: 'Концепты',
            createdAt: '2021-06-03T16:26:11.000Z',
            lastEditedAt: '2021-06-03T16:26:11.000Z',
        },
        TAG_ATTRIBUTES_2: {
            urlPart: 'podcast',
            service: 'autoru',
            title: ' Подкаст',
            draftTitle: ' Подкаст',
            createdAt: '2021-06-03T16:26:24.000Z',
            lastEditedAt: '2021-06-03T16:26:24.000Z',
        },
    },
    'Get category transformer Может возвращать трансформированный черновик категории': {
        CATEGORY_ATTRIBUTES: {
            urlPart: 'news',
            service: 'autoru',
            title: 'Новости',
            draftTitle: 'Новости (draft)',
            shortTitle: 'Ньюс',
            draftShortTitle: 'Ньюс (draft)',
            isArchived: false,
            metaTitle: 'Новости (мета тайтл)',
            metaDescription: 'Новости (мета дескрипшен)',
            blocks: [],
            draftBlocks: [],
            createdAt: '2021-06-03T16:25:54.000Z',
            lastEditedAt: '2021-06-03T16:25:54.000Z',
        },
    },
    'Get category transformer Может возвращать категорию с трансформированными блоками': {
        CATEGORY_ATTRIBUTES: {
            urlPart: 'news',
            service: 'autoru',
            title: 'Новости',
            draftTitle: 'Новости (draft)',
            shortTitle: 'Ньюс',
            draftShortTitle: 'Ньюс (draft)',
            isArchived: false,
            metaTitle: 'Новости (мета тайтл)',
            metaDescription: 'Новости (мета дескрипшен)',
            blocks: [{ type: 'text', text: 'raw block' }],
            draftBlocks: [{ type: 'text', text: 'raw draft block' }],
            createdAt: '2021-06-03T16:25:54.000Z',
            lastEditedAt: '2021-06-03T16:25:54.000Z',
        },
    },
    'Get category transformer Может возвращает категорию с трансформированными черновыми блоками': {
        CATEGORY_ATTRIBUTES: {
            urlPart: 'news',
            service: 'autoru',
            title: 'Новости',
            draftTitle: 'Новости (draft)',
            shortTitle: 'Ньюс',
            draftShortTitle: 'Ньюс (draft)',
            isArchived: false,
            metaTitle: 'Новости (мета тайтл)',
            metaDescription: 'Новости (мета дескрипшен)',
            blocks: [{ type: 'text', text: 'raw block' }],
            draftBlocks: [{ type: 'text', text: 'raw draft block' }],
            createdAt: '2021-06-03T16:25:54.000Z',
            lastEditedAt: '2021-06-03T16:25:54.000Z',
        },
    },
};
