source 'https://github.com/CocoaPods/Specs.git'
source 'https://stash.desktop.dev.yandex.net/scm/mcp/mobile-cocoa-pod-specs.git'

project 'YandexGeoToolboxTestApp'

platform :ios, '7.0'
inhibit_all_warnings!

def common_pods
    pod 'GoogleProtobuf'
    pod 'AFNetworking', '2.6.1'
    pod 'RaptureXML'
    pod 'Punycode-Cocoa'
    pod 'YXAccountManager'
    pod 'YXMetricaStartupClientIdentifier'
    pod 'YXLibraryMetricaAnalytics/YXAccountManager'
#    pod 'YandexMapKit', '13.69.11'
#    pod 'YandexDataSync', '9.1.0'

#    pod 'YandexMapKit', :git => 'https://knkiselyov@bitbucket.browser.yandex-team.ru/scm/~knkiselyov/yandexmapkit.git'
#    pod 'YandexDataSync', :git => 'https://knkiselyov@bitbucket.browser.yandex-team.ru/scm/~knkiselyov/yandexdatasync.git'
#    pod 'YandexRuntime', :git => 'https://knkiselyov@bitbucket.browser.yandex-team.ru/scm/~knkiselyov/yandexruntime.git'
end

target :YandexGeoToolboxTestApp do
    common_pods
end

target :YandexGeoToolboxTestAppTests do
    common_pods
    pod 'FBSnapshotTestCase/Core'
end
