source 'https://stash.desktop.dev.yandex.net/scm/mcp/mobile-cocoa-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

def common_pods
    pod 'YXPlatformDescription'
    pod 'YXMobileMetrica'
end

target 'MetroKitTestApp' do
    common_pods
end

target 'MetroKitTestAppDev' do
    common_pods
end
