CREATE TABLE `clients` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` int(10) unsigned NOT NULL DEFAULT '1',
  `product_id` smallint(5) unsigned NOT NULL,
  `country_id` int(10) unsigned NOT NULL,
  `region_id` int(10) unsigned NOT NULL,
  `city_id` int(10) unsigned NOT NULL,
  `ya_country_id` int(10) unsigned NOT NULL,
  `ya_region_id` int(10) unsigned NOT NULL,
  `ya_city_id` int(10) unsigned NOT NULL,
  `url` varchar(255) NOT NULL COMMENT 'Client''s site url',
  `email` varchar(70) NOT NULL,
  `responsible_manager_email` varchar(255) NULL DEFAULT NULL,
  `phone` bigint(20) unsigned NOT NULL COMMENT 'Client''s phone number',
  `phone_mask` varchar(10) NOT NULL COMMENT 'Client''s phone mask',
  `description` text NOT NULL COMMENT 'Client description',
  `logo` varchar(255) NOT NULL COMMENT 'Logo URL',
  `logosize` varchar(32) NOT NULL COMMENT 'Logo size',
  `comment` mediumtext NOT NULL COMMENT 'Comment about client (for managers only)',
  `is_agent` tinyint(1) unsigned NOT NULL,
  `agent_id` int(10) unsigned NOT NULL,
  `loader_id` int(10) unsigned NOT NULL,
  `origin` varchar(10) NOT NULL,
  `status` enum('new','active','inactive','deleted','freezed','waiting','stopped') DEFAULT 'inactive',
  `contact_name` varchar(255) NOT NULL,
  `fax` bigint(20) unsigned NOT NULL,
  `fax_mask` varchar(10) NOT NULL,
  `contract_version` enum('old','new') NOT NULL,
  `create_date` datetime NOT NULL,
  `first_activation_date` datetime DEFAULT NULL,
  `last_activation_date` datetime DEFAULT NULL,
  `is_agreement_accept` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'подтверждено ли пользовательское соглашение',
  `agreement_accept_date` datetime NOT NULL,
  `agreement_number` varchar(32) NOT NULL COMMENT 'Номер договора клиента',
  `post_index` varchar(6) NOT NULL,
  `adress` text NOT NULL,
  `contactname` varchar(255) NOT NULL,
  `is_suspected` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Является ли подозрительным по мнению spy',
  `first_moderated` tinyint(1) NOT NULL COMMENT 'Прошел первичную модерацию',
  `is_onmoderate` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_rejected` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_info` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_trademark` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_dealership` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_salons` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_onmoderate_properties` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_new` tinyint(1) unsigned NOT NULL,
  `is_new_info` tinyint(1) unsigned NOT NULL,
  `is_new_properties` tinyint(1) unsigned NOT NULL,
  `is_mounting` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `is_deleted` tinyint(1) unsigned NOT NULL,
  `is_freezed` tinyint(1) unsigned NOT NULL,
  `is_imported` tinyint(6) unsigned NOT NULL,
  `date_update` datetime NOT NULL,
  `id_1c` int(9) unsigned DEFAULT NULL,
  `id_clients` int(11) DEFAULT NULL,
  `id_agent_old` int(10) unsigned NOT NULL,
  `id_contacts_old` int(10) unsigned NOT NULL,
  `paid_with` datetime DEFAULT NULL,
  `paid_till` datetime DEFAULT NULL,
  `month_sum` int(11) DEFAULT '0',
  `use_office_tariff` int(1) unsigned NOT NULL DEFAULT '0',
  `use_premium_tariff` int(1) unsigned NOT NULL DEFAULT '0',
  `is_gold_partner` int(1) unsigned NOT NULL DEFAULT '0',
  `discard_agency_discount` int(1) unsigned DEFAULT NULL,
  `wallet_available` int(1) unsigned NOT NULL DEFAULT '1',
  `is_self_registered` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `auto_prolong` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `use_office7_v2` tinyint(1) NOT NULL DEFAULT '1',
  `can_switch_v2` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `company_id` int(11) NOT NULL COMMENT 'группы компаний',
  `new_billing_available` tinyint(1) DEFAULT '0',
  `name` varchar(255) DEFAULT NULL,
  `sale_discount_available` tinyint(1) NOT NULL DEFAULT '1',
  `money_running_out` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `with_autoservices` tinyint(1) NOT NULL DEFAULT '0',
  `single_payment_model` varchar(128) DEFAULT NULL,
  `actual_stock` tinyint(1) NOT NULL DEFAULT '0',
  `feedprocessor_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_loyalty` tinyint(1) NOT NULL DEFAULT '0',
  `calls_auction_available` tinyint(1) NOT NULL DEFAULT '0',
  `redemption_available` tinyint(1) NOT NULL DEFAULT '0',
  `epoch` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_1c_UNIQUE` (`id_1c`),
  KEY `product_id` (`product_id`),
  KEY `group_id` (`group_id`),
  KEY `id_clients` (`id_clients`)
) ENGINE=InnoDB AUTO_INCREMENT=37354 DEFAULT CHARSET=utf8 COMMENT='Clients table';


INSERT INTO `clients` (`id`, `group_id`, `product_id`, `country_id`, `region_id`, `city_id`, `ya_country_id`, `ya_region_id`, `ya_city_id`, `url`, `email`, `phone`, `phone_mask`, `description`, `logo`, `logosize`, `comment`, `is_agent`, `agent_id`, `loader_id`, `origin`, `status`, `contact_name`, `fax`, `fax_mask`, `contract_version`, `create_date`, `first_activation_date`, `last_activation_date`, `is_agreement_accept`, `agreement_accept_date`, `agreement_number`, `post_index`, `adress`, `contactname`, `is_suspected`, `first_moderated`, `is_onmoderate`, `is_onmoderate_rejected`, `is_onmoderate_info`, `is_onmoderate_trademark`, `is_onmoderate_dealership`, `is_onmoderate_salons`, `is_onmoderate_properties`, `is_new`, `is_new_info`, `is_new_properties`, `is_mounting`, `is_deleted`, `is_freezed`, `is_imported`, `date_update`, `id_1c`, `id_clients`, `id_agent_old`, `id_contacts_old`, `paid_with`, `paid_till`, `month_sum`, `use_office_tariff`, `use_premium_tariff`, `is_gold_partner`, `discard_agency_discount`, `wallet_available`, `is_self_registered`, `auto_prolong`, `use_office7_v2`, `can_switch_v2`, `company_id`, `new_billing_available`, `name`, `sale_discount_available`, `money_running_out`, `with_autoservices`, `single_payment_model`, `actual_stock`, `feedprocessor_enabled`, `is_loyalty`, `calls_auction_available`, `redemption_available`, `epoch`)
VALUES
	(16453, 1, 65, 1, 87, 1123, 225, 1, 213, 'http://www.major-expert.ru', 'aristos@ma.ru', 74951350605, '1:3:7', '', '', '', '', 0, 0, 0, 'msk2418', 'active', '', 0, '', 'old', '2001-01-28 18:36:41', '2001-01-28 18:36:41', '2017-03-02 13:05:12', 0, '1970-01-01 00:00:00', '', '', 'Новорижское ш., 9км от МКАД', '', 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, '2015-04-02 12:34:01', NULL, 15867, 0, 0, '2018-08-02 05:39:52', '2018-09-09 05:39:52', 1532550, 0, 0, 0, 1, 1, 0, 0, 1, 0, 4, 1, 'MAJOR EXPERT', 1, 0, 0, 'cars:used,commercial', 1, 1, 1, 1, 1, '2018-08-02 12:50:53.565');


CREATE TABLE `key_value` (
  `key` varchar(128) NOT NULL,
  `value` varchar(512) NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;