node ('maven') {

    stage('Checkout') {
        checkout scm
    }

    stage('Build') {
        String goals = env.BRANCH_NAME == 'master' ? 'clean deploy' : 'clean test'
        withMaven(maven: 'default') {
            sh "mvn ${goals}"
        }
    }

}