// Code generated by mockery v2.12.2. DO NOT EDIT.

package downtime

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// SetDowntime provides a mock function with given fields: dc, layer, duration
func (_m *IClient) SetDowntime(dc string, layer string, duration time.Duration) error {
	ret := _m.Called(dc, layer, duration)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, time.Duration) error); ok {
		r0 = rf(dc, layer, duration)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIClient creates a new instance of IClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t testing.TB) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
