# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controltest',
            name='adjusted_risk',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='controltest',
            name='how_management_identifies',
            field=models.TextField(blank=True, help_text='Describe how management identifies, investigates and resolves deviations or differences', null=True),
        ),
        migrations.AddField(
            model_name='controltest',
            name='how_precision_is_affected',
            field=models.TextField(blank=True, help_text='How does the level of predictability, level of aggregation, consistency of control performance and criteria for investigation affect precision', null=True),
        ),
        migrations.AddField(
            model_name='controltest',
            name='mrc',
            field=models.BooleanField(default=False, help_text='Use of judgement, including steps to identify and investigate significant differences from expectations and conclusions reached'),
        ),
        migrations.AddField(
            model_name='controltest',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controltest',
            name='roll_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='controltest',
            name='threshold_for_investigation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
