#!/bin/bash

rm -rf root
rm -rf saas_test*
rm -rf rst_*
rm -rf qst_*
rm backend*
rm deploy*
rm is*
rm sp*
rm ip*
rm result*

pkill -9 rty
pkill -9 search
pkill -9 index
pkill -9 deploy
pkill -9 monolith
