#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
no_color='\033[0m'

maps_branch_prefix='MAPSMOBILETEST'

current_branch=`git branch --show-current`
hint="Используйте параметр ${green}--no-verify${no_color}, чтобы игнорировать эту проверку\n"

if [[ $current_branch != $maps_branch_prefix* ]]; then
	>&2 echo -e "\n${red} НЕКОРРЕКТНОЕ ИМЯ ЛОКАЛЬНОЙ ВЕТКИ ${no_color}\n"
	>&2 echo -e " Текущая: ${red}${current_branch} ${no_color}"
	>&2 echo -e " Разрешенные: ${green}${maps_branch_prefix}-XXXX ${no_color}\n"
	>&2 echo -e " ${hint}"
	exit 1
fi

exit 0