module.exports = {
    ANIMATION_TIMEOUT: 1000,
    CLEANUP_TIMEOUT: 1000,
    COMMENTS_TIMEOUT: 200,
    DRAW_TIMEOUT: 200,
    HINT_TIMEOUT: 1000,
    ALERT_TIMEOUT: 1000,
    SUGGEST_TIMEOUT: 500,
    UPDATE_TIMEOUT: 1000,
    VALIDATOR_TIMEOUT: 1000,

    CLEANUP_INTERVAL: 3000,
    WAIT_FOR_CLASS_TIMEOUT: 5000,
    WAIT_FOR_TILES_TIMEOUT: 20000,
    WAIT_FOR_LOGIN_FORM_TIMEOUT: 1000,
    WAIT_FOR_NOTIFICATION_SUCCESS: 15000,

    INIT_TIMEOUT: 10000,
    INIT_RETRY_COUNT: 3,

    MAP_TOLERANCE: 50,
    DEFAULT_TOLERANCE: 4,
    ANTIALIASING_TOLERANCE: 10,

    CLEANUP_LONGITUDE_MIN: 0,
    CLEANUP_LONGITUDE_MAX: 8,
    CLEANUP_LATITUDE_STEP: 0.005,

    DEFAULT_TLD: 'ru',
    DEFAULT_LANG: 'ru',

    ALL_OBJECTS_FILTER_EXPRESSION_ID: process.env.YENV === 'testing'? 2376 : 1817 // not cat:xxx=1
};
