#!/usr/bin/env node
'use strict';

/* eslint-disable no-console */

const assert = require('assert');

const { findAffectedTests } = require('../src')

assert(process.env.TEST_FILES_REGEXP !== undefined, 'Не передан регэксп для файлов тестов (TEST_FILES_REGEXP)');
assert(process.env.BASE_SHA !== undefined, 'Не передан хэш базовой ветки (BASE_SHA)');
assert(process.env.HEAD_SHA !== undefined, 'Не передан хэш последнего коммита (HEAD_SHA)');

findAffectedTests({
    testFilesRegexpString: process.env.TEST_FILES_REGEXP,
    baseSha: process.env.BASE_SHA,
    headSha: process.env.HEAD_SHA,
    triggerAllTestsRegexp: process.env.TRIGGER_ALL_TESTS_REGEXP,
    testLimitInOnePart: process.env.TEST_LIMIT_IN_ONE_PART,
    forceRunAllTests: process.env.FORCE_RUN_ALL_TESTS === 'true',
});
