#!/usr/bin/env node
'use strict';

/* eslint-disable no-console */

const { getPackagesWithAffectedTests } = require('../src');


async function main() {
    try {
        const affectedPackages = await getPackagesWithAffectedTests(
            process.env.BASE_SHA,
            process.env.HEAD_SHA,
            process.env.TEST_FILES_REGEXP,
            process.env.TRIGGER_ALL_TESTS_REGEXP,
        );

        console.log(JSON.stringify(affectedPackages));

    } catch (e) {
        console.error(e);
        process.exit(1);
    }
}

main();
