#!/bin/bash

set -e

case "$1" in
    remove|purge)
        _env_file='/etc/environment'

        sed -i '/^export AUTORU_CONFIG_PHP_LIB5/d' ${_env_file}
        sed -i '/^export AUTORU_CONFIG_PHP_LIB5/d' ${_env_file}
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

