#!/bin/bash

set -e

case "$1" in
    configure)
        _env_file='/etc/environment'

        grep -q "^export AUTORU_CONFIG_PHP_LIB5" ${_env_file} || \
            echo "export AUTORU_CONFIG_PHP_LIB5='/servers/_templiered_config_lib5.php'" >> ${_env_file}

        grep -q "^export AUTORU_CONFIG_PHP_LIB2" ${_env_file} || \
            echo "export AUTORU_CONFIG_PHP_LIB2='/servers/_templiered_config_lib2.php'" >> ${_env_file}
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0

