INSERT INTO {transport_tmp_out} (ft_id, line_type_id, network, line, color, mtr_types,
  basic_icon, composite_icon, icon_line, icon_line_exit, icon_network, icon_network_exit, icon_network_line, icon_network_line_exit,
  legacy_name, composite_name) VALUES

(100000069,  632, 'moscow_metro', 'moscow_metro-2', '#0a6f20', [], null, null, null, null, null, null, null, null, null, null),
(100000078,  632, 'moscow_metro', 'moscow_metro-9', '#a2a5b4', [], null, null, null, null, null, null, null, null, null, null),
(100000088,  632, 'moscow_metro', 'moscow_metro-5', '#7f0000', [], null, null, null, null, null, null, null, null, null, null),
(100000114,  632, 'moscow_metro', 'moscow_metro-7', '#92007b', [], null, null, null, null, null, null, null, null, null, null),

(100079104,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-7','moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  null,
  null, null),
(100079108,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-5','moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  null,
  null, null),
(100079120,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  null,
  null, null),
(100079132,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9','moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  null,
  null, null),
(100079140,  632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-2.moscow_metro-7','moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  null,
  null, null),
(100079180,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-2','moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  null,
  null, null),
(100079184,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  null,
  null, null),
(100079200,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-9','moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  null,
  null, null),
(100079216,  632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-5','moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  null,
  ['moscow_metro','metro'],
  null,
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  null,
  null, null),

(100128479,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-7.exit_yellow_1','moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_1','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Краснопресненская\\nвход 1"}'), json('{"ru_RU_LOCAL":"Краснопресненская\\nБаррикадная"}')),

(100128483,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-5.exit_yellow_2','moscow_metro.moscow_metro-7.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_2','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Баррикадная\\nвход 2"}'), json('{"ru_RU_LOCAL":"Баррикадная\\nКраснопресненская"}')),

(100128491,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9.exit_yellow_9','moscow_metro.moscow_metro-2.exit_yellow_9','moscow_metro.exit_yellow_9','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_9','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_9','moscow_metro.exit_yellow_9','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Тверская\\nвход 9"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская\\nЧеховская"}')),

(100128503,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_8','moscow_metro.moscow_metro-7.exit_yellow_8','moscow_metro.exit_yellow_8','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_8','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_8','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_8','moscow_metro.exit_yellow_8','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 8"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(100128511,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9.exit_yellow_5','moscow_metro.moscow_metro-2.exit_yellow_5','moscow_metro.exit_yellow_5','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_5','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_5','moscow_metro.exit_yellow_5','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Тверская\\nвход 5"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская\\nЧеховская"}')),

(100128515,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_4','moscow_metro.moscow_metro-7.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_4','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 4"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(100128523,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9.exit_yellow_2','moscow_metro.moscow_metro-2.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_2','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Тверская\\nвход 2"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская\\nЧеховская"}')),

(100128527,  632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-2.moscow_metro-7.exit_yellow_12','moscow_metro.moscow_metro-9.exit_yellow_12','moscow_metro.exit_yellow_12','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9.exit_yellow_12','moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_12','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9.exit_yellow_12','moscow_metro.exit_yellow_12','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Чеховская\\nвход 12"}'), json('{"ru_RU_LOCAL":"Чеховская\\nТверская\\nПушкинская"}')),

(100128539,  632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_1','moscow_metro.moscow_metro-7.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_1','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 1"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(100128607,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-2.exit_yellow_1','moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_1','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвход 1"}'), json('{"ru_RU_LOCAL":"Белорусская"}')),

(100128615,  632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвход"}'), json('{"ru_RU_LOCAL":"Белорусская"}')),

(100128619,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-2.exit_yellow_3','moscow_metro.moscow_metro-5.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_3','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвход 3"}'), json('{"ru_RU_LOCAL":"Белорусская"}')),

(100128651,  632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_1','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Новослободская\\nвход закрыт"}'), json('{"ru_RU_LOCAL":"Новослободская"}')),

(100128667,  632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-5.exit_yellow_3','moscow_metro.moscow_metro-9.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9.exit_yellow_3','moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Менделеевская\\nвход 3"}'), json('{"ru_RU_LOCAL":"Менделеевская\\nНовослободская"}')),

(100128675,  632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-5.exit_yellow_4','moscow_metro.moscow_metro-9.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9.exit_yellow_4','moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Менделеевская\\nвход 4"}'), json('{"ru_RU_LOCAL":"Менделеевская\\nНовослободская"}')),

(1442284011, 632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_13','moscow_metro.moscow_metro-7.exit_yellow_13','moscow_metro.exit_yellow_13','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_13','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_13','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_13','moscow_metro.exit_yellow_13','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 13"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(1563446362, 632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвход"}'), json('{"ru_RU_LOCAL":"Белорусская"}')),

(1572494862, 632, 'moscow_metro', 'moscow_metro-5', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-2.exit_yellow_2','moscow_metro.moscow_metro-5.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_2','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвход 2"}'), json('{"ru_RU_LOCAL":"Белорусская"}')),

(1574711572, 632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-2.moscow_metro-7.exit_yellow_14','moscow_metro.moscow_metro-9.exit_yellow_14','moscow_metro.exit_yellow_14','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9.exit_yellow_14','moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_14','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9.exit_yellow_14','moscow_metro.exit_yellow_14','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Чеховская\\nвход 14"}'), json('{"ru_RU_LOCAL":"Чеховская\\nТверская\\nПушкинская"}')),

(1574711602, 632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_11','moscow_metro.moscow_metro-7.exit_yellow_11','moscow_metro.exit_yellow_11','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_11','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_11','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_11','moscow_metro.exit_yellow_11','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 11"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(1596302108, 632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_6','moscow_metro.moscow_metro-7.exit_yellow_6','moscow_metro.exit_yellow_6','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_6','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_6','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_6','moscow_metro.exit_yellow_6','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 6"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(1659964751, 632, 'moscow_metro', 'moscow_metro-9', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-9.moscow_metro-5.exit_yellow_2','moscow_metro.moscow_metro-9.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro-9.exit_yellow_2','moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-9.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Менделеевская\\nвход 2"}'), json('{"ru_RU_LOCAL":"Менделеевская\\nНовослободская"}')),

(1685966687, 632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9.exit_yellow_3','moscow_metro.moscow_metro-2.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_3','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_3','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_3','moscow_metro.exit_yellow_3','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Тверская\\nвход 3"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская\\nЧеховская"}')),

(1685971717, 632, 'moscow_metro', 'moscow_metro-7', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.moscow_metro-9.exit_yellow_10','moscow_metro.moscow_metro-7.exit_yellow_10','moscow_metro.exit_yellow_10','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_10','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_10','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_10','moscow_metro.exit_yellow_10','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 10"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская\\nЧеховская"}')),

(1685977647, 632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.moscow_metro-9.exit_yellow_7','moscow_metro.moscow_metro-2.exit_yellow_7','moscow_metro.exit_yellow_7','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_7','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_7','moscow_metro.exit_yellow_7','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Тверская\\nвход 7"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская\\nЧеховская"}')),

(3402688745, 632, 'moscow_metro', 'moscow_metro-2', null, ['underground'],
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5.exit_yellow_4','moscow_metro.moscow_metro-2.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_4','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  json('{"ru_RU_LOCAL":"Белорусская\\nвыход 4"}'), json('{"ru_RU_LOCAL":"Белорусская"}'));
