#!/bin/sh

echo "$(python -c 'import time; print time.time()') $$ $@" >> bad_result.txt

sleep 1

rc=$(python -c 'import random;random.seed();print random.sample([1, 2, 3, 4, -6, -9], 1)[0]')

if [ ${rc} -ge 0 ]; then
    exit ${rc}
else
    kill ${rc} $$
fi
