export const listParams = {
    items: [
        {
            invoiceCount: 0,
            clientId: 134887050,
            inn: '467502985392',
            hidden: false,
            name: 'YT legal Payer',
            kpp: null,
            clientName: 'ООО "Клиент"',
            type: 'yt',
            id: 12092319,
            email: 'email9yt@ya.ru',
            isPartner: false
        },
        {
            invoiceCount: 0,
            clientId: 134887049,
            inn: '467502985392',
            hidden: false,
            name: 'ООО "Плательщик"',
            kpp: '912788793',
            clientName: 'ООО "Клиент"',
            type: 'ur',
            id: 12092318,
            email: 'email9partner@ya.ru',
            isPartner: true
        }
    ],
    totalRowCount: 30,
    isFetching: false,
    isUpdating: false,
    pageNumber: 1,
    pageSize: 10,
    pageSizes: [10, 25, 50, 100, 1000],
    totalPages: 3,
    personTypes: {
        ALL: 'Все',
        am_jp: 'Юр. лицо-резидент, Армения',
        am_np: 'Физ. лицо-резидент, Армения',
        az_ur: 'Юр. лицо, Азербайджан',
        byp: 'Физ. лицо, Республика Беларусь',
        byu: 'Юр. лицо, Республика Беларусь',
        by_ytph: 'Физ. лицо-нерезидент, СНГ',
        endbuyer_ph: 'Физ. лицо, покупатель',
        endbuyer_ur: 'Юр. лицо, покупатель',
        endbuyer_yt: 'Нерезидент, покупатель',
        eu_ur: 'Юр. лицо, Нидерланды',
        eu_yt: 'Нерезидент, Нидерланды',
        hk_ur: 'Юр. лицо, Гонконг',
        hk_yt: 'Нерезидент, Гонконг',
        hk_ytph: 'Физ. лицо-нерезидент, Гонконг',
        il_ur: 'Юр. лицо, Израиль',
        kzp: 'Физ. лицо, Казахстан',
        kzu: 'Юр. лицо, Казахстан',
        ph: 'Физ. лицо',
        ph_autoru: 'Физ. лицо Авто.ру',
        pu: 'Физ. лицо, Украина',
        ro_ur: 'Юр. лицо, Румыния',
        sw_ph: 'Физ. лицо, Швейцария',
        sw_ur: 'Юр. лицо, Швейцария',
        sw_yt: 'Нерезидент, Швейцария',
        sw_ytph: 'Физ. лицо-нерезидент, Швейцария',
        trp: 'Физ. лицо, Турция',
        tru: 'Юр. лицо, Турция',
        ua: 'Юр. лицо, Украина',
        ur: 'Юр. лицо',
        ur_autoru: 'Юр. лицо Авто.ру',
        usp: 'Физ. лицо, США',
        usu: 'Юр. лицо, США',
        yt: 'Нерезидент',
        yt_kzp: 'Физ. лицо, Нерезидент РФ, Казахстан',
        yt_kzu: 'Юр. лицо, Нерезидент РФ, Казахстан',
        ytph: 'Физ. лицо-нерезидент'
    }
};
