/// This file was generated by figma export tool(mobile/geo/maps/tools/figma)
/// Do not update it manually

#pragma once

namespace yandex::maps::navikit::resources::colors {
struct OverviewRouteBalloonShadowTestNightColor {
    static const char* const colorInternalId;
};
}
