// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM test/non-authorized-tests.ts >>>

import Foundation

open class NonAuthorizedPayWithNewCardTest: MBTTest<PaymentDataPreparer> {
  private var card: BoundCard = BoundCard.generated()
  public init() {
    super.init("\(TestScenario.nonAuthorized) Pay with new card")
  }

  open override func setupSettings(_ settings: TestSettings) -> Void {
    settings.commonCase(69).ignoreOn(MBTPlatform.IOS)
  }

  open override func prepareAccounts(_ preparers: YSArray<PaymentDataPreparer>) -> Void {
    preparers[0].setPaymentMethodsFilter(PaymentMethodsFilter(false, false, false, false)).setPersonalInfoShowingMode(PersonalInfoMode.AUTOMATIC).setAuthorizationMode(AuthorizationMode.nonauthorized)
  }

  @discardableResult
  open override func requiredAccounts() -> YSArray<AccountType2> {
    return YSArray(AccountType2.YandexTest)
  }

  @discardableResult
  open override func scenario(_ accounts: YSArray<UserAccount>, _ model: AppModel!, _ supportedFeatures: YSArray<FeatureID>) -> TestPlan {
    return TestPlan.empty().then(OpenSampleAppAction()).then(AssertAction()).then(StartRegularPaymentProcessAction()).then(AssertAction()).then(FillNewCardDataAction(self.card, true))
  }

}

