// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM mbt/test/regular-yandex-test-base.ts >>>

import Foundation

open class RegularYandexTestBase<T: AccountDataPreparer>: RegularTestBase<T> {
  public init(_ description: String, _ suite: YSArray<TestSuite> = YSArray(TestSuite.Fixed)) {
    super.init(description, AccountType2.Yandex, suite)
  }

}

