// Code generated by mockery v2.14.0. DO NOT EDIT.

package pipeline

import mock "github.com/stretchr/testify/mock"

// ICMSActions is an autogenerated mock type for the ICMSActions type
type ICMSActions struct {
	mock.Mock
}

// Disable provides a mock function with given fields: layer, dc
func (_m *ICMSActions) Disable(layer string, dc string) error {
	ret := _m.Called(layer, dc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(layer, dc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Enable provides a mock function with given fields: layer, dc
func (_m *ICMSActions) Enable(layer string, dc string) error {
	ret := _m.Called(layer, dc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(layer, dc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewICMSActions interface {
	mock.TestingT
	Cleanup(func())
}

// NewICMSActions creates a new instance of ICMSActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewICMSActions(t mockConstructorTestingTNewICMSActions) *ICMSActions {
	mock := &ICMSActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
