// Code generated by mockery v2.12.2. DO NOT EDIT.

package pipeline

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IHBFActions is an autogenerated mock type for the IHBFActions type
type IHBFActions struct {
	mock.Mock
}

// Start provides a mock function with given fields: dc, duration, issue
func (_m *IHBFActions) Start(dc string, duration time.Duration, issue string) error {
	ret := _m.Called(dc, duration, issue)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, string) error); ok {
		r0 = rf(dc, duration, issue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: dc
func (_m *IHBFActions) Stop(dc string) error {
	ret := _m.Called(dc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIHBFActions creates a new instance of IHBFActions. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHBFActions(t testing.TB) *IHBFActions {
	mock := &IHBFActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
