#%RAML 0.8
title: Realty Back
baseUri: back-rt-01-sas.test.vertis.yandex.net:36134/api/2.x
mediaType:  application/json

/{service}:
  uriParameters:
    service:
      displayName: service
      required: true
      default: realty

  /user/{user}:
    uriParameters:
      customer:
        displayName: user
        required: true

    #/{service}/user/{user}/subscriptions/
    /subscriptions:
      get:
        description: Lists user's subscriptions
        responses:
          200:
            description: Lists user's subscriptions
            body:
              application/json:
                schema: !include schemas/back-rt/resp/subscriptions_resp.json
          400:
            description: Malformed requests
      post:
        description: Creates subscription
        body:
          application/json:
            schema: !include schemas/back-rt/req/subscriptions_req.json
        responses:
          200:
            description: Creates subscription
            body:
              application/json:
                schema: !include schemas/back-rt/resp/subscriptions_resp.json
          400:
            description: Malformed requests

      /{id}:
        uriParameters:
          id:
            displayName: Subscription's ID
            required: true
        delete:
          description: Deletes subscriptions by ID
          responses:
            200:
              description: Subscriptions removed