#%RAML 0.8
title: Bnb searcher
baseUri: http://realty-bnb-searcher-01-sas.test.vertis.yandex.net:36259
mediaType:  application/json

/newbuildingCard:
  get:
    queryParameters:
      siteId:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/bnb-searcher/newBuildingCard.json

/newbuildingNameSuggest:
  get:
    queryParameters:
      text:
        type: string
        required: true
      rgid:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/bnb-searcher/suggest.json

