#%RAML 0.8
title: promo
baseUri: http://promocoder-01-sas.test.vertis.yandex.net:2000/api/1.x/service/realty
mediaType:  application/json

/promocode:
  post:
    description: Creates a user
    headers:
      X-Promocoder-User:
        default: promocoder
    body:
      application/json:
        schema: !include schemas/promo/create_promo_body.json
    responses:
      200:
  /{codeName}:
    uriParameters:
      codeName:
        displayName: code name
        required: true
    /user:
      /{userId}:
        uriParameters:
          userId:
            displayName: user id
            required: true
        post:
          description: Apply promocode
          headers:
            X-Promocoder-User:
              default: promocoder
          responses:
            200: