#%RAML 0.8
title: Searcher
baseUri: http://realty-searcher-02-sas.test.vertis.yandex.net:36610
mediaType:  application/json

/card.json:
  get:
    description: Info about offer
    queryParameters:
      id:
        description: Id of seller
        type: string
        required: true
      login:
        description: user login
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/searcher/card.json

/estimateCost.json:
  get:
    description: Info about offer
    queryParameters:
      category:
        description: category
        type: string
        required: true
      type:
        description: type
        type: string
        required: true
      rgid:
        description: rgid
        type: string
        required: true
      bucket:
        description: bucket
        type: string
        required: true
      pricingPeriod:
         description: pricing period
         type: string
         required: true
      paymentType:
          description: payment type
          type: string
          required: false
    responses:
      200:
        body:
          application/json:
            schema: !include schemas/searcher/estimateCost.json