#%RAML 0.8
title: Vos2
baseUri: http://vos2-rt-01-sas.test.vertis.yandex.net:36217/api/realty/
mediaType:  application/json

/user:
  /{userID}:
    uriParameters:
      userID:
        displayName: userID
        required: true
    get:
      description: Shows a user
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/vos2/resp/get_user_resp.json
  /create:
    post:
      description: Creates a user
      body:
        application/json:
          schema: !include schemas/vos2/req/user_req.json
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/vos2/resp/user_resp.json

  /update:
     /{userID}:
         uriParameters:
           userID:
             displayName: userID
             required: true
         put:
           description: Updates a user
           body:
             application/json:
               schema: !include schemas/vos2/req/user_req.json
           responses:
             200:
               body:
                 application/json:
                   schema: !include schemas/vos2/resp/user_resp.json
/offer:
  /moderation:
    get:
      description: Shows an offer
      queryParameters:
        offerID:
          type: string
          required: false

  /{userID}:
    uriParameters:
      userID:
        displayName: userID
        required: true
    /{offerID}:
      uriParameters:
        offerID:
          displayName: offerID
          required: true
      get:
        description: Shows an offer
        responses:
          200:
            body:
              application/json:
                schema: !include schemas/vos2/resp/offer_info.json
  /create:
    /{userID}:
      uriParameters:
        userID:
          displayName: userID
          required: true
      post:
        description: Creates a batch of offers
        body:
          application/json:
            schema: !include schemas/vos2/req/create_offer_req.json
        responses:
          200:
            body:
              application/json:
                schema: !include schemas/vos2/resp/create_offer_resp.json
  /delete:
    /{userID}:
      uriParameters:
        userID:
          displayName: userID
          required: true
      /{offerID}:
        uriParameters:
          offerID:
            displayName: offerID
            required: true
        delete:
          description: Deletes an offer
          body:
            application/json:
              schema: !include schemas/vos2/req/delete_offer_req.json
          responses:
            200:
              body:
                application/json:
                  schema: !include schemas/vos2/resp/delete_offer_resp.json
  /update_price:
    /{userID}:
      uriParameters:
        userID:
          displayName: userID
          required: true
      /{offerID}:
        uriParameters:
          offerID:
            displayName: offerID
            required: true
        put:
          description: Updates the price of an offer
          body:
            application/json:
              schema: !include schemas/vos2/req/update_price.json
          responses:
            200:
              body:
                application/json:
                  schema: !include schemas/vos2/resp/update_price_resp.json
/user_offers:
  /by_ids:
    /{userID}:
      uriParameters:
        userID:
          displayName: userID
          required: true
      get:
        description: Shows an offer
        queryParameters:
          offerIDs:
            type: string
            required: false

  /{userID}:
    uriParameters:
      userID:
        displayName: userID
        required: true
    get:
      description: Shows an offer
      queryParameters:
        p:
          default: 1
          type: string
          required: false
        num:
          type: string
          required: true
        sort:
          default: createTime
          type: string
          required: false
        direction:
          default: desc
          type: string
          repeat: false
      responses:
        200:
          body:
            application/json:
              schema: !include schemas/vos2/resp/user_offers_resp.json

/draft:
  /create:
    /{userID}:
      uriParameters:
            userID:
              displayName: userID
              required: true
      post:
          description: Create a draft
          body:
            application/json:
              schema: !include schemas/vos2/req/create_draft_req.json
          responses:
            200:
              body:
                application/json:
                  schema: !include schemas/vos2/resp/create_offer_resp.json