project 'YxSwissKnife/YxSwissKnife.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YxSwissKnife' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for YxSwissKnife


end

target 'YxSwissKnifeTests' do
  inherit! :search_paths
  pod 'Swifter', :git => 'https://github.com/httpswift/swifter.git', branch: 'stable'
end

target 'YxSwissKnifeUITests' do
    inherit! :search_paths
    # Pods for testing
end
