# coding: utf-8

import pytest

from btestlib import seqdiff
from btestlib.diffutils import Change, Types


@pytest.mark.parametrize("old, new, add_same, expected_changes", [
    # remove
    ('abc', 'bc', False, [Change(type=Types.DELETE, elem='a', id=0)]),
    ('abc', 'bc', True, [Change(type=Types.DELETE, elem='a', id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                         Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1)]),
    ('abc', 'ac', False, [Change(type=Types.DELETE, elem='b', id=1)]),
    ('abc', 'ac', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.DELETE, elem='b', id=1),
                         Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1)]),
    ('abc', 'ab', False, [Change(type=Types.DELETE, elem='c', id=2)]),
    ('abc', 'ab', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.DELETE, elem='c', id=2)]),
    ('aab', 'ab', False, [Change(type=Types.DELETE, elem='a', id=1)]),
    ('aab', 'ab', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.DELETE, elem='a', id=1),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1)]),
    ('abb', 'ab', False, [Change(type=Types.DELETE, elem='b', id=2)]),
    ('abb', 'ab', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.DELETE, elem='b', id=2)]),
    ('aa', 'a', False, [Change(type=Types.DELETE, elem='a', id=1)]),
    ('aa', 'a', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                       Change(type=Types.DELETE, elem='a', id=1)]),
    ('a', '', False, [Change(type=Types.DELETE, elem='a', id=0)]),
    ('a', '', True, [Change(type=Types.DELETE, elem='a', id=0)]),
    ('aab', 'b', False, [Change(type=Types.DELETE, elem='a', id=0),
                         Change(type=Types.DELETE, elem='a', id=1)]),
    ('aab', 'b', True, [Change(type=Types.DELETE, elem='a', id=0),
                        Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=0),
                        Change(type=Types.DELETE, elem='a', id=1)]),
    ('aa', '', False, [Change(type=Types.DELETE, elem='a', id=0),
                       Change(type=Types.DELETE, elem='a', id=1)]),
    ('aa', '', True, [Change(type=Types.DELETE, elem='a', id=0),
                      Change(type=Types.DELETE, elem='a', id=1)]),
    # add
    ('ab', 'cab', False, [Change(type=Types.INSERT, to_elem='c', to_id=0)]),
    ('ab', 'cab', True, [Change(type=Types.INSERT, to_elem='c', to_id=0),
                         Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2)]),
    ('ab', 'acb', False, [Change(type=Types.INSERT, to_elem='c', to_id=1)]),
    ('ab', 'acb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.INSERT, to_elem='c', to_id=1),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2)]),
    ('ab', 'abc', False, [Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('ab', 'abc', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('a', 'aa', False, [Change(type=Types.INSERT, to_elem='a', to_id=1)]),
    ('a', 'aa', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                       Change(type=Types.INSERT, to_elem='a', to_id=1)]),
    ('', 'a', False, [Change(type=Types.INSERT, to_elem='a', to_id=0)]),
    ('', 'a', True, [Change(type=Types.INSERT, to_elem='a', to_id=0)]),
    ('', 'aa', False, [Change(type=Types.INSERT, to_elem='a', to_id=0),
                       Change(type=Types.INSERT, to_elem='a', to_id=1)]),
    ('', 'aa', True, [Change(type=Types.INSERT, to_elem='a', to_id=0),
                      Change(type=Types.INSERT, to_elem='a', to_id=1)]),
    ('ab', 'abb', False, [Change(type=Types.INSERT, to_elem='b', to_id=2)]),
    ('ab', 'abb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.INSERT, to_elem='b', to_id=2)]),
    ('abb', 'abab', False, [Change(type=Types.INSERT, to_elem='a', to_id=2)]),
    ('abb', 'abab', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                           Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                           Change(type=Types.INSERT, to_elem='a', to_id=2),
                           Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=3)]),
    # change
    ('abc', 'dbc', False, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0)]),
    ('abc', 'dbc', True, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2)]),
    ('abc', 'adc', False, [Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1)]),
    ('abc', 'adc', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2)]),
    ('abc', 'abd', False, [Change(type=Types.REPLACE, elem='c', to_elem='d', id=2, to_id=2)]),
    ('abc', 'abd', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.REPLACE, elem='c', to_elem='d', id=2, to_id=2)]),
    ('a', 'b', False, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0)]),
    ('a', 'b', True, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0)]),
    ('ab', 'cd', False, [Change(type=Types.REPLACE, elem='a', to_elem='c', id=0, to_id=0),
                         Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1)]),
    ('ab', 'cd', True, [Change(type=Types.REPLACE, elem='a', to_elem='c', id=0, to_id=0),
                        Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1)]),
    ('ab', 'aa', False, [Change(type=Types.REPLACE, elem='b', to_elem='a', id=1, to_id=1)]),
    ('ab', 'aa', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                        Change(type=Types.REPLACE, elem='b', to_elem='a', id=1, to_id=1)]),
    ('abc', 'aac', False, [Change(type=Types.REPLACE, elem='b', to_elem='a', id=1, to_id=1)]),
    ('abc', 'aac', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.REPLACE, elem='b', to_elem='a', id=1, to_id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2)]),
    ('aab', 'cab', False, [Change(type=Types.REPLACE, elem='a', to_elem='c', id=0, to_id=0)]),
    ('aab', 'cab', True, [Change(type=Types.REPLACE, elem='a', to_elem='c', id=0, to_id=0),
                          Change(type=Types.SAME, elem='a', to_elem='a', id=1, to_id=1),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=2)]),
    ('aab', 'acb', False, [Change(type=Types.REPLACE, elem='a', to_elem='c', id=1, to_id=1)]),
    ('aab', 'acb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.REPLACE, elem='a', to_elem='c', id=1, to_id=1),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=2)]),
    ('aabb', 'dabb', False, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0)]),
    ('aabb', 'dabb', True, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                            Change(type=Types.SAME, elem='a', to_elem='a', id=1, to_id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=2),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=3, to_id=3)]),
    # same
    ('a', 'a', False, []),
    ('a', 'a', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0)]),
    ('ab', 'ab', False, []),
    ('ab', 'ab', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                        Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1)]),
    ('abc', 'abc', False, []),
    ('abc', 'abc', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2)]),
    ('', '', False, []),
    ('', '', True, []),
    # move
    ('abc', 'bac', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1)]),
    ('abc', 'bac', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2)]),
    ('abc', 'cab', False, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0)]),
    ('abc', 'cab', True, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                          Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abc', 'acb', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abc', 'acb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                          Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abc', 'bca', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('abc', 'bca', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('ab', 'ba', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1)]),
    ('ab', 'ba', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                        Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1)]),
    ('abb', 'bab', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0)]),
    ('abb', 'bab', True, [Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0),
                          Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abb', 'bba', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('abb', 'bba', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('aabb', 'abba', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=1, to_id=3)]),
    ('aabb', 'abba', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=3, to_id=2),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=1, to_id=3)]),
    ('abcd', 'acbd', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abcd', 'acbd', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                            Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                            Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2),
                            Change(type=Types.SAME, elem='d', to_elem='d', id=3, to_id=3)]),
    # move and move
    ('abc', 'cba', False, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                           Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('abc', 'cba', True, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('aabb', 'baba', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=3, to_id=0),
                             Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=3)]),
    ('aabb', 'baba', True, [Change(type=Types.MOVE, elem='b', to_elem='b', id=3, to_id=0),
                            Change(type=Types.SAME, elem='a', to_elem='a', id=1, to_id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=2),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=3)]),
    ('aabb', 'bbaa', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2),
                             Change(type=Types.MOVE, elem='a', to_elem='a', id=1, to_id=3)]),
    ('aabb', 'bbaa', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=0),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=3, to_id=1),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=1, to_id=3)]),
    ('abcd', 'cdab', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2),
                             Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=3)]),
    ('abcd', 'cdab', True, [Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=0),
                            Change(type=Types.SAME, elem='d', to_elem='d', id=3, to_id=1),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2),
                            Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=3)]),
    ('abcd', 'badc', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                             Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=3)]),
    ('abcd', 'badc', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                            Change(type=Types.SAME, elem='d', to_elem='d', id=3, to_id=2),
                            Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=3)]),
    # move and move and move
    ('abcd', 'dcba', False, [Change(type=Types.MOVE, elem='d', to_elem='d', id=3, to_id=0),
                             Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2),
                             Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=3)]),
    ('abcd', 'dcba', True, [Change(type=Types.MOVE, elem='d', to_elem='d', id=3, to_id=0),
                            Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                            Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=2),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=3)]),
    # add and move
    ('ab', 'bac', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('ab', 'bac', True, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=0),
                         Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                         Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('ab', 'cba', False, [Change(type=Types.INSERT, to_elem='c', to_id=0),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('ab', 'cba', True, [Change(type=Types.INSERT, to_elem='c', to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('ab', 'bca', False, [Change(type=Types.INSERT, to_elem='c', to_id=1),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('ab', 'bca', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                         Change(type=Types.INSERT, to_elem='c', to_id=1),
                         Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('ab', 'baa', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.INSERT, to_elem='a', to_id=2)]),
    ('ab', 'baa', True, [Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=0),
                         Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                         Change(type=Types.INSERT, to_elem='a', to_id=2)]),
    ('abb', 'baba', False, [Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0),
                            Change(type=Types.INSERT, to_elem='a', to_id=3)]),
    ('abb', 'baba', True, [Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0),
                           Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                           Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2),
                           Change(type=Types.INSERT, to_elem='a', to_id=3)]),
    # remove and move
    ('abc', 'ca', False, [Change(type=Types.DELETE, id=1, elem='b'),
                          Change(type=Types.MOVE, id=0, to_id=1, elem='a', to_elem='a')]),
    ('abc', 'ca', True, [Change(type=Types.SAME, id=2, to_id=0, elem='c', to_elem='c'),
                         Change(type=Types.DELETE, id=1, elem='b'),
                         Change(type=Types.MOVE, id=0, to_id=1, elem='a', to_elem='a')]
     ),
    ('abc', 'ba', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.DELETE, elem='c', id=2)]),
    ('abc', 'ba', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                         Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                         Change(type=Types.DELETE, elem='c', id=2)]),
    ('aab', 'ba', False, [Change(type=Types.DELETE, elem='a', id=0),
                          Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0)]),
    ('aab', 'ba', True, [Change(type=Types.DELETE, elem='a', id=0),
                         Change(type=Types.MOVE, elem='b', to_elem='b', id=2, to_id=0),
                         Change(type=Types.SAME, elem='a', to_elem='a', id=1, to_id=1)]),
    # move and change
    ('abbc', 'acdb', False, [Change(type=Types.MOVE, elem='c', to_elem='c', id=3, to_id=1),
                             Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=2)]),
    ('abbc', 'acdb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                            Change(type=Types.MOVE, elem='c', to_elem='c', id=3, to_id=1),
                            Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=2),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=3)]),

    # todo-igogor здесь должен быть реплейс, но чтобы этого добиться надо сликом много переборов. Не коротко, но верно.
    ('abc', 'bad', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                           Change(type=Types.REPLACE, elem='c', to_elem='d', id=2, to_id=2)]),
    ('abc', 'bad', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.REPLACE, elem='c', to_elem='d', id=2, to_id=2)]),
    ('abc', 'cad', False, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                           Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=2)]),
    ('abc', 'cad', True, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                          Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=1),
                          Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=2)]),
    # todo-igogor здесь должен быть реплейс, но чтобы этого добиться надо сликом много переборов. Не коротко, но верно.
    ('abbc', 'baac', False, [Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                             Change(type=Types.INSERT, to_elem='a', to_id=2),
                             Change(type=Types.DELETE, elem='b', id=2)]),
    ('abbc', 'baac', True, [Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                            Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=1),
                            Change(type=Types.INSERT, to_elem='a', to_id=2),
                            Change(type=Types.DELETE, elem='b', id=2),
                            Change(type=Types.SAME, elem='c', to_elem='c', id=3, to_id=3)]),

    # add and remove
    ('ab', 'ca', False, [Change(type=Types.INSERT, to_elem='c', to_id=0),
                         Change(type=Types.DELETE, elem='b', id=1)]),
    ('ab', 'ca', True, [Change(type=Types.INSERT, to_id=0, to_elem='c'), Change(type=Types.DELETE, id=1, elem='b'),
                        Change(type=Types.SAME, id=0, to_id=1, elem='a', to_elem='a')]),
    ('ab', 'bc', False, [Change(type=Types.DELETE, elem='a', id=0),
                         Change(type=Types.INSERT, to_elem='c', to_id=1)]),
    ('ab', 'bc', True, [Change(type=Types.DELETE, elem='a', id=0),
                        Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=0),
                        Change(type=Types.INSERT, to_elem='c', to_id=1)]),
    ('abc', 'dac', False, [Change(type=Types.INSERT, to_elem='d', to_id=0),
                           Change(type=Types.DELETE, elem='b', id=1)]),
    ('abc', 'dac', True, [Change(type=Types.INSERT, to_id=0, to_elem='d'), Change(type=Types.DELETE, id=1, elem='b'),
                          Change(type=Types.SAME, id=0, to_id=1, elem='a', to_elem='a'),
                          Change(type=Types.SAME, id=2, to_id=2, elem='c', to_elem='c')]),
    ('abc', 'acd', False, [Change(type=Types.DELETE, elem='b', id=1),
                           Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('abc', 'acd', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.DELETE, elem='b', id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                          Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('abc', 'aca', False, [Change(type=Types.DELETE, elem='b', id=1),
                           Change(type=Types.INSERT, to_elem='a', to_id=2)]),
    ('abc', 'aca', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.DELETE, elem='b', id=1),
                          Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=1),
                          Change(type=Types.INSERT, to_elem='a', to_id=2)]),
    ('aab', 'abd', False, [Change(type=Types.DELETE, elem='a', id=1),
                           Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('aab', 'abd', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                          Change(type=Types.DELETE, elem='a', id=1),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1),
                          Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('abc', 'aab', False, [Change(type=Types.INSERT, to_elem='a', to_id=1),
                           Change(type=Types.DELETE, elem='c', id=2)]),
    ('abc', 'aab', True,
     [Change(type=Types.SAME, id=0, to_id=0, elem='a', to_elem='a'), Change(type=Types.INSERT, to_id=1, to_elem='a'),
      Change(type=Types.DELETE, id=2, elem='c'), Change(type=Types.SAME, id=1, to_id=2, elem='b', to_elem='b')]),
    ('aabb', 'abbd', False, [Change(type=Types.DELETE, elem='a', id=1),
                             Change(type=Types.INSERT, to_elem='d', to_id=3)]),
    ('aabb', 'abbd', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                            Change(type=Types.DELETE, elem='a', id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=3, to_id=2),
                            Change(type=Types.INSERT, to_elem='d', to_id=3)]),
    ('aabb', 'abdb', False, [Change(type=Types.DELETE, elem='a', id=1),
                             Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('aabb', 'abdb', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                            Change(type=Types.DELETE, elem='a', id=1),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=2, to_id=1),
                            Change(type=Types.INSERT, to_elem='d', to_id=2),
                            Change(type=Types.SAME, elem='b', to_elem='b', id=3, to_id=3)]),
    # add and change
    ('ab', 'dbc', False, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                          Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('ab', 'dbc', True, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.INSERT, to_elem='c', to_id=2)]),
    ('a', 'bc', False, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0),
                        Change(type=Types.INSERT, to_elem='c', to_id=1)]),
    ('a', 'bc', True, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0),
                       Change(type=Types.INSERT, to_elem='c', to_id=1)]),
    ('ab', 'bdb', False, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0),
                          Change(type=Types.INSERT, to_elem='d', to_id=1)]),
    ('ab', 'bdb', True, [Change(type=Types.REPLACE, elem='a', to_elem='b', id=0, to_id=0),
                         Change(type=Types.INSERT, to_elem='d', to_id=1),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2)]),
    ('abc', 'adbe', False, [Change(type=Types.INSERT, to_elem='d', to_id=1),
                            Change(type=Types.REPLACE, elem='c', to_elem='e', id=2, to_id=3)]),
    ('abc', 'adbe', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                           Change(type=Types.INSERT, to_elem='d', to_id=1),
                           Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=2),
                           Change(type=Types.REPLACE, elem='c', to_elem='e', id=2, to_id=3)]),
    # change and remove
    ('abc', 'db', False, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                          Change(type=Types.DELETE, elem='c', id=2)]),
    ('abc', 'db', True, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                         Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                         Change(type=Types.DELETE, elem='c', id=2)]),
    ('ab', 'c', False, [Change(type=Types.DELETE, elem='a', id=0),
                        Change(type=Types.REPLACE, elem='b', to_elem='c', id=1, to_id=0)]),
    ('ab', 'c', True, [Change(type=Types.DELETE, elem='a', id=0),
                       Change(type=Types.REPLACE, elem='b', to_elem='c', id=1, to_id=0)]),
    ('abc', 'aa', False, [Change(type=Types.DELETE, elem='b', id=1),
                          Change(type=Types.REPLACE, elem='c', to_elem='a', id=2, to_id=1)]),
    ('abc', 'aa', True, [Change(type=Types.SAME, elem='a', to_elem='a', id=0, to_id=0),
                         Change(type=Types.DELETE, elem='b', id=1),
                         Change(type=Types.REPLACE, elem='c', to_elem='a', id=2, to_id=1)]),
    # replace, replace
    ('abc', 'dbe', False, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                           Change(type=Types.REPLACE, elem='c', to_elem='e', id=2, to_id=2)]),
    ('abc', 'dbe', True, [Change(type=Types.REPLACE, elem='a', to_elem='d', id=0, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.REPLACE, elem='c', to_elem='e', id=2, to_id=2)]),
    # add, remove, move
    ('abc', 'cbd', False, [Change(type=Types.DELETE, elem='a', id=0),
                           Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                           Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    ('abc', 'cbd', True, [Change(type=Types.DELETE, elem='a', id=0),
                          Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                          Change(type=Types.SAME, elem='b', to_elem='b', id=1, to_id=1),
                          Change(type=Types.INSERT, to_elem='d', to_id=2)]),
    # add, move, replace
    ('abc', 'edcb', False, [Change(type=Types.REPLACE, elem='a', to_elem='e', id=0, to_id=0),
                            Change(type=Types.INSERT, to_elem='d', to_id=1),
                            Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=3)]),
    ('abc', 'edcb', True, [Change(type=Types.REPLACE, elem='a', to_elem='e', id=0, to_id=0),
                           Change(type=Types.INSERT, to_elem='d', to_id=1),
                           Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=2),
                           Change(type=Types.MOVE, elem='b', to_elem='b', id=1, to_id=3)]),
    # add, remove, replace
    ('abc', 'edb', False, [Change(type=Types.REPLACE, elem='a', to_elem='e', id=0, to_id=0),
                           Change(type=Types.INSERT, to_elem='d', to_id=1),
                           Change(type=Types.DELETE, elem='c', id=2)]),
    ('abc', 'edb', True,
     [Change(type=Types.REPLACE, id=0, to_id=0, elem='a', to_elem='e'), Change(type=Types.INSERT, to_id=1, to_elem='d'),
      Change(type=Types.DELETE, id=2, elem='c'), Change(type=Types.SAME, id=1, to_id=2, elem='b', to_elem='b')]),
    # move, move, replace
    ('abc', 'cda', False, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                           Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1),
                           Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    ('abc', 'cda', True, [Change(type=Types.MOVE, elem='c', to_elem='c', id=2, to_id=0),
                          Change(type=Types.REPLACE, elem='b', to_elem='d', id=1, to_id=1),
                          Change(type=Types.MOVE, elem='a', to_elem='a', id=0, to_id=2)]),
    # add, remove, move
    ('abcd', 'cade', False,
     [Change(type=Types.DELETE, id=1, elem='b'), Change(type=Types.MOVE, id=0, to_id=1, elem='a', to_elem='a'),
      Change(type=Types.INSERT, to_id=3, to_elem='e')]),
    ('abcd', 'cade', True,
     [Change(type=Types.SAME, id=2, to_id=0, elem='c', to_elem='c'), Change(type=Types.DELETE, id=1, elem='b'),
      Change(type=Types.MOVE, id=0, to_id=1, elem='a', to_elem='a'),
      Change(type=Types.SAME, id=3, to_id=2, elem='d', to_elem='d'), Change(type=Types.INSERT, to_id=3, to_elem='e')]),
    # delete, delete, insert
    ('abc', 'ce', False, [Change(type=Types.DELETE, elem='a', id=0),
                          Change(type=Types.INSERT, to_elem='e', to_id=1),
                          Change(type=Types.DELETE, elem='b', id=1)]),
    ('abc', 'ce', True, [Change(type=Types.DELETE, elem='a', id=0),
                         Change(type=Types.SAME, elem='c', to_elem='c', id=2, to_id=0),
                         Change(type=Types.INSERT, to_elem='e', to_id=1),
                         Change(type=Types.DELETE, elem='b', id=1)]),
    # delete, replace, move
    ('abcd', 'dae', False, [Change(type=Types.MOVE, elem='d', to_elem='d', id=3, to_id=0),
                            Change(type=Types.DELETE, elem='b', id=1),
                            Change(type=Types.REPLACE, elem='c', to_elem='e', id=2, to_id=2)]),
    ('abcd', 'dae', True,
     [Change(type=Types.MOVE, id=3, to_id=0, elem='d', to_elem='d'), Change(type=Types.DELETE, id=1, elem='b'),
      Change(type=Types.SAME, id=0, to_id=1, elem='a', to_elem='a'),
      Change(type=Types.REPLACE, id=2, to_id=2, elem='c', to_elem='e')]),
], ids=lambda old, new, add_same, expected_changes: '{}->{}_add_same={}'.format(old, new, add_same))
def test_short_diff(old, new, add_same, expected_changes):
    changes = seqdiff.seqdiff(old, new, add_same=add_same)
    print changes
    if changes != expected_changes:
        print expected_changes
    assert changes == expected_changes
