java_library(
    name = "toxiproxy",
    srcs = glob(["src/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:com_github_docker_java_docker_java_api",
        "@maven//:eu_rekawek_toxiproxy_toxiproxy_java",
        "@maven//:org_testcontainers_testcontainers",
    ],
)
