#!/bin/bash

set -e

COMPONENT=auto2-config
PROJECT=auto2
USER=auto2
GROUP=nogroup
RUNDIR=/etc/yandex/$COMPONENT/ru

case "$1" in
    configure)
        # Create user if not existing
        if ! getent passwd | grep -q "^$USER:"; then
            echo -n "Adding system user $USER... "
            adduser --quiet \
                    --system \
                    --ingroup $GROUP \
                    --no-create-home \
                    --disabled-password \
                    $USER 2>/dev/null || true
            echo "DONE"
        fi

        # Chowning...
        chown -R $USER:$GROUP $RUNDIR

	    chmod 755 $RUNDIR
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
