#!/bin/sh

ACTION="$1"
COOKIE="$2"
PARAMS=""
if [ "x$ACTION" != "x" ] ; then
    PARAMS="?$ACTION=$COOKIE"
fi
RES=$(wget -T 1 -q -O /dev/stdout "http://localhost:30702/ping$PARAMS" 2> /dev/null)

if echo "$RES" | grep -q 'check_passport OK\|SUCCESS' ; then
    exit 0
fi
exit 13
