# coding: utf-8
__author__ = 'a-vasin'


class Features(object):
    ACT = 'act'
    ADDAPTER = 'addapter'
    ADDAPPTER2 = 'addappter2'
    ADFOX = 'adfox'
    AGENT_REPORT = 'agent_report'
    APIKEYS = 'api_keys'
    AUTOBUS = 'autobus'
    AUTOOVERDRAFT = 'autooverdraft'
    AVIA = 'avia'
    CALENDAR = 'calendar'
    CART = 'cart'
    CERTIFICATE = 'certificate'
    CHARGE_NOTE = 'charge_note'
    CLIENT = 'client'
    CLIENT_LIMIT = 'client_limit'  # Индивидуальные лимиты
    COLLATERAL = 'collateral'
    COMMON = 'common'
    COMPENSATION = 'compensation'
    COMPLETION = 'completion'
    CONSUME = 'consume'
    CONTRACT = 'contract'
    CONTRACT_DEACTIVATION = 'contract_deactivation'
    CONTRACT_OFFER = 'contract_offer'
    CONTRACT_PRINT_FORM = 'contract_print_form'
    CONVERSION = 'conversion'
    CORE = 'core'
    COROBA = 'coroba'
    CORP_TAXI = 'corp_taxi'
    CORPORATE = 'corporate'
    CORRECTION = 'correction'
    COUPON = 'coupon'
    CREDIT = 'credit'
    CURRENCY_RATE = 'currency_rate'
    DEAL_PASSPORT = 'deal passport'
    DEFERPAY = 'deferpay'
    DISCOUNT = 'discount'
    DISK = 'disk'
    DISTRIBUTION = 'distribution'
    DONATE = 'donate'
    DOWNLOADS = 'downloads'
    DRIVE = 'drive'
    DSP = 'dsp'
    EDO = 'edo'
    ELS = 'els'
    EMAIL = 'email'
    EVENTS_TICKETS = 'events_tickets'
    EVENTS_TICKETS_NEW = 'events_tickets_new'
    SUBAGENCY_EVENTS_TICKETS = 'subagency_events_tickets'
    FICTIVE_PERSONAL_ACCOUNT = 'fictive personal account'
    FOOD = 'food'
    FOOD_CORP = 'food_corp'
    FOOD_PHARMACY = 'food_pharmacy'
    GET_CLIENT_CONTRACTS = 'GetClientContracts'
    GET_PARTNER_CONTRACTS = 'GetPartnerContracts'
    GET_CURRENCY_RATE = 'GetCurrencyRate'
    GET_DSP_STAT = 'GetDspStat'
    INSTALLS = 'installs'
    INVOICE = 'invoice'
    INTEGRATION_CONFIG = 'integration_config'
    INTERBRANCH = 'interbranch'
    INVOICE_PRINT_FORM = 'invoice_print_form'
    KINOPOISK_PLUS = 'kinopoisk_plus'
    MAGAZIN = 'magazin'
    MANAGER = 'manager'
    MASTERCARD_DISCOUNT = 'mastercard_discount'
    MARKUP = 'markup'
    MARKET = 'market'
    MARKETPLACE = 'marketplace'
    MAILPRO = 'mail_pro'
    MEDICINE = 'telemedicine'
    MULTICURRENCY = 'multicurrency'
    MUSIC = 'music'
    NETTING = 'netting'
    NDS = 'nds'
    NON_RESIDENT = 'non-resident'
    NOTIFICATION = 'notification'
    NOTIFY = 'notify'  # Рассылки
    OEBS = 'oebs'
    OFFER = 'offer'
    OPERATION = 'operation'
    ORDER = 'order'
    OVERDRAFT = 'overdraft'
    PARTNER = 'partner'
    PARTNER_ACT = 'partner_act'
    PARTNER_COMPLETIONS = 'partner_completions'
    PARTNER_REWARD = 'partner_reward'
    PAYMENT = 'payment'
    PAYMETHOD_MARKUP = 'paymethod_markup'
    PAYSTEP = 'paystep'
    PERMISSION = 'permission'
    PERSON = 'person'
    PERSONAL_ACCOUNT = 'personal_account'
    PLUS = 'plus'
    PREPAYMENT = 'prepayment'
    PYCRON = 'pycron'
    PROMOCODE = 'promocode'
    REALTY = 'realty'
    REFUELLER = 'refueller'
    REFUND = 'refund'
    REFUND_API = 'refund_api'
    REQUEST = 'request'
    RETRODISCOUNT = 'retrodiscount'
    REVERSE = 'reverse'
    REVSHARE = 'revshare'
    ROLE = 'role'
    SEASON_COEFF = 'season_coeff'
    SIDEPAYMENT = 'sidepayment'
    SPENDABLE = 'spendable'
    SUPERCHECK = 'supercheck'
    SSP = 'ssp'
    STAGER = 'stager'
    STATION = 'station'
    SUBSIDY = 'subsidy'
    TAXI = 'taxi'
    TELEMEDICINE = 'telemedicine'
    TICKETS = 'tickets'
    TLOG = 'tlog'
    TPT = 'tpt'
    TRANSFER = 'transfer'
    TRAVEL = 'travel'
    TRUST = 'trust'
    TRUST_LOGIC = 'trust_logic'
    TRUST_API = 'trust_api'
    TVM = 'tvm'
    UFS = 'ufs'
    UI = 'ui'
    UNIFIED_ACCOUNT = 'unified_account'
    UNIFIED_CORP_CONTRACT = 'unified_corp_contract'
    UNIFIED_CORP_CONTRACT_CONTEXT_WITH_ZAXI = 'unified_corp_contract_with_zaxi'
    ZAXI = 'zaxi'
    UPRAVLIATOR = 'upravliator'
    XMLRPC = 'xmlrpc'
    CLOUD = 'cloud'
    DISK_B2B = 'disk_b2b'
    DRIVE_B2B = 'drive_b2b'
    DRIVE_CORP = 'drive_corp'
    INGAME_PURCHASES = 'ingame_purchases'
    ADVERTISEMENT = 'advertisement'
    TAXI_REQUEST = 'taxi_request'
    K50 = 'K50'
    TM_ONLY = 'tm_only'
    TO_UNIT = 'to_unit'     # кандидаты на перенос в юнит


class AuditFeatures(object):
    # ---------- AUDIT ----------
    # Взаимозачёт Такси
    RV_C02_1_Taxi = 'RV-C02-1.Taxi'
    # Взаимозачет Еда
    RV_C02_1_Eda = 'RV-C02-1.Eda'
    # Активация услуг сервиса_оферта
    RV_C03_2_Taxi = 'RV-C03-2.Taxi'
    # Активация услуг сервиса_платеж
    RV_C03_3_Taxi = 'RV-C03-3.Taxi'
    # Активация услуг сервиса
    RV_C03_5_Eda = 'RV-C03-5.Eda'
    # [?] Приостановление договора через 3 месяца (9\9 по фирмам)
    RV_C04_1 = 'RV-C04-1'
    # [+] НЕдействительность договора (5\5 тестов)
    RV_C04_3 = 'RV-C04-3'
    # [-] Способы зачисления на заказ (2\6 тестов)
    RV_C04_4 = 'RV-C04-4'
    # Такси БЮ: Зачисление средств на заказ в системе Баланс
    RV_C04_4_Taxi = 'RV-C04-4.Group/Taxi'
    # [+] Расчет субсидий осуществляется только после подписания договора
    RV_C04_8_Taxi = 'RV-C04-8.Taxi'
    # [-] Запрет на выставление в овердрафт (1\2) и кредит (2\4)
    RV_C04_11 = 'RV-C04-11'
    # Автоматическое списание средств с лицевого счета таксопарка
    RV_C04_11_Taxi = 'RV-C04-11.Taxi'
    # [-] Пересчёт кредитного лимита
    RV_C05_2 = 'RV-C05-2'
    # [+] RV_C04_3, но для Такси (0\0 тестов)
    RV_C06_4_Taxi = 'RV-C06-4.Taxi'
    # [+] Валютные курсы (0\0 тестов)
    RV_C09_6 = 'RV-C09-6'
    # [-] Расчёт стоимость услуг по медийной рекламе
    RV_C09_15 = 'RV-C09-15'
    # [-] Автоматическое формирование актов (
    RV_C10_1 = 'RV-C10-1'
    # Автоматическое формирование актов БЮ Такси
    RV_C10_1_Taxi = 'RV-C10-1 Group/Taxi'
    # [ ] Расчёт партнёрского вознаграждения
    RV_C11_1 = 'RV-C11-1'
    # платежи по такси и другим сервисам БЮ, нет номера контроля, но аудит такие тесты просматривал
    Taxi_Payments = 'TAXI_PAYMENTS'
    # [+] Работа с НЕрезидентами (3\3 теста)
    TR_C19 = 'TR-C19'
    # [+] РУЧНОЙ: задолженность по субсидиям
    TR_C43 = 'TR-C43'
    # [+] РУЧНОЙ: Проверка формирования проводок по исходящему НДС.
    TX_CB2 = 'TX_CB2'
    # [+] РУЧНОЙ: Проверка формирования проводок по НДС с авансов.
    TX_CB6_1 = 'TX_CB6.1'
    # [+] РУЧНОЙ: Проверка формирования проводок по сторно ранее учтенного НДС с авансов.
    TX_CB6_2 = 'TX_CB6.2'
    # [+] РУЧНОЙ: Реализованные курсовые разницы
    FR_C22 = 'FR_C22'