export const courierNameRecord: CouriersNameT = {
  courierForRemove: '12345678910',
  courierForSearch: 'courier_login',
  gumba: `Гумба`,
  kypa: `Купа`,
  spaini: `Спайни`,
  red: `Красный`,
  pink: `Розовый`,
  green: `Зеленый`,
  lightGreen: `Салатовый`,
  orange: `Оранжевый`,
  сarrot: `Морковный`,
  blue: `Синий`,
  lightBlue: `Голубой`,
  brown: `Коричневый`,
  vinous: `Бордовый`,
  courierWithSingleRoute: 'Курьер с одним маршрутом',
  john: 'John',
};

export const courierNumberRecord: CouriersNumberT = {
  courierForRemove: '10987654321',
  courierForSearch: '79665554433',
  gumba: '1',
  kypa: '2',
  spaini: '3',
  red: '1',
  pink: '2',
  green: '1',
  lightGreen: '2',
  orange: '1',
  сarrot: '2',
  blue: '1',
  lightBlue: '2',
  brown: '1',
  vinous: '2',
  courierWithSingleRoute: '1',
  john: '45678abcde',
};
