enum depotEnum {
  castlePeach = 'castlePeach',
  yoshisHouse = 'yoshisHouse',
  toadsTent = 'toadsTent',
  englishPub = 'englishPub',
  fourwordsallcapslock = 'fourwordsallcapslock',
  ONEWORDCAPSLOCK = 'ONEWORDCAPSLOCK',
  rocketjump5G = 'rocketjump5G',
  some = 'some',
  some2 = 'some2',
  additional1 = 'additional1',
  additional2 = 'additional2',
  additional3 = 'additional3',
  additional4 = 'additional4',

  compAVisible = 'compAVisible',
  compANotVisible = 'compANotVisible',
  compBVisible = 'compBVisible',
  compBNotVisible = 'compBNotVisible',
  compVVisible = 'compVVisible',
  compVNotVisible = 'compVNotVisible',
  compGVisible = 'compGVisible',
  compGNotVisible = 'compGNotVisible',
  compDVisible = 'compDVisible',
  compDNotVisible = 'compDNotVisible',
  compEVisible = 'compEVisible',
  compENotVisible = 'compENotVisible',
  depotLotOfOrders = 'depotLotOfOrders',
}

export const depotNameRecord: DepotNameRecordT = {
  castlePeach: `Замок Пич`,
  yoshisHouse: `Дом Йоши`,
  toadsTent: `Палатка Тоада`,
  englishPub: `English Pub`,
  fourwordsallcapslock: `fourwordsallcapslock`,
  ONEWORDCAPSLOCK: `ONEWORDCAPSLOCK`,
  rocketjump5G: `Rocketjump 5G`,
  some: `(_!_);`,
  some2: `ололоkek888;()`,
  additional1: `Дополнительный 1`,
  additional2: `Дополнительный 2`,
  additional3: `Дополнительный 3`,
  additional4: `Дополнительный 4`,

  compAVisible: `Комп. А видимый`,
  compANotVisible: `Комп. А невидимый`,
  compBVisible: `Комп. Б видимый`,
  compBNotVisible: `Комп. Б невидимый`,
  compVVisible: `Комп. В видимый`,
  compVNotVisible: `Комп. В невидимый`,
  compGVisible: `Комп. Г видимый`,
  compGNotVisible: `Комп. Г невидимый`,
  compDVisible: `Комп. Д видимый`,
  compDNotVisible: `Комп. Д невидимый`,
  compEVisible: `Комп. Е видимый`,
  compENotVisible: `Комп. Е невидимый`,

  depotLotOfOrders: 'lotofordersDEPOT',
};

export const depotNumberRecord: Record<depotEnum, string> = {
  [depotEnum.castlePeach]: '1',
  [depotEnum.yoshisHouse]: '2',
  [depotEnum.toadsTent]: '3',
  [depotEnum.englishPub]: '4',
  [depotEnum.fourwordsallcapslock]: '5',
  [depotEnum.ONEWORDCAPSLOCK]: '6',
  [depotEnum.rocketjump5G]: '7',
  [depotEnum.some]: '8',
  [depotEnum.some2]: '9',
  [depotEnum.additional1]: '10',
  [depotEnum.additional2]: '11',
  [depotEnum.additional3]: '12',
  [depotEnum.additional4]: '13',

  [depotEnum.compAVisible]: '1',
  [depotEnum.compANotVisible]: '2',
  [depotEnum.compBVisible]: '1',
  [depotEnum.compBNotVisible]: '2',
  [depotEnum.compVVisible]: '1',
  [depotEnum.compVNotVisible]: '2',
  [depotEnum.compGVisible]: '1',
  [depotEnum.compGNotVisible]: '2',
  [depotEnum.compDVisible]: '1',
  [depotEnum.compDNotVisible]: '2',
  [depotEnum.compEVisible]: '1',
  [depotEnum.compENotVisible]: '2',

  [depotEnum.depotLotOfOrders]: '14',
};

export const depotAddressRecord = {
  [depotEnum.castlePeach]: 'Россия, Санкт-Петербург, Пискаревский проспект, 2к2',
};
