MainObjectType: "PN_Collections#OT_Card"

ObjectIdMappingConfig {
    Wad: "object_id_mapping.wad"
}
CounterKeyTypeMappingFilename: "counter_key_type_mapping.proto"

ObjectTypeIndexBuilder {
    [NDJ.EmbeddingsWadIndexBuilder] {
        ObjectType: "PN_Collections#OT_Card"
        EmbeddingKeyProvider {
            EmbeddingKey: {
                EmbeddingType: "PN_Collections#ET_TextHistoryDssmCard"
                Version: 0
                Reducer: RT_Sum
            }
            EmbeddingFormat: EF_i8
            Multiplier: 1.0
            Wad: "OT_Card_ET_TextHistoryDssmCard.wad"
        }
    }
}

ObjectTypeIndexBuilder {
    [NDJ.CountersWadIndexBuilder] {
        ObjectType: "PN_Collections#OT_Card"
        Wad: "card_counters.wad"
        CounterSlices {
            ObjectType: "PN_Collections#OT_Flag"
            CounterType: "PN_Collections#CT_CardFlags"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_OntoId"
            CounterType: "PN_Collections#CT_CardOntoId"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_ContentImageStats"
            CounterType: "PN_Collections#CT_CardStats"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Stats"
            CounterType: "PN_Collections#CT_CardStats"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_CardText"
            CounterType: "PN_Collections#CT_CardText"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Flag"
            CounterType: "PN_Collections#CT_Freshness"
            Reducer: RT_Sum_7d
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Flag"
            CounterType: "PN_Collections#CT_Freshness"
            Reducer: RT_Sum_21d
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Board"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_BroadTheme"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Channel"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_Image"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_ImageDup"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_ImageSemidup"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_MainContentType"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
    }
}
ObjectTypeIndexBuilder {
    [NDJ.CountersWadIndexBuilder] {
        ObjectType: "PN_Collections#OT_Board"
        Wad: "board_counters.wad"
        CounterSlices {
            ObjectType: "PN_Collections#OT_Card"
            CounterType: "PN_Collections#CT_Link"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_ImageText"
            CounterType: "PN_Collections#CT_ImageText"
            Reducer: RT_Sum
        }
        CounterSlices {
            ObjectType: "PN_Collections#OT_BoardText"
            CounterType: "PN_Collections#CT_BoardTitle"
            Reducer: RT_Sum
        }
    }
}
