#pragma once

#include <limits>
#include <map>
#include <string>

#include <maps/indoor/libs/indoor_positioning/include/common.h>

namespace INDOOR_POSITIONING_NAMESPACE {

namespace {

[[maybe_unused]] const auto inf = std::numeric_limits<double>::infinity();

} // namespace

const auto TEST_METRICS = std::map<std::pair<std::string, std::string>, double>{
        {{"Skolkovo_level_1_track_26_android_old_indoor", "median_50"}, 5.0},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "median_70"}, 7.8},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "median_90"}, 12.6},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "duration"}, 274.4},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_26_android_indoor", "median_50"}, 5.7},
        {{"Skolkovo_level_1_track_26_android_indoor", "median_70"}, 9.8},
        {{"Skolkovo_level_1_track_26_android_indoor", "median_90"}, 20.0},
        {{"Skolkovo_level_1_track_26_android_indoor", "duration"}, 274.4},
        {{"Skolkovo_level_1_track_26_android_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_26_android_fused", "median_50"}, 6.1},
        {{"Skolkovo_level_1_track_26_android_fused", "median_70"}, 8.3},
        {{"Skolkovo_level_1_track_26_android_fused", "median_90"}, 11.1},
        {{"Skolkovo_level_1_track_26_android_fused", "duration"}, 274.4},
        {{"Skolkovo_level_1_track_26_android_fused", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_fused", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_26_android_fused", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_30_android_old_indoor", "median_50"}, 3.4},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "median_70"}, 4.7},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "median_90"}, 6.1},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "duration"}, 240.2},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_30_android_indoor", "median_50"}, 4.7},
        {{"Skolkovo_level_1_track_30_android_indoor", "median_70"}, 7.7},
        {{"Skolkovo_level_1_track_30_android_indoor", "median_90"}, 12.0},
        {{"Skolkovo_level_1_track_30_android_indoor", "duration"}, 240.2},
        {{"Skolkovo_level_1_track_30_android_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_30_android_fused", "median_50"}, 9.4},
        {{"Skolkovo_level_1_track_30_android_fused", "median_70"}, 11.0},
        {{"Skolkovo_level_1_track_30_android_fused", "median_90"}, 15.0},
        {{"Skolkovo_level_1_track_30_android_fused", "duration"}, 240.2},
        {{"Skolkovo_level_1_track_30_android_fused", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_fused", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_30_android_fused", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_31_android_old_indoor", "median_50"}, 5.3},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "median_70"}, 8.9},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "median_90"}, 14.2},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "duration"}, 296.2},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_31_android_indoor", "median_50"}, 8.2},
        {{"Skolkovo_level_1_track_31_android_indoor", "median_70"}, 11.2},
        {{"Skolkovo_level_1_track_31_android_indoor", "median_90"}, 24.4},
        {{"Skolkovo_level_1_track_31_android_indoor", "duration"}, 296.2},
        {{"Skolkovo_level_1_track_31_android_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_31_android_fused", "median_50"}, 8.2},
        {{"Skolkovo_level_1_track_31_android_fused", "median_70"}, 10.5},
        {{"Skolkovo_level_1_track_31_android_fused", "median_90"}, 13.3},
        {{"Skolkovo_level_1_track_31_android_fused", "duration"}, 296.2},
        {{"Skolkovo_level_1_track_31_android_fused", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_fused", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_31_android_fused", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_9a_android_old_indoor", "median_50"}, 7.5},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "median_70"}, 9.3},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "median_90"}, 12.1},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "duration"}, 219.2},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_9a_android_indoor", "median_50"}, 4.5},
        {{"Skolkovo_level_1_track_9a_android_indoor", "median_70"}, 6.8},
        {{"Skolkovo_level_1_track_9a_android_indoor", "median_90"}, 10.8},
        {{"Skolkovo_level_1_track_9a_android_indoor", "duration"}, 219.2},
        {{"Skolkovo_level_1_track_9a_android_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_9a_android_fused", "median_50"}, 5.5},
        {{"Skolkovo_level_1_track_9a_android_fused", "median_70"}, 9.2},
        {{"Skolkovo_level_1_track_9a_android_fused", "median_90"}, 12.6},
        {{"Skolkovo_level_1_track_9a_android_fused", "duration"}, 219.2},
        {{"Skolkovo_level_1_track_9a_android_fused", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_fused", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_9a_android_fused", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_dc_android_old_indoor", "median_50"}, 7.3},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "median_70"}, 10.0},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "median_90"}, 14.4},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "duration"}, 302.2},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_dc_android_indoor", "median_50"}, 10.0},
        {{"Skolkovo_level_1_track_dc_android_indoor", "median_70"}, 13.4},
        {{"Skolkovo_level_1_track_dc_android_indoor", "median_90"}, 18.1},
        {{"Skolkovo_level_1_track_dc_android_indoor", "duration"}, 302.2},
        {{"Skolkovo_level_1_track_dc_android_indoor", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_indoor", "level_switch_count"}, 0.0},

        {{"Skolkovo_level_1_track_dc_android_fused", "median_50"}, 12.1},
        {{"Skolkovo_level_1_track_dc_android_fused", "median_70"}, 14.4},
        {{"Skolkovo_level_1_track_dc_android_fused", "median_90"}, 17.2},
        {{"Skolkovo_level_1_track_dc_android_fused", "duration"}, 302.2},
        {{"Skolkovo_level_1_track_dc_android_fused", "no_solution_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_fused", "level_mismatch_time"}, 0.0},
        {{"Skolkovo_level_1_track_dc_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "median_50"}, 3.6},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "median_70"}, 4.7},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "median_90"}, 7.9},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "duration"}, 263.6},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "median_50"}, 4.6},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "median_70"}, 9.9},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "median_90"}, 26.3},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "duration"}, 263.6},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "no_solution_time"}, 5.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "level_mismatch_time"}, 30.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "median_50"}, 7.5},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "median_70"}, 10.9},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "median_90"}, 16.9},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "duration"}, 263.6},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "no_solution_time"}, 5.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "level_mismatch_time"}, 30.0},
        {{"Ohotnyi_Ryad_level_1_track_81_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "median_50"}, 2.7},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "median_70"}, 4.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "median_90"}, 6.9},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "duration"}, 98.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "median_50"}, 5.8},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "median_70"}, 12.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "median_90"}, 20.4},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "duration"}, 98.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "level_mismatch_time"}, 6.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "median_50"}, 5.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "median_70"}, 8.7},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "median_90"}, 13.9},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "duration"}, 98.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "level_mismatch_time"}, 6.2},
        {{"Ohotnyi_Ryad_level_1_track_86_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "median_50"}, 5.5},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "median_70"}, 8.8},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "median_90"}, 25.4},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "duration"}, 261.2},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "level_mismatch_time"}, 41.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "median_50"}, 7.2},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "median_70"}, 11.8},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "median_90"}, 19.2},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "duration"}, 261.2},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "level_mismatch_time"}, 41.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "median_50"}, 8.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "median_70"}, 11.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "median_90"}, 19.3},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "duration"}, 261.2},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "level_mismatch_time"}, 41.0},
        {{"Ohotnyi_Ryad_level_2_track_49_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "median_50"}, 3.8},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "median_70"}, 5.8},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "median_90"}, 8.9},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "duration"}, 285.2},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "median_50"}, 13.4},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "median_70"}, 19.4},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "median_90"}, 29.5},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "duration"}, 285.2},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "no_solution_time"}, 2.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "median_50"}, 6.6},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "median_70"}, 11.2},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "median_90"}, 21.4},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "duration"}, 285.2},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "no_solution_time"}, 2.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_62_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "median_50"}, 3.9},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "median_70"}, 5.7},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "median_90"}, 8.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "duration"}, 227.2},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "median_50"}, 6.7},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "median_70"}, 9.6},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "median_90"}, 13.9},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "duration"}, 227.2},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "median_50"}, 5.6},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "median_70"}, 7.1},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "median_90"}, 11.4},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "duration"}, 227.2},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_2_track_95_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "median_50"}, 4.2},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "median_70"}, 5.6},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "median_90"}, 7.1},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "duration"}, 204.2},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "median_50"}, 5.7},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "median_70"}, 7.9},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "median_90"}, 16.3},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "duration"}, 204.2},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "median_50"}, 6.7},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "median_70"}, 8.1},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "median_90"}, 11.2},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "duration"}, 204.2},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_3c_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "median_50"}, 4.5},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "median_70"}, 5.7},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "median_90"}, 8.4},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "duration"}, 136.2},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "median_50"}, 8.7},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "median_70"}, 14.1},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "median_90"}, 24.8},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "duration"}, 136.2},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "no_solution_time"}, 1.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "median_50"}, 4.7},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "median_70"}, 6.7},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "median_90"}, 14.4},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "duration"}, 136.2},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "no_solution_time"}, 1.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_48_android_fused", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "median_50"}, 4.1},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "median_70"}, 5.8},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "median_90"}, 8.6},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "duration"}, 225.4},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_old_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "median_50"}, 7.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "median_70"}, 12.6},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "median_90"}, 21.4},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "duration"}, 225.4},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_indoor", "level_switch_count"}, 0.0},

        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "median_50"}, 6.6},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "median_70"}, 7.9},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "median_90"}, 15.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "duration"}, 225.4},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "no_solution_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "level_mismatch_time"}, 0.0},
        {{"Ohotnyi_Ryad_level_3_track_ce_android_fused", "level_switch_count"}, 0.0},
    };

} // INDOOR_POSITIONING_NAMESPACE
