load("//tools:defaults.bzl", "scala_library")

scala_library(
    name = "testkit",
    srcs = glob(["src/*.scala"]),
    deps = [
        "@maven//:dev_zio_zio_2_13",
        "@maven//:org_typelevel_cats_core_2_13",
    ],
)
