const getAvailableCondition = require('realty-router/lib/filters/getAvailableCondition');

describe('getAvailableCondition', () => {
    it('should get available filters for empty matching params', () => {
        const params = {};
        const condition = getAvailableCondition('SELL', params);

        expect(condition.filters).toEqual([
            's-vidom-na-kreml', 'elitnye-penthouse',
            'business-klass', 'loft-econom-klassa',
            'ryadom-metro', 'elit-premium-klass', 'evroplanirovka',
            's-terrasoi', 'raspashonki',
            'v-vysotke-stalinke',
            'v-putinke', '1-etazh', 's-terrasoi',
            'penthouse-s-terrasoy', 'novostroyki-s-basseinom',
            'novostroyki-s-terrasoi',
            'ryadom-s-zalivom',
            'podzemnaya-parkovka',
            'deshevie',
            'ryadom-s-morem',
            '8m',
            '9m',
            '12m',
            '13m',
            '14m',
            '15m',
            '16m',
            '17m',
            '18m',
            '20m',
            '23m',
            '26m',
            '30m',
            '34m',
            '40m',
            '50m',
            '70m',
            '120m',
            '200m',
            '300m',
            '400m',
            '500m',
            '600m',
            '1000m',
            'ryadom-s-lesom',
            'ryadom-s-ozerom',
            'ryadom-s-prudom',
            'ryadom-s-rekoy',
            'ryadom-s-vodokhranilishem',
            's-remontom', 'bez-remonta',
            'dizain-remont', 'sovremenniy-remont',
            'vtorichniy-rynok', 'novostroyki',
            'bez-posrednikov', 'apartamenty',
            's-parkovkoy', 'kirpich',
            'monolit', 'panel',
            'khrushevskiy', 'stalinskiy',
            'brezhnevskiy', 'pod-snos',
            's-mebeliu', 's-vodoyomom',
            's-parkom', 's-lodzhiej',
            's-balkonom', 's-bolshoy-kuhney',
            's-vysokimi-potolkami', 'razdelniy-sanuzel',
            'loft', 'penthouse',
            'dvuhurovnevye',
            'v-neboskrebah', 'kirpichno-monolitnye',
            'blochnye', 'bolshie-kvartiry',
            'malenkye-kvartiry', '10m',
            '100m', '11m',
            'do-800000', 'do-500000',
            'do-1000000', 'do-1500000',
            'do-2000000', 'do-2500000',
            'do-3000000', 'do-3500000',
            'do-4000000', 'do-5000000',
            'do-6000000', 's-obmenom',
            's-pereustupkoy', 'seriya-137',
            'seriya-504', 'seriya-bashnya-vulha',
            'seriya-p44', 'seriya-p44k',
            'seriya-p44t', 'seriya-p46',
            'seriya-p47', 'dvuhurovnevye', 'penthouse',
            'v-pyatietazhnom-dome',
            'v-maloetazhnom-dome', 'v-vysotke',
            'loft', 's-panoramnymi-oknami',
            'pod-kluch', 'v-mnogoetazhnom-dome',
            's-otdelkoy', 's-basseinom',
            'podzemniy-parking',
            'deshevye', 'v-ipoteku',
            'ryadom-fitness',
            'ryadom-detskiy-sad',
            'ryadom-shkola',
            'kommunalnye-kvartiry',
        ]);
    });

    it('should get available filters for one matching param', () => {
        const params = {
            metroGeoId: '322'
        };
        const condition = getAvailableCondition('SELL', params);

        expect(condition.filters).toEqual([
            's-vidom-na-kreml', 'elitnye-penthouse',
            'business-klass', 'loft-econom-klassa',
            'elit-premium-klass',
            'evroplanirovka',
            's-terrasoi', 'raspashonki',
            'v-vysotke-stalinke', 'v-putinke',
            '1-etazh', 's-terrasoi',
            'penthouse-s-terrasoy', 'novostroyki-s-basseinom',
            'novostroyki-s-terrasoi',
            'ryadom-s-zalivom',
            'podzemnaya-parkovka', 'deshevie', 'ryadom-s-morem',
            '8m',
            '9m',
            '12m',
            '13m',
            '14m',
            '15m',
            '16m',
            '17m',
            '18m',
            '20m',
            '23m',
            '26m',
            '30m',
            '34m',
            '40m',
            '50m',
            '70m',
            '120m',
            '200m',
            '300m',
            '400m',
            '500m',
            '600m',
            '1000m',
            'ryadom-s-lesom',
            'ryadom-s-ozerom',
            'ryadom-s-prudom',
            'ryadom-s-rekoy',
            'ryadom-s-vodokhranilishem',
            's-remontom',
            'bez-remonta', 'dizain-remont',
            'sovremenniy-remont', 'vtorichniy-rynok',
            'novostroyki', 'bez-posrednikov',
            'apartamenty', 's-lodzhiej',
            's-balkonom', 's-bolshoy-kuhney',
            's-vysokimi-potolkami', 'razdelniy-sanuzel', 'loft', 'penthouse',
            'dvuhurovnevye',
            'v-neboskrebah', 'kirpichno-monolitnye',
            'blochnye', 'bolshie-kvartiry',
            'malenkye-kvartiry', '10m',
            '100m', '11m',
            'do-800000', 'do-500000',
            'do-1000000', 'do-1500000',
            'do-2000000', 'do-2500000',
            'do-3000000', 'do-3500000',
            'do-4000000', 'do-5000000',
            'do-6000000',
            's-obmenom', 's-pereustupkoy',
            'seriya-137', 'seriya-504',
            'seriya-bashnya-vulha', 'seriya-p44',
            'seriya-p44k', 'seriya-p44t',
            'seriya-p46', 'seriya-p47', 'dvuhurovnevye', 'penthouse',
            'v-pyatietazhnom-dome', 'v-maloetazhnom-dome',
            'v-vysotke', 'loft', 's-panoramnymi-oknami',
            'v-mnogoetazhnom-dome', 'pod-kluch',
            's-otdelkoy', 's-basseinom',
            'podzemniy-parking', 'deshevye', 'v-ipoteku',
            'ryadom-fitness',
            'ryadom-detskiy-sad',
            'ryadom-shkola',
            'kommunalnye-kvartiry',
        ]);
    });

    it('should get available filters for many matching params', () => {
        const params = {
            roomsTotal: 1,
            metroGeoId: 322
        };
        const condition = getAvailableCondition('SELL', params);

        expect(condition.filters).toEqual([
            'gostinichnogo-tipa',
            'dvuhurovnevye-econom-klass',
            'loft-econom-klass',
            'bolshie-studii',
            'malenkye-studii',
            'loft-econom-klassa',
            'ekonom-klass',
            'studii-11m',
            'studii-12m',
            'studii-23m',
            'v-vysotke-stalinke',
            'v-putinke', '1-etazh', 's-terrasoi',
            'penthouse-s-terrasoy', 'novostroyki-s-basseinom',
            'novostroyki-s-terrasoi',
            'ryadom-s-zalivom', 'podzemnaya-parkovka', 'deshevie', 'ryadom-s-morem',
            '8m',
            '9m',
            '12m',
            '13m',
            '14m',
            '15m',
            '16m',
            '17m',
            '18m',
            '20m',
            '23m',
            '26m',
            '30m',
            '34m',
            '40m',
            '50m',
            '70m',
            '120m',
            '200m',
            '300m',
            '400m',
            '500m',
            '600m',
            '1000m',
            'ryadom-s-lesom',
            'ryadom-s-ozerom',
            'ryadom-s-prudom',
            'ryadom-s-rekoy',
            'ryadom-s-vodokhranilishem',
            's-lodzhiej',
            's-balkonom',
            's-bolshoy-kuhney',
            's-vysokimi-potolkami',
            'razdelniy-sanuzel',
            'do-800000', 'do-500000',
            'do-1000000', 'do-1500000',
            'do-2000000', 'do-2500000',
            'do-3000000', 'do-3500000',
            'do-4000000', 'do-5000000',
            'do-6000000', 'v-mnogoetazhnom-dome', 'pod-kluch',
            's-otdelkoy', 's-basseinom',
            'podzemniy-parking',
            'deshevye', 'v-ipoteku',
            'ryadom-fitness',
            'ryadom-detskiy-sad',
            'ryadom-shkola',
            'kommunalnye-kvartiry',
        ]);
    });

    it('should not get available filters for excess count of matching params', () => {
        const params = {
            roomsTotal: 1,
            metroGeoId: 322,
            subLocality: 123
        };
        const condition = getAvailableCondition('SELL', params);

        expect(condition.filters).toEqual([]);
    });
});
