#!/bin/bash
TEST_DIR="/intranet/paste/tests"

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ARC_ROOT="$(realpath ${MY_DIR}/../../../)"
DOT_ENV="${MY_DIR}/../.env"

# use arc root
export Y_PYTHON_SOURCE_ROOT=$ARC_ROOT
export Y_PYTHON_ENTRY_POINT="${Y_PYTHON_ENTRY_POINT:=:main}"
export NO_MIGRATE_DB=True
export PYCHARM_TEST_RUN=True
export PYTHONWARNINGS=ignore

# if [ -f "${DOT_ENV}" ]
#then
#  echo "Dotenv found and loaded"
#  export $(cat "${DOT_ENV}" | sed 's/#.*//g' | xargs)
#else
#  echo "No .env is loaded! Have you copied .env.example to .env?"
#  exit -1
#fi


export DJANGO_SETTINGS_MODULE=intranet.paste.src.unittest_settings
export TESTS=1
export ARC=1

export PYTHONPATH="${PYTHONPATH}:${ARC_ROOT}/intranet/paste/tests:${ARC_ROOT}/intranet/paste/src"

export PG_LOCAL_DATABASE=postgres
export PG_LOCAL_USER=postgres
export PG_LOCAL_PORT=5433
export PG_LOCAL_PASSWORD=postgres

${MY_DIR}/run-tests "$@"
