DISABLE_DATA_VALIDATION(
    sbr://2621856804  # GEODATA6BIN_STABLE  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2622946140  # TSAR_DUMPS_LIST  # AUTO UPDATED RESOURCE  # robdrynkin_bsdev_75076_prod_v3_vinyl_uint16
    sbr://2380921696  # CRYPTA_REAL_TIME_SOCDEM_MODELS  # AUTO UPDATED RESOURCE  rt_socdem
    sbr://2622946636  # CRYPTA_LOOKALIKE_PARENT_TO_LAL_MAPPING  # AUTO UPDATED RESOURCE  mapping.json
    sbr://2622912405  # CRYPTA_AUDIENCE_SEGMENTS_PRIORITIES_VINYL  # AUTO UPDATED RESOURCE  priorities.vinyl
    sbr://2619668694  # CRYPTA_REAL_TIME_PRISM_MODEL  # AUTO UPDATED RESOURCE  prism_rt_model
)

SET(EAGLE_RESOURCES

    sbr://3358317045  # BS_YETI_HEAVY_BASES  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2622930990  # BS_YETI_LIGHT_CONFIGS  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2621856804  # GEODATA6BIN_STABLE  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://1150327925  # BIGB_CODECS_FOLDER  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2620413911  # BIGB_COUNTERS_IDF_BASE  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE

    sbr://1338416714=jamshid_dssm_pack   # jruziev_dssmtsar2_ctr_bc_50_2l.appl.query
    sbr://1338402966=jamshid_dssm_pack   # jruziev_tsar_searchBC1.appl.query

    sbr://1589892031=future_prgg_pack   # ab_tsar.appl.query
    sbr://1589954382=future_prgg_pack   # future_prgg_v2.appl.query

    sbr://2622946140  # TSAR_DUMPS_LIST  # AUTO UPDATED RESOURCE  # robdrynkin_bsdev_75076_prod_v3_vinyl_uint16
    sbr://2622944957=pytorch_tsar_models  # TORCH_TSAR_USER_MODEL  # AUTO UPDATED RESOURCE  # UserNamespaces_3
    sbr://2622944957=torch_v2_model_float16  # TORCH_TSAR_USER_MODEL  # AUTO UPDATED RESOURCE  # fake torch v2 model  # UserNamespaces_3
    sbr://2622924121  # BIGB_AB_EXPERIMENTS_PRODUCTION_CONFIG  # AUTO UPDATED RESOURCE
    sbr://1625663443=query_banner_dssm   # assessor.appl.scale_before_dot
    sbr://1633564729=tsar_organic_conv_search # tsar_mixagol_search_bc_organic_conv
    sbr://1597931701=alb_fresh_dssm_pack # alb_fresh.appl.query
    sbr://1648100505=basyl_dssm_pack # model_rsya_apply
    sbr://2380921696  # CRYPTA_REAL_TIME_SOCDEM_MODELS  # AUTO UPDATED RESOURCE  rt_socdem
    sbr://2622946636  # CRYPTA_LOOKALIKE_PARENT_TO_LAL_MAPPING  # AUTO UPDATED RESOURCE  mapping.json
    sbr://2622912405  # CRYPTA_AUDIENCE_SEGMENTS_PRIORITIES_VINYL  # AUTO UPDATED RESOURCE  priorities.vinyl
    sbr://1983565593 # mobile_app_categories
    sbr://2619668694  # CRYPTA_REAL_TIME_PRISM_MODEL  # AUTO UPDATED RESOURCE  prism_rt_model
    sbr://2102155672 # CRYPTA_DMP_KEYWORD_TO_CRYPTA_DMP_MAPPING keyword_to_dmp_mapping_v1.vinyl
)

TAG(sb:~intel_e5645)
