#pragma once

#include <string>

namespace quasar {

    namespace TestUtils {

        struct TestKeys {
            const std::string PRIVATE_PEM =
                "-----BEGIN PRIVATE KEY-----\n"
                "MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQC/tsszPS+WHMLo\n"
                "9znSMV2I8fR7KOgewwmnX430yvjouii1dUvuSYzFd/axq5QORl4Eo2p5EH7PWjW+\n"
                "Z5bAkFNDQFynin9I4oSqLASiqCQqNzFzIJp8tclf1/iYMqX0RHt2AhjTLJP+WTAB\n"
                "fibc2VGywawzDO+6wa65EbnZH8WOWg4JBuANqclM6KnqBstBq7Se2Vo5XBGHvAvl\n"
                "PWpDhMpEkigGLlbYee6hiGQ0MIey9wWL94E5r5gYUcQd0lg569RDuZU2ZBwPpQbX\n"
                "PR4Rl7tplqcbmwWJWcR/OzCL55s6fEIL209VNSx+yc5ozY4cs34JMljpXCJ0Pvh9\n"
                "ZC5nU4lFsO5pRpzsY6KwfwdoFAvNsHEooPiGayusDORyRk3aWzuYM/6g8IkxXy8f\n"
                "K9WoGMGLpd7KxMhUs0ZvsJUcZMsNjWRNVNO/N44HEAaksJ3Of9KZjeJe/4+KiNmG\n"
                "7gndN5AfiYHJrSoSjCpAeHhfNF+8jUhmzBm3HCxGWMVERSub22Dhk8+t7LbgNL9g\n"
                "vGC2KzXMeaL4nieRwx+yQLKIJkh8lcYYKfbyhWoS6WCuGCTFZKcugUrc/05XyIMg\n"
                "uCZR/THnLVu3/h6n4pQjrX5ZtV7p+OwQTkc853BlLNOwCi5WrvqwJAjyj9NBR5cS\n"
                "bFnNROrYtk25oBWs6BDPqxEN+iQ9rwIDAQABAoICAEYPeSbaf19uV1RntLu5yqLX\n"
                "OS8g/eLwB8EgzHHfEyOJlILrwLnuKwGnG4JGX67vzEAJsElZ293O68EPfioVFDiJ\n"
                "dtLLbESocy71MyR2KfE7hli6W3qjvFnIRVLpf3hK5otzrLrPma3jzgVdoromuRKI\n"
                "cHOfkKRBT6bWcYKFd97TzjlCR/L2T1hJ1n5tyS3QoAtFBxHbMZTXBcnardDK4Fg6\n"
                "yWGo4Zfux2REwcnIym5+k4pZAuKf5wdMKk1zp0ZThpjRY1QjNZYKCvvxm+F1/8lQ\n"
                "gvU1q8pMAeE1MkKOe03eRwyqMs3CxuX2vfXS2NJoTfDyc0ekofq1YH4CdGrSPmGU\n"
                "Qjb5lSUiS8+I9vAaXMdbe5FUWhY2riICVld6J2vxA9OpbwCwlzpDOyjorZZbf3iu\n"
                "IV0CHtFqGzMxeTcH16PVYyvtzGvLOPZFuyTHbm1H3N5PE1QgUZ0RfI7clLaWMfpF\n"
                "Ie7WFFqCqOqA095LyVM5LDsDt9Kviy6+YcNzmHx6BU1lq/VSV+uqOZHXuKfUmOuh\n"
                "RZCJdsRW0aPyaPYosGeXWlNo6WmRcc5dEcbaGzXx/m+NZ4W93y4JGLh2rEJKE6Zs\n"
                "ZTkmvaGHQoYs2TO9tUVA0DXp9FgLW4ygJM9FN8qjQyMOEwudPcMPLZC19ie+aOXy\n"
                "2s9uT1VTyWvpt+StNFRBAoIBAQD8UMsiA7PmhdX+73Z1kBN7PJmkzq5JxU/K4rcD\n"
                "/CP9zn5taWP1WmviefI+3YB+jvGAoRYLq1s67T/+nuhCLVXMNQWW/e9lssG9hPKR\n"
                "1TWV5Jw1DeSaT4XSIru0huazVRGdTP9e2mEnHj14iABb+Wqf7Tlh21e7mqwILbj3\n"
                "IAxQ1UL6ALZfznTNUWr1fKyB7dvzTKI6Lb7HXReowgcWOOuDgVW0PKhpwPVdYJTY\n"
                "zwiw/NBvjmXHqMZ8G3Iu4y/VI3oF7tAnLmlAVsDsx+kaqmEu8hMh2c6Uj4ClGfqA\n"
                "ub0FV5WbW6erkfOE4WoZlBI9LuMjV5lS7NLy67xO5By4nQeRAoIBAQDCg3Wc2Qak\n"
                "OV+XOCYb9kSw3cxnjP0gmuvTm5GRITnw6iHzMQR2Yl5VgcKdgKQuU6aBklQqLr6V\n"
                "6EwZYi2KHt1uzhUWRY7rm9kZoFigV4sksiE4O4yidSucFMnjFdv0m61pPkLQFWka\n"
                "9RULoPCPgVSzcwh5f50PJFDoaYT2ZYSclzZqgZGIMQTJ53id99wc7WFl2fwD6UIn\n"
                "HV267OKdGyENzS9d7OLCHYqWBm1kVt6dmXZgrFWjo01xMDCFJmQq8WlIvGS1SATy\n"
                "XQ1rRZ9ejvaQPZlxqunpk1AFeeGNvbbPkFoTzZOSxPIKGuIG+oQE12IctlpaCtHC\n"
                "Bbet+Cf+MtE/AoIBAQCLaFBz4LvbWIMeMkyvNAWvh5IUnyVpGR23KYCZMQzpxNfR\n"
                "t/NEssr8/Qe9eEDwrCX/PgGiPPFRI5jCJCaLueS3yWvnOzK0bAnjnrsvnC/ZO9Ca\n"
                "96whHmL/8bToT8jTuOLcmJhYXixjoq+wEuSv7KTe7AFSchCNVS5L7odN82UanFo/\n"
                "K3mYgcfDUYLZVCM0PqnSSbswjenk2SijU2D7BEQMCr/Br+oVVEm9aAmVqP5SW70G\n"
                "hhTyNexE0h1Kjrf0+X8IHCTiISCCLey2ZtYCp7S+bX3orCEZsBgSIMJpsTYg531/\n"
                "syp2/1MfTjSDIW7aYzeYZWQPj04Wbe1DYYIE9q4hAoIBAQCGL6BEaueNBVNvg7mu\n"
                "ko7CoNAxI29APf+wRGMAhrZs/2gaV9dnP+cp/9FdTHB20RhNzL+pNgQecFmHLVaT\n"
                "MUW6+gpMCgJVgXccmaRqQNppn0URgOs8664BB8pakSrjLT5NGzmGSS7v/ODe29D4\n"
                "ftUK0rGm96VG29vA6YJjZJc+W4abpPTbyk0uaDOqbmH3xr7pP57+p70ONNEDcgXH\n"
                "Mf70gXdKyW+JUE3Zv2dZ0B/VAxhKCrktoSt8iSz/vgNeKJpkJisncB6RgCYQub/+\n"
                "wItR6FzhsHGbxBdxH6q9WIIz4LZzcN98YcdDt1X0UIAgwuEZQ6dC9LHNspoLNuWI\n"
                "FFCLAoIBAQDKrPPOTSPWOZQTPa5nrEXBrNVZkyXdHDCVDSuBweKDwEAWtIWrrd9z\n"
                "u7oYOr26zhwBH68xDOZReV5+T88nTLBcu3nIRumHZlRCHWWl4+pYnzuIOjaxXIRv\n"
                "mUZvHPNnacozlo1aovh/EP7l5H0TkaJHjw9AxehH3/tW758LFcGGgmMOQ+6ao8Rb\n"
                "LsEF+9f+nYzinh2R/1TvJSSQekqIUXkjrpemmwAURz/ghkbK6jkSpY8RUjqgfhHi\n"
                "QzrQXLKibwV9oMIY4Hng81+apjWCoDzBrUHXVGQHpMO4ePd7yB80x2yuIiy+LdpR\n"
                "2U5f5aK141LJDHxJaaNTrAZRXjX+HF+b\n"
                "-----END PRIVATE KEY-----\n"
                "-----BEGIN CERTIFICATE-----\n"
                "MIIFCTCCAvGgAwIBAgIUVnBKmTUSk7F7h7fqqFNeWh96zBowDQYJKoZIhvcNAQEL\n"
                "BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIxMTAxMTA5MDE0MFoXDTQzMDkw\n"
                "NjA5MDE0MFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIICIjANBgkqhkiG9w0BAQEF\n"
                "AAOCAg8AMIICCgKCAgEAv7bLMz0vlhzC6Pc50jFdiPH0eyjoHsMJp1+N9Mr46Loo\n"
                "tXVL7kmMxXf2sauUDkZeBKNqeRB+z1o1vmeWwJBTQ0Bcp4p/SOKEqiwEoqgkKjcx\n"
                "cyCafLXJX9f4mDKl9ER7dgIY0yyT/lkwAX4m3NlRssGsMwzvusGuuRG52R/FjloO\n"
                "CQbgDanJTOip6gbLQau0ntlaOVwRh7wL5T1qQ4TKRJIoBi5W2HnuoYhkNDCHsvcF\n"
                "i/eBOa+YGFHEHdJYOevUQ7mVNmQcD6UG1z0eEZe7aZanG5sFiVnEfzswi+ebOnxC\n"
                "C9tPVTUsfsnOaM2OHLN+CTJY6VwidD74fWQuZ1OJRbDuaUac7GOisH8HaBQLzbBx\n"
                "KKD4hmsrrAzkckZN2ls7mDP+oPCJMV8vHyvVqBjBi6XeysTIVLNGb7CVHGTLDY1k\n"
                "TVTTvzeOBxAGpLCdzn/SmY3iXv+PiojZhu4J3TeQH4mBya0qEowqQHh4XzRfvI1I\n"
                "ZswZtxwsRljFREUrm9tg4ZPPrey24DS/YLxgtis1zHmi+J4nkcMfskCyiCZIfJXG\n"
                "GCn28oVqEulgrhgkxWSnLoFK3P9OV8iDILgmUf0x5y1bt/4ep+KUI61+WbVe6fjs\n"
                "EE5HPOdwZSzTsAouVq76sCQI8o/TQUeXEmxZzUTq2LZNuaAVrOgQz6sRDfokPa8C\n"
                "AwEAAaNTMFEwHQYDVR0OBBYEFPBs7+ThdL0nKJwlIY/SLW7xCOOxMB8GA1UdIwQY\n"
                "MBaAFPBs7+ThdL0nKJwlIY/SLW7xCOOxMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI\n"
                "hvcNAQELBQADggIBALHGmveXcLTqMefPneFbNi55WwRob4HONP4yDI2pbzDqCker\n"
                "RUTQC7fOnVnhlf0Q5ru3nBOILXCZ8aZ07kPKGVIAdTWvI7ckHAuhox0aHOpiuak1\n"
                "6+aVWCDky12In359F35iV7pjvjrj+fdCnDDwTw/Pv6uUuWL5Vlebh8DaoRoNVuaZ\n"
                "9ObH+WB3XHiSJZ++B6Ivuxd5UmTwp1DI9wsT5aKQZbjplcYbbBsWUBKDwj6v1oD6\n"
                "SmdKf1+fIIni8H1+icEpk/HK456V4qf7WtDx+PmnitV/6MqSKvQSfWMOmhg4srYf\n"
                "ulNMmhOkbvf5izHl7L6HcwMQSnFQ+SJCOziLpwEpCB+tpc9Pg/2Ay0ort8G2A4jH\n"
                "cHcZIftdHj05Kkz9RyIQV8b3EEa+Lb+2zZbwgqdDX4jhhdBSXObnE1WTHRTabKKe\n"
                "6JsJDBlo7nm29tbzukBXjiL+8BScQAw+Fkfr59VTN8Dq5L+f6NSEXnl2XRdNzNqt\n"
                "9r30NIAkB4RLMD+oZW9ZZVxQnaeEwnpDuX0Hd14fXZc1u0abROHyczEtw/ZkYs5V\n"
                "C9IazscaSlKpmE1CKMJVfxqvfclwTM1/8wtUvYS1yTJ4ecep8EoivYUdxxVwItlT\n"
                "2d474SNCjpxMIEXp67UbHOXM2416DAYS+dIYY/s6q/+9KxJt7SURQTZ5jV1H\n"
                "-----END CERTIFICATE-----\n";
            std::string PUBLIC_PEM =
                "-----BEGIN CERTIFICATE-----\n"
                "MIIFCTCCAvGgAwIBAgIUVnBKmTUSk7F7h7fqqFNeWh96zBowDQYJKoZIhvcNAQEL\n"
                "BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTIxMTAxMTA5MDE0MFoXDTQzMDkw\n"
                "NjA5MDE0MFowFDESMBAGA1UEAwwJbG9jYWxob3N0MIICIjANBgkqhkiG9w0BAQEF\n"
                "AAOCAg8AMIICCgKCAgEAv7bLMz0vlhzC6Pc50jFdiPH0eyjoHsMJp1+N9Mr46Loo\n"
                "tXVL7kmMxXf2sauUDkZeBKNqeRB+z1o1vmeWwJBTQ0Bcp4p/SOKEqiwEoqgkKjcx\n"
                "cyCafLXJX9f4mDKl9ER7dgIY0yyT/lkwAX4m3NlRssGsMwzvusGuuRG52R/FjloO\n"
                "CQbgDanJTOip6gbLQau0ntlaOVwRh7wL5T1qQ4TKRJIoBi5W2HnuoYhkNDCHsvcF\n"
                "i/eBOa+YGFHEHdJYOevUQ7mVNmQcD6UG1z0eEZe7aZanG5sFiVnEfzswi+ebOnxC\n"
                "C9tPVTUsfsnOaM2OHLN+CTJY6VwidD74fWQuZ1OJRbDuaUac7GOisH8HaBQLzbBx\n"
                "KKD4hmsrrAzkckZN2ls7mDP+oPCJMV8vHyvVqBjBi6XeysTIVLNGb7CVHGTLDY1k\n"
                "TVTTvzeOBxAGpLCdzn/SmY3iXv+PiojZhu4J3TeQH4mBya0qEowqQHh4XzRfvI1I\n"
                "ZswZtxwsRljFREUrm9tg4ZPPrey24DS/YLxgtis1zHmi+J4nkcMfskCyiCZIfJXG\n"
                "GCn28oVqEulgrhgkxWSnLoFK3P9OV8iDILgmUf0x5y1bt/4ep+KUI61+WbVe6fjs\n"
                "EE5HPOdwZSzTsAouVq76sCQI8o/TQUeXEmxZzUTq2LZNuaAVrOgQz6sRDfokPa8C\n"
                "AwEAAaNTMFEwHQYDVR0OBBYEFPBs7+ThdL0nKJwlIY/SLW7xCOOxMB8GA1UdIwQY\n"
                "MBaAFPBs7+ThdL0nKJwlIY/SLW7xCOOxMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZI\n"
                "hvcNAQELBQADggIBALHGmveXcLTqMefPneFbNi55WwRob4HONP4yDI2pbzDqCker\n"
                "RUTQC7fOnVnhlf0Q5ru3nBOILXCZ8aZ07kPKGVIAdTWvI7ckHAuhox0aHOpiuak1\n"
                "6+aVWCDky12In359F35iV7pjvjrj+fdCnDDwTw/Pv6uUuWL5Vlebh8DaoRoNVuaZ\n"
                "9ObH+WB3XHiSJZ++B6Ivuxd5UmTwp1DI9wsT5aKQZbjplcYbbBsWUBKDwj6v1oD6\n"
                "SmdKf1+fIIni8H1+icEpk/HK456V4qf7WtDx+PmnitV/6MqSKvQSfWMOmhg4srYf\n"
                "ulNMmhOkbvf5izHl7L6HcwMQSnFQ+SJCOziLpwEpCB+tpc9Pg/2Ay0ort8G2A4jH\n"
                "cHcZIftdHj05Kkz9RyIQV8b3EEa+Lb+2zZbwgqdDX4jhhdBSXObnE1WTHRTabKKe\n"
                "6JsJDBlo7nm29tbzukBXjiL+8BScQAw+Fkfr59VTN8Dq5L+f6NSEXnl2XRdNzNqt\n"
                "9r30NIAkB4RLMD+oZW9ZZVxQnaeEwnpDuX0Hd14fXZc1u0abROHyczEtw/ZkYs5V\n"
                "C9IazscaSlKpmE1CKMJVfxqvfclwTM1/8wtUvYS1yTJ4ecep8EoivYUdxxVwItlT\n"
                "2d474SNCjpxMIEXp67UbHOXM2416DAYS+dIYY/s6q/+9KxJt7SURQTZ5jV1H\n"
                "-----END CERTIFICATE-----\n";

            std::string INCORRECT_PUBLIC_PEM =
                "-----BEGIN CERTIFICATE-----\n"
                "LIIDBjCCAe4CCQCifnwdKnB7CDANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJB\n"
                "VTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0\n"
                "cyBQdHkgTHRkMB4XDTE5MDExNDA1NDI0MFoXDTIxMTAxMDA1NDI0MFowRTELMAkG\n"
                "A1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0\n"
                "IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\n"
                "AOVHP4mXGPpEgbPw1EUdRZ3qiyu1FQyK7vJg6D/vZKGiUt/sw1eEUay/rZ168cXT\n"
                "7nKT3/4G5IyeJ3elwjNeGxmU3jeG0dYexn44ryyi7ujXTjb2s0kbHKSa5f9bwzo5\n"
                "ka3UHmX/cZwUe9AgGjmHcj6qYlUhOQKCllV5TyuzkkuxBgndiuOUZE7SHdtICMCT\n"
                "/OOjxBVk/ooeeAi9kL0eROExFN30YG+3JjfcH3jt4jqoGKgw69vnLJVNWg6rlGxa\n"
                "DnVVoWPe6C9q/vlGe7GpbFjYthoFFYBfcRLEHDrQRR4/ZYaWCyf6m1QriS5EE7xk\n"
                "6VWM0qaCapqZtRPIwR7HB+8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEABunHHtlx\n"
                "Zm0bpYzCA4njE4CdIRR9jvz7RxvJE9IMpdr4dTBPbY7JLDNUALIA7EYzwbSZyjpK\n"
                "esG/DCNAymzVoa98Y6ldjl0ftCRNMF8cG1hqNFMk8NTq852jQkBEFGEGon/cXJom\n"
                "hoSeWuvqbEYyAmvt3sd7+fNh+/gZiQacRYNohw10qYz4s4AAhAJbHtd4nCi25e9d\n"
                "+vNrIyXzIfX94pmNnnMXt3KmkMotxAhmfOlZcMtu7/sSdLg0nZQOyZu9MoKhUDUg\n"
                "DH9rbaQeLpYJ5Knq0PZ7GBoljr3Pkosj2LDk9YomWsK2KCnErRw2QmGyOUMWMdHY\n"
                "xTajk6l3fymisA==\n"
                "-----END CERTIFICATE-----";
        };
    } // namespace TestUtils
} // namespace quasar
