type GeoType = 'UNKNOWN' | 'COUNTRY' | 'SUBJECT_FEDERATION' | 'CITY' | 'SUBJECT_FEDERATION_DISTRICT';

const SUBJECT_FEDERATION: GeoType = 'SUBJECT_FEDERATION';

export enum LocationAction {
    'PUSH' = 'PUSH',
    'POP' = 'POP',
    'REPLACE' = 'REPLACE',
}

export enum View {
    DESKTOP = 'desktop',
    TOUCH_PHONE = 'touch-phone',
}

export enum PageName {
    INDEX = 'index',
}

export enum UserTypes {
    OWNER = 'OWNER',
    AGENT = 'AGENT',
    AGENCY = 'AGENCY',
    DEVELOPER = 'DEVELOPER',
    AD_AGENCY = 'AD_AGENCY',
}

export enum PaymentType {
    JURIDICAL_PERSON = 'juridical',
    NATURAL_PERSON = 'natural',
}

export enum MainMenuPromoBlockType {
    CHECK_APARTMENT = 'CHECK_APARTMENT',
    DEVELOPERS_MAP = 'DEVELOPERS_MAP',
    FIND_AGENT = 'FIND_AGENT',
    MORTGAGE_CALCULATOR = 'MORTGAGE_CALCULATOR',
    YANDEX_RENT_LISTING = 'YANDEX_RENT_LISTING',
    YANDEX_RENT_LANDING = 'YANDEX_RENT_LANDING',
    YANDEX_DEAL_VALUATION = 'YANDEX_DEAL_VALUATION',
}

export enum EAdBlockSourceType {
    ADFOX = 'adfox',
    RTB = 'rtb',
    DIRECT = 'direct',
}

const adfox: EAdBlockSourceType.ADFOX = EAdBlockSourceType.ADFOX;

export const mockState = {
    geo: {
        id: 1,
        type: SUBJECT_FEDERATION,
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        parents: [],
        heatmaps: [],
        refinements: [],
        searchFilters: {
            'COMMERCIAL:RENT': {},
            'COMMERCIAL:SELL': {},
        },
        sitesRgids: {
            district: 741964,
            mainCity: 587795,
        },
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        sublocalities: [],
        highwayDirections: [],
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        heatmapInfos: [],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: false,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    routing: {
        currentRoute: '/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        prevRoute: null,
        locationBeforeTransitions: {
            pathname: '/moskva_i_moskovskaya_oblast/kupit/kvartira/',
            search: '',
            hash: '',
            action: LocationAction['POP'],
            key: null,
            query: {},
        },
    },
    cookies: {},
    config: {
        view: View.DESKTOP,
        retpath:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        isMobile: undefined,
        cspNonce: 'tqEQZhZ/wCNiVI6nwRAXMw==',
        traceId: '111ffd1747a82d06997c9bfe656658a7',
        referer: 'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/',
        version: '1',
        hasDevTools: true,
        hostname: 'realty-frontend.realty.local.dev.vertis.yandex.ru',
        origin: 'https://realty-frontend.realty.local.dev.vertis.yandex.ru',
        env: 'development',
        passHost: 'https://pass-test.yandex.ru',
        passportHost: 'https://passport-test.yandex.ru',
        passportApiHost: 'https://api.passport-test.yandex.ru',
        apiServerHost: 'https://realty.test.vertis.yandex.ru/api/1.0',
        partnerUrl: 'https://partner.realty.test.vertis.yandex.ru',
        rootUrl: 'https://realty.test.vertis.yandex.ru',
        ugcTestingUid: '971923671',
        domains: {
            desktop: 'realty-frontend.realty.local.dev.vertis.yandex.ru',
            'touch-phone': 'realty-frontend.m.realty.local.dev.vertis.yandex.ru',
        },
        sharedCookiesDomain: '.realty.local.dev.vertis.yandex.ru',
        adAliasName: 'ebac773e71954',
        yapicHost: 'yapic-test.yandex.ru',
        avatarsHost: 'avatars.mdst.yandex.net',
        yandexKassaV3ShopId: 601234,
        mosruRedirectLinks: {},
        trafficFrom: 'direct',
        yaArendaUrl: 'https://arenda.test.vertis.yandex.ru/',
        realtyUrl: 'https://realty.test.vertis.yandex.ru/',
        creamUrl: 'https://cream.test.vertis.yandex-team.ru',
        yaArendaAgencyId: 4062678234,
        cspDomains: [
            "'self'",
            'data:',
            "'unsafe-eval'",
            "'unsafe-inline'",
            '%nonce%',
            'blob:',
            'an.yandex.ru',
            'strm.yandex.ru',
            '*.strm.yandex.net',
            'verify.yandex.ru',
            '*.verify.yandex.ru',
            'mc.yandex.ru',
            'yandex.st',
            'yastatic.net',
            'matchid.adfox.yandex.ru',
            'adfox.yandex.ru',
            'ads.adfox.ru',
            'ads6.adfox.ru',
            'jstracer.yandex.ru',
            'yastat.net',
            'yandex.ru',
            'tps.doubleverify.com',
            'pixel.adsafeprotected.com',
            'avatars-fast.yandex.net',
            'favicon.yandex.net',
            'banners.adfox.ru',
            'content.adfox.ru',
            'avatars.mds.yandex.net',
            'bs.serving-sys.com',
            'ad.adriver.ru',
            'wcm.solution.weborama.fr',
            'wcm-ru.frontend.weborama.fr',
            'mc.admetrica.ru',
            'ad.doubleclick.net',
            'rgi.io',
            'track.rutarget.ru',
            'ssl.hurra.com',
            'px.moatads.com',
            'amc.yandex.ru',
            'gdeby.hit.gemius.pl',
            'impression.appsflyer.com',
            'z.moatads.com',
            'storage.mds.yandex.net',
            '*.yandex.ru',
            '*.yandexadexchange.net',
            'awaps.yandex.net',
            'yandexadexchange.net',
            '*.maps.yandex.net',
            'api-maps.yandex.ru',
            'suggest-maps.yandex.ru',
            'forms.yandex.ru',
            'forms.yandex.%tld%',
            'api-maps.tst.c.maps.yandex.ru',
            '*.yandex.net',
            '127.0.0.1:29009',
            '127.0.0.1:30102',
            'yandexmetrika.com:29010',
            'yandexmetrika.com:30103',
            'mc.webvisor.com',
            'mc.webvisor.org',
            'mc.yandex.com',
            'mc.yandex.by',
            'mc.yandex.com.tr',
            'mc.yandex.kz',
            'mc.yandex.ua',
            'mc.yandex.az',
            'mc.yandex.co.il',
            'mc.yandex.com.am',
            'mc.yandex.com.ge',
            'mc.yandex.ee',
            'mc.yandex.fr',
            'mc.yandex.kg',
            'mc.yandex.lt',
            'mc.yandex.lv',
            'mc.yandex.md',
            'mc.yandex.tj',
            'mc.yandex.tm',
            'mc.yandex.uz',
            'yandexmetrica.com:*',
            '*.adfox.ru',
            '*.weborama.fr',
            '*.doubleclick.net',
            'creativecdn.com',
            'ams.creativecdn.com',
            'alfabank.ru',
            'auto.ru',
            'www.facebook.com',
            'connect.facebook.net',
            'moderation.vertis.yandex-team.ru',
            'code.createjs.com',
            'unpkg.com',
            'yandex.net',
            'wss://*.yandex.ru',
            '*.yandex',
            '*.admetrica.ru',
            'www.youtube.com',
            'img.youtube.com',
            'i.ytimg.com',
            'android-webview-video-poster',
            '*.matterport.com',
            'widget.planoplan.com',
            'view3d.pik.ru',
            '*.immercyb.com',
            'biganto.com',
        ],
        cspServiceName: 'realty-desktop',
        moderationServiceHost: 'moderation.test.vertis.yandex-team.ru',
        constants: {
            VOS_PARTNER_ID: '1035218734',
            APP_LINKS: {
                ios: 'https://redirect.appmetrica.yandex.com/serve/888818511672008835',
                android: 'https://redirect.appmetrica.yandex.com/serve/744703322706954699',
            },
            BANNER_APP_LINKS: {
                ios: {
                    facebook: {
                        smart: 'https://app.adjust.com/lkti2n',
                        splash: 'https://app.adjust.com/7yarl2',
                    },
                    yandex_direct_app: {
                        smart: 'https://app.adjust.com/24uc8h',
                        splash: 'https://app.adjust.com/w7a63t',
                    },
                    mytargetapp: {
                        smart: 'https://app.adjust.com/vmnv9vy',
                        splash: 'https://app.adjust.com/54usmg7',
                    },
                    mytargetpublic: {
                        smart: 'https://app.adjust.com/l9kf4xv',
                        splash: 'https://app.adjust.com/fgztes2',
                    },
                    default: {
                        smart: 'https://redirect.appmetrica.yandex.com/serve/888818511672008835',
                        splash: 'https://appmetrika.yandex.ru/serve/744703321465478374/?geo=ru',
                    },
                },
                android: {
                    facebook: {
                        smart: 'https://app.adjust.com/tvwv7s',
                        splash: 'https://app.adjust.com/fc3bu1',
                    },
                    yandex_direct_app: {
                        smart: 'https://app.adjust.com/5ydr7r',
                        splash: 'https://app.adjust.com/fhen6j',
                    },
                    mytargetapp: {
                        smart: 'https://app.adjust.com/t1ipzcu',
                        splash: 'https://app.adjust.com/fbv97bv',
                    },
                    mytargetpublic: {
                        smart: 'https://app.adjust.com/hpx6qmt',
                        splash: 'https://app.adjust.com/qek32ql',
                    },
                    default: {
                        smart: 'https://redirect.appmetrica.yandex.com/serve/744703322706954699',
                        splash: 'https://appmetrika.yandex.ru/serve/744703142049973589/?geo=ru',
                    },
                },
            },
            PIK_PARTNER_ID: '1069052819',
            SAMOLET_DEVELOPER_ID: 102320,
        },
        serverTimeStamp: 1640595245875,
        timeDelta: -4470,
        experimentsData: {
            statId: '300',
        },
        branch: '123',
        canary: '123',
        uatraits: {
            isBrowser: false,
            isMobile: false,
            isTouch: false,
        },
        featureToggles: [],
        newbuildingJivoSiteChatId: '',
    },
    loader: {},
    page: {
        isLoading: false,
        isLocked: false,
        name: PageName.INDEX,
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        queryId: '111ffd1747a82d06997c9bfe656658a7',
        isFailed: false,
    },
    user: {
        crc: 'y5a6a8bfe274a1a2afd4c88960cc5eb06',
        uid: '',
        yuid: '393167231637669633',
        isVosUser: false,
        isAuth: false,
        isJuridical: false,
        userType: UserTypes.OWNER,
        paymentTypeSuffix: PaymentType.JURIDICAL_PERSON,
        promoSubscription: {},
        avatarHost: 'avatars.mdst.yandex.net',
        emails: [],
        emailHash: '',
        defaultPhone: undefined,
        passHost: 'https://pass-test.yandex.ru',
        passportHost: 'https://passport-test.yandex.ru',
        passportApiHost: 'https://api.passport-test.yandex.ru',
        passportOrigin: 'realty_moscow',
        passportPhones: [],
        favorites: [],
        favoritesMap: {},
        comparison: [],
        statistics: {},
        walletInfo: {
            isFilled: false,
        },
    },
    siteSpecialProject: {
        developerId: 102320,
        developerName: 'Группа «Самолет»',
        showTab: true,
        hasLogoInTab: true,
        tabUrl: '/samolet/?from=main_menu',
        showPin: true,
        showFilter: true,
        filterText: 'ЖК от Самолет',
        developerFullName: 'Группа «Самолет»',
        sideMenuText: 'Квартиры от Самолет',
        hideAds: true,
    },
    siteSpecialProjectSecondPackage: {
        developerId: 102320,
        developerName: 'Группа «Самолет»',
        phones: [
            {
                geoId: 1,
                number: '+74953634998',
            },
            {
                geoId: 10174,
                number: '+78129201984',
            },
        ],
        pinnedSiteIds: [1839196, 2677588, 2651324],
        mixedListingBannerUrl: 'https://avatars.mdst.yandex.net/get-realty/3013/filename',
        mixedListingBannerText: 'Скидка 10% на квартиры и апартаменты',
        hasSiteListingBanner: true,
        siteListingBannerUrl: 'https://avatars.mdst.yandex.net/get-realty/3013/filename',
        siteListingBannerText: 'Скидка 10% на квартиры и апартаменты',
        commercialListingBannerUrl: '123',
        commercialListingBannerText: '123',
    },
    header: {
        promoblocks: {
            SELL: MainMenuPromoBlockType.CHECK_APARTMENT,
            RENT: MainMenuPromoBlockType.CHECK_APARTMENT,
            SITES: MainMenuPromoBlockType.CHECK_APARTMENT,
            COMMERCIAL: MainMenuPromoBlockType.CHECK_APARTMENT,
            MORTGAGE: MainMenuPromoBlockType.CHECK_APARTMENT,
            FOR_PROFESSIONAL: MainMenuPromoBlockType.CHECK_APARTMENT,
            YANDEX_ARENDA: MainMenuPromoBlockType.CHECK_APARTMENT,
            SPECIAL_PROJECT: MainMenuPromoBlockType.CHECK_APARTMENT,
            JOURNAL: MainMenuPromoBlockType.CHECK_APARTMENT,
        },
    },
    ads: {
        direct: {},
        code: 'listing-second',
        blocks: {
            'menu-newbuilding-small': {
                sources: [
                    {
                        type: adfox,
                        async: true,
                        ownerId: '243420',
                        params: {
                            pp: 'bqtn',
                            ps: 'cjtp',
                            p2: 'fifn',
                        },
                        scroll: {},
                    },
                ],
                id: 'hgxxum7pvj',
            },
        },
        server: {},
    },
};
