import { ISiteStatisticsFiltersProps } from '../';

export const defaultProps = ({
    searchQuery: {
        siteId: ['131977'],
        statistics: ['offersNumber', 'pricePerMeter'],
        fromDate: '2021-11-01',
        untilDate: '2021-12-01',
        clientId: '10090064',
    },
    defaultSearchQuery: {
        siteId: ['131977'],
        fromDate: '2021-11-01',
        untilDate: '2021-12-01',
        statistics: ['offersNumber', 'pricePerMeter'],
    },
    clients: [
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090064,
                name: 'ФСК Лидер',
                phone: '',
                regionId: 225,
                type: 'Other',
                url: '',
            },
            id: 10090064,
            isAgencyInService: false,
            resource: { developerId: '295544' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090062,
                name: 'Мартин',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090062,
            isAgencyInService: false,
            resource: { developerId: '295479' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090068,
                name: 'Capital Group',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090068,
            isAgencyInService: false,
            resource: { developerId: '295494' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090070,
                name: 'Главстрой',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090070,
            isAgencyInService: false,
            resource: { developerId: '295499' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090073,
                name: 'ЦНН',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090073,
            isAgencyInService: false,
            resource: { developerId: '295506' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090076,
                name: 'БЭСТКОН',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090076,
            isAgencyInService: false,
            resource: { developerId: '295524' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 10090079,
                name: 'ГК «Веста»',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 10090079,
            isAgencyInService: false,
            resource: { developerId: '295533' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 13897620,
                name: 'Ремикс',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 13897620,
            isAgencyInService: false,
            resource: { developerId: '321667' },
        },
        {
            agencyId: 10046004,
            client: {
                agency: false,
                agencyId: 10046004,
                city: '',
                email: '',
                fax: '',
                id: 13897628,
                name: 'ООО "ЖК на Ивановcкой"',
                phone: '',
                regionId: 225,
                type: 'IndividualPerson',
                url: '',
            },
            id: 13897628,
            isAgencyInService: false,
            resource: { developerId: '321674' },
        },
    ],
    clientSites: [
        { id: '131977', siteId: '131977', name: 'Гагаринский (Жуковский)' },
        { id: '170725', siteId: '170725', name: 'Дыхание' },
        { id: '193551', siteId: '193551', name: 'Кварталы 21/19' },
        { id: '441250', siteId: '441250', name: 'Лисицына 5' },
        { id: '85348', siteId: '85348', name: 'Некрасовка (ДСК-1-Авеста-Строй)' },
        { id: '94712', siteId: '94712', name: 'Новое Тушино' },
        { id: '86941', siteId: '86941', name: 'Новый Раменский' },
        { id: '217598', siteId: '217598', name: 'Первый Андреевский' },
        { id: '558418', siteId: '558418', name: 'Первый Юбилейный' },
        { id: '376370', siteId: '376370', name: 'Скандинавский' },
        { id: '67810', siteId: '67810', name: 'Сколковский' },
        { id: '64153', siteId: '64153', name: 'Центр-2' },
    ],
    onSubmit: () => null,
    queryId: '',
} as unknown) as ISiteStatisticsFiltersProps;

export const oneClientProps = ({
    ...defaultProps,
    clients: defaultProps.clients.slice(0, 1),
} as unknown) as ISiteStatisticsFiltersProps;

export const oneSiteProps = ({
    ...defaultProps,
    clientSites: defaultProps.clientSites.slice(0, 1),
} as unknown) as ISiteStatisticsFiltersProps;

export const noSiteProps = ({
    ...defaultProps,
    clientSites: [],
    searchQuery: {
        ...defaultProps.searchQuery,
        siteId: undefined,
    },
} as unknown) as ISiteStatisticsFiltersProps;

export const noAgencyProps = ({
    ...defaultProps,
    clients: [],
    client: {
        agency: false,
        city: 'Санкт-Петербург',
        email: '322@yandex.ru',
        fax: '',
        id: 10090064,
        name: 'Частный Агент 228',
        phone: '',
        regionId: 225,
        type: 'LimitedCompany',
        url: '',
    },
} as unknown) as ISiteStatisticsFiltersProps;
