import { AuthorCategoryTypes, CommunicationChannels } from 'realty-core/types/offerCard';
import { IOfferSnippet } from 'realty-core/types/offerSnippet';

export const getInitialState = () => ({
    user: {
        favorites: [],
        favoritesMap: {},
    },
});

export const getOfferSnippet = (params: { withoutMetro?: boolean; withChats?: boolean } = {}) =>
    (({
        offerId: '370237082731537985',
        trust: 'NORMAL',
        url:
            'http://na100.pro/go.php?link=aE55HltR2O02DWj2lcKqJo4uC9J2zk0Fyk1tJDiuJHQDG0kMVGtrT8w8GVF9EPTcHrcFTWEI5u1n1KfFYhnXirRFZ62FnF5Iv6cnHCJX2nnMBX9Lj%2B32yG6COIe80mp6pAYj1gdgA07aViJIHl92OzF%2F7swi%2BEspV%2Fjyc49oXuQ%3D',
        unsignedInternalUrl: '//realty.test.vertis.yandex.ru/offer/370237082731537985',
        partnerId: '1069200103',
        partnerName: 'Агентство',
        offerType: 'SELL',
        offerCategory: 'APARTMENT',
        clusterId: '370237082731537985',
        clusterHeader: true,
        clusterSize: 1,
        author: {
            category: AuthorCategoryTypes.DEVELOPER,
            organization: 'Агентство',
            agentName: 'Офис продаж А101',
            photo: '',
            creationDate: '2020-02-06T08:04:03Z',
            allowedCommunicationChannels: [CommunicationChannels.COM_CALLS],
            name: 'Агентство',
            redirectPhonesFailed: false,
            redirectPhones: true,
            encryptedPhoneNumbers: [{ phone: 'KzcF0OHTUJxMLzINyNPzUR5', redirectId: '+74951322759' }],
            encryptedPhones: ['KzcF0OHTUJxMLzINyNPzUR5'],
        },
        creationDate: '2021-10-28T09:25:53Z',
        updateDate: '2021-11-02T09:26:58Z',
        floorsTotal: 15,
        floorsOffered: [12],
        flatType: 'NEW_SECONDARY',
        ceilingHeight: 2.89,
        area: { value: 19.2, unit: 'SQUARE_METER' },
        livingSpace: { value: 12.2, unit: 'SQUARE_METER' },
        price: {
            currency: 'RUR',
            value: 5475000,
            period: 'WHOLE_LIFE',
            unit: 'WHOLE_OFFER',
            trend: 'UNCHANGED',
            hasPriceHistory: false,
            valuePerPart: 285156,
            unitPerPart: 'SQUARE_METER',
            valueForWhole: 5475000,
            unitForWhole: 'WHOLE_OFFER',
            price: { value: 5475000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
            pricePerPart: { value: 285156, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
            priceForWhole: { value: 5475000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        },
        notForAgents: false,
        totalImages: 12,
        minicardImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/minicard'],
        mainImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/main'],
        fullImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/large'],
        large1242Images: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/large_1242'],
        alikeImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/alike'],
        cosmicImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/cosmic'],
        appMiddleImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_middle'],
        appLargeImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_large'],
        appMiniSnippetImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_snippet_mini'],
        appSmallSnippetImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_snippet_small'],
        appMiddleSnippetImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_snippet_middle'],
        appLargeSnippetImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/app_snippet_large'],
        origImages: ['//avatars.mdst.yandex.net/get-realty/2899/w1927/orig'],
        photoPreviews: ['', '', '', '', '', '', '', '', '', '', '', ''],
        apartment: { renovation: 'NEEDS_RENOVATION', quality: 'EXCELLENT' },
        location: {
            rgid: 230739,
            geoId: 29393,
            populatedRgid: 741964,
            subjectFederationId: 1,
            subjectFederationRgid: 741964,
            settlementRgid: 587795,
            settlementGeoId: 213,
            address: 'посёлок Коммунарка, улица Потаповская Роща, 24к3',
            point: { latitude: 55.550503, longitude: 37.508984, precision: 'EXACT' },
            metro: params.withoutMetro
                ? undefined
                : {
                      metroGeoId: 20518,
                      name: 'Бульвар Адмирала Ушакова',
                      metroTransport: 'ON_TRANSPORT',
                      timeToMetro: 14,
                      latitude: 55.545322,
                      longitude: 37.542835,
                      minTimeToMetro: 14,
                      lineColors: ['8dbece'],
                      rgbColor: '8dbece',
                  },
            streetAddress: 'улица Потаповская Роща, 24к3',
        },
        house: {
            bathroomUnit: 'MATCHED',
            balconyType: 'BALCONY',
            windowView: 'YARD',
            studio: true,
            apartments: false,
            housePart: false,
        },
        building: {
            hasDeveloperChat: params?.withChats,
            builtYear: 2019,
            builtQuarter: 3,
            buildingState: 'HAND_OVER',
            buildingType: 'MONOLIT',
            parkingType: 'OPEN',
            siteId: 374276,
            siteName: 'Белые ночи',
            siteDisplayName: 'Жилой район «Белые ночи»',
            developerIds: [269230],
            houseId: '1654691',
            houseReadableName: 'Корпус 2.3',
            buildingId: '7748127967945771150',
            heatingType: 'UNKNOWN',
            priceStatistics: {
                sellPricePerSquareMeter: {
                    level: 0,
                    maxLevel: 9,
                    rgbColor: '',
                    value: '0',
                    regionValueFrom: '22727',
                    regionValueTo: '2234148',
                },
                sellPriceByRooms: {
                    '1': {
                        level: 4,
                        maxLevel: 9,
                        rgbColor: 'fbae1e',
                        value: '8200000',
                        regionValueFrom: '300000',
                        regionValueTo: '1989368448',
                    },
                },
            },
            apartmentType: 'FLATS',
        },
        internal: true,
        active: true,
        vas: {
            raised: false,
            premium: false,
            placement: false,
            promoted: false,
            turboSale: false,
            raisingSale: false,
            tuzFeatured: false,
            vasAvailable: true,
        },
        dealStatus: 'PRIMARY_SALE_OF_SECONDARY',
        uid: '326455128',
        relevance: 0,
        commissioningDateIndexValue: 0,
        partnerInternalId: '159743743',
        enrichedFields: ['SECURITY'],
        callCenter: false,
        tags: [],
        exclusive: true,
        predictions: { predictedPrice: { min: '2758000', max: '3371000', value: '3064000' } },
        obsolete: false,
        withExcerpt: false,
        freeReportAccessibility: 'FRA_NONE',
        paidReportAccessibility: 'PPA_ALLOWED_TO_BUY_WITH_ADDITIONAL_DATA_REQUIRED',
        allowedCommunicationChannels: ['COM_CALLS'],
        remoteReview: { onlineShow: false, youtubeVideoReviewUrl: '' },
        socialPessimization: false,
        chargeForCallsType: 'NO_CHARGE',
        trustedOfferInfo: {
            isFullTrustedOwner: false,
            ownerTrustedStatus: 'NOT_LINKED_MOSRU',
            isCadastrPersonMatched: false,
        },
        yandexRent: false,
        offerState: {
            indexerState: {
                indexationWarning: [
                    {
                        code: 'DISABLED_CHATS_FOR_OWNER_TYPE',
                        debugInfo: 'AllowedCommunicationChannelsUnifier$: DEVELOPER',
                    },
                ],
            },
        },
        newFlatSale: true,
        openPlan: false,
        primarySaleV2: false,
        raised: false,
        premium: false,
        vasAvailable: true,
        suspicious: false,
        shareUrl: 'https://realty.test.vertis.yandex.ru/offer/370237082731537985',
        transactionConditionsMap: { MORTGAGE: true },
        placement: false,
        promoted: false,
        newBuilding: false,
        roomsTotalKey: 'studio',
        roomsTotalColor: '#3bbd25',
        page: 0,
        idx: 0,
        queryId: '62d0a0b1c5b967d07c023176d4aa121a',
    } as unknown) as IOfferSnippet);
