/* eslint-disable max-len */

import { IGetAddressContentProps } from '../../ItemAddress/getItemAddressContent';

export const SITE_ADDRESS_ONE: IGetAddressContentProps = {
    item: {
        location: {
            geoId: 215293,
            rgid: 17367497,
            settlementRgid: 17367497,
            settlementGeoId: 121813,
            populatedRgid: 741964,
            address: 'Москва, пос. Сосенское, д. Столбово, пр. Куприна',
            distanceFromRingRoad: 9880,
            subjectFederationId: 1,
            subjectFederationRgid: 741964,
            subjectFederationName: 'Москва и МО',
            point: {
                latitude: 55.54082,
                longitude: 37.45504,
                precision: 'EXACT',
            },
            parks: [],
            ponds: [],
            airports: [],
            cityCenter: [],
            heatmaps: [],
            allHeatmaps: [
                {
                    name: 'price-sell',
                    rgbColor: '30ce12',
                    description: 'низкая',
                    level: 7,
                    maxLevel: 9,
                    title: 'Цена продажи',
                },
            ],
            structuredAddress: {
                unifiedOneline: '',
                component: [
                    {
                        value: 'Россия',
                        regionType: 'COUNTRY',
                        geoId: 225,
                        rgid: '143',
                        valueForAddress: 'Россия',
                        queryParams: {
                            rgid: '143',
                            address: 'Россия',
                        },
                    },
                    {
                        value: 'Москва',
                        regionType: 'CITY',
                        geoId: 213,
                        rgid: '587795',
                        valueForAddress: 'Москва',
                        queryParams: {
                            rgid: '587795',
                            address: 'Россия, Москва',
                        },
                    },
                    {
                        value: 'Новомосковский административный округ',
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        geoId: 213,
                        rgid: '587795',
                        valueForAddress: 'Новомосковский административный округ',
                        queryParams: {
                            rgid: '587795',
                            address: 'Россия, Москва, Новомосковский административный округ',
                        },
                    },
                    {
                        value: 'поселение Сосенское',
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        geoId: 213,
                        rgid: '587795',
                        valueForAddress: 'поселение Сосенское',
                        queryParams: {
                            rgid: '587795',
                            address: 'Россия, Москва, Новомосковский административный округ, поселение Сосенское',
                        },
                    },
                    {
                        value: 'проспект Куприна',
                        regionType: 'STREET',
                        geoId: 213,
                        rgid: '587795',
                        valueForAddress: 'проспект Куприна',
                        queryParams: {
                            rgid: '587795',
                            address:
                                'Россия, Москва, Новомосковский административный округ, поселение Сосенское, проспект Куприна',
                            streetId: 230052,
                        },
                    },
                    {
                        value: '34к2',
                        regionType: 'HOUSE',
                        geoId: 213,
                        rgid: '587795',
                        valueForAddress: '34к2',
                        queryParams: {
                            rgid: '587795',
                            address:
                                'Россия, Москва, Новомосковский административный округ, поселение Сосенское, проспект Куприна, 34к2',
                            streetId: 230052,
                        },
                    },
                ],
            },
            metro: {
                metroCityRgid: 741964,
                lineColors: ['e4402d'],
                metroGeoId: 218465,
                rgbColor: 'e4402d',
                metroTransport: 'ON_TRANSPORT',
                name: 'Ольховая',
                timeToMetro: 16,
            },
            metroList: [
                {
                    metroCityRgid: 741964,
                    lineColors: ['e4402d'],
                    metroGeoId: 218465,
                    rgbColor: 'e4402d',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Ольховая',
                    timeToMetro: 16,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['e4402d'],
                    metroGeoId: 218464,
                    rgbColor: 'e4402d',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Коммунарка',
                    timeToMetro: 18,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['8dbece'],
                    metroGeoId: 20520,
                    rgbColor: '8dbece',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Бунинская Аллея',
                    timeToMetro: 22,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['e4402d'],
                    metroGeoId: 218466,
                    rgbColor: 'e4402d',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Прокшино',
                    timeToMetro: 24,
                },
            ],
        },
    },
};

export const SITE_ADDRESS_TWO: IGetAddressContentProps = {
    item: {
        location: {
            geoId: 10738,
            rgid: 274798,
            settlementRgid: 596066,
            settlementGeoId: 10738,
            populatedRgid: 741964,
            address: 'Московская обл., Люберцы, ул. Камова',
            distanceFromRingRoad: 9591,
            subjectFederationId: 1,
            subjectFederationRgid: 741964,
            subjectFederationName: 'Москва и МО',
            point: {
                latitude: 55.6975,
                longitude: 37.954872,
                precision: 'EXACT',
            },
            parks: [],
            ponds: [],
            airports: [],
            cityCenter: [],
            heatmaps: [
                {
                    name: 'infrastructure',
                    rgbColor: 'f87c19',
                    description: 'минимальная',
                    level: 2,
                    maxLevel: 8,
                    title: 'Инфраструктура',
                },
                {
                    name: 'transport',
                    rgbColor: '620801',
                    description: 'низкая доступность',
                    level: 1,
                    maxLevel: 9,
                    title: 'Транспорт',
                },
            ],
            allHeatmaps: [
                {
                    name: 'infrastructure',
                    rgbColor: 'f87c19',
                    description: 'минимальная',
                    level: 2,
                    maxLevel: 8,
                    title: 'Инфраструктура',
                },
                {
                    name: 'price-rent',
                    rgbColor: '20a70a',
                    description: 'очень низкая',
                    level: 8,
                    maxLevel: 9,
                    title: 'Цена аренды',
                },
                {
                    name: 'price-sell',
                    rgbColor: '20a70a',
                    description: 'очень низкая',
                    level: 8,
                    maxLevel: 9,
                    title: 'Цена продажи',
                },
                {
                    name: 'profitability',
                    rgbColor: '128000',
                    description: 'очень высокая',
                    level: 9,
                    maxLevel: 9,
                    title: 'Прогноз окупаемости',
                },
                {
                    name: 'transport',
                    rgbColor: '620801',
                    description: 'низкая доступность',
                    level: 1,
                    maxLevel: 9,
                    title: 'Транспорт',
                },
                {
                    name: 'carsharing',
                    rgbColor: 'ffe424',
                    description: 'выше средней',
                    level: 4,
                    maxLevel: 8,
                    title: 'Доступность Яндекс.Драйва',
                },
            ],
            structuredAddress: {
                unifiedOneline: '',
                component: [
                    {
                        value: 'Россия',
                        regionType: 'COUNTRY',
                        geoId: 225,
                        rgid: '143',
                        valueForAddress: 'Россия',
                        queryParams: {
                            rgid: '143',
                            address: 'Россия',
                        },
                    },
                    {
                        value: 'Московская',
                        regionType: 'SUBJECT_FEDERATION',
                        geoId: 1,
                        rgid: '587654',
                        valueForAddress: 'Московская область',
                        queryParams: {
                            rgid: '587654',
                            address: 'Россия, Московская область',
                        },
                    },
                    {
                        value: 'округ Люберцы',
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        geoId: 98594,
                        rgid: '587697',
                        valueForAddress: 'Люберцы (городской округ)',
                        queryParams: {
                            rgid: '587697',
                            address: 'Россия, Московская область, Люберцы (городской округ)',
                        },
                    },
                    {
                        value: 'Люберцы',
                        regionType: 'CITY',
                        geoId: 10738,
                        rgid: '596066',
                        valueForAddress: 'Люберцы',
                        queryParams: {
                            rgid: '596066',
                            address: 'Россия, Московская область, Люберцы (городской округ), Люберцы',
                        },
                    },
                    {
                        value: 'улица Камова',
                        regionType: 'STREET',
                        geoId: 10738,
                        rgid: '596066',
                        valueForAddress: 'улица Камова',
                        queryParams: {
                            rgid: '596066',
                            address: 'Россия, Московская область, Люберцы (городской округ), Люберцы, улица Камова',
                            streetId: 91646,
                        },
                    },
                    {
                        value: '5к2',
                        regionType: 'HOUSE',
                        geoId: 10738,
                        rgid: '596066',
                        valueForAddress: '5к2',
                        queryParams: {
                            rgid: '596066',
                            address:
                                'Россия, Московская область, Люберцы (городской округ), Люберцы, улица Камова, 5к2',
                            streetId: 91646,
                        },
                    },
                ],
            },
            metro: {
                metroCityRgid: 741964,
                lineColors: ['ff66e8'],
                metroGeoId: 218432,
                rgbColor: 'ff66e8',
                metroTransport: 'ON_TRANSPORT',
                name: 'Некрасовка',
                timeToMetro: 22,
            },
            metroList: [
                {
                    metroCityRgid: 741964,
                    lineColors: ['ff66e8'],
                    metroGeoId: 218432,
                    rgbColor: 'ff66e8',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Некрасовка',
                    timeToMetro: 22,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['ff66e8'],
                    metroGeoId: 218431,
                    rgbColor: 'ff66e8',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Лухмановская',
                    timeToMetro: 26,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['ff66e8'],
                    metroGeoId: 218430,
                    rgbColor: 'ff66e8',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'ул. Дмитриевского',
                    timeToMetro: 29,
                },
                {
                    metroCityRgid: 741964,
                    lineColors: ['b1179a'],
                    metroGeoId: 115040,
                    rgbColor: 'b1179a',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Лермонтовский проспект',
                    timeToMetro: 35,
                },
            ],
        },
    },
};

export const SITE_ADDRESS_THREE: IGetAddressContentProps = {
    item: {
        location: {
            geoId: 171731,
            rgid: 104245,
            settlementRgid: 104245,
            settlementGeoId: 171731,
            populatedRgid: 426764,
            address: 'Нижегородская обл., Кстовский район, пос. Культура, ул. Изумрудная',
            subjectFederationId: 11079,
            subjectFederationRgid: 426764,
            subjectFederationName: 'Нижегородская область',
            point: {
                latitude: 56.216385,
                longitude: 44.019066,
                precision: 'EXACT',
            },
            parks: [],
            ponds: [],
            airports: [],
            cityCenter: [],
            heatmaps: [],
            allHeatmaps: [],
            structuredAddress: {
                unifiedOneline: '',
                component: [
                    {
                        value: 'Россия',
                        regionType: 'COUNTRY',
                        geoId: 225,
                        rgid: '143',
                        valueForAddress: 'Россия',
                        queryParams: {
                            rgid: '143',
                            address: 'Россия',
                        },
                    },
                    {
                        value: 'Нижегородская область',
                        regionType: 'SUBJECT_FEDERATION',
                        geoId: 11079,
                        rgid: '426764',
                        valueForAddress: 'Нижегородская область',
                        queryParams: {
                            rgid: '426764',
                            address: 'Россия, Нижегородская область',
                        },
                    },
                    {
                        value: 'Кстовский округ',
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        geoId: 99555,
                        rgid: '427200',
                        valueForAddress: 'Кстовский  (городской округ)',
                        queryParams: {
                            rgid: '427200',
                            address: 'Россия, Нижегородская область, Кстовский  (городской округ)',
                        },
                    },
                    {
                        value: 'Культура',
                        regionType: 'CITY',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: 'посёлок Культура',
                        queryParams: {
                            rgid: '104245',
                            address: 'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура',
                        },
                    },
                    {
                        value: 'Изумрудная улица',
                        regionType: 'STREET',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: 'Изумрудная улица',
                        queryParams: {
                            rgid: '104245',
                            address:
                                'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура, Изумрудная улица',
                            streetId: 237311,
                        },
                    },
                    {
                        value: '14к2',
                        regionType: 'HOUSE',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: '14к2',
                        queryParams: {
                            rgid: '104245',
                            address:
                                'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура, Изумрудная улица, 14к2',
                            streetId: 237311,
                        },
                    },
                ],
            },
            metro: {
                lineColors: ['f03d2f'],
                metroGeoId: 101939,
                rgbColor: 'f03d2f',
                metroTransport: 'ON_TRANSPORT',
                name: 'Пролетарская',
                metroCityRgid: 575243,
                timeToMetro: 33,
            },
            metroList: [
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101939,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Пролетарская',
                    metroCityRgid: 575243,
                    timeToMetro: 33,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101940,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Автозаводская',
                    metroCityRgid: 575243,
                    timeToMetro: 36,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101938,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Двигатель Революции',
                    metroCityRgid: 575243,
                    timeToMetro: 37,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101942,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Кировская',
                    metroCityRgid: 575243,
                    timeToMetro: 38,
                },
            ],
        },
    },
};

export const SITE_ADDRESS_FOUR: IGetAddressContentProps = {
    item: {
        location: {
            geoId: 171731,
            rgid: 104245,
            settlementRgid: 104245,
            settlementGeoId: 171731,
            populatedRgid: 426764,
            address: 'Нижегородская обл., Кстовский район, пос. Культура, ул. Изумрудная',
            subjectFederationId: 11079,
            subjectFederationRgid: 426764,
            subjectFederationName: 'Нижегородская область',
            point: {
                latitude: 56.216385,
                longitude: 44.019066,
                precision: 'EXACT',
            },
            parks: [],
            ponds: [],
            airports: [],
            cityCenter: [],
            heatmaps: [],
            allHeatmaps: [],
            structuredAddress: {
                unifiedOneline: '',
                component: [
                    {
                        value: 'Россия',
                        regionType: 'COUNTRY',
                        geoId: 225,
                        rgid: '143',
                        valueForAddress: 'Россия',
                        queryParams: {
                            rgid: '143',
                            address: 'Россия',
                        },
                    },
                    {
                        value: 'Нижегородская обл.',
                        regionType: 'SUBJECT_FEDERATION',
                        geoId: 11079,
                        rgid: '426764',
                        valueForAddress: 'Нижегородская обл.',
                        queryParams: {
                            rgid: '426764',
                            address: 'Россия, Нижегородская обл.',
                        },
                    },
                    {
                        value: 'Кстовский округ',
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        geoId: 99555,
                        rgid: '427200',
                        valueForAddress: 'Кстовский  (городской округ)',
                        queryParams: {
                            rgid: '427200',
                            address: 'Россия, Нижегородская область, Кстовский  (городской округ)',
                        },
                    },
                    {
                        value: 'Культура',
                        regionType: 'CITY',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: 'посёлок Культура',
                        queryParams: {
                            rgid: '104245',
                            address: 'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура',
                        },
                    },
                    {
                        value: 'Изумрудная улица',
                        regionType: 'STREET',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: 'Изумрудная улица',
                        queryParams: {
                            rgid: '104245',
                            address:
                                'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура, Изумрудная улица',
                            streetId: 237311,
                        },
                    },
                    {
                        value: '14к2',
                        regionType: 'HOUSE',
                        geoId: 171731,
                        rgid: '104245',
                        valueForAddress: '14к2',
                        queryParams: {
                            rgid: '104245',
                            address:
                                'Россия, Нижегородская область, Кстовский  (городской округ), посёлок Культура, Изумрудная улица, 14к2',
                            streetId: 237311,
                        },
                    },
                ],
            },
            metro: {
                lineColors: ['f03d2f'],
                metroGeoId: 101939,
                rgbColor: 'f03d2f',
                metroTransport: 'ON_TRANSPORT',
                name: 'Пролетарская',
                metroCityRgid: 575243,
                timeToMetro: 33,
            },
            metroList: [
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101939,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Пролетарская',
                    metroCityRgid: 575243,
                    timeToMetro: 33,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101940,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Автозаводская',
                    metroCityRgid: 575243,
                    timeToMetro: 36,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101938,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Двигатель Революции',
                    metroCityRgid: 575243,
                    timeToMetro: 37,
                },
                {
                    lineColors: ['f03d2f'],
                    metroGeoId: 101942,
                    rgbColor: 'f03d2f',
                    metroTransport: 'ON_TRANSPORT',
                    name: 'Кировская',
                    metroCityRgid: 575243,
                    timeToMetro: 38,
                },
            ],
        },
    },
};
