/* eslint-disable max-len */
export const mockState = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?from=main_menu',
        queryId: '9615acefa745f3acc19607d298412119',
        isFailed: false,
        params: {
            from: 'main_menu',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        parents: [
            {
                id: 225,
                rgid: '143',
                name: 'Россия',
                type: 'COUNTRY',
                genitive: 'России',
            },
            {
                id: 0,
                rgid: '0',
                name: 'Весь мир',
                type: 'UNKNOWN',
            },
        ],
        heatmaps: ['infrastructure', 'price-rent', 'price-sell', 'profitability', 'transport', 'carsharing'],
        refinements: ['metro', 'directions', 'sub-localities', 'map-area'],
        sitesRgids: {
            district: 741964,
            mainCity: 587795,
        },
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 26267,
    },
    search: {
        offers: {
            pager: {
                page: 0,
                pageSize: 20,
                sitesPageSize: 20,
                totalItems: 26196,
                totalPages: 25,
                minPriceTotalItems: 50000,
                maxPriceTotalItems: 1000000000,
            },
            params: {
                rgid: 741964,
                currency: 'RUR',
                yandexUid: '393167231637669633',
                queryId: '9615acefa745f3acc19607d298412119',
                pageSize: 20,
                from: 'direct',
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                maxCoordinates: 500,
                showUniquePoints: 'NO',
                searchType: 'search',
                login: 'yandexuid:393167231637669633',
                showRevoked: 'YES',
                expFlags: [
                    'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                    'REALTYFRONT-12172_banners_ArendaGV',
                    'REALTYFRONT-12308_noticeable_filter_arenda',
                    'REALTYFRONT-12326_mini_widget_chats',
                    'REALTYFRONT-12146_chat_presets',
                    'REALTYFRONT-12147_new_snippet_nb_map_v1',
                    'REALTYFRONT-12096_popup_phone_show',
                    'REALTYFRONT-11455_new_card_second_iteration',
                    'REALTYFRONT-11292_new_offer_card',
                    'INTMONETIZATION-111-4-D',
                    'REALTYFRONT-12632_popup_gv',
                    'REALTYFRONT-11902_slider_middle',
                    'VSML-1007_ranking_sites',
                    'INTMONETIZATION-39-direct-search-off',
                    'REALTYFRONT-12105_snippets_on_landing',
                    'REALTYFRONT-10490_cannibalization',
                ],
            },
            direct: null,
        },
    },
    filtersParams: {
        offers: {
            rgid: 741964,
            subRegionId: null,
            mapPolygon: null,
            subLocality: null,
            subLocalityType: null,
            subLocalityName: null,
            nonAdminSubLocality: null,
            metroGeoId: null,
            railwayStation: null,
            direction: null,
            siteId: null,
            siteName: null,
            commercialBuildingId: null,
            streetId: null,
            unifiedAddress: null,
            address: null,
            villageId: null,
            leftLongitude: null,
            topLatitude: null,
            rightLongitude: null,
            bottomLatitude: null,
            streetName: null,
            streetNameCode: null,
            bcName: null,
            bcNameCode: null,
            'geo-suggest': null,
            commuteTransport: null,
            commuteTime: null,
            commutePointLatitude: null,
            commutePointLongitude: null,
            commuteAddress: null,
            zoom: null,
            expectMetro: null,
            hasPark: null,
            hasPond: null,
            type: 'SELL',
            category: 'APARTMENT',
            priceMin: null,
            priceMax: null,
            priceType: null,
            placementPeriod: null,
            areaMin: null,
            areaMax: null,
            lotAreaMin: null,
            lotAreaMax: null,
            hasPhoto: null,
            showSimilar: null,
            agents: null,
            metroTransport: null,
            directionDistanceMax: null,
            timeToMetro: null,
            hasFurniture: null,
            improvements: null,
            limitations: null,
            infrastructure: null,
            spots: null,
            newFlat: null,
            roomsTotal: null,
            livingSpaceMin: null,
            livingSpaceMax: null,
            kitchenSpaceMin: null,
            ceilingHeightMin: null,
            renovation: null,
            commercialPlanType: null,
            floorMin: null,
            floorMax: null,
            minFloors: null,
            maxFloors: null,
            lastFloor: null,
            floorExceptFirst: null,
            buildingType: null,
            buildingEpoch: null,
            buildingSeriesId: null,
            builtYearMin: null,
            builtYearMax: null,
            bathroomUnit: null,
            apartments: null,
            developerId: null,
            developerName: null,
            includeTag: null,
            excludeTag: null,
            parkingType: null,
            uid: null,
            yandexRent: null,
            conciergeBanner: null,
            insideTextLabel: null,
            showTextLabel: null,
            inRoom: null,
            balcony: null,
            rentTime: null,
            withPets: null,
            withChildren: null,
            hasAircondition: null,
            hasTwentyFourSeven: null,
            hasVentilation: null,
            hasParking: null,
            hasElectricitySupply: null,
            hasRefrigerator: null,
            hasTelevision: null,
            hasWashingMachine: null,
            hasPhone: null,
            hasDishwasher: null,
            hasWaterSupply: null,
            hasHeatingSupply: null,
            hasSecurity: null,
            hasGasSupply: null,
            hasSewerageSupply: null,
            hasAgentFee: null,
            maxFee: null,
            houseType: null,
            lotType: null,
            deliveryDate: null,
            garageType: null,
            expectDemolition: null,
            withExcerptsOnly: null,
            videoUrl: null,
            onlineShow: null,
            commercialType: null,
            pricingPeriod: null,
            commissionMax: null,
            commissionMin: null,
            commercialBuildingType: null,
            officeClass: null,
            entranceType: null,
            dealStatus: null,
            dealType: null,
            buildingClass: null,
            objectType: null,
            taxationForm: null,
            included: null,
            hasCleaningIncluded: null,
            hasUtilitiesIncluded: null,
            hasElectricityIncluded: null,
            profFilters: null,
            exclusive: null,
        },
    },
};

export const mockStateWithFilters = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        isFailed: false,
        params: {
            priceMin: '67777',
            areaMax: '50',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
            roomsTotal: '2',
        },
        isFromGate: true,
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            currencies: ['RUR', 'USD', 'EUR'],
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 5632,
    },
    search: {
        offers: {
            pager: {
                page: 0,
                pageSize: 20,
                sitesPageSize: 20,
                totalItems: 5632,
                totalPages: 25,
                minPriceTotalItems: 340000,
                maxPriceTotalItems: 94820304,
            },
            params: {
                rgid: '741964',
                currency: 'RUR',
                yandexUid: '393167231637669633',
                queryId: '42cb2bf27387bd4e0af7bbf4c8373772',
                pageSize: 20,
                priceMin: '67777',
                areaMax: '50',
                roomsTotal: '2',
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                maxCoordinates: 500,
                showUniquePoints: 'NO',
                searchType: 'search',
                from: 'direct',
                login: 'yandexuid:393167231637669633',
                showRevoked: 'YES',
                expFlags: [
                    'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                    'REALTYFRONT-12172_banners_ArendaGV',
                    'REALTYFRONT-12308_noticeable_filter_arenda',
                    'REALTYFRONT-12326_mini_widget_chats',
                    'REALTYFRONT-12146_chat_presets',
                    'REALTYFRONT-12147_new_snippet_nb_map_v1',
                    'REALTYFRONT-12096_popup_phone_show',
                    'REALTYFRONT-11455_new_card_second_iteration',
                    'REALTYFRONT-11292_new_offer_card',
                    'INTMONETIZATION-111-4-D',
                    'REALTYFRONT-12632_popup_gv',
                    'REALTYFRONT-11902_slider_middle',
                    'VSML-1007_ranking_sites',
                    'INTMONETIZATION-39-direct-search-off',
                    'REALTYFRONT-12105_snippets_on_landing',
                    'REALTYFRONT-10490_cannibalization',
                ],
            },
            direct: null,
        },
        serpSnippets: {},
        queryId: '42cb2bf27387bd4e0af7bbf4c8373772',
        refinements: {},
    },
    filtersParams: {
        offers: {
            rgid: 741964,
            subRegionId: null,
            mapPolygon: null,
            subLocality: null,
            subLocalityType: null,
            subLocalityName: null,
            nonAdminSubLocality: null,
            metroGeoId: null,
            railwayStation: null,
            direction: null,
            siteId: null,
            siteName: null,
            commercialBuildingId: null,
            streetId: null,
            unifiedAddress: null,
            address: null,
            villageId: null,
            leftLongitude: null,
            topLatitude: null,
            rightLongitude: null,
            bottomLatitude: null,
            streetName: null,
            streetNameCode: null,
            bcName: null,
            bcNameCode: null,
            'geo-suggest': null,
            commuteTransport: null,
            commuteTime: null,
            commutePointLatitude: null,
            commutePointLongitude: null,
            commuteAddress: null,
            zoom: null,
            expectMetro: null,
            hasPark: null,
            hasPond: null,
            type: 'SELL',
            category: 'APARTMENT',
            priceMin: 67777,
            priceMax: null,
            priceType: null,
            placementPeriod: null,
            areaMin: null,
            areaMax: 50,
            lotAreaMin: null,
            lotAreaMax: null,
            hasPhoto: null,
            showSimilar: null,
            agents: null,
            metroTransport: null,
            directionDistanceMax: null,
            timeToMetro: null,
            hasFurniture: null,
            improvements: null,
            limitations: null,
            infrastructure: null,
            spots: null,
            newFlat: null,
            roomsTotal: ['2'],
            livingSpaceMin: null,
            livingSpaceMax: null,
            kitchenSpaceMin: null,
            ceilingHeightMin: null,
            renovation: null,
            commercialPlanType: null,
            floorMin: null,
            floorMax: null,
            minFloors: null,
            maxFloors: null,
            lastFloor: null,
            floorExceptFirst: null,
            buildingType: null,
            buildingEpoch: null,
            buildingSeriesId: null,
            builtYearMin: null,
            builtYearMax: null,
            bathroomUnit: null,
            apartments: null,
            developerId: null,
            developerName: null,
            includeTag: null,
            excludeTag: null,
            parkingType: null,
            uid: null,
            yandexRent: null,
            conciergeBanner: null,
            insideTextLabel: null,
            showTextLabel: null,
            inRoom: null,
            balcony: null,
            rentTime: null,
            withPets: null,
            withChildren: null,
            hasAircondition: null,
            hasTwentyFourSeven: null,
            hasVentilation: null,
            hasParking: null,
            hasElectricitySupply: null,
            hasRefrigerator: null,
            hasTelevision: null,
            hasWashingMachine: null,
            hasPhone: null,
            hasDishwasher: null,
            hasWaterSupply: null,
            hasHeatingSupply: null,
            hasSecurity: null,
            hasGasSupply: null,
            hasSewerageSupply: null,
            hasAgentFee: null,
            maxFee: null,
            houseType: null,
            lotType: null,
            deliveryDate: null,
            garageType: null,
            expectDemolition: null,
            withExcerptsOnly: null,
            videoUrl: null,
            onlineShow: null,
            commercialType: null,
            pricingPeriod: null,
            commissionMax: null,
            commissionMin: null,
            commercialBuildingType: null,
            officeClass: null,
            entranceType: null,
            dealStatus: null,
            dealType: null,
            buildingClass: null,
            objectType: null,
            taxationForm: null,
            included: null,
            hasCleaningIncluded: null,
            hasUtilitiesIncluded: null,
            hasElectricityIncluded: null,
            profFilters: null,
            exclusive: null,
        },
    },
};

export const mockStateNonResidential = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/?priceMin=67777&areaMax=234',
        queryId: 'd4e24b7d22f5fc979ee8279cad86ac50',
        isFailed: false,
        params: {
            priceMin: '67777',
            areaMax: '234',
            rgid: 741964,
            type: 'SELL',
            category: 'COMMERCIAL',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        heatmapInfos: [
            {
                name: 'infrastructure-1',
                type: 'infrastructure',
                palette: [
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: 'ee4613',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'f87c19',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'fbae1e',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'ffe424',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: '9ada1b',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '30ce12',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '20a70a',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'price-rent-1',
                type: 'price-rent',
                palette: [
                    {
                        level: 1,
                        from: 128478,
                        to: 73416,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 73416,
                        to: 62358,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 62358,
                        to: 53751,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 53751,
                        to: 47500,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 47500,
                        to: 42541,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 42541,
                        to: 38380,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 38380,
                        to: 34542,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 34542,
                        to: 29184,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 29184,
                        to: 10374,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'price-sell-1',
                type: 'price-sell',
                palette: [
                    {
                        level: 1,
                        from: 1858678,
                        to: 538026,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 538026,
                        to: 411297,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 411297,
                        to: 347648,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 347648,
                        to: 308167,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 308167,
                        to: 274577,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 274577,
                        to: 240300,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 240300,
                        to: 208315,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 208315,
                        to: 139831,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 139831,
                        to: 18182,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'profitability-1',
                type: 'profitability',
                palette: [
                    {
                        level: 1,
                        from: 82,
                        to: 33,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 33,
                        to: 29,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 29,
                        to: 27,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 27,
                        to: 26,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 26,
                        to: 25,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 25,
                        to: 23,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 23,
                        to: 22,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 22,
                        to: 20,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 20,
                        to: 5,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'transport-1',
                type: 'transport',
                palette: [
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 9,
                        to: 10,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'carsharing-1',
                type: 'carsharing',
                palette: [
                    {
                        level: 0,
                        from: 0,
                        to: 1,
                        color: '620801',
                    },
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: 'ee4613',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'f87c19',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'fbae1e',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'ffe424',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: '9ada1b',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '30ce12',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '20a70a',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '128000',
                    },
                ],
            },
        ],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 4,
    },
    search: {
        offers: {
            pager: {
                page: 0,
                pageSize: 20,
                sitesPageSize: 20,
                totalItems: 4,
                totalPages: 1,
                minPriceTotalItems: 19290000,
                maxPriceTotalItems: 30000000,
            },
            params: {
                rgid: 741964,
                currency: 'RUR',
                yandexUid: '393167231637669633',
                queryId: 'd4e24b7d22f5fc979ee8279cad86ac50',
                pageSize: 20,
                priceMin: '67777',
                areaMax: '234',
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'COMMERCIAL',
                maxCoordinates: 500,
                showUniquePoints: 'NO',
                searchType: 'search',
                from: 'direct',
                login: 'yandexuid:393167231637669633',
                showRevoked: 'YES',
                expFlags: [
                    'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                    'REALTYFRONT-12172_banners_ArendaGV',
                    'REALTYFRONT-12308_noticeable_filter_arenda',
                    'REALTYFRONT-12326_mini_widget_chats',
                    'REALTYFRONT-12146_chat_presets',
                    'REALTYFRONT-12147_new_snippet_nb_map_v1',
                    'REALTYFRONT-12096_popup_phone_show',
                    'REALTYFRONT-11455_new_card_second_iteration',
                    'REALTYFRONT-11292_new_offer_card',
                    'INTMONETIZATION-111-4-D',
                    'REALTYFRONT-12632_popup_gv',
                    'REALTYFRONT-11902_slider_middle',
                    'VSML-1007_ranking_sites',
                    'INTMONETIZATION-39-direct-search-off',
                    'REALTYFRONT-12105_snippets_on_landing',
                    'REALTYFRONT-10490_cannibalization',
                ],
            },
            direct: null,
        },
        serpSnippets: {},
        queryId: 'd4e24b7d22f5fc979ee8279cad86ac50',
        refinements: {},
        mapsPromo: {
            displayedWizzardTips: [],
            displayedWizzards: [],
            isPopupDeactivated: false,
            availableWizzards: {
                desktopMap: 'desktopMap-0.1',
                touchMap: 'touchMap-0.1',
            },
            bannerType: 'draw',
        },
        newbuildingPromo: {
            total: 449,
        },
        serpDirectPicType: 4,
        searchPresets: [],
    },
    filtersParams: {
        offers: {
            rgid: 741964,
            subRegionId: null,
            mapPolygon: null,
            subLocality: null,
            subLocalityType: null,
            subLocalityName: null,
            nonAdminSubLocality: null,
            metroGeoId: null,
            railwayStation: null,
            direction: null,
            siteId: null,
            siteName: null,
            commercialBuildingId: null,
            streetId: null,
            unifiedAddress: null,
            address: null,
            villageId: null,
            leftLongitude: null,
            topLatitude: null,
            rightLongitude: null,
            bottomLatitude: null,
            streetName: null,
            streetNameCode: null,
            bcName: null,
            bcNameCode: null,
            'geo-suggest': null,
            commuteTransport: null,
            commuteTime: null,
            commutePointLatitude: null,
            commutePointLongitude: null,
            commuteAddress: null,
            zoom: null,
            expectMetro: null,
            hasPark: null,
            hasPond: null,
            type: 'SELL',
            category: 'COMMERCIAL',
            priceMin: 67777,
            priceMax: null,
            priceType: null,
            placementPeriod: null,
            areaMin: null,
            areaMax: 234,
            lotAreaMin: null,
            lotAreaMax: null,
            hasPhoto: null,
            showSimilar: null,
            agents: null,
            metroTransport: null,
            directionDistanceMax: null,
            timeToMetro: null,
            hasFurniture: null,
            improvements: null,
            limitations: null,
            infrastructure: null,
            spots: null,
            newFlat: null,
            roomsTotal: null,
            livingSpaceMin: null,
            livingSpaceMax: null,
            kitchenSpaceMin: null,
            ceilingHeightMin: null,
            renovation: null,
            commercialPlanType: null,
            floorMin: null,
            floorMax: null,
            minFloors: null,
            maxFloors: null,
            lastFloor: null,
            floorExceptFirst: null,
            buildingType: null,
            buildingEpoch: null,
            buildingSeriesId: null,
            builtYearMin: null,
            builtYearMax: null,
            bathroomUnit: null,
            apartments: null,
            developerId: null,
            developerName: null,
            includeTag: null,
            excludeTag: null,
            parkingType: null,
            uid: null,
            yandexRent: null,
            conciergeBanner: null,
            insideTextLabel: null,
            showTextLabel: null,
            inRoom: null,
            balcony: null,
            rentTime: null,
            withPets: null,
            withChildren: null,
            hasAircondition: null,
            hasTwentyFourSeven: null,
            hasVentilation: null,
            hasParking: null,
            hasElectricitySupply: null,
            hasRefrigerator: null,
            hasTelevision: null,
            hasWashingMachine: null,
            hasPhone: null,
            hasDishwasher: null,
            hasWaterSupply: null,
            hasHeatingSupply: null,
            hasSecurity: null,
            hasGasSupply: null,
            hasSewerageSupply: null,
            hasAgentFee: null,
            maxFee: null,
            houseType: null,
            lotType: null,
            deliveryDate: null,
            garageType: null,
            expectDemolition: null,
            withExcerptsOnly: null,
            videoUrl: null,
            onlineShow: null,
            commercialType: null,
            pricingPeriod: null,
            commissionMax: null,
            commissionMin: null,
            commercialBuildingType: null,
            officeClass: null,
            entranceType: null,
            dealStatus: null,
            dealType: null,
            buildingClass: null,
            objectType: null,
            taxationForm: null,
            included: null,
            hasCleaningIncluded: null,
            hasUtilitiesIncluded: null,
            hasElectricityIncluded: null,
            profFilters: null,
            exclusive: null,
        },
    },
};

export const mockStateWithoutMinPrice = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?from=main_menu',
        queryId: '9615acefa745f3acc19607d298412119',
        isFailed: false,
        params: {
            from: 'main_menu',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        parents: [
            {
                id: 225,
                rgid: '143',
                name: 'Россия',
                type: 'COUNTRY',
                genitive: 'России',
            },
            {
                id: 0,
                rgid: '0',
                name: 'Весь мир',
                type: 'UNKNOWN',
            },
        ],
        heatmaps: ['infrastructure', 'price-rent', 'price-sell', 'profitability', 'transport', 'carsharing'],
        refinements: ['metro', 'directions', 'sub-localities', 'map-area'],
        sitesRgids: {
            district: 741964,
            mainCity: 587795,
        },
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 26267,
    },
    search: {
        offers: {
            pager: {
                page: 0,
                pageSize: 20,
                sitesPageSize: 20,
                totalItems: 26196,
                totalPages: 25,
                minPriceTotalItems: 0,
                maxPriceTotalItems: 1000000000,
            },
            params: {
                rgid: 741964,
                currency: 'RUR',
                yandexUid: '393167231637669633',
                queryId: '9615acefa745f3acc19607d298412119',
                pageSize: 20,
                from: 'direct',
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                maxCoordinates: 500,
                showUniquePoints: 'NO',
                searchType: 'search',
                login: 'yandexuid:393167231637669633',
                showRevoked: 'YES',
                expFlags: [
                    'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                    'REALTYFRONT-12172_banners_ArendaGV',
                    'REALTYFRONT-12308_noticeable_filter_arenda',
                    'REALTYFRONT-12326_mini_widget_chats',
                    'REALTYFRONT-12146_chat_presets',
                    'REALTYFRONT-12147_new_snippet_nb_map_v1',
                    'REALTYFRONT-12096_popup_phone_show',
                    'REALTYFRONT-11455_new_card_second_iteration',
                    'REALTYFRONT-11292_new_offer_card',
                    'INTMONETIZATION-111-4-D',
                    'REALTYFRONT-12632_popup_gv',
                    'REALTYFRONT-11902_slider_middle',
                    'REALTYFRONT-12490_samolet_extended_card',
                    'VSML-1007_ranking_sites',
                    'INTMONETIZATION-39-direct-search-off',
                    'REALTYFRONT-12105_snippets_on_landing',
                    'REALTYFRONT-10490_cannibalization',
                ],
            },
            direct: null,
        },
    },
    filtersParams: {
        offers: {
            rgid: 741964,
            subRegionId: null,
            mapPolygon: null,
            subLocality: null,
            subLocalityType: null,
            subLocalityName: null,
            nonAdminSubLocality: null,
            metroGeoId: null,
            railwayStation: null,
            direction: null,
            siteId: null,
            siteName: null,
            commercialBuildingId: null,
            streetId: null,
            unifiedAddress: null,
            address: null,
            villageId: null,
            leftLongitude: null,
            topLatitude: null,
            rightLongitude: null,
            bottomLatitude: null,
            streetName: null,
            streetNameCode: null,
            bcName: null,
            bcNameCode: null,
            'geo-suggest': null,
            commuteTransport: null,
            commuteTime: null,
            commutePointLatitude: null,
            commutePointLongitude: null,
            commuteAddress: null,
            zoom: null,
            expectMetro: null,
            hasPark: null,
            hasPond: null,
            type: 'SELL',
            category: 'APARTMENT',
            priceMin: null,
            priceMax: null,
            priceType: null,
            placementPeriod: null,
            areaMin: null,
            areaMax: null,
            lotAreaMin: null,
            lotAreaMax: null,
            hasPhoto: null,
            showSimilar: null,
            agents: null,
            metroTransport: null,
            directionDistanceMax: null,
            timeToMetro: null,
            hasFurniture: null,
            improvements: null,
            limitations: null,
            infrastructure: null,
            spots: null,
            newFlat: null,
            roomsTotal: null,
            livingSpaceMin: null,
            livingSpaceMax: null,
            kitchenSpaceMin: null,
            ceilingHeightMin: null,
            renovation: null,
            commercialPlanType: null,
            floorMin: null,
            floorMax: null,
            minFloors: null,
            maxFloors: null,
            lastFloor: null,
            floorExceptFirst: null,
            buildingType: null,
            buildingEpoch: null,
            buildingSeriesId: null,
            builtYearMin: null,
            builtYearMax: null,
            bathroomUnit: null,
            apartments: null,
            developerId: null,
            developerName: null,
            includeTag: null,
            excludeTag: null,
            parkingType: null,
            uid: null,
            yandexRent: null,
            conciergeBanner: null,
            insideTextLabel: null,
            showTextLabel: null,
            inRoom: null,
            balcony: null,
            rentTime: null,
            withPets: null,
            withChildren: null,
            hasAircondition: null,
            hasTwentyFourSeven: null,
            hasVentilation: null,
            hasParking: null,
            hasElectricitySupply: null,
            hasRefrigerator: null,
            hasTelevision: null,
            hasWashingMachine: null,
            hasPhone: null,
            hasDishwasher: null,
            hasWaterSupply: null,
            hasHeatingSupply: null,
            hasSecurity: null,
            hasGasSupply: null,
            hasSewerageSupply: null,
            hasAgentFee: null,
            maxFee: null,
            houseType: null,
            lotType: null,
            deliveryDate: null,
            garageType: null,
            expectDemolition: null,
            withExcerptsOnly: null,
            videoUrl: null,
            onlineShow: null,
            commercialType: null,
            pricingPeriod: null,
            commissionMax: null,
            commissionMin: null,
            commercialBuildingType: null,
            officeClass: null,
            entranceType: null,
            dealStatus: null,
            dealType: null,
            buildingClass: null,
            objectType: null,
            taxationForm: null,
            included: null,
            hasCleaningIncluded: null,
            hasUtilitiesIncluded: null,
            hasElectricityIncluded: null,
            profFilters: null,
            exclusive: null,
        },
    },
};
