import { generateImageAliases } from '@realty-front/jest-utils/puppeteer/tests-helpers/image';

import { AreaUnits } from 'realty-core/types/offerCard';
import { IOfferSnippet } from 'realty-core/types/offerSnippet';

const image = generateImageAliases({
    width: 480,
    height: 480,
});

const appMiddleSnippetImages = [image.appSnippetMiddle];
const appSmallSnippetImages = [image.appSnippetSmall];

export const mockSell: IOfferSnippet = {
    active: true,
    appLargeImages: [],
    appMiddleImages: [],
    appMiddleSnippetImages,
    appSmallSnippetImages,
    area: {
        unit: 'SQUARE_METER',
        value: 35,
    },
    fullImages: ['//avatars.mdst.yandex.net/get-realty/2991/w1364/large'],
    location: {
        address: 'Москва, улица Кубинка',
        airports: [],
        cityCenter: [],
        geoId: 213,
        geocoderAddress: 'Россия, Москва, улица Кубинка',
        metro: {
            latitude: 55.724213,
            lineColors: ['ed9f2d'],
            longitude: 37.39848,
            metroCityRgid: 587795,
            metroGeoId: 218550,
            metroTransport: 'ON_FOOT',
            minTimeToMetro: 6,
            name: 'Сетунь',
            rgbColor: 'ed9f2d',
            timeToMetro: 13,
        },
        metroList: [
            {
                latitude: 55.724213,
                lineColors: ['ed9f2d'],
                longitude: 37.39848,
                metroCityRgid: 587795,
                metroGeoId: 218550,
                metroTransport: 'ON_FOOT',
                minTimeToMetro: 6,
                name: 'Сетунь',
                rgbColor: 'ed9f2d',
                timeToMetro: 13,
            },
            {
                latitude: 55.72692,
                lineColors: ['ed9f2d'],
                longitude: 37.417885,
                metroCityRgid: 587795,
                metroGeoId: 218541,
                metroTransport: 'ON_FOOT',
                minTimeToMetro: 7,
                name: 'Рабочий поселок',
                rgbColor: 'ed9f2d',
                timeToMetro: 15,
            },
            {
                latitude: 55.74087,
                lineColors: ['0042a5'],
                longitude: 37.416622,
                metroCityRgid: 587795,
                metroGeoId: 20454,
                metroTransport: 'ON_TRANSPORT',
                minTimeToMetro: 8,
                name: 'Молодёжная',
                rgbColor: '0042a5',
                timeToMetro: 8,
            },
            {
                latitude: 55.715996,
                lineColors: ['ed9f2d'],
                longitude: 37.375362,
                metroCityRgid: 587795,
                metroGeoId: 218555,
                metroTransport: 'ON_TRANSPORT',
                minTimeToMetro: 18,
                name: 'Немчиновка',
                rgbColor: 'ed9f2d',
                timeToMetro: 18,
            },
        ],
        point: {
            latitude: 55.72115,
            longitude: 37.407288,
            precision: 'EXACT',
        },
        ponds: [],
        populatedRgid: 587795,
        rgid: 193323,
        settlementGeoId: 213,
        settlementRgid: 587795,
        station: {
            distanceKm: 0.667,
            name: 'Сетунь',
        },
        streetAddress: 'улица Кубинка',
        streetId: 76395,
        structuredAddress: {
            component: [
                {
                    address: 'Россия',
                    geoId: 225,
                    queryParams: {
                        address: 'Россия',
                        rgid: '143',
                    },
                    regionGraphId: '143',
                    regionType: 'COUNTRY',
                    value: 'Россия',
                    rgid: '143',
                },
                {
                    address: 'Москва',
                    geoId: 213,
                    queryParams: {
                        address: 'Россия, Москва',
                        rgid: '587795',
                    },
                    regionGraphId: '587795',
                    regionType: 'CITY',
                    value: 'Москва',
                    rgid: '587795',
                },
                {
                    address: 'улица Кубинка',
                    geoId: 213,
                    queryParams: {
                        address: 'Россия, Москва, улица Кубинка',
                        rgid: '587795',
                    },
                    regionGraphId: '587795',
                    regionType: 'STREET',
                    value: 'улица Кубинка',
                    rgid: '587795',
                },
            ],
        },
        subjectFederationId: 1,
        subjectFederationName: 'Москва и МО',
        subjectFederationRgid: 741964,
    },
    offerCategory: 'APARTMENT',
    offerId: '484071773530062483',
    offerType: 'SELL',
    photoPreviews: [''],
    price: {
        currency: 'RUR',
        hasPriceHistory: false,
        period: 'WHOLE_LIFE',
        price: {
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'WHOLE_LIFE',
            value: 13000000,
        },
        priceForWhole: {
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'WHOLE_LIFE',
            value: 13000000,
        },
        pricePerPart: {
            currency: 'RUB',
            priceType: 'PER_METER',
            pricingPeriod: 'WHOLE_LIFE',
            value: 371429,
        },
        trend: 'UNCHANGED',
        unit: 'WHOLE_OFFER',
        unitForWhole: 'WHOLE_OFFER',
        unitPerPart: 'SQUARE_METER' as AreaUnits,
        value: 13000000,
        valueForWhole: 13000000,
        valuePerPart: 371429,
    },
    roomsTotal: 1,
    uid: '4061896948',
};

export const mockRent: IOfferSnippet = {
    active: true,
    appLargeImages: [],
    appMiddleImages: [],
    appMiddleSnippetImages,
    appSmallSnippetImages,
    area: {
        unit: 'SQUARE_METER',
        value: 67,
    },
    fullImages: ['//avatars.mdst.yandex.net/get-realty/2991/w1364/large'],
    location: {
        address: 'Москва, улица Кубинка',
        airports: [],
        cityCenter: [],
        geoId: 213,
        geocoderAddress: 'Россия, Москва, улица Кубинка',
        metro: {
            latitude: 55.724213,
            lineColors: ['ed9f2d'],
            longitude: 37.39848,
            metroCityRgid: 587795,
            metroGeoId: 218550,
            metroTransport: 'ON_FOOT',
            minTimeToMetro: 6,
            name: 'Сетунь',
            rgbColor: 'ed9f2d',
            timeToMetro: 13,
        },
        metroList: [
            {
                latitude: 55.724213,
                lineColors: ['ed9f2d'],
                longitude: 37.39848,
                metroCityRgid: 587795,
                metroGeoId: 218550,
                metroTransport: 'ON_FOOT',
                minTimeToMetro: 6,
                name: 'Сетунь',
                rgbColor: 'ed9f2d',
                timeToMetro: 13,
            },
            {
                latitude: 55.72692,
                lineColors: ['ed9f2d'],
                longitude: 37.417885,
                metroCityRgid: 587795,
                metroGeoId: 218541,
                metroTransport: 'ON_FOOT',
                minTimeToMetro: 7,
                name: 'Рабочий поселок',
                rgbColor: 'ed9f2d',
                timeToMetro: 15,
            },
            {
                latitude: 55.74087,
                lineColors: ['0042a5'],
                longitude: 37.416622,
                metroCityRgid: 587795,
                metroGeoId: 20454,
                metroTransport: 'ON_TRANSPORT',
                minTimeToMetro: 8,
                name: 'Молодёжная',
                rgbColor: '0042a5',
                timeToMetro: 8,
            },
            {
                latitude: 55.715996,
                lineColors: ['ed9f2d'],
                longitude: 37.375362,
                metroCityRgid: 587795,
                metroGeoId: 218555,
                metroTransport: 'ON_TRANSPORT',
                minTimeToMetro: 18,
                name: 'Немчиновка',
                rgbColor: 'ed9f2d',
                timeToMetro: 18,
            },
        ],
        point: {
            latitude: 55.72115,
            longitude: 37.407288,
            precision: 'EXACT',
        },
        ponds: [],
        populatedRgid: 587795,
        rgid: 193323,
        settlementGeoId: 213,
        settlementRgid: 587795,
        station: {
            distanceKm: 0.667,
            name: 'Сетунь',
        },
        streetAddress: 'улица Кубинка',
        streetId: 76395,
        structuredAddress: {
            component: [
                {
                    address: 'Россия',
                    geoId: 225,
                    queryParams: {
                        address: 'Россия',
                        rgid: '143',
                    },
                    regionGraphId: '143',
                    regionType: 'COUNTRY',
                    value: 'Россия',
                    rgid: '143',
                },
                {
                    address: 'Москва',
                    geoId: 213,
                    queryParams: {
                        address: 'Россия, Москва',
                        rgid: '587795',
                    },
                    regionGraphId: '587795',
                    regionType: 'CITY',
                    value: 'Москва',
                    rgid: '587795',
                },
                {
                    address: 'улица Кубинка',
                    geoId: 213,
                    queryParams: {
                        address: 'Россия, Москва, улица Кубинка',
                        rgid: '587795',
                    },
                    regionGraphId: '587795',
                    regionType: 'STREET',
                    value: 'улица Кубинка',
                    rgid: '587795',
                },
            ],
        },
        subjectFederationId: 1,
        subjectFederationName: 'Москва и МО',
        subjectFederationRgid: 741964,
    },
    offerCategory: 'APARTMENT',
    offerId: '484071773530062483',
    offerType: 'RENT',
    photoPreviews: [''],
    price: {
        currency: 'RUR',
        hasPriceHistory: false,
        period: 'PER_MONTH',
        price: {
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'PER_MONTH',
            value: 57000,
        },
        priceForWhole: {
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'PER_MONTH',
            value: 57000,
        },
        pricePerPart: {
            currency: 'RUB',
            priceType: 'PER_METER',
            pricingPeriod: 'PER_MONTH',
            value: 851,
        },
        trend: 'UNCHANGED',
        unit: 'WHOLE_OFFER',
        unitForWhole: 'WHOLE_OFFER',
        unitPerPart: 'SQUARE_METER' as AreaUnits,
        value: 57000,
        valueForWhole: 57000,
        valuePerPart: 851,
    },
    roomsTotal: 2,
    uid: '4061896948',
};

export const initialState = {
    user: {
        favorites: [2],
        favoritesMap: {
            2: true,
        },
    },
    page: {
        name: 'offer',
    },
};
