/* eslint-disable max-len */
export const mockState = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?from=main_menu',
        queryId: '9615acefa745f3acc19607d298412119',
        isFailed: false,
        params: {
            from: 'main_menu',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        parents: [
            {
                id: 225,
                rgid: '143',
                name: 'Россия',
                type: 'COUNTRY',
                genitive: 'России',
            },
            {
                id: 0,
                rgid: '0',
                name: 'Весь мир',
                type: 'UNKNOWN',
            },
        ],
        heatmaps: ['infrastructure', 'price-rent', 'price-sell', 'profitability', 'transport', 'carsharing'],
        refinements: ['metro', 'directions', 'sub-localities', 'map-area'],
        sitesRgids: {
            district: 741964,
            mainCity: 587795,
        },
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 26267,
    },
    offersSearchPage: {
        direct: null,
        directList: [
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
        ],
        directParams: {
            rgid: 741964,
            currency: 'RUR',
            yandexUid: '393167231637669633',
            queryId: '581ebf066e5ba01922069a416ddf2612',
            pageSize: 10,
            sort: 'RELEVANCE',
            type: 'SELL',
            category: 'APARTMENT',
            searchType: 'offers',
            from: 'direct',
            login: 'yandexuid:393167231637669633',
        },
        searchResults: {
            pager: {
                isNewPager: true,
                firstPageIndex: 0,
                lastPageIndex: 0,
                totalItems: 26175,
                pageSize: 10,
                totalPages: 50,
                minPriceTotalItems: 50000,
                maxPriceTotalItems: 1000000000,
            },
            queryId: '581ebf066e5ba01922069a416ddf2612',
            searchParams: {
                pageSize: 10,
                rgid: 741964,
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                siteName: null,
            },
            isLoading: false,
            isPageLoading: false,
        },
        searchPresets: [
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/novostroyki/?isFastlink=true',
                text: 'В новостройке',
                canonical: '',
                offersCount: 25197,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?withExcerptsOnly=YES&isFastlink=true',
                text: 'Проверенные в ЕГРН',
                canonical: '',
                offersCount: 56,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/s-balkonom/?isFastlink=true',
                text: 'С балконом',
                canonical: '',
                offersCount: 25583,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?floorExceptFirst=YES&isFastlink=true',
                text: 'Не первый этаж',
                canonical: '',
                offersCount: 24838,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?renovation=COSMETIC_DONE&isFastlink=true',
                text: 'С косметическим ремонтом',
                canonical: '',
                offersCount: 23650,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/?isFastlink=true',
                text: '2 комнаты',
                canonical: '',
                offersCount: 9553,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/ryadom-metro/?isFastlink=true',
                text: 'Рядом с метро',
                canonical: '',
                offersCount: 9004,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/odnokomnatnaya/?isFastlink=true',
                text: '1 комната',
                canonical: '',
                offersCount: 8351,
            },
        ],
        searchQuery: {
            offset: 0,
            page: 0,
            pageSize: 10,
            sort: 'RELEVANCE',
            maxCoordinates: 100,
            clusterSize: 0,
            excludePartnerId: false,
            commutePoint: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            commuteTransport: 'NOT_DEFINED',
            lt: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            rb: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            regionId: 0,
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
            propertyType: 'UNKNOWN',
            price: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            currency: 'RUR',
            locale: 'RU',
            priceType: 'PER_OFFER',
            rentTime: 'LARGE',
            floor: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            area: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            livingSpace: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            kitchenSpace: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            lotArea: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            metroTransport: 'UNKNOWN',
            directionDistance: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            balcony: 'UNKNOWN',
            minTrust: 'UNKNOWN',
            newFlat: true,
            placementPeriod: 'UNKNOWN',
            showSimilar: true,
            manualyAdded: false,
            payed: false,
            yandexUid: '393167231637669633',
            clusterHead: true,
            premoderation: false,
            showAll: false,
            raised: false,
            premium: false,
            showPlan: false,
            commercialPlanType: 'UNKNOWN',
            commission: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            securityPayment: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            dealStatus: 'UNKNOWN',
            entranceType: 'UNKNOWN',
            pricingPeriod: 'UNKNOWN',
            flatType: 'UNKNOWN',
            from: 'direct',
            searchWithDeleted: false,
            login: 'yandexuid:393167231637669633',
            showUniquePoints: true,
            queryId: '581ebf066e5ba01922069a416ddf2612',
            onlyPIK: false,
            expFlags: [
                'REALTYFRONT-12147_new_snippet_nb_map_v1',
                'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                'REALTYFRONT-11292_new_offer_card',
                'REALTYFRONT-12308_noticeable_filter_arenda',
                'REALTYFRONT-10490_cannibalization',
                'REALTYFRONT-12326_mini_widget_chats',
                'REALTYFRONT-11455_new_card_second_iteration',
                'VSML-1007_ranking_sites',
                'REALTYFRONT-12096_popup_phone_show',
                'INTMONETIZATION-111-4-D',
                'REALTYFRONT-12632_popup_gv',
                'REALTYFRONT-12105_snippets_on_landing',
                'REALTYFRONT-12172_banners_ArendaGV',
                'REALTYFRONT-12146_chat_presets',
                'REALTYFRONT-11902_slider_middle',
                'INTMONETIZATION-39-direct-search-off',
            ],
            nearSubway: false,
            ceilingHeight: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            clusterizationType: 'DEFAULT',
            userPlatform: 'DESKTOP',
            mixedSearch: true,
            revoked: false,
            routesWithMKAD: false,
            landType: 'LAND_TYPE_UNKNOWN',
            withExcerptsOnly: false,
            videoUrl: false,
            onlineShow: false,
            paymentType: 'UNKNOWN',
            url:
                'offerSearchV2.json?queryId=581ebf066e5ba01922069a416ddf2612&pageSize=10&searchType=offers&userPlatform=desktop&rgid=741964&expFlags=REALTYFRONT-12444_add_whatsapp_landing_arenda&expFlags=REALTYFRONT-12172_banners_ArendaGV&expFlags=REALTYFRONT-12308_noticeable_filter_arenda&expFlags=REALTYFRONT-12326_mini_widget_chats&expFlags=REALTYFRONT-12146_chat_presets&expFlags=REALTYFRONT-12147_new_snippet_nb_map_v1&expFlags=REALTYFRONT-12096_popup_phone_show&expFlags=REALTYFRONT-11455_new_card_second_iteration&expFlags=REALTYFRONT-11292_new_offer_card&expFlags=INTMONETIZATION-111-4-D&expFlags=REALTYFRONT-12632_popup_gv&expFlags=REALTYFRONT-11902_slider_middle&expFlags=VSML-1007_ranking_sites&expFlags=INTMONETIZATION-39-direct-search-off&expFlags=REALTYFRONT-12105_snippets_on_landing&expFlags=REALTYFRONT-10490_cannibalization&from=direct&currency=RUR&category=APARTMENT&sort=RELEVANCE&login=yandexuid:393167231637669633&type=SELL&yandexUid=393167231637669633',
            paidOnly: 'UNKNOWN',
            pointSize: 0,
            fullTrustedOwner: false,
            yandexRent: false,
            emptyLocationSubqueries: true,
            roomsTotalFirstValueValid: false,
            subLocalityFirstValueValid: false,
            nonAdminSubLocalityFirstValueValid: false,
            roomsOfferedFirstValueValid: false,
            metroGeoIdFirstValueValid: false,
            directionFirstValueValid: false,
            directionDistanceInMeters: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            logQueryId: '1aa0696c76ebe9142a6a7746ebf280e6',
        },
        serpSnippets: {},
    },
    filters: {
        offers: {
            type: 'offers',
            data: {
                'geo-refinement-multi': [],
                type: 'SELL',
                ctype: 'SELL',
                category: 'APARTMENT',
                priceType: 'PER_OFFER',
                metroTransport: 'ON_FOOT',
                pricingPeriod: 'PER_MONTH',
                commissionMax: null,
                'geo-region': {
                    label: 'Москва и МО',
                    rgid: 741964,
                },
                sort: 'RELEVANCE',
            },
        },
    },
};

export const mockStateWithFilters = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        isFailed: false,
        params: {
            priceMin: '67777',
            areaMax: '50',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
            roomsTotal: '2',
        },
        isFromGate: true,
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            currencies: ['RUR', 'USD', 'EUR'],
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 5632,
    },
    offersSearchPage: {
        direct: null,
        directList: [
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
        ],
        directParams: {
            rgid: 741964,
            currency: 'RUR',
            yandexUid: '393167231637669633',
            queryId: '2a96fbee3a436a371370f2d8650da522',
            pageSize: 10,
            priceMin: '1230000',
            areaMax: '56',
            roomsTotal: '2',
            sort: 'RELEVANCE',
            type: 'SELL',
            category: 'APARTMENT',
            searchType: 'offers',
            from: 'direct',
            login: 'yandexuid:393167231637669633',
        },
        searchResults: {
            pager: {
                isNewPager: true,
                firstPageIndex: 0,
                lastPageIndex: 0,
                totalItems: 7987,
                pageSize: 10,
                totalPages: 50,
                minPriceTotalItems: 3802277,
                maxPriceTotalItems: 94820304,
            },
            queryId: '2a96fbee3a436a371370f2d8650da522',
            searchParams: {
                pageSize: 10,
                priceMin: '1230000',
                areaMax: '56',
                rgid: 741964,
                roomsTotal: '2',
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                siteName: null,
            },
            isLoading: false,
            isPageLoading: false,
        },
        searchPresets: [
            {
                url:
                    '/moskva_i_moskovskaya_oblast/kupit/kvartira/odnokomnatnaya/?areaMax=56&priceMin=1230000&isFastlink=true',
                text: '1 комната',
                canonical: '',
                offersCount: 8229,
            },
            {
                url:
                    '/moskva_i_moskovskaya_oblast/kupit/kvartira/tryohkomnatnaya/?areaMax=56&priceMin=1230000&isFastlink=true',
                text: '3 комнаты',
                canonical: '',
                offersCount: 1069,
            },
        ],
        searchQuery: {
            offset: 0,
            page: 0,
            pageSize: 10,
            sort: 'RELEVANCE',
            maxCoordinates: 100,
            clusterSize: 0,
            excludePartnerId: false,
            commutePoint: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            commuteTransport: 'NOT_DEFINED',
            lt: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            rb: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            regionId: 0,
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
            propertyType: 'UNKNOWN',
            price: {
                first: 1230000,
                leftOpen: false,
                rightOpen: true,
                open: false,
                from: 1230000,
            },
            currency: 'RUR',
            locale: 'RU',
            priceType: 'PER_OFFER',
            rentTime: 'LARGE',
            roomsTotal: ['_2'],
            floor: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            area: {
                second: 56,
                to: 56,
                leftOpen: true,
                rightOpen: false,
                open: false,
            },
            livingSpace: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            kitchenSpace: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            lotArea: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            metroTransport: 'UNKNOWN',
            directionDistance: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            balcony: 'UNKNOWN',
            minTrust: 'UNKNOWN',
            newFlat: true,
            placementPeriod: 'UNKNOWN',
            showSimilar: true,
            manualyAdded: false,
            payed: false,
            yandexUid: '393167231637669633',
            clusterHead: true,
            premoderation: false,
            showAll: false,
            raised: false,
            premium: false,
            showPlan: false,
            commercialPlanType: 'UNKNOWN',
            commission: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            securityPayment: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            dealStatus: 'UNKNOWN',
            entranceType: 'UNKNOWN',
            pricingPeriod: 'UNKNOWN',
            flatType: 'UNKNOWN',
            from: 'direct',
            searchWithDeleted: false,
            login: 'yandexuid:393167231637669633',
            showUniquePoints: true,
            queryId: '2a96fbee3a436a371370f2d8650da522',
            onlyPIK: false,
            expFlags: [
                'REALTYFRONT-12147_new_snippet_nb_map_v1',
                'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                'REALTYFRONT-11292_new_offer_card',
                'REALTYFRONT-12308_noticeable_filter_arenda',
                'REALTYFRONT-10490_cannibalization',
                'REALTYFRONT-12326_mini_widget_chats',
                'REALTYFRONT-11455_new_card_second_iteration',
                'VSML-1007_ranking_sites',
                'REALTYFRONT-12096_popup_phone_show',
                'INTMONETIZATION-111-4-D',
                'REALTYFRONT-12632_popup_gv',
                'REALTYFRONT-12105_snippets_on_landing',
                'REALTYFRONT-12172_banners_ArendaGV',
                'REALTYFRONT-12146_chat_presets',
                'REALTYFRONT-11902_slider_middle',
                'INTMONETIZATION-39-direct-search-off',
            ],
            nearSubway: false,
            ceilingHeight: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            clusterizationType: 'DEFAULT',
            userPlatform: 'DESKTOP',
            mixedSearch: true,
            revoked: false,
            routesWithMKAD: false,
            landType: 'LAND_TYPE_UNKNOWN',
            withExcerptsOnly: false,
            videoUrl: false,
            onlineShow: false,
            paymentType: 'UNKNOWN',
            url:
                'offerSearchV2.json?queryId=2a96fbee3a436a371370f2d8650da522&pageSize=10&roomsTotal=2&areaMax=56&searchType=offers&userPlatform=desktop&rgid=741964&expFlags=REALTYFRONT-12444_add_whatsapp_landing_arenda&expFlags=REALTYFRONT-12172_banners_ArendaGV&expFlags=REALTYFRONT-12308_noticeable_filter_arenda&expFlags=REALTYFRONT-12326_mini_widget_chats&expFlags=REALTYFRONT-12146_chat_presets&expFlags=REALTYFRONT-12147_new_snippet_nb_map_v1&expFlags=REALTYFRONT-12096_popup_phone_show&expFlags=REALTYFRONT-11455_new_card_second_iteration&expFlags=REALTYFRONT-11292_new_offer_card&expFlags=INTMONETIZATION-111-4-D&expFlags=REALTYFRONT-12632_popup_gv&expFlags=REALTYFRONT-11902_slider_middle&expFlags=VSML-1007_ranking_sites&expFlags=INTMONETIZATION-39-direct-search-off&expFlags=REALTYFRONT-12105_snippets_on_landing&expFlags=REALTYFRONT-10490_cannibalization&from=direct&priceMin=1230000&currency=RUR&category=APARTMENT&sort=RELEVANCE&login=yandexuid:393167231637669633&type=SELL&yandexUid=393167231637669633',
            paidOnly: 'UNKNOWN',
            pointSize: 0,
            fullTrustedOwner: false,
            yandexRent: false,
            emptyLocationSubqueries: true,
            roomsTotalFirstValueValid: true,
            subLocalityFirstValueValid: false,
            nonAdminSubLocalityFirstValueValid: false,
            roomsOfferedFirstValueValid: false,
            metroGeoIdFirstValueValid: false,
            directionFirstValueValid: false,
            directionDistanceInMeters: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            logQueryId: '2536f31187e1391ec671924cd5546602',
            priceMin: 1230000,
            areaMax: 56,
        },
        serpSnippets: {},
    },
    filters: {
        offers: {
            type: 'offers',
            data: {
                'geo-refinement-multi': [],
                type: 'SELL',
                ctype: 'SELL',
                category: 'APARTMENT',
                price: [1230000, null],
                priceType: 'PER_OFFER',
                area: [null, 56],
                metroTransport: 'ON_FOOT',
                roomsTotal: ['2'],
                pricingPeriod: 'PER_MONTH',
                commissionMax: null,
                'geo-region': {
                    label: 'Москва и МО',
                    rgid: 741964,
                },
                sort: 'RELEVANCE',
            },
        },
    },
};

export const mockStateNonResidential = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/?priceMin=67777&areaMax=234',
        queryId: 'd4e24b7d22f5fc979ee8279cad86ac50',
        isFailed: false,
        params: {
            priceMin: '67777',
            areaMax: '234',
            rgid: 741964,
            type: 'SELL',
            category: 'COMMERCIAL',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        heatmapInfos: [
            {
                name: 'infrastructure-1',
                type: 'infrastructure',
                palette: [
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: 'ee4613',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'f87c19',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'fbae1e',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'ffe424',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: '9ada1b',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '30ce12',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '20a70a',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'price-rent-1',
                type: 'price-rent',
                palette: [
                    {
                        level: 1,
                        from: 128478,
                        to: 73416,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 73416,
                        to: 62358,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 62358,
                        to: 53751,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 53751,
                        to: 47500,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 47500,
                        to: 42541,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 42541,
                        to: 38380,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 38380,
                        to: 34542,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 34542,
                        to: 29184,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 29184,
                        to: 10374,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'price-sell-1',
                type: 'price-sell',
                palette: [
                    {
                        level: 1,
                        from: 1858678,
                        to: 538026,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 538026,
                        to: 411297,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 411297,
                        to: 347648,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 347648,
                        to: 308167,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 308167,
                        to: 274577,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 274577,
                        to: 240300,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 240300,
                        to: 208315,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 208315,
                        to: 139831,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 139831,
                        to: 18182,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'profitability-1',
                type: 'profitability',
                palette: [
                    {
                        level: 1,
                        from: 82,
                        to: 33,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 33,
                        to: 29,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 29,
                        to: 27,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 27,
                        to: 26,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 26,
                        to: 25,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 25,
                        to: 23,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 23,
                        to: 22,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 22,
                        to: 20,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 20,
                        to: 5,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'transport-1',
                type: 'transport',
                palette: [
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: '620801',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'ee4613',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'f87c19',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'fbae1e',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: 'ffe424',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '9ada1b',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '30ce12',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '20a70a',
                    },
                    {
                        level: 9,
                        from: 9,
                        to: 10,
                        color: '128000',
                    },
                ],
            },
            {
                name: 'carsharing-1',
                type: 'carsharing',
                palette: [
                    {
                        level: 0,
                        from: 0,
                        to: 1,
                        color: '620801',
                    },
                    {
                        level: 1,
                        from: 1,
                        to: 2,
                        color: 'ee4613',
                    },
                    {
                        level: 2,
                        from: 2,
                        to: 3,
                        color: 'f87c19',
                    },
                    {
                        level: 3,
                        from: 3,
                        to: 4,
                        color: 'fbae1e',
                    },
                    {
                        level: 4,
                        from: 4,
                        to: 5,
                        color: 'ffe424',
                    },
                    {
                        level: 5,
                        from: 5,
                        to: 6,
                        color: '9ada1b',
                    },
                    {
                        level: 6,
                        from: 6,
                        to: 7,
                        color: '30ce12',
                    },
                    {
                        level: 7,
                        from: 7,
                        to: 8,
                        color: '20a70a',
                    },
                    {
                        level: 8,
                        from: 8,
                        to: 9,
                        color: '128000',
                    },
                ],
            },
        ],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kommercheskaya-nedvizhimost/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 4,
    },
    offersSearchPage: {
        direct: null,
        directList: [
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
        ],
        directParams: {
            rgid: 741964,
            currency: 'RUR',
            yandexUid: '393167231637669633',
            queryId: '6e930ea352c00acd04aa15faf6b19e79',
            pageSize: 10,
            priceMin: '4',
            sort: 'RELEVANCE',
            type: 'SELL',
            category: 'COMMERCIAL',
            searchType: 'offers',
            from: 'direct',
            login: 'yandexuid:393167231637669633',
        },
        searchResults: {
            pager: {
                isNewPager: true,
                firstPageIndex: 0,
                lastPageIndex: 0,
                totalItems: 8,
                pageSize: 10,
                totalPages: 1,
                minPriceTotalItems: 3400000,
                maxPriceTotalItems: 33290000,
            },
            queryId: '6e930ea352c00acd04aa15faf6b19e79',
            searchParams: {
                pageSize: 10,
                priceMin: '4',
                rgid: 741964,
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'COMMERCIAL',
                siteName: null,
            },
            isLoading: false,
            isPageLoading: false,
        },
        searchPresets: [],
        searchQuery: {
            offset: 0,
            page: 0,
            pageSize: 10,
            sort: 'RELEVANCE',
            maxCoordinates: 100,
            clusterSize: 0,
            excludePartnerId: false,
            commutePoint: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            commuteTransport: 'NOT_DEFINED',
            lt: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            rb: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            regionId: 0,
            rgid: 741964,
            type: 'SELL',
            category: 'COMMERCIAL',
            propertyType: 'UNKNOWN',
            price: {
                first: 4,
                leftOpen: false,
                rightOpen: true,
                from: 4,
                open: false,
            },
            currency: 'RUR',
            locale: 'RU',
            priceType: 'PER_OFFER',
            rentTime: 'LARGE',
            floor: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            area: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            livingSpace: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            kitchenSpace: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            lotArea: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            metroTransport: 'UNKNOWN',
            directionDistance: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            balcony: 'UNKNOWN',
            minTrust: 'UNKNOWN',
            placementPeriod: 'UNKNOWN',
            showSimilar: true,
            manualyAdded: false,
            payed: false,
            yandexUid: '393167231637669633',
            clusterHead: true,
            premoderation: false,
            showAll: false,
            raised: false,
            premium: false,
            showPlan: false,
            commercialPlanType: 'UNKNOWN',
            commission: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            securityPayment: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            dealStatus: 'UNKNOWN',
            entranceType: 'UNKNOWN',
            pricingPeriod: 'UNKNOWN',
            flatType: 'UNKNOWN',
            from: 'direct',
            searchWithDeleted: false,
            login: 'yandexuid:393167231637669633',
            showUniquePoints: true,
            queryId: '6e930ea352c00acd04aa15faf6b19e79',
            onlyPIK: false,
            expFlags: [
                'REALTYFRONT-12147_new_snippet_nb_map_v1',
                'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                'REALTYFRONT-11292_new_offer_card',
                'REALTYFRONT-12308_noticeable_filter_arenda',
                'REALTYFRONT-10490_cannibalization',
                'REALTYFRONT-12326_mini_widget_chats',
                'REALTYFRONT-11455_new_card_second_iteration',
                'VSML-1007_ranking_sites',
                'REALTYFRONT-12096_popup_phone_show',
                'INTMONETIZATION-111-4-D',
                'REALTYFRONT-12632_popup_gv',
                'REALTYFRONT-12105_snippets_on_landing',
                'REALTYFRONT-12172_banners_ArendaGV',
                'REALTYFRONT-12146_chat_presets',
                'REALTYFRONT-11902_slider_middle',
                'INTMONETIZATION-39-direct-search-off',
            ],
            nearSubway: false,
            ceilingHeight: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            clusterizationType: 'DEFAULT',
            userPlatform: 'DESKTOP',
            revoked: false,
            routesWithMKAD: false,
            landType: 'LAND_TYPE_UNKNOWN',
            withExcerptsOnly: false,
            videoUrl: false,
            onlineShow: false,
            paymentType: 'UNKNOWN',
            url:
                'offerSearchV2.json?queryId=6e930ea352c00acd04aa15faf6b19e79&pageSize=10&searchType=offers&userPlatform=desktop&rgid=741964&expFlags=REALTYFRONT-12444_add_whatsapp_landing_arenda&expFlags=REALTYFRONT-12172_banners_ArendaGV&expFlags=REALTYFRONT-12308_noticeable_filter_arenda&expFlags=REALTYFRONT-12326_mini_widget_chats&expFlags=REALTYFRONT-12146_chat_presets&expFlags=REALTYFRONT-12147_new_snippet_nb_map_v1&expFlags=REALTYFRONT-12096_popup_phone_show&expFlags=REALTYFRONT-11455_new_card_second_iteration&expFlags=REALTYFRONT-11292_new_offer_card&expFlags=INTMONETIZATION-111-4-D&expFlags=REALTYFRONT-12632_popup_gv&expFlags=REALTYFRONT-11902_slider_middle&expFlags=VSML-1007_ranking_sites&expFlags=INTMONETIZATION-39-direct-search-off&expFlags=REALTYFRONT-12105_snippets_on_landing&expFlags=REALTYFRONT-10490_cannibalization&from=direct&priceMin=4&currency=RUR&category=COMMERCIAL&sort=RELEVANCE&login=yandexuid:393167231637669633&type=SELL&yandexUid=393167231637669633',
            paidOnly: 'UNKNOWN',
            pointSize: 0,
            fullTrustedOwner: false,
            yandexRent: false,
            emptyLocationSubqueries: true,
            roomsTotalFirstValueValid: false,
            subLocalityFirstValueValid: false,
            nonAdminSubLocalityFirstValueValid: false,
            roomsOfferedFirstValueValid: false,
            metroGeoIdFirstValueValid: false,
            directionFirstValueValid: false,
            directionDistanceInMeters: {
                leftOpen: true,
                rightOpen: true,
                open: true,
            },
            logQueryId: '5ddbf8b046d4af3575a10fdc44cf4adf',
            priceMin: 4,
        },
        serpSnippets: {},
    },
    filters: {
        offers: {
            type: 'offers',
            data: {
                'geo-refinement-multi': [],
                type: 'SELL',
                ctype: 'SELL',
                category: 'COMMERCIAL',
                price: [23123, null],
                priceType: 'PER_OFFER',
                area: [null, 234],
                metroTransport: 'ON_FOOT',
                pricingPeriod: 'PER_MONTH',
                commissionMax: null,
                'geo-region': {
                    label: 'Москва и МО',
                    rgid: 741964,
                },
                sort: 'RELEVANCE',
            },
        },
    },
};

export const mockStateWithoutMinPrice = {
    page: {
        isLoading: false,
        isLocked: false,
        name: 'search',
        route: 'search',
        path: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?from=main_menu',
        queryId: '9615acefa745f3acc19607d298412119',
        isFailed: false,
        params: {
            from: 'main_menu',
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
        },
    },
    geo: {
        id: 1,
        type: 'SUBJECT_FEDERATION',
        rgid: 741964,
        populatedRgid: 741964,
        name: 'Москва и МО',
        locative: 'в Москве и МО',
        parents: [
            {
                id: 225,
                rgid: '143',
                name: 'Россия',
                type: 'COUNTRY',
                genitive: 'России',
            },
            {
                id: 0,
                rgid: '0',
                name: 'Весь мир',
                type: 'UNKNOWN',
            },
        ],
        heatmaps: ['infrastructure', 'price-rent', 'price-sell', 'profitability', 'transport', 'carsharing'],
        refinements: ['metro', 'directions', 'sub-localities', 'map-area'],
        sitesRgids: {
            district: 741964,
            mainCity: 587795,
        },
        latitude: 55.75322,
        longitude: 37.62251,
        zoom: 10,
        ridWithMetro: 213,
        country: 225,
        currencies: ['RUR', 'USD', 'EUR'],
        hasConcierge: true,
        hasCommercialBuildings: true,
        hasMetro: true,
        hasSites: true,
        hasVillages: true,
        hasPik: true,
        hasYandexRent: true,
        showMap: true,
        schoolInfo: {
            total: 399,
            highRatingColor: 'c847ff',
            lowRatingColor: '36107c',
        },
        isInOrlovskObl: false,
        isInPrimorskiyKrai: false,
        isInHabarovskKrai: false,
        isInTomskObl: false,
        isInKurganskObl: false,
        isInKirovskObl: false,
        isInUlyanovskObl: false,
        isInVologodskObl: false,
        isInPskovskObl: false,
        isInKalinigradskObl: false,
        isInIvanovskObl: false,
        isInChuvashskiya: false,
        isInUdmurtiya: false,
        isInSmolenskObl: false,
        isInKemerovskObl: false,
        isInTambovskObl: false,
        isInOmskObl: false,
        isInVladimirskObl: false,
        isInAltayskKrai: false,
        isInOrenburgObl: false,
        isInIrkutskObl: false,
        isInBashkortostan: false,
        isInStavropolskKrai: false,
        isInYaroslavskObl: false,
        isInVolgogradskObl: false,
        isInSevastopol: false,
        isInCrimea: false,
        isInBryanskObl: false,
        isInRyazanObl: false,
        isInLipetskObl: false,
        isInTverObl: false,
        isInTulaObl: false,
        isInTatarstan: false,
        isInKurskObl: false,
        isInKrasnoyarskKrai: false,
        isInTyumenObl: false,
        isInSaratovObl: false,
        isInChelyabinskObl: false,
        isInNovosibirskObl: false,
        isInSamaraObl: false,
        isInVoronezhObl: false,
        isInNizhnyNovgorodObl: false,
        isInPermKrai: false,
        isInKalugaObl: false,
        isInYaroslavlObl: false,
        isInAdygeya: false,
        isInSverdObl: false,
        isInRostovObl: false,
        isInBelgorodskObl: false,
        isInPenzenskObl: false,
        isInArhangelskObl: false,
        isInMO: true,
        isInLO: false,
        isInKK: false,
        isObninsk: false,
        isRostovOnDon: false,
        isMsk: false,
        isSpb: false,
        rgidVoronezh: 569171,
        rgidVoronezhObl: 475531,
        rgidSverdObl: 326698,
        rgidRostovObl: 211571,
        rgidKK: 353118,
        rgidMsk: 587795,
        rgidMO: 741964,
        rgidLO: 741965,
        rgidSpb: 417899,
        rgidTatarstan: 426660,
        rgidNizhnyNovgorodObl: 426764,
    },
    seo: {
        canonicalUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        alternateUrl:
            'https://realty-frontend.m.realty.local.dev.vertis.yandex.ru/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        ampUrl:
            'https://realty-frontend.realty.local.dev.vertis.yandex.ru/amp/moskva_i_moskovskaya_oblast/kupit/kvartira/',
        region: {
            rgid: 587795,
            name: 'Москва',
            locative: 'в Москве',
            country: 225,
            type: 'CITY',
            showMap: true,
            zoom: 10,
            populatedRgid: 587795,
            latitude: 55.75322,
            longitude: 37.62251,
            hasSites: true,
            hasVillages: true,
            hasCommercialBuildings: true,
            hasPik: true,
            hasMetro: true,
            hasYandexRent: true,
            schoolInfo: {
                total: 399,
                highRatingColor: 'c847ff',
                lowRatingColor: '36107c',
            },
            hasConcierge: true,
            hasDeveloperLegendaPromo: false,
            hasPaidSites: true,
            isInMO: true,
            rgidMO: 741964,
            isMsk: true,
            rgidMsk: 587795,
            isInLO: false,
            rgidLO: 741965,
            isSpb: false,
            rgidSpb: 417899,
            isInKK: false,
            rgidKK: 353118,
            isKras: false,
            rgidKras: 355968,
            isNovorossiysk: false,
            rgidNovorossiysk: 581131,
            isInRostovObl: false,
            rgidRostovObl: 211571,
            isRostovOnDon: false,
            rgidRostovOnDon: 214386,
            isInSverdObl: false,
            rgidSverdObl: 326698,
            isEkb: false,
            rgidEkb: 559132,
            isInAdygeya: false,
            rgidAdygeya: 353117,
            isMaikop: false,
            rgidMaikop: 17082541,
            isInYaroslavlObl: false,
            rgidYaroslavlObl: 475525,
            isYaroslavl: false,
            rgidYaroslavl: 556547,
            isInKalugaObl: false,
            rgidKalugaObl: 475523,
            isKaluga: false,
            rgidKaluga: 539155,
            isObninsk: false,
            rgidObninsk: 554526,
            isInPermKrai: false,
            rgidPermKrai: 426964,
            isPerm: false,
            rgidPerm: 570459,
            isInNizhnyNovgorodObl: false,
            rgidNizhnyNovgorodObl: 426764,
            isNizhnyNovgorod: false,
            rgidNizhnyNovgorod: 575243,
            isInVoronezhObl: false,
            rgidVoronezhObl: 475531,
            isVoronezh: false,
            rgidVoronezh: 569171,
            isInSamaraObl: false,
            rgidSamaraObl: 426678,
            isSamara: false,
            rgidSamara: 613432,
            isInNovosibirskObl: false,
            rgidNovosibirskObl: 255535,
            isNovosibirsk: false,
            rgidNovosibirsk: 579098,
            isInChelyabinskObl: false,
            rgidChelyabinskObl: 276551,
            isChelyabinsk: false,
            rgidChelyabinsk: 565122,
            isInSaratovObl: false,
            rgidSaratovObl: 426676,
            isSaratov: false,
            rgidSaratov: 574385,
            isInTyumenObl: false,
            rgidTyumenObl: 250682,
            isTyumen: false,
            rgidTyumen: 566725,
            isInKrasnoyarskKrai: false,
            rgidKrasnoyarskKrai: 344963,
            isKrasnoyarsk: false,
            rgidKrasnoyarsk: 555093,
            isInKurskObl: false,
            rgidKurskObl: 475529,
            isKursk: false,
            rgidKursk: 17182522,
            isInTatarstan: false,
            rgidTatarstan: 426660,
            isInTulaObl: false,
            rgidTulaObl: 475527,
            isTula: false,
            rgidTula: 571827,
            isInTverObl: false,
            rgidTverObl: 475528,
            isTver: false,
            rgidTver: 586858,
            isInLipetskObl: false,
            rgidLipetskObl: 475517,
            isLipetsk: false,
            rgidLipetsk: 562258,
            isInRyazanObl: false,
            rgidRyazanObl: 475526,
            isRyazan: false,
            rgidRyazan: 549570,
            isInBryanskObl: false,
            rgidBryanskObl: 475530,
            isBryansk: false,
            rgidBryansk: 564288,
            isInKaliningradObl: false,
            rgidKaliningradObl: 357969,
            isKaliningrad: false,
            rgidKaliningrad: 406766,
            isInCrimea: false,
            rgidCrimea: 681264,
            isInSevastopol: false,
            rgidSevastopol: 348613,
            isInVolgogradskObl: false,
            rgidVolgogradskObl: 202930,
            isInYaroslavskObl: false,
            rgidYaroslavskObl: 475525,
            isInStavropolskKrai: false,
            rgidStavropolskKrai: 202908,
            isInBashkortostan: false,
            rgidBashkortostan: 427111,
            isInIrkutskObl: false,
            rgidIrkutskObl: 281170,
            isInOrenburgObl: false,
            rgidOrenburgObl: 426680,
            isInAltayskKrai: false,
            rgidAltayskKrai: 315296,
            isInVladimirskObl: false,
            rgidVladimirskObl: 475524,
            isInOmskObl: false,
            rgidOmskObl: 332756,
            isInTambovskObl: false,
            rgidTambovskObl: 475519,
            isInKemerovskObl: false,
            rgidKemerovskObl: 297512,
            isInSmolenskObl: false,
            rgidSmolenskObl: 475522,
            isInUdmurtiya: false,
            rgidUdmurtiya: 426690,
            isInChuvashskiya: false,
            rgidChuvashskiya: 426657,
            isInIvanovskObl: false,
            rgidIvanovskObl: 475521,
            isInKalinigradskObl: false,
            rgidKalinigradskObl: 357969,
            isInPskovskObl: false,
            rgidPskovskObl: 357978,
            isInVologodskObl: false,
            rgidVologodskObl: 357974,
            isInUlyanovskObl: false,
            rgidUlyanovskObl: 426750,
            isInKirovskObl: false,
            rgidKirovskObl: 426967,
            isInKurganskObl: false,
            rgidKurganskObl: 242563,
            isInTomskObl: false,
            rgidTomskObl: 336098,
            isInHabarovskKrai: false,
            rgidHabarovskKrai: 262722,
            isInPrimorskiyKrai: false,
            rgidPrimorskiyKrai: 320568,
            isInOrlovskObl: false,
            rgidOrlovskObl: 475518,
            isInBelgorodskObl: false,
            rgidBelgorodskObl: 475532,
            isInPenzenskObl: false,
            rgidPenzenskObl: 426685,
            isInArhangelskObl: false,
            rgidArhangelskObl: 357972,
            refinements: ['metro', 'sub-localities', 'map-area'],
            ridWithMetro: 213,
            id: 213,
            sitesRgids: {
                district: 741964,
                mainCity: 587795,
            },
        },
        offersCount: 26267,
    },
    offersSearchPage: {
        direct: null,
        directList: [
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
            {
                directFormat: 'stub',
            },
        ],
        directParams: {
            rgid: 741964,
            currency: 'RUR',
            yandexUid: '393167231637669633',
            queryId: '581ebf066e5ba01922069a416ddf2612',
            pageSize: 10,
            sort: 'RELEVANCE',
            type: 'SELL',
            category: 'APARTMENT',
            searchType: 'offers',
            from: 'direct',
            login: 'yandexuid:393167231637669633',
        },
        searchResults: {
            pager: {
                isNewPager: true,
                firstPageIndex: 0,
                lastPageIndex: 0,
                totalItems: 26175,
                pageSize: 10,
                totalPages: 50,
                minPriceTotalItems: 0,
                maxPriceTotalItems: 1000000000,
            },
            queryId: '581ebf066e5ba01922069a416ddf2612',
            searchParams: {
                pageSize: 10,
                rgid: 741964,
                sort: 'RELEVANCE',
                type: 'SELL',
                category: 'APARTMENT',
                siteName: null,
            },
            isLoading: false,
            isPageLoading: false,
        },
        searchPresets: [
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/novostroyki/?isFastlink=true',
                text: 'В новостройке',
                canonical: '',
                offersCount: 25197,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?withExcerptsOnly=YES&isFastlink=true',
                text: 'Проверенные в ЕГРН',
                canonical: '',
                offersCount: 56,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/s-balkonom/?isFastlink=true',
                text: 'С балконом',
                canonical: '',
                offersCount: 25583,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?floorExceptFirst=YES&isFastlink=true',
                text: 'Не первый этаж',
                canonical: '',
                offersCount: 24838,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/?renovation=COSMETIC_DONE&isFastlink=true',
                text: 'С косметическим ремонтом',
                canonical: '',
                offersCount: 23650,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/dvuhkomnatnaya/?isFastlink=true',
                text: '2 комнаты',
                canonical: '',
                offersCount: 9553,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/ryadom-metro/?isFastlink=true',
                text: 'Рядом с метро',
                canonical: '',
                offersCount: 9004,
            },
            {
                url: '/moskva_i_moskovskaya_oblast/kupit/kvartira/odnokomnatnaya/?isFastlink=true',
                text: '1 комната',
                canonical: '',
                offersCount: 8351,
            },
        ],
        searchQuery: {
            offset: 0,
            page: 0,
            pageSize: 10,
            sort: 'RELEVANCE',
            maxCoordinates: 100,
            clusterSize: 0,
            excludePartnerId: false,
            commutePoint: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            commuteTransport: 'NOT_DEFINED',
            lt: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            rb: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            viewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportLT: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            excludeViewportRB: {
                latitude: -1000,
                longitude: -1000,
                defined: false,
            },
            regionId: 0,
            rgid: 741964,
            type: 'SELL',
            category: 'APARTMENT',
            propertyType: 'UNKNOWN',
            price: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            currency: 'RUR',
            locale: 'RU',
            priceType: 'PER_OFFER',
            rentTime: 'LARGE',
            floor: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            area: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            livingSpace: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            kitchenSpace: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            lotArea: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            metroTransport: 'UNKNOWN',
            directionDistance: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            balcony: 'UNKNOWN',
            minTrust: 'UNKNOWN',
            newFlat: true,
            placementPeriod: 'UNKNOWN',
            showSimilar: true,
            manualyAdded: false,
            payed: false,
            yandexUid: '393167231637669633',
            clusterHead: true,
            premoderation: false,
            showAll: false,
            raised: false,
            premium: false,
            showPlan: false,
            commercialPlanType: 'UNKNOWN',
            commission: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            securityPayment: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            dealStatus: 'UNKNOWN',
            entranceType: 'UNKNOWN',
            pricingPeriod: 'UNKNOWN',
            flatType: 'UNKNOWN',
            from: 'direct',
            searchWithDeleted: false,
            login: 'yandexuid:393167231637669633',
            showUniquePoints: true,
            queryId: '581ebf066e5ba01922069a416ddf2612',
            onlyPIK: false,
            expFlags: [
                'REALTYFRONT-12147_new_snippet_nb_map_v1',
                'REALTYFRONT-12444_add_whatsapp_landing_arenda',
                'REALTYFRONT-11292_new_offer_card',
                'REALTYFRONT-12308_noticeable_filter_arenda',
                'REALTYFRONT-10490_cannibalization',
                'REALTYFRONT-12326_mini_widget_chats',
                'REALTYFRONT-11455_new_card_second_iteration',
                'VSML-1007_ranking_sites',
                'REALTYFRONT-12096_popup_phone_show',
                'INTMONETIZATION-111-4-D',
                'REALTYFRONT-12632_popup_gv',
                'REALTYFRONT-12105_snippets_on_landing',
                'REALTYFRONT-12172_banners_ArendaGV',
                'REALTYFRONT-12146_chat_presets',
                'REALTYFRONT-11902_slider_middle',
                'REALTYFRONT-12490_samolet_extended_card',
                'INTMONETIZATION-39-direct-search-off',
            ],
            nearSubway: false,
            ceilingHeight: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            clusterizationType: 'DEFAULT',
            userPlatform: 'DESKTOP',
            mixedSearch: true,
            revoked: false,
            routesWithMKAD: false,
            landType: 'LAND_TYPE_UNKNOWN',
            withExcerptsOnly: false,
            videoUrl: false,
            onlineShow: false,
            paymentType: 'UNKNOWN',
            url:
                'offerSearchV2.json?queryId=581ebf066e5ba01922069a416ddf2612&pageSize=10&searchType=offers&userPlatform=desktop&rgid=741964&expFlags=REALTYFRONT-12444_add_whatsapp_landing_arenda&expFlags=REALTYFRONT-12172_banners_ArendaGV&expFlags=REALTYFRONT-12308_noticeable_filter_arenda&expFlags=REALTYFRONT-12326_mini_widget_chats&expFlags=REALTYFRONT-12146_chat_presets&expFlags=REALTYFRONT-12147_new_snippet_nb_map_v1&expFlags=REALTYFRONT-12096_popup_phone_show&expFlags=REALTYFRONT-11455_new_card_second_iteration&expFlags=REALTYFRONT-11292_new_offer_card&&expFlags=INTMONETIZATION-111-4-D&expFlags=REALTYFRONT-12632_popup_gv&expFlags=REALTYFRONT-11902_slider_middle&expFlags=REALTYFRONT-12490_samolet_extended_card&expFlags=VSML-1007_ranking_sites&expFlags=INTMONETIZATION-39-direct-search-off&expFlags=REALTYFRONT-12105_snippets_on_landing&expFlags=REALTYFRONT-10490_cannibalization&from=direct&currency=RUR&category=APARTMENT&sort=RELEVANCE&login=yandexuid:393167231637669633&type=SELL&yandexUid=393167231637669633',
            paidOnly: 'UNKNOWN',
            pointSize: 0,
            fullTrustedOwner: false,
            yandexRent: false,
            emptyLocationSubqueries: true,
            roomsTotalFirstValueValid: false,
            subLocalityFirstValueValid: false,
            nonAdminSubLocalityFirstValueValid: false,
            roomsOfferedFirstValueValid: false,
            metroGeoIdFirstValueValid: false,
            directionFirstValueValid: false,
            directionDistanceInMeters: {
                open: true,
                leftOpen: true,
                rightOpen: true,
            },
            logQueryId: '1aa0696c76ebe9142a6a7746ebf280e6',
        },
        serpSnippets: {},
    },
    filters: {
        offers: {
            type: 'offers',
            data: {
                'geo-refinement-multi': [],
                type: 'SELL',
                ctype: 'SELL',
                category: 'APARTMENT',
                priceType: 'PER_OFFER',
                metroTransport: 'ON_FOOT',
                pricingPeriod: 'PER_MONTH',
                commissionMax: null,
                'geo-region': {
                    label: 'Москва и МО',
                    rgid: 741964,
                },
                sort: 'RELEVANCE',
            },
        },
    },
};
