import {
    CallEventCallResult,
    CallResolutionStatus,
    CampaignCallComplaintStatus,
    CampaignCallComplaintStatusNG,
    CampaignCallStatus,
    CampaignCallStatusNG,
} from 'realty-core/types/partner/cabinet';

import { ICallsPageProps } from '../index';

export const genericCallsList: ICallsPageProps['calls'] = [
    {
        call: {
            timestamp: '2022-03-09',
            incoming: '+7993XXXabcd',
            redirect: { wholePhoneNumber: '79991845803' },
            internal: { wholePhoneNumber: '79499503038' },
            waitDuration: '69',
            callDuration: '420',
            id: 'told',
            recordId: '123abc',
            callResult: CallEventCallResult.BLOCKED,
        },
        revenue: '1500',
        callStatus: CampaignCallStatus.EMPTY_INCOMING,
        callStatusNg: CampaignCallStatusNG.NON_TARGET,
        complaint: {
            text: 'abcdefg',
            createTime: '2020-12-02',
            email: 'me@hotmail.com',
        },
        manualResolutionStatus: CallResolutionStatus.FAIL,
        complaintStatus: CampaignCallComplaintStatus.ALREADY_MODERATED,
        complaintStatusNg: CampaignCallComplaintStatusNG.REJECTED,
        campaignName: 'Shrek',
    },
    {
        call: {
            timestamp: '2022-02-11',
            incoming: '+79932139939',
            redirect: { wholePhoneNumber: '79991845803' },
            internal: { wholePhoneNumber: '79499503038' },
            waitDuration: '39',
            callDuration: '120',
            id: 'baj',
            recordId: '',
            callResult: CallEventCallResult.SUCCESS,
        },
        revenue: '12032000',
        callStatus: CampaignCallStatus.OK,
        callStatusNg: CampaignCallStatusNG.TARGET,
        manualResolutionStatus: CallResolutionStatus.PASS,
        complaintStatus: CampaignCallComplaintStatus.IS_ABLE_TO_COMPLAINT,
        complaintStatusNg: CampaignCallComplaintStatusNG.READY_TO_COMPLAIN,
        campaignName: 'Donkey',
    },
    {
        call: {
            timestamp: '2021-03-12',
            incoming: '+7993xxxXXX2',
            redirect: { wholePhoneNumber: '79991845803' },
            internal: { wholePhoneNumber: '79499503038' },
            waitDuration: '234',
            callDuration: '908',
            id: 'ldkfjgjkh123',
            recordId: '1029380',
            callResult: CallEventCallResult.ERROR,
        },
        revenue: '1500',
        callStatus: CampaignCallStatus.REPEATED_ON_CURRENT_DAY,
        callStatusNg: CampaignCallStatusNG.NON_TARGET,
        complaint: {
            text: 'abcdefg',
            createTime: '2020-12-02',
            email: 'me@hotmail.com',
        },
        manualResolutionStatus: CallResolutionStatus.UNKNOWN,
        complaintStatus: CampaignCallComplaintStatus.NOT_BILLED_CALL,
        complaintStatusNg: CampaignCallComplaintStatusNG.ACCEPTED,
        campaignName: 'Dragon',
    },
    {
        call: {
            timestamp: '2022-01-22',
            incoming: '+79932390489',
            redirect: { wholePhoneNumber: '79120935803' },
            internal: { wholePhoneNumber: '79499320948' },
            waitDuration: '6',
            callDuration: '12',
            id: 'ldflkjskjdf',
            recordId: '123dwlk,mabc',
            callResult: CallEventCallResult.INVALIDATE_CALLEE,
        },
        revenue: '1599',
        callStatus: CampaignCallStatus.REPEATED_ON_HISTORY,
        callStatusNg: CampaignCallStatusNG.REPEATED,
        complaint: {
            text: 'abcdefg',
            createTime: '2020-12-02',
            email: 'me@hotmail.com',
        },
        manualResolutionStatus: CallResolutionStatus.PASS,
        complaintStatus: CampaignCallComplaintStatus.ON_MODERATION,
        complaintStatusNg: CampaignCallComplaintStatusNG.ON_MODERATION,
        campaignName: 'Gingerbread man',
    },
    {
        call: {
            timestamp: '2022-03-09',
            incoming: '+79931239999',
            redirect: { wholePhoneNumber: '79991846000' },
            internal: { wholePhoneNumber: '79499503103' },
            waitDuration: '1',
            callDuration: '123',
            id: 'lkjdfgj',
            recordId: 'pohjg98',
            callResult: CallEventCallResult.NO_ANSWER,
        },
        revenue: '133300',
        callStatus: CampaignCallStatus.SUSPICIOUS,
        callStatusNg: CampaignCallStatusNG.UNKNOWN,
        complaint: {
            text: 'abcdefg',
            createTime: '2020-12-02',
            email: 'me@hotmail.com',
        },
        manualResolutionStatus: CallResolutionStatus.PASS,
        complaintStatus: CampaignCallComplaintStatus.TOO_OLD,
        complaintStatusNg: CampaignCallComplaintStatusNG.UNKNOWN,
        campaignName: 'Puss in boots',
    },
];
