import { IOfferCard } from 'realty-core/types/offerCard';

export const offer = ({
    offerId: '4675231262176926720',
    trust: 'NORMAL',
    url: '//realty.test.vertis.yandex.ru/offer/4675231262176926720',
    unsignedInternalUrl: '//realty.test.vertis.yandex.ru/offer/4675231262176926720',
    partnerId: '1035218734',
    partnerName: 'Яндекс.Недвижимость',
    offerType: 'SELL',
    offerCategory: 'APARTMENT',
    clusterId: '4675231262176926720',
    clusterHeader: true,
    clusterSize: 1,
    creationDate: '2020-08-07T10:51:25Z',
    updateDate: '2020-08-27T13:33:44Z',
    roomsTotal: 2,
    floorsTotal: 9,
    floorsOffered: [3],
    offerStatus: 'active',
    flatType: 'SECONDARY',
    ceilingHeight: 2.5,
    area: { value: 45, unit: 'SQUARE_METER' },
    livingSpace: { value: 30, unit: 'SQUARE_METER' },
    kitchenSpace: { value: 15, unit: 'SQUARE_METER' },
    roomSpace: [
        { value: 20, unit: 'SQUARE_METER' },
        { value: 10, unit: 'SQUARE_METER' },
    ],
    price: {
        currency: 'RUR',
        value: 7007007,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 155711,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 7007007,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 7007007, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 155711, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 7007007, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    notForAgents: false,
    totalImages: 3,
    apartment: { renovation: 'COSMETIC_DONE', improvements: { INTERNET: true } },
    location: {
        rgid: 12450,
        geoId: 213,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587795,
        settlementGeoId: 213,
        address: 'Москва, Нагатинская набережная, 18',
        geocoderAddress: 'Россия, Москва, Нагатинская набережная, 18',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Москва',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Москва',
                    regionType: 'CITY',
                    queryParams: { rgid: '587795', address: 'Россия, Москва' },
                },
                {
                    value: 'Нагатинская набережная',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Нагатинская набережная',
                    regionType: 'STREET',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Нагатинская набережная' },
                },
                {
                    value: '18',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: '18',
                    regionType: 'HOUSE',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Нагатинская набережная, 18' },
                },
            ],
        },
        point: { latitude: 55.682762, longitude: 37.65449, precision: 'EXACT' },
        metro: {
            metroGeoId: 20418,
            name: 'Коломенская',
            metroTransport: 'ON_FOOT',
            timeToMetro: 11,
            latitude: 55.67841,
            longitude: 37.663834,
            minTimeToMetro: 8,
            lineColors: ['4f8242'],
            rgbColor: '4f8242',
        },
        streetAddress: 'Нагатинская набережная, 18',
        metroList: [
            {
                metroGeoId: 20418,
                name: 'Коломенская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 11,
                latitude: 55.67841,
                longitude: 37.663834,
                minTimeToMetro: 8,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 123593,
                name: 'Технопарк',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 11,
                latitude: 55.69393,
                longitude: 37.664425,
                minTimeToMetro: 11,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 20427,
                name: 'Нагатинская',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 14,
                latitude: 55.68339,
                longitude: 37.622868,
                minTimeToMetro: 14,
                lineColors: ['909090'],
                rgbColor: '909090',
            },
        ],
        schools: [
            {
                schoolId: '1053014602',
                name: 'Школа № 1375',
                address: 'Россия, Москва, Нагатинская набережная, 24',
                ratingPlace: 218,
                timeOnFoot: 236,
                distanceOnFoot: 328,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 3, distance: 328 }],
                rating: { place: 218, total: 399, high: false, rgbColor: '36107c' },
            },
        ],
        ponds: [
            {
                pondId: '137667589',
                name: 'река Москва',
                timeOnFoot: 312,
                distanceOnFoot: 433,
                latitude: 55.685143,
                longitude: 37.654305,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 5, distance: 433 }],
            },
            {
                pondId: '1568283182',
                name: 'канал Нагатинское спрямление',
                timeOnFoot: 312,
                distanceOnFoot: 433,
                latitude: 55.685143,
                longitude: 37.654305,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 5, distance: 433 }],
            },
            {
                pondId: '1504256147',
                name: 'затон Новинки',
                timeOnFoot: 420,
                distanceOnFoot: 603,
                latitude: 55.687717,
                longitude: 37.650566,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 7, distance: 603 }],
            },
        ],
        airports: [
            {
                id: '858742',
                name: 'Домодедово',
                timeOnCar: 2198,
                distanceOnCar: 36283,
                latitude: 55.41435,
                longitude: 37.90048,
                timeDistanceList: [{ transport: 'ON_CAR', time: 36, distance: 36283 }],
            },
            {
                id: '878042',
                name: 'Шереметьево',
                timeOnCar: 2784,
                distanceOnCar: 44184,
                latitude: 55.963852,
                longitude: 37.4169,
                timeDistanceList: [{ transport: 'ON_CAR', time: 46, distance: 44184 }],
            },
            {
                id: '878109',
                name: 'Жуковский (Раменское)',
                timeOnCar: 2886,
                distanceOnCar: 42531,
                latitude: 55.568665,
                longitude: 38.143654,
                timeDistanceList: [{ transport: 'ON_CAR', time: 48, distance: 42531 }],
            },
            {
                id: '878065',
                name: 'Внуково',
                timeOnCar: 3722,
                distanceOnCar: 36240,
                latitude: 55.604942,
                longitude: 37.282578,
                timeDistanceList: [{ transport: 'ON_CAR', time: 62, distance: 36240 }],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '9ada1b',
                description: 'средняя',
                level: 6,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: 'fbae1e',
                description: 'высокая',
                level: 4,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: 'fbae1e',
                description: 'ниже средней',
                level: 4,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '9ada1b',
                description: 'высокая',
                level: 5,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Москва и МО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 986,
                distance: 12519,
                latitude: 55.749893,
                longitude: 37.623425,
                timeDistanceList: [{ transport: 'ON_CAR', time: 16, distance: 12519 }],
            },
        ],
    },
    house: {
        bathroomUnit: 'SEPARATED',
        balconyType: 'BALCONY',
        windowView: 'STREET',
        studio: false,
        apartments: false,
        housePart: false,
    },
    building: {
        builtYear: 1968,
        buildingType: 'PANEL',
        buildingSeries: 'II-49',
        buildingSeriesId: '712013',
        improvements: { LIFT: true, RUBBISH_CHUTE: true, GUARDED: false, SECURITY: false },
        parkingType: 'OPEN',
        buildingId: '7569661224225966028',
        flatsCount: 215,
        porchesCount: 6,
        heatingType: 'CENTRAL',
        priceStatistics: {
            sellPricePerSquareMeter: {
                level: 0,
                maxLevel: 9,
                rgbColor: '',
                value: '0',
                regionValueFrom: '22727',
                regionValueTo: '2234148',
            },
        },
        hasDeveloperChat: false,
        buildingImprovementsMap: { LIFT: true, RUBBISH_CHUTE: true, GUARDED: false, SECURITY: false },
    },
    description: 'dom is kirpicha',
    internal: true,
    active: true,
    vas: {
        raised: false,
        premium: false,
        placement: false,
        promoted: false,
        turboSale: false,
        raisingSale: false,
        tuzFeatured: false,
        vasAvailable: true,
    },
    dealStatus: 'COUNTERSALE',
    uid: '4030469986',
    relevance: 0,
    commissioningDateIndexValue: 0,
    partnerInternalId: '4675231262176926720',
    history: {
        prices: [
            {
                date: '2020-08-07T10:51:25Z',
                value: 7007007,
                price: {
                    currency: 'RUR',
                    value: 7007007,
                    period: 'WHOLE_LIFE',
                    unit: 'WHOLE_OFFER',
                    trend: 'UNCHANGED',
                    hasPriceHistory: false,
                    valuePerPart: 155711,
                    unitPerPart: 'SQUARE_METER',
                    valueForWhole: 7007007,
                    unitForWhole: 'WHOLE_OFFER',
                    price: { value: 7007007, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
                    pricePerPart: {
                        value: 155711,
                        currency: 'RUB',
                        priceType: 'PER_METER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                    priceForWhole: {
                        value: 7007007,
                        currency: 'RUB',
                        priceType: 'PER_OFFER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                },
            },
        ],
    },
    enrichedFields: [
        'BUILDING_SERIES_ID',
        'SECURITY',
        'GUARDED',
        'PORCHES_COUNT',
        'GAS',
        'HEATING_TYPE',
        'FLATS_COUNT',
    ],
    callCenter: false,
    exclusive: true,
    predictions: { predictedPrice: { min: '1144000', max: '1399000', value: '1272000' } },
    obsolete: false,
    complaintReasons: [
        { reason: 'SOLD', text: 'Продано' },
        { reason: 'WRONG_PRICE', text: 'Неверная цена' },
        { reason: 'WRONG_ADDRESS', text: 'Невреный адрес' },
        {
            reason: 'WRONG_PHOTO',
            text: 'Некорректные фотографии',
            subreasons: [
                { reason: 'WRONG_PHOTO->ANOTHER_OBJECT', text: 'Фото принадлежат другому объекту' },
                { reason: 'WRONG_PHOTO->STUPID_PHOTO', text: 'Фото не дают представления об объекте' },
                { reason: 'WRONG_PHOTO->ADS_OR_BAD_INFO', text: 'На фото посторонняя информация или реклама' },
            ],
        },
        {
            reason: 'DONT_CALL',
            text: 'Нельзя дозвониться',
            subreasons: [
                { reason: 'DONT_CALL->NOT_IN_NET', text: 'Абонент недоступен' },
                { reason: 'DONT_CALL->NOT_ANSWER', text: 'Не снимают трубку или сбрасывают звонок' },
                { reason: 'DONT_CALL->DONT_WORK_WITH_OBJ', text: 'Не занимаются объектом' },
            ],
        },
        { reason: 'HIDDEN_AGENT', text: 'Агент под видом собственника' },
        {
            reason: 'DANGER_SCHEME',
            text: 'Подозрительна схема, сомнительное предложение…',
            subreasons: [
                { reason: 'DANGER_SCHEME->ASK_PREPAY', text: 'Предложили перевести предоплату за просмотр' },
                { reason: 'DANGER_SCHEME->SELL_BY_RENT', text: 'Продажа по договору ренты' },
                { reason: 'DANGER_SCHEME->AUCTION', text: 'Продажа с аукциона' },
                { reason: 'DANGER_SCHEME->ANOTHER_VARS', text: 'Предложили подобрать варианты' },
            ],
        },
        { reason: 'DONT_GIVE_APPROVE', text: 'Я не давал(а) права на размещение объекта', askContacts: true },
        { reason: 'ANOTHER', text: 'Другая причина' },
    ],
    withExcerpt: true,
    freeReportAccessibility: 'FRA_READY',
    paidReportAccessibility: 'PPA_ALLOWED_TO_BUY',
    allowedCommunicationChannels: ['COM_CALLS'],
    remoteReview: { onlineShow: false, youtubeVideoReviewUrl: '' },
    socialPessimization: false,
    chargeForCallsType: 'NO_CHARGE',
    trustedOfferInfo: {
        isFullTrustedOwner: false,
        ownerTrustedStatus: 'ERROR_NOT_TRUSTED_MOSRU',
        isCadastrPersonMatched: false,
        agencyTrustedUserInfo: {
            fullTrustedAgencyOwner: false,
            userInfo: {
                mosRuTaskId: '',
                requestAttemptsCount: 0,
                mosRuTrustedStatus: 'NOT_PROCESSED',
                mosRuAvailable: false,
                timeTaskSet: '0',
            },
            lingStatus: 'NOT_OPENED',
            timeWasOpened: '0',
        },
    },
    yandexRent: false,
    offerState: {
        indexerState: {
            indexationWarning: [
                { code: 'DISABLED_CHATS_FOR_OWNER_TYPE', debugInfo: 'AllowedCommunicationChannelsUnifier$: DEVELOPER' },
            ],
        },
    },
    newFlatSale: false,
    openPlan: false,
    primarySaleV2: false,
    raised: false,
    premium: false,
    vasAvailable: true,
    suspicious: false,
    shareUrl: 'https://realty.test.vertis.yandex.ru/offer/4675231262176926720',
    transactionConditionsMap: { HAGGLE: true, MORTGAGE: true },
    supplyMap: { GAS: true },
    placement: false,
    promoted: false,
    newBuilding: false,
    shareURL: 'https://realty.test.vertis.yandex.ru/offer/4675231262176926720/',
    views: 39,
    excerptReport: {
        cadastralNumber: '77:05:0004005:****',
        createDate: '2020-08-07T13:51:35.956Z',
        flatReport: {
            buildingInfo: {
                area: 38.9,
                floorString: '10',
                address: 'р-н Нагатино-Садовники, наб Нагатинская, д 18, корп 1, кв *',
            },
            costInfo: { cadastralCost: '5772488' },
            currentRights: [
                {
                    owners: [{ type: 'NATURAL_PERSON', name: 'Д******** Д.В.' }],
                    registration: {
                        idRecord: '436305533277',
                        regNumber: '77-77-22/024/2011-***',
                        type: 'OWNERSHIP',
                        regDate: '2011-06-27T00:00:00Z',
                    },
                },
                { owners: [{ type: 'UNKNOWN' }], registration: { regNumber: '', regDate: '1970-01-01T00:00:00Z' } },
                { owners: [{ type: 'UNKNOWN' }], registration: { regNumber: '', regDate: '1970-01-01T00:00:00Z' } },
                { owners: [{ type: 'UNKNOWN' }], registration: { regNumber: '', regDate: '1970-01-01T00:00:00Z' } },
            ],
            previousRights: [
                {
                    owners: [{ type: 'JURIDICAL_PERSON' }],
                    registration: {
                        idRecord: '436305532377',
                        regNumber: '77-77-22/017/2011-***',
                        type: 'OWNERSHIP',
                        regDate: '2011-04-22T00:00:00Z',
                        endDate: '2011-06-27T00:00:00Z',
                    },
                },
            ],
            encumbrances: [],
            currentOwnersCount: 4,
        },
    },
    paidReportsInfo: {
        price: {
            isAvailable: true,
            effective: 123,
            base: 410,
            reasons: [],
            modifiers: { bonusDiscount: { percent: 70, amount: 2.87 } },
        },
        paidReports: [],
    },
    cardShow: 14,
    isRealtyOffer: true,
    author: {
        id: '0',
        category: 'DEVELOPER',
        agentName: 'Александр Илларионович Крестовский-Константинопольский',
        creationDate: '2019-10-10T10:28:24Z',
        humanPhoto: '//avatars.mdst.yandex.net/get-yapic/1824/eCQ9R5hSYwPFGUhA6cSQvX3uJaA-1/islands-200',
        allowedCommunicationChannels: ['COM_CALLS'],
        redirectPhones: true,
        redirectPhonesFailed: false,
        encryptedPhones: ['KzcF5MHTAJ0NLzIN0NPzcR0'],
    },
} as unknown) as IOfferCard;
