import { ISiteCardMobile } from 'realty-core/types/siteCard';

export const SITE_CARD = ({
    location: {
        rgid: 12450,
        geoId: 213,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587795,
        settlementGeoId: 213,
        address: 'Москва, Нагатинская набережная, 18',
        geocoderAddress: 'Россия, Москва, Нагатинская набережная, 18',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Москва',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Москва',
                    regionType: 'CITY',
                    queryParams: { rgid: '587795', address: 'Россия, Москва' },
                },
                {
                    value: 'Нагатинская набережная',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Нагатинская набережная',
                    regionType: 'STREET',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Нагатинская набережная' },
                },
                {
                    value: '18',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: '18',
                    regionType: 'HOUSE',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Нагатинская набережная, 18' },
                },
            ],
        },
        point: { latitude: 55.682762, longitude: 37.65449, precision: 'EXACT' },
        metro: {
            metroGeoId: 20418,
            name: 'Коломенская',
            metroTransport: 'ON_FOOT',
            timeToMetro: 11,
            latitude: 55.67841,
            longitude: 37.663834,
            minTimeToMetro: 8,
            lineColors: ['4f8242'],
            rgbColor: '4f8242',
        },
        streetAddress: 'Нагатинская набережная, 18',
        metroList: [
            {
                metroGeoId: 20418,
                name: 'Коломенская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 11,
                latitude: 55.67841,
                longitude: 37.663834,
                minTimeToMetro: 8,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 123593,
                name: 'Технопарк',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 11,
                latitude: 55.69393,
                longitude: 37.664425,
                minTimeToMetro: 11,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 115040,
                name: 'Лермонтовский проспект',
                metroTransport: 'ON_FOOT',
                timeToMetro: 19,
                latitude: 55.839886,
                longitude: 37.48678,
                minTimeToMetro: 16,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
        ],
        schools: [
            {
                schoolId: '1053014602',
                name: 'Школа № 1375',
                address: 'Россия, Москва, Нагатинская набережная, 24',
                ratingPlace: 218,
                timeOnFoot: 236,
                distanceOnFoot: 328,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 3, distance: 328 }],
                rating: { place: 218, total: 399, high: false, rgbColor: '36107c' },
            },
        ],
        ponds: [
            {
                pondId: '137667589',
                name: 'река Москва',
                timeOnFoot: 312,
                distanceOnFoot: 433,
                latitude: 55.685143,
                longitude: 37.654305,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 5, distance: 433 }],
            },
            {
                pondId: '1568283182',
                name: 'канал Нагатинское спрямление',
                timeOnFoot: 312,
                distanceOnFoot: 433,
                latitude: 55.685143,
                longitude: 37.654305,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 5, distance: 433 }],
            },
            {
                pondId: '1504256147',
                name: 'затон Новинки',
                timeOnFoot: 420,
                distanceOnFoot: 603,
                latitude: 55.687717,
                longitude: 37.650566,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 7, distance: 603 }],
            },
        ],
        airports: [
            {
                id: '858742',
                name: 'Домодедово',
                timeOnCar: 2198,
                distanceOnCar: 36283,
                latitude: 55.41435,
                longitude: 37.90048,
                timeDistanceList: [{ transport: 'ON_CAR', time: 36, distance: 36283 }],
            },
            {
                id: '878042',
                name: 'Шереметьево',
                timeOnCar: 2784,
                distanceOnCar: 44184,
                latitude: 55.963852,
                longitude: 37.4169,
                timeDistanceList: [{ transport: 'ON_CAR', time: 46, distance: 44184 }],
            },
            {
                id: '878109',
                name: 'Жуковский (Раменское)',
                timeOnCar: 2886,
                distanceOnCar: 42531,
                latitude: 55.568665,
                longitude: 38.143654,
                timeDistanceList: [{ transport: 'ON_CAR', time: 48, distance: 42531 }],
            },
            {
                id: '878065',
                name: 'Внуково',
                timeOnCar: 3722,
                distanceOnCar: 36240,
                latitude: 55.604942,
                longitude: 37.282578,
                timeDistanceList: [{ transport: 'ON_CAR', time: 62, distance: 36240 }],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '9ada1b',
                description: 'средняя',
                level: 6,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: 'fbae1e',
                description: 'высокая',
                level: 4,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: 'fbae1e',
                description: 'ниже средней',
                level: 4,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '9ada1b',
                description: 'высокая',
                level: 5,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Москва и МО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 986,
                distance: 12519,
                latitude: 55.749893,
                longitude: 37.623425,
                timeDistanceList: [{ transport: 'ON_CAR', time: 16, distance: 12519 }],
            },
        ],
    },
} as unknown) as ISiteCardMobile;
