import { generateImageUrl } from '@realty-front/jest-utils/puppeteer/tests-helpers/image';

import {
    OfferType,
    OfferCategory,
    AuthorCategoryTypes,
    PaidReportAccessibility,
    FreeReportAccessibility,
    AreaUnits,
} from 'realty-core/types/offerCard';
import { TransportDistanceType } from 'realty-core/types/location';

const image = generateImageUrl({ width: 232, height: 232 });
const images = [image, image, image, image, image, image];

export const getOffer = () => ({
    offerId: '7175042308909368517',
    trust: 'NORMAL',
    url: 'https://spb.yit.ru/sankt-peterburg-1/zk_tarmo/tarmo5/ru940001205a131',
    unsignedInternalUrl: '//realty.test.vertis.yandex.ru/offer/7175042308909368517',
    partnerId: '1069062416',
    partnerName: 'ЮИТ',
    offerType: OfferType.SELL,
    offerCategory: OfferCategory.APARTMENT,
    clusterId: '7504278408042413079',
    clusterHeader: false,
    clusterSize: 3,
    author: {
        id: '0',
        category: AuthorCategoryTypes.DEVELOPER,
        organization: 'АО «ЮИТ Санкт-Петербург»',
        creationDate: '2017-06-20T09:31:21Z',
        name: 'АО «ЮИТ Санкт-Петербург»',
        redirectPhones: true,
        redirectPhonesFailed: false,
        encryptedPhones: ['KzcF4MHTIJ3MLDMN0NPDQR0'],
    },
    creationDate: '2020-10-15T12:26:29Z',
    updateDate: '2020-10-15T12:26:35Z',
    roomsTotal: 1,
    floorsTotal: 11,
    floorsOffered: [8],
    flatType: 'NEW_FLAT',
    area: {
        value: 42.29,
        unit: 'SQUARE_METER',
    },
    livingSpace: {
        value: 12.53,
        unit: 'SQUARE_METER',
    },
    kitchenSpace: {
        value: 18.4,
        unit: 'SQUARE_METER',
    },
    price: {
        currency: 'RUR',
        value: 3000000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 53571,
        unitPerPart: AreaUnits.SQUARE_METER,
        valueForWhole: 3000000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 3000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 53571, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 3000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    notForAgents: false,
    totalImages: 6,
    minicardImages: images,
    mainImages: images,
    fullImages: images,
    alikeImages: images,
    cosmicImages: images,
    appMiddleImages: images,
    appLargeImages: images,
    appMiniSnippetImages: images,
    appSmallSnippetImages: images,
    appMiddleSnippetImages: images,
    appLargeSnippetImages: images,
    origImages: images,
    photoPreviews: ['', '', '', '', '', ''],
    apartment: {
        siteFlatPlanId: '549393-0A020801-35C88CCF46CE6505',
    },
    location: {
        rgid: 285002,
        populatedRgid: 741965,
        geoId: 2,
        subjectFederationId: 10174,
        subjectFederationRgid: 741965,
        settlementRgid: 417899,
        settlementGeoId: 2,
        address: 'Приморский район, муниципальный округ Чёрная Речка',
        geocoderAddress: 'Россия, Санкт-Петербург, Студенческая улица, 26к2',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: {
                        rgid: '143',
                        address: 'Россия',
                    },
                },
                {
                    value: 'Санкт-Петербург',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: 'Санкт-Петербург',
                    regionType: 'CITY',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург',
                    },
                },
                {
                    value: 'Студенческая улица',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: 'Студенческая улица',
                    regionType: 'STREET',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург, Студенческая улица',
                    },
                },
                {
                    value: '26к2',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: '26к2',
                    regionType: 'HOUSE',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург, Студенческая улица, 26к2',
                    },
                },
            ],
        },
        point: {
            latitude: 59.994987,
            longitude: 30.32239,
            precision: 'EXACT',
        },
        metro: {
            metroGeoId: 20323,
            name: 'Чёрная Речка',
            metroTransport: TransportDistanceType.ON_TRANSPORT,
            timeToMetro: 11,
            latitude: 59.98551,
            longitude: 30.300838,
            minTimeToMetro: 11,
            lineColors: ['16bdf0'],
            rgbColor: '16bdf0',
        },
        streetAddress: 'Студенческая улица, 26к2',
        metroList: [
            {
                metroGeoId: 20323,
                name: 'Чёрная Речка',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 11,
                latitude: 59.98551,
                longitude: 30.300838,
                minTimeToMetro: 11,
                lineColors: ['16bdf0'],
                rgbColor: '16bdf0',
            },
            {
                metroGeoId: 20318,
                name: 'Лесная',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 11,
                latitude: 59.984768,
                longitude: 30.344358,
                minTimeToMetro: 11,
                lineColors: ['f03d2f'],
                rgbColor: 'f03d2f',
            },
            {
                metroGeoId: 20322,
                name: 'Пионерская',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 16,
                latitude: 60.002518,
                longitude: 30.296667,
                minTimeToMetro: 16,
                lineColors: ['16bdf0'],
                rgbColor: '16bdf0',
            },
        ],
        parks: [
            {
                parkId: '123259023',
                name: 'Пионерский сад',
                timeOnFoot: 285,
                distanceOnFoot: 396,
                latitude: 59.99291,
                longitude: 30.323935,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 4,
                        distance: 396,
                    },
                ],
            },
            {
                parkId: '1492425560',
                name: 'Ланской сад',
                timeOnFoot: 446,
                distanceOnFoot: 620,
                latitude: 59.997246,
                longitude: 30.325552,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 7,
                        distance: 620,
                    },
                ],
            },
            {
                parkId: '4015494950',
                name: 'Луспекаевский сквер',
                timeOnFoot: 494,
                distanceOnFoot: 686,
                latitude: 59.991703,
                longitude: 30.318687,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 8,
                        distance: 686,
                    },
                ],
            },
        ],
        ponds: [
            {
                pondId: '170487388',
                name: 'Сердобольский пруд',
                timeOnFoot: 433,
                distanceOnFoot: 602,
                latitude: 59.99538,
                longitude: 30.331242,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 7,
                        distance: 602,
                    },
                ],
            },
            {
                pondId: '170487099',
                name: 'Длинный пруд',
                timeOnFoot: 646,
                distanceOnFoot: 897,
                latitude: 59.99586,
                longitude: 30.333702,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 10,
                        distance: 897,
                    },
                ],
            },
        ],
        airports: [
            {
                id: '858726',
                name: 'Пулково',
                timeOnCar: 2491,
                distanceOnCar: 39902,
                latitude: 59.79992,
                longitude: 30.271744,
                timeDistanceList: [
                    {
                        transport: 'ON_CAR',
                        time: 41,
                        distance: 39902,
                    },
                ],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '20a70a',
                description: 'очень низкая',
                level: 8,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: 'ffe424',
                description: 'выше средней',
                level: 5,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: '9ada1b',
                description: 'выше средней',
                level: 6,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '9ada1b',
                description: 'высокая',
                level: 5,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Санкт-Петербург и ЛО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 1030,
                distance: 8478,
                latitude: 59.934994,
                longitude: 30.306541,
                timeDistanceList: [
                    {
                        transport: 'ON_CAR',
                        time: 17,
                        distance: 8478,
                    },
                ],
            },
        ],
    },
    house: {
        apartments: false,
        housePart: false,
    },
    building: {
        builtYear: 2022,
        builtQuarter: 3,
        buildingState: 'UNFINISHED',
        improvements: {
            PARKING: false,
        },
        parkingType: 'OPEN',
        siteId: 549393,
        siteName: 'TARMO',
        siteDisplayName: 'ЖК «TARMO»',
        developerIds: [2725],
        houseId: '1517348',
        houseReadableName: 'Корпус 5',
        heatingType: 'UNKNOWN',
        buildingImprovementsMap: {
            PARKING: false,
        },
    },
    internal: true,
    active: true,
    vas: {
        raised: false,
        premium: false,
        placement: false,
        promoted: false,
        turboSale: false,
        raisingSale: false,
        tuzFeatured: false,
        vasAvailable: true,
    },
    dealStatus: 'PRIMARY_SALE',
    salesDepartments: [
        {
            id: 267521,
            name: 'YIT',
            isRedirectPhones: true,
            weekTimetable: [
                {
                    dayFrom: 1,
                    dayTo: 5,
                    timePattern: [
                        {
                            open: '09:00',
                            close: '19:00',
                        },
                    ],
                },
                {
                    dayFrom: 6,
                    dayTo: 6,
                    timePattern: [
                        {
                            open: '11:00',
                            close: '17:00',
                        },
                    ],
                },
            ],
            logo: image,
            statParams: '',
            encryptedPhones: ['KzcF4MHTIJ3MLDMN0NPDQR0'],
            encryptedDump: '',
        },
    ],
    uid: '313962949',
    relevance: 0,
    commissioningDateIndexValue: 20223,
    partnerInternalId: 'RU940001205A131',
    callCenter: false,
    exclusive: false,
    obsolete: false,
    withExcerpt: false,
    freeReportAccessibility: FreeReportAccessibility.FRA_NONE,
    paidReportAccessibility: PaidReportAccessibility.PPA_NOT_ALLOWED_TO_BUY,
    remoteReview: {
        onlineShow: false,
        youtubeVideoReviewUrl: '',
        virtualTour: {
            modelUrl: '',
            previewUrl: '',
        },
    },
    socialPessimization: false,
    chargeForCallsType: 'BY_CAMPAIGN',
    trustedOfferInfo: {
        isFullTrustedOwner: false,
        ownerTrustedStatus: 'NOT_LINKED_MOSRU',
        isCadastrPersonMatched: false,
    },
    yandexRent: false,
    openPlan: false,
    primarySaleV2: true,
    raised: false,
    premium: false,
    vasAvailable: true,
    placement: false,
    promoted: false,
    suspicious: false,
    shareUrl: 'https://realty.test.vertis.yandex.ru/offer/7175042308909368517',
    transactionConditionsMap: {
        MORTGAGE: true,
    },
    newBuilding: true,
    roomsTotalKey: '1',
    roomsTotalColor: '#4a85f2',
    page: 2,
    idx: 3,
    queryId: '578626e460489c2513f05301e721a989',
});

export const getOfferWith3dTour = () => ({
    ...getOffer(),
    virtualTours: [{ enabled: true }],
});

export const statsSelector = () => () => ({});
