export const Gate = {
    create: () => Promise.resolve({ isDone: true }),
};

const item = {
    page: 0,
    favoriteType: 'OFFER',
    favoriteId: '6885852605830049537',
    offerId: '6885852605830049537',
    trust: 'NORMAL',
    url: '//realty.test.vertis.yandex.ru/offer/6885852605830049537',
    unsignedInternalUrl: '//realty.test.vertis.yandex.ru/offer/6885852605830049537',
    partnerId: '1035218734',
    partnerName: 'Яндекс.Недвижимость',
    offerType: 'SELL',
    offerCategory: 'APARTMENT',
    clusterId: '6885852605830049537',
    clusterHeader: true,
    clusterSize: 1,
    author: {
        id: '0',
        category: 'OWNER',
        agentName: 'obro dobro',
        creationDate: '2021-02-20T17:02:23Z',
        allowedCommunicationChannels: ['COM_CALLS'],
        redirectPhones: true,
        redirectPhonesFailed: false,
        encryptedPhoneNumbers: [
            {
                phone: 'KzcF5MHjEJ0NLDIN4NPTkR4',
                redirectId: '+79214428598',
            },
        ],
        encryptedPhones: ['KzcF5MHjEJ0NLDIN4NPTkR4'],
    },
    creationDate: '2021-02-24T15:21:06Z',
    updateDate: '2021-04-07T07:06:00Z',
    roomsTotal: 1,
    floorsTotal: 12,
    floorsOffered: [5],
    flatType: 'SECONDARY',
    ceilingHeight: 3,
    area: {
        value: 55,
        unit: 'SQUARE_METER',
    },
    livingSpace: {
        value: 45,
        unit: 'SQUARE_METER',
    },
    kitchenSpace: {
        value: 10,
        unit: 'SQUARE_METER',
    },
    roomSpace: [
        {
            value: 25,
            unit: 'SQUARE_METER',
        },
    ],
    price: {
        currency: 'RUR',
        value: 7777777,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'DECREASED',
        previous: 8888888,
        hasPriceHistory: true,
        valuePerPart: 141414,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 7777777,
        unitForWhole: 'WHOLE_OFFER',
        price: {
            value: 7777777,
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'WHOLE_LIFE',
        },
        pricePerPart: {
            value: 141414,
            currency: 'RUB',
            priceType: 'PER_METER',
            pricingPeriod: 'WHOLE_LIFE',
        },
        priceForWhole: {
            value: 7777777,
            currency: 'RUB',
            priceType: 'PER_OFFER',
            pricingPeriod: 'WHOLE_LIFE',
        },
    },
    notForAgents: false,
    totalImages: 5,
    photoPreviews: ['', '', '', '', ''],
    apartment: {
        renovation: 'EURO',
    },
    location: {
        rgid: 12438,
        geoId: 213,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587795,
        settlementGeoId: 213,
        address: 'Москва, Крапивенский переулок, 1с2',
        geocoderAddress: 'Россия, Москва, Крапивенский переулок, 1с2',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: {
                        rgid: '143',
                        address: 'Россия',
                    },
                },
                {
                    value: 'Москва',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Москва',
                    regionType: 'CITY',
                    queryParams: {
                        rgid: '587795',
                        address: 'Россия, Москва',
                    },
                },
                {
                    value: 'Крапивенский переулок',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Крапивенский переулок',
                    regionType: 'STREET',
                    queryParams: {
                        rgid: '587795',
                        address: 'Россия, Москва, Крапивенский переулок',
                    },
                },
                {
                    value: '1с2',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: '1с2',
                    regionType: 'HOUSE',
                    queryParams: {
                        rgid: '587795',
                        address: 'Россия, Москва, Крапивенский переулок, 1с2',
                    },
                },
            ],
        },
        point: {
            latitude: 55.76716,
            longitude: 37.616173,
            precision: 'EXACT',
        },
        metro: {
            metroGeoId: 20565,
            name: 'Трубная',
            metroTransport: 'ON_FOOT',
            timeToMetro: 6,
            latitude: 55.76794,
            longitude: 37.621883,
            minTimeToMetro: 5,
            lineColors: ['69cd37'],
            rgbColor: '69cd37',
        },
        streetAddress: 'Крапивенский переулок, 1с2',
        metroList: [
            {
                metroGeoId: 20565,
                name: 'Трубная',
                metroTransport: 'ON_FOOT',
                timeToMetro: 6,
                latitude: 55.76794,
                longitude: 37.621883,
                minTimeToMetro: 5,
                lineColors: ['69cd37'],
                rgbColor: '69cd37',
            },
            {
                metroGeoId: 20506,
                name: 'Чеховская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 8,
                latitude: 55.765846,
                longitude: 37.60817,
                minTimeToMetro: 8,
                lineColors: ['909090'],
                rgbColor: '909090',
            },
            {
                metroGeoId: 20501,
                name: 'Пушкинская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 8,
                latitude: 55.76575,
                longitude: 37.6039,
                minTimeToMetro: 7,
                lineColors: ['b1179a'],
                rgbColor: 'b1179a',
            },
            {
                metroGeoId: 20472,
                name: 'Тверская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 10,
                latitude: 55.764458,
                longitude: 37.605946,
                minTimeToMetro: 8,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 20505,
                name: 'Цветной Бульвар',
                metroTransport: 'ON_FOOT',
                timeToMetro: 11,
                latitude: 55.77176,
                longitude: 37.62074,
                minTimeToMetro: 9,
                lineColors: ['909090'],
                rgbColor: '909090',
            },
            {
                metroGeoId: 20473,
                name: 'Театральная',
                metroTransport: 'ON_FOOT',
                timeToMetro: 14,
                latitude: 55.75797,
                longitude: 37.619,
                minTimeToMetro: 9,
                lineColors: ['4f8242'],
                rgbColor: '4f8242',
            },
            {
                metroGeoId: 20502,
                name: 'Кузнецкий Мост',
                metroTransport: 'ON_FOOT',
                timeToMetro: 14,
                latitude: 55.76151,
                longitude: 37.624516,
                minTimeToMetro: 13,
                lineColors: ['b1179a'],
                rgbColor: 'b1179a',
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '20a70a',
                description: 'отличная',
                level: 7,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: '9ada1b',
                description: 'высокая доступность',
                level: 6,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '20a70a',
                description: 'отличная',
                level: 7,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '620801',
                description: 'очень высокая',
                level: 1,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: '620801',
                description: 'очень высокая',
                level: 1,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: '9ada1b',
                description: 'выше средней',
                level: 6,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: '9ada1b',
                description: 'высокая доступность',
                level: 6,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: 'ffe424',
                description: 'выше средней',
                level: 4,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Москва и МО',
    },
    house: {
        studio: false,
        apartments: false,
        housePart: false,
    },
    building: {
        parkingType: 'OPEN',
        heatingType: 'UNKNOWN',
        hasDeveloperChat: false,
    },
    description: 'weir iowjeirj weir weir',
    internal: true,
    active: true,
    vas: {
        raised: true,
        premium: true,
        placement: false,
        promoted: true,
        turboSale: true,
        raisingSale: false,
        tuzFeatured: false,
        vasAvailable: true,
    },
    dealStatus: 'SALE',
    uid: '4065458552',
    relevance: 0,
    socialReasonRejectDefinitions: {
        not_trusted_owner: 'Не доверенный пользователь',
    },
    partnerInternalId: '6885852605830049537',
    callCenter: false,
    exclusive: true,
    predictions: {
        predictedPrice: {
            min: '19507000',
            max: '23842000',
            value: '21674000',
        },
    },
    obsolete: false,
    withExcerpt: false,
    freeReportAccessibility: 'FRA_NONE',
    paidReportAccessibility: 'PPA_ALLOWED_TO_BUY_WITH_ADDITIONAL_DATA_REQUIRED',
    allowedCommunicationChannels: ['COM_CALLS'],
    remoteReview: {
        onlineShow: false,
        youtubeVideoReviewUrl: '',
    },
    socialPessimization: true,
    chargeForCallsType: 'NO_CHARGE',
    trustedOfferInfo: {
        isFullTrustedOwner: false,
        ownerTrustedStatus: 'NOT_LINKED_MOSRU',
        isCadastrPersonMatched: false,
    },
    yandexRent: false,
    offerState: {
        indexerState: {},
    },
    newFlatSale: false,
    placement: false,
    promoted: true,
    suspicious: false,
    shareUrl: 'https://realty.test.vertis.yandex.ru/offer/6885852605830049537',
    primarySaleV2: false,
    raised: true,
    premium: true,
    vasAvailable: true,
    openPlan: false,
    newBuilding: false,
};

export const initialState = {
    user: {
        favorites: [],
        favoritesMap: {},
    },
    sharedFavorites: {
        items: [item, item, item, item],
        queryId: '',
        pager: {
            pageSize: 1,
            page: 0,
            totalItems: 1,
            totalPages: 1,
        },
    },
};

export const sharedEmptyInitialState = {
    ...initialState,
    sharedFavorites: {
        ...initialState.sharedFavorites,
        items: [],
    },
};
