import { generateImageUrl } from '@realty-front/jest-utils/puppeteer/tests-helpers/image';

import { SitePlansSortTypes } from 'realty-core/types/sitePlans';

const plansSiteFilter = [
    { value: '202457', label: 'Пригород Лесное' },
    { value: '1680614', label: 'Большое Путилково' },
    { value: '1839196', label: 'Люберцы' },
    { value: '1645991', label: 'Остафьево' },
];

const plans = [
    {
        roomType: 'STUDIO',
        roomCount: 0,
        wholeArea: { value: 19.8, unit: 'SQ_M' },
        livingArea: { value: 9.4, unit: 'SQ_M' },
        images: {
            large: generateImageUrl({ width: 300, height: 700 }),
        },
        clusterId: '299766-1200-753C4889D6C4F3B1',
        floors: [2, 4, 6, 8, 9, 10, 11, 12, 13, 14, 22, 25],
        commissioningDate: [
            { year: 2020, quarter: 4, constructionState: 'CONSTRUCTION_STATE_FINISHED' },
            { year: 2021, quarter: 4, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
            { year: 2023, quarter: 1, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
        ],
        pricePerOffer: { currency: 'RUB', from: '4284720', to: '5983560' },
        pricePerMeter: { currency: 'RUB', from: '216400', to: '302200' },
        offersCount: 17,
        offerId: '5131474176413169075',
        site: {
            name: 'Белая Дача парк',
        },
    },
    {
        roomType: '1',
        roomCount: 1,
        wholeArea: { value: 41.2, unit: 'SQ_M' },
        livingArea: { value: 10.7, unit: 'SQ_M' },
        kitchenArea: { value: 21.2, unit: 'SQ_M' },
        images: {
            large: generateImageUrl({ width: 500, height: 500 }),
        },
        clusterId: '299766-0A020801-B7BEFDADB553AB78',
        floors: [4, 22],
        commissioningDate: [{ year: 2020, quarter: 4, constructionState: 'CONSTRUCTION_STATE_FINISHED' }],
        pricePerOffer: { currency: 'RUB', from: '7621900', to: '8137000' },
        pricePerMeter: { currency: 'RUB', from: '185900', to: '197499' },
        offersCount: 2,
        offerId: '9173195163408377043',
        site: {
            name: 'Белая Дача парк',
        },
    },
    {
        roomType: '2',
        roomCount: 2,
        wholeArea: { value: 65.2, unit: 'SQ_M' },
        livingArea: { value: 28.1, unit: 'SQ_M' },
        kitchenArea: { value: 11.4, unit: 'SQ_M' },
        images: {
            large: generateImageUrl({ width: 600, height: 300 }),
        },
        clusterId: '299766-0A020802-C4227F9D97006DB7',
        floors: [16],
        commissioningDate: [{ year: 2020, quarter: 4, constructionState: 'CONSTRUCTION_STATE_FINISHED' }],
        pricePerOffer: { currency: 'RUB', from: '9291000', to: '9291000' },
        pricePerMeter: { currency: 'RUB', from: '142500', to: '142500' },
        offersCount: 1,
        offerId: '2750761085058936320',
        site: {
            name: 'Белая Дача парк',
        },
    },
    {
        roomType: '3',
        roomCount: 3,
        wholeArea: { value: 80, unit: 'SQ_M' },
        livingArea: { value: 41.6, unit: 'SQ_M' },
        kitchenArea: { value: 17, unit: 'SQ_M' },
        images: {},
        clusterId: '299766-0A020803-3F726A3B699CA00A',
        floors: [5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 19, 25],
        commissioningDate: [
            { year: 2021, quarter: 4, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
            { year: 2023, quarter: 1, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
        ],
        pricePerOffer: { currency: 'RUB', from: '8872000', to: '12232000' },
        pricePerMeter: { currency: 'RUB', from: '110900', to: '152900' },
        offersCount: 14,
        offerId: '5130893357616671754',
        site: {
            name: 'Белая Дача парк',
        },
    },
    {
        roomType: 'PLUS_4',
        roomCount: 5,
        wholeArea: { value: 120.6, unit: 'SQ_M' },
        livingArea: { value: 34.1, unit: 'SQ_M' },
        kitchenArea: { value: 21.5, unit: 'SQ_M' },
        images: {
            large: generateImageUrl({ width: 300, height: 300 }),
        },
        clusterId: '299766-0A020802-145C60E9447ACD5',
        floors: [2, 3, 4, 6, 7, 8, 12, 15],
        commissioningDate: [
            { year: 2021, quarter: 4, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
            { year: 2023, quarter: 1, constructionState: 'CONSTRUCTION_STATE_UNFINISHED' },
        ],
        pricePerOffer: { currency: 'RUB', from: '8118460', to: '10194940' },
        pricePerMeter: { currency: 'RUB', from: '112600', to: '141400' },
        offersCount: 10,
        offerId: '7370704626681979494',
        site: {
            name: 'Белая Дача парк',
        },
    },
    {
        roomType: '3',
        roomCount: 3,
        wholeArea: { value: 72.2, unit: 'SQ_M' },
        livingArea: { value: 41.9, unit: 'SQ_M' },
        kitchenArea: { value: 12.6, unit: 'SQ_M' },
        images: {},
        clusterId: '299766-0A020803-59B372C6CC4E1369',
        floors: [19],
        commissioningDate: [{ year: 2020, quarter: 4, constructionState: 'CONSTRUCTION_STATE_FINISHED' }],
        pricePerOffer: { currency: 'RUB', from: '10136880', to: '10136880' },
        pricePerMeter: { currency: 'RUB', from: '140400', to: '140400' },
        offersCount: 1,
        offerId: '3436789108370829316',
        site: {
            name: 'Белая Дача парк',
        },
    },
];

const site = {
    id: 299766,
    name: 'Белая Дача парк',
    locativeFullName: 'в жилом комплексе «Белая Дача парк»',
    location: {
        geoId: 21651,
        rgid: 592850,
        settlementRgid: 592850,
        settlementGeoId: 21651,
        populatedRgid: 592850,
        address: 'Московская обл., Котельники, Яничкин проезд, вблизи д. 2',
        distanceFromRingRoad: 3306,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        subjectFederationName: 'Москва и МО',
        point: { latitude: 55.659836, longitude: 37.874886, precision: 'EXACT' },
        expectedMetroList: [],
        schools: [],
        parks: [],
        ponds: [],
        airports: [],
        cityCenter: [],
        heatmaps: [],
        allHeatmaps: [],
        insideMKAD: false,
        routeDistances: [],
        structuredAddress: {},
        metro: {},
        metroList: [],
    },
    viewTypes: [],
    images: [],
    appLargeImages: [],
    appMiddleSnippetImages: [],
    appLargeSnippetImages: [],
    minicardImages: [],
    siteSpecialProposals: [],
    buildingClass: 'COMFORT',
    state: 'UNFINISHED',
    finishedApartments: true,
    price: {
        from: 4314420,
        to: 12982720,
        currency: 'RUR',
        minPricePerMeter: 108699,
        maxPricePerMeter: 312500,
        averagePricePerMeter: 152329,
        rooms: {
            '1': {
                soldout: false,
                from: 5538260,
                to: 8477010,
                currency: 'RUR',
                areas: { from: '33.5', to: '44.7' },
                hasOffers: true,
                offersCount: 135,
                priceRatioToMarket: 0,
                status: 'ON_SALE',
            },
            '2': {
                soldout: false,
                from: 5670080,
                to: 10428590,
                currency: 'RUR',
                areas: { from: '35.8', to: '72.1' },
                hasOffers: true,
                offersCount: 192,
                priceRatioToMarket: 0,
                status: 'ON_SALE',
            },
            '3': {
                soldout: false,
                from: 7687820,
                to: 12982720,
                currency: 'RUR',
                areas: { from: '56.3', to: '92.8' },
                hasOffers: true,
                offersCount: 87,
                priceRatioToMarket: 0,
                status: 'ON_SALE',
            },
            OPEN_PLAN: { soldout: false, currency: 'RUR', hasOffers: false, offersCount: 0, priceRatioToMarket: 0 },
            STUDIO: {
                soldout: false,
                from: 4314420,
                to: 7242300,
                currency: 'RUR',
                areas: { from: '19.5', to: '28.8' },
                hasOffers: true,
                offersCount: 47,
                priceRatioToMarket: 0,
                status: 'ON_SALE',
            },
            PLUS_4: { soldout: false, currency: 'RUR', hasOffers: false, offersCount: 0, priceRatioToMarket: 0 },
        },
        totalOffers: 461,
        priceRatioToMarket: 0,
        minArea: 19.5,
        maxArea: 92.8,
    },
    flatStatus: 'ON_SALE',
    developers: [],
    backCallTrafficInfo: {},
    withBilling: true,
    awards: {},
    limitedCard: false,
    timestamp: 1631712184241,
};

const state = {
    user: {
        favoritesMap: {},
    },
};

export const baseState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: plans,
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 6,
            },
            searchQuery: {
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: false,
    },
    loader: {},
};

export const emptyListState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: [],
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 0,
            },
            searchQuery: {
                roomsTotal: ['PLUS_4'],
                priceMin: 1000000,
                priceMax: 5500000,
                siteId: ['1839196'],
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: false,
    },
    loader: {},
};

export const hasMoreState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: plans,
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 8,
            },
            searchQuery: {
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: false,
    },
    loader: {},
};

export const loadingMoreState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: plans,
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 8,
            },
            searchQuery: {
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: true,
    },
    loader: {
        plans: { isLoading: true },
    },
};

export const loadingState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: plans,
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 20,
            },
            searchQuery: {
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: false,
    },
    loader: {
        plans: { isLoading: true },
    },
};

export const planModalState = {
    ...state,
    samoletCard: {
        plansSiteFilter,
        plans: {
            items: plans.map((plan) => ({ ...plan, site })),
            pager: {
                page: 0,
                pageSize: 6,
                totalItems: 6,
            },
            searchQuery: {
                sort: SitePlansSortTypes.AREA_DESC,
            },
        },
        isPlansMoreLoading: false,
    },
    loader: {},
    cardPlansOffers: {
        page: 0,
        isLoading: false,
        totalOffers: 2,
        error: false,
        offers: [
            {
                offerId: '3436765227421780968',
                building: {
                    builtYear: 2020,
                    builtQuarter: 4,
                    buildingState: 'HAND_OVER',
                    buildingType: 'PANEL',
                    improvements: {
                        PARKING: true,
                        LIFT: true,
                    },
                    parkingType: 'OPEN',
                    siteId: 299766,
                    siteName: 'Белая Дача парк',
                    siteDisplayName: 'Жилой комплекс «Белая Дача парк»',
                    developerIds: [52308],
                    houseId: '1682422',
                    houseReadableName: 'Корпус 1',
                    heatingType: 'UNKNOWN',
                    hasDeveloperChat: false,
                    apartmentType: 'FLATS',
                    buildingImprovementsMap: {
                        PARKING: true,
                        LIFT: true,
                    },
                },
                floorsOffered: [4],
                floorsTotal: 25,
                area: {
                    value: 41,
                    unit: 'SQUARE_METER',
                },
                apartment: {
                    renovation: 'TURNKEY',
                    decoration: 'TURNKEY',
                    siteFlatPlanId: '299766-0A020801-B7BEFDADB553AB78',
                },
                price: {
                    currency: 'RUR',
                    value: 7621900,
                    period: 'WHOLE_LIFE',
                    unit: 'WHOLE_OFFER',
                    trend: 'INCREASED',
                    previous: 7474300,
                    hasPriceHistory: true,
                    valuePerPart: 185900,
                    unitPerPart: 'SQUARE_METER',
                    valueForWhole: 7621900,
                    unitForWhole: 'WHOLE_OFFER',
                    price: {
                        value: 7621900,
                        currency: 'RUB',
                        priceType: 'PER_OFFER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                    pricePerPart: {
                        value: 185900,
                        currency: 'RUB',
                        priceType: 'PER_METER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                    priceForWhole: {
                        value: 7621900,
                        currency: 'RUB',
                        priceType: 'PER_OFFER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                },
                flatType: 'NEW_SECONDARY',
                offerType: 'SELL',
                offerCategory: 'APARTMENT',
                roomsTotal: 1,
                house: {
                    bathroomUnit: 'MATCHED',
                    windowView: 'STREET',
                    apartments: false,
                    housePart: false,
                },
                partnerId: '1069052819',
                uid: '561248415',
                primarySaleV2: true,
                location: {
                    rgid: 592850,
                    geoId: 21651,
                    subjectFederationId: 1,
                    subjectFederationRgid: 741964,
                    settlementRgid: 592850,
                    settlementGeoId: 21651,
                    address: 'Котельники, жилой комплекс Белая Дача Парк, к. 19.1',
                    geocoderAddress: 'Россия, Московская область, Котельники, Яничкин проезд, 2',
                    structuredAddress: {},
                    point: {
                        latitude: 55.65695,
                        longitude: 37.87485,
                        precision: 'EXACT',
                    },
                    metro: {
                        metroGeoId: 121428,
                        name: 'Котельники',
                        metroTransport: 'ON_TRANSPORT',
                        timeToMetro: 15,
                        latitude: 55.674137,
                        longitude: 37.858643,
                        minTimeToMetro: 15,
                        lineColors: ['b1179a'],
                        rgbColor: 'b1179a',
                    },
                    station: {
                        name: 'Люберцы 1',
                        distanceKm: 3.159,
                    },
                    streetAddress: 'Яничкин проезд, 2',
                    metroList: [
                        {
                            metroGeoId: 121428,
                            name: 'Котельники',
                            metroTransport: 'ON_TRANSPORT',
                            timeToMetro: 15,
                            latitude: 55.674137,
                            longitude: 37.858643,
                            minTimeToMetro: 15,
                            lineColors: ['b1179a'],
                            rgbColor: 'b1179a',
                        },
                    ],
                    airports: [],
                    heatmaps: [],
                    allHeatmaps: [],
                    routeDistances: [
                        {
                            geoPoint: {
                                latitude: 55.65824,
                                longitude: 37.83995,
                            },
                            distance: 3428,
                        },
                    ],
                    subjectFederationName: 'Москва и МО',
                    cityCenter: [],
                },
                queryId: '6b6390f6e3c158ac2ff07716a58568e4',
                author: {
                    category: 'DEVELOPER',
                },
            },
            {
                offerId: '9173195163408377043',
                building: {
                    builtYear: 2020,
                    builtQuarter: 4,
                    buildingState: 'HAND_OVER',
                    buildingType: 'PANEL',
                    improvements: {
                        PARKING: true,
                        LIFT: true,
                    },
                    parkingType: 'OPEN',
                    siteId: 299766,
                    siteName: 'Белая Дача парк',
                    siteDisplayName: 'Жилой комплекс «Белая Дача парк»',
                    developerIds: [52308],
                    houseId: '1682422',
                    houseReadableName: 'Корпус 1',
                    heatingType: 'UNKNOWN',
                    hasDeveloperChat: false,
                    apartmentType: 'FLATS',
                    buildingImprovementsMap: {
                        PARKING: true,
                        LIFT: true,
                    },
                },
                floorsOffered: [22],
                floorsTotal: 25,
                area: {
                    value: 41.2,
                    unit: 'SQUARE_METER',
                },
                apartment: {
                    renovation: 'TURNKEY',
                    decoration: 'TURNKEY',
                    siteFlatPlanId: '299766-0A020801-B7BEFDADB553AB78',
                },
                price: {
                    currency: 'RUR',
                    value: 8137000,
                    period: 'WHOLE_LIFE',
                    unit: 'WHOLE_OFFER',
                    trend: 'DECREASED',
                    previous: 8301800,
                    hasPriceHistory: true,
                    valuePerPart: 197500,
                    unitPerPart: 'SQUARE_METER',
                    valueForWhole: 8137000,
                    unitForWhole: 'WHOLE_OFFER',
                    price: {
                        value: 8137000,
                        currency: 'RUB',
                        priceType: 'PER_OFFER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                    pricePerPart: {
                        value: 197500,
                        currency: 'RUB',
                        priceType: 'PER_METER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                    priceForWhole: {
                        value: 8137000,
                        currency: 'RUB',
                        priceType: 'PER_OFFER',
                        pricingPeriod: 'WHOLE_LIFE',
                    },
                },
                flatType: 'NEW_SECONDARY',
                offerType: 'SELL',
                offerCategory: 'APARTMENT',
                roomsTotal: 1,
                house: {
                    bathroomUnit: 'MATCHED',
                    windowView: 'STREET',
                    apartments: false,
                    housePart: false,
                },
                partnerId: '1069052819',
                uid: '561248415',
                primarySaleV2: true,
                location: {
                    rgid: 592850,
                    geoId: 21651,
                    subjectFederationId: 1,
                    subjectFederationRgid: 741964,
                    settlementRgid: 592850,
                    settlementGeoId: 21651,
                    address: 'Котельники, микрорайон Парковый, 1, к. 3',
                    geocoderAddress: 'Россия, Московская область, Котельники, Яничкин проезд, 2',
                    structuredAddress: {
                        component: [],
                    },
                    point: {
                        latitude: 55.658897,
                        longitude: 37.875076,
                        precision: 'EXACT',
                    },
                    metro: {
                        metroGeoId: 121428,
                        name: 'Котельники',
                        metroTransport: 'ON_TRANSPORT',
                        timeToMetro: 15,
                        latitude: 55.674137,
                        longitude: 37.858643,
                        minTimeToMetro: 15,
                        lineColors: ['b1179a'],
                        rgbColor: 'b1179a',
                    },
                    station: {
                        name: 'Люберцы 1',
                        distanceKm: 2.959,
                    },
                    streetAddress: 'Яничкин проезд, 2',
                    metroList: [],
                    airports: [],
                    heatmaps: [],
                    allHeatmaps: [],
                    routeDistances: [
                        {
                            geoPoint: {
                                latitude: 55.65824,
                                longitude: 37.83995,
                            },
                            distance: 3314,
                        },
                    ],
                    subjectFederationName: 'Москва и МО',
                    cityCenter: [],
                },
                queryId: '6b6390f6e3c158ac2ff07716a58568e4',
                author: {
                    category: 'DEVELOPER',
                },
            },
        ],
        pager: {
            page: 0,
            pageSize: 10,
            sitesPageSize: 10,
            totalItems: 2,
            totalPages: 1,
        },
    },
};
