export const fixtures = {
    'Public sitemap controller GET /sitemap Возвращает массив элементов для сайтмапа': {
        POST_ATTRIBUTES_1: {
            status: 'publish',
            id: 370,
            urlPart: 'kak-vybrat-raskladnoy-divan-v-malenkuyu-kvartiru',
            service: 'realty',
            title: 'Как выбрать раскладной диван в маленькую квартиру: простые советы',
            draftTitle: 'Как выбрать раскладной диван в маленькую квартиру: простые советы',
            lead: 'Рассказываем, какие диваны подойдут для небольшой квартиры и на что обращать внимание при выборе',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Марина Шумаркина',
            lastEditLogin: 'mtsymbal',
            publishAt: '2022-02-15T14:58:05.000Z',
            createdAt: '2022-02-14T10:01:18.000Z',
            lastEditedAt: '2022-02-16T12:29:09.000Z',
            lastOnlineTime: '2022-02-16T12:29:09.000Z',
            lastOnlineLogin: 'pruginka',
        },
        TAG_ATTRIBUTES_1: {
            urlPart: 'arenda',
            service: 'realty',
            draftTitle: 'Аренда',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T22:49:54.000Z',
        },
        CATEGORY_ATTRIBUTES_1: {
            urlPart: 'dizayn',
            service: 'realty',
            draftTitle: 'Дизайн',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T21:49:54.000Z',
        },
    },
};
