export const fixtures = {
    'Sitemap service getSitemapElements Возвращает опубликованные открытые для индексирования посты': {
        POST_ATTRIBUTES_1: {
            status: 'draft',
            id: 384,
            urlPart:
                'vernuvshis-posle-neyo-v-kvartiru-ya-uzhasnulas-kak-arendator-ubil-syomnuyu-kvartiru-i-chto-delat-v-takih-sluchayah',
            service: 'realty',
            draftTitle:
                '«Вернувшись после неё в квартиру, я ужаснулась». Как арендатор «убил» съёмную квартиру и что делать в таких случаях',
            lead: 'Арендодатель рассказывает о том, почему квартира, в которой год жила молодая девушка, больше не сдается',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Аня Устюжанинова',
            lastEditLogin: 'pruginka',
            createdAt: '2022-02-21T11:45:22.000Z',
            lastEditedAt: '2022-02-22T10:53:58.000Z',
            lastOnlineTime: '2022-02-22T10:53:58.000Z',
            lastOnlineLogin: 'avlyalin',
        },
        POST_ATTRIBUTES_2: {
            status: 'closed',
            id: 378,
            urlPart: 'doma-luchshe-10-idey-dlya-klassnyh-vyhodnyh-ne-vyhodya-iz-kvartiry',
            service: 'realty',
            title: 'Чем заняться в выходные, не выходя из дома: 10 классных идей',
            draftTitle: 'Чем заняться в выходные, не выходя из дома: 10 классных идей',
            lead: 'Как сделать выходные отличными и запоминающимися, если выходить из квартиры совсем не хочется',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Настя Житинская',
            lastEditLogin: 'mtsymbal',
            publishAt: '2022-02-18T16:12:01.000Z',
            createdAt: '2022-02-16T11:42:24.000Z',
            lastEditedAt: '2022-02-22T11:13:21.000Z',
            lastOnlineTime: '2022-02-22T11:13:21.000Z',
            lastOnlineLogin: 'avlyalin',
        },
        POST_ATTRIBUTES_3: {
            status: 'publish',
            id: 377,
            urlPart: 'kvartira-dnya-izyskannaya-dvushka-dlya-ceniteley-komforta',
            service: 'realty',
            title: 'Квартира дня: изысканная «двушка» для ценителей комфорта',
            draftTitle: 'Квартира дня: изысканная «двушка» для ценителей комфорта',
            lead: 'Продуманная красота в паре с яркостью и уютом\n',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Редакция Яндекс.Недвижимости',
            indexOff: true,
            lastEditLogin: 'mtsymbal',
            publishAt: '2022-02-16T13:56:02.000Z',
            createdAt: '2022-02-16T11:19:52.000Z',
            lastEditedAt: '2022-02-17T15:24:23.000Z',
            lastOnlineTime: '2022-02-17T15:24:23.000Z',
            lastOnlineLogin: 'pruginka',
        },
        POST_ATTRIBUTES_4: {
            status: 'publish',
            id: 370,
            urlPart: 'kak-vybrat-raskladnoy-divan-v-malenkuyu-kvartiru',
            service: 'realty',
            title: 'Как выбрать раскладной диван в маленькую квартиру: простые советы',
            draftTitle: 'Как выбрать раскладной диван в маленькую квартиру: простые советы',
            lead: 'Рассказываем, какие диваны подойдут для небольшой квартиры и на что обращать внимание при выборе',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Марина Шумаркина',
            lastEditLogin: 'mtsymbal',
            publishAt: '2022-02-15T14:58:05.000Z',
            createdAt: '2022-02-14T10:01:18.000Z',
            lastEditedAt: '2022-02-16T12:29:09.000Z',
            lastOnlineTime: '2022-02-16T12:29:09.000Z',
            lastOnlineLogin: 'pruginka',
        },
        POST_ATTRIBUTES_5: {
            status: 'publish',
            id: 368,
            urlPart: 'nado-bylo-ranshe-kak-snimayut-kvartiry-v-stokgolme',
            service: 'realty',
            title: 'Надо раньше! Почему в очередь на съёмную квартиру в Стокгольме приходится вставать в 18 лет',
            draftTitle: 'Надо раньше! Почему в очередь на съёмную квартиру в Стокгольме приходится вставать в 18 лет',
            lead: 'Пост поддержки для тех, кто отчаялся искать съёмную квартиру и живёт поисками уже очень долго',
            draftBlocks: [],
            draftMainImage: {},
            author: 'pruginka',
            authorHelp: 'Редакция Яндекс.Недвижимости',
            commentsOff: false,
            rssOff: false,
            advertisementOff: false,
            subscribeOff: false,
            indexOff: false,
            lastEditLogin: 'mtsymbal',
            publishAt: '2022-02-14T17:02:31.000Z',
            createdAt: '2022-02-14T07:11:20.000Z',
            lastEditedAt: '2022-02-22T11:28:01.000Z',
            lastOnlineTime: '2022-02-22T11:28:01.000Z',
            lastOnlineLogin: 'avlyalin',
        },
    },

    'Sitemap service getSitemapElements Возвращает неархивные теги': {
        TAG_ATTRIBUTES_1: {
            urlPart: 'diy',
            service: 'realty',
            draftTitle: 'DIY',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T20:49:54.000Z',
            isArchived: true,
        },
        TAG_ATTRIBUTES_2: {
            urlPart: 'arenda',
            service: 'realty',
            draftTitle: 'Аренда',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T22:49:54.000Z',
        },
        TAG_ATTRIBUTES_3: {
            urlPart: 'valo',
            service: 'realty',
            draftTitle: 'VALO',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T21:49:54.000Z',
        },
    },

    'Sitemap service getSitemapElements Возвращает неархивные категории': {
        CATEGORY_ATTRIBUTES_1: {
            urlPart: 'analytics',
            service: 'realty',
            draftTitle: 'Аналитика',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T20:49:54.000Z',
            isArchived: true,
        },
        CATEGORY_ATTRIBUTES_2: {
            urlPart: 'dizayn',
            service: 'realty',
            draftTitle: 'Дизайн',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T21:49:54.000Z',
        },
        CATEGORY_ATTRIBUTES_3: {
            urlPart: 'specproekt',
            service: 'realty',
            draftTitle: 'Спецпроект',
            draftBlocks: [],
            createdAt: '2021-12-21T20:49:53.000Z',
            lastEditedAt: '2021-12-21T22:49:54.000Z',
        },
    },
};
