// Code generated by mockery v2.12.2. DO NOT EDIT.

package hbf

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// Start provides a mock function with given fields: dc, duration, issue
func (_m *IClient) Start(dc string, duration time.Duration, issue string) error {
	ret := _m.Called(dc, duration, issue)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, string) error); ok {
		r0 = rf(dc, duration, issue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields: dc
func (_m *IClient) Stop(dc string) (bool, error) {
	ret := _m.Called(dc)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(dc)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(dc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIClient creates a new instance of IClient. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t testing.TB) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
