import { generateImageUrl } from '@realty-front/jest-utils/puppeteer/tests-helpers/image';

import {
    IOfferCardMobile,
    OfferType,
    OfferCategory,
    AuthorCategoryTypes,
    PaidReportAccessibility,
    FreeReportAccessibility,
    AreaUnits,
} from 'realty-core/types/offerCard';
import { TransportDistanceType } from 'realty-core/types/location';

const image = generateImageUrl({ width: 480, height: 336 });

const images = [image, image, image, image, image, image];

export const baseOffer: IOfferCardMobile = {
    offerId: '7175042308909368517',
    trust: 'NORMAL',
    url: 'https://spb.yit.ru/sankt-peterburg-1/zk_tarmo/tarmo5/ru940001205a131',
    unsignedInternalUrl: '//realty.test.vertis.yandex.ru/offer/7175042308909368517',
    partnerId: '1069062416',
    partnerName: 'ЮИТ',
    offerType: OfferType.SELL,
    offerCategory: OfferCategory.APARTMENT,
    clusterId: '7504278408042413079',
    clusterHeader: false,
    clusterSize: 3,
    author: {
        id: '0',
        category: AuthorCategoryTypes.DEVELOPER,
        organization: 'АО «ЮИТ Санкт-Петербург»',
        creationDate: '2017-06-20T09:31:21Z',
        name: 'АО «ЮИТ Санкт-Петербург»',
        redirectPhones: true,
        redirectPhonesFailed: false,
        encryptedPhones: ['KzcF4MHTIJ3MLDMN0NPDQR0'],
    },
    creationDate: '2020-10-15T12:26:29Z',
    updateDate: '2020-10-15T12:26:35Z',
    roomsTotal: 1,
    floorsTotal: 11,
    floorsOffered: [8],
    flatType: 'NEW_FLAT',
    area: {
        value: 42.29,
        unit: 'SQUARE_METER',
    },
    livingSpace: {
        value: 12.53,
        unit: 'SQUARE_METER',
    },
    kitchenSpace: {
        value: 18.4,
        unit: 'SQUARE_METER',
    },
    price: {
        currency: 'RUR',
        value: 3000000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 53571,
        unitPerPart: AreaUnits.SQUARE_METER,
        valueForWhole: 3000000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 3000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 53571, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 3000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    notForAgents: false,
    totalImages: 6,
    minicardImages: images,
    mainImages: images,
    fullImages: images,
    alikeImages: images,
    cosmicImages: images,
    appMiddleImages: images,
    appLargeImages: images,
    appMiniSnippetImages: images,
    appSmallSnippetImages: images,
    appMiddleSnippetImages: images,
    appLargeSnippetImages: images,
    origImages: images,
    photoPreviews: ['', '', '', '', '', ''],
    apartment: {
        siteFlatPlanId: '549393-0A020801-35C88CCF46CE6505',
    },
    location: {
        rgid: 285002,
        populatedRgid: 741965,
        geoId: 2,
        subjectFederationId: 10174,
        subjectFederationRgid: 741965,
        settlementRgid: 417899,
        settlementGeoId: 2,
        address: 'Приморский район, муниципальный округ Чёрная Речка',
        geocoderAddress: 'Россия, Санкт-Петербург, Студенческая улица, 26к2',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: {
                        rgid: '143',
                        address: 'Россия',
                    },
                    rgid: '143',
                },
                {
                    value: 'Санкт-Петербург',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: 'Санкт-Петербург',
                    regionType: 'CITY',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург',
                    },
                    rgid: '417899',
                },
                {
                    value: 'Студенческая улица',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: 'Студенческая улица',
                    regionType: 'STREET',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург, Студенческая улица',
                    },
                    rgid: '417899',
                },
                {
                    value: '26к2',
                    geoId: 2,
                    regionGraphId: '417899',
                    address: '26к2',
                    regionType: 'HOUSE',
                    queryParams: {
                        rgid: '417899',
                        address: 'Россия, Санкт-Петербург, Студенческая улица, 26к2',
                    },
                    rgid: '417899',
                },
            ],
        },
        point: {
            latitude: 59.994987,
            longitude: 30.32239,
            precision: 'EXACT',
        },
        metro: {
            metroCityRgid: 417899,
            metroGeoId: 20323,
            name: 'Чёрная Речка',
            metroTransport: TransportDistanceType.ON_TRANSPORT,
            timeToMetro: 11,
            latitude: 59.98551,
            longitude: 30.300838,
            minTimeToMetro: 11,
            lineColors: ['16bdf0'],
            rgbColor: '16bdf0',
        },
        streetAddress: 'Студенческая улица, 26к2',
        metroList: [
            {
                metroCityRgid: 417899,
                metroGeoId: 20323,
                name: 'Чёрная Речка',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 11,
                latitude: 59.98551,
                longitude: 30.300838,
                minTimeToMetro: 11,
                lineColors: ['16bdf0'],
                rgbColor: '16bdf0',
            },
            {
                metroCityRgid: 417899,
                metroGeoId: 20318,
                name: 'Лесная',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 11,
                latitude: 59.984768,
                longitude: 30.344358,
                minTimeToMetro: 11,
                lineColors: ['f03d2f'],
                rgbColor: 'f03d2f',
            },
            {
                metroCityRgid: 417899,
                metroGeoId: 20322,
                name: 'Пионерская',
                metroTransport: TransportDistanceType.ON_TRANSPORT,
                timeToMetro: 16,
                latitude: 60.002518,
                longitude: 30.296667,
                minTimeToMetro: 16,
                lineColors: ['16bdf0'],
                rgbColor: '16bdf0',
            },
        ],
        parks: [
            {
                parkId: '123259023',
                name: 'Пионерский сад',
                timeOnFoot: 285,
                distanceOnFoot: 396,
                latitude: 59.99291,
                longitude: 30.323935,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 4,
                        distance: 396,
                    },
                ],
            },
            {
                parkId: '1492425560',
                name: 'Ланской сад',
                timeOnFoot: 446,
                distanceOnFoot: 620,
                latitude: 59.997246,
                longitude: 30.325552,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 7,
                        distance: 620,
                    },
                ],
            },
            {
                parkId: '4015494950',
                name: 'Луспекаевский сквер',
                timeOnFoot: 494,
                distanceOnFoot: 686,
                latitude: 59.991703,
                longitude: 30.318687,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 8,
                        distance: 686,
                    },
                ],
            },
        ],
        ponds: [
            {
                pondId: '170487388',
                name: 'Сердобольский пруд',
                timeOnFoot: 433,
                distanceOnFoot: 602,
                latitude: 59.99538,
                longitude: 30.331242,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 7,
                        distance: 602,
                    },
                ],
            },
            {
                pondId: '170487099',
                name: 'Длинный пруд',
                timeOnFoot: 646,
                distanceOnFoot: 897,
                latitude: 59.99586,
                longitude: 30.333702,
                timeDistanceList: [
                    {
                        transport: TransportDistanceType.ON_FOOT,
                        time: 10,
                        distance: 897,
                    },
                ],
            },
        ],
        airports: [
            {
                id: '858726',
                name: 'Пулково',
                timeOnCar: 2491,
                distanceOnCar: 39902,
                latitude: 59.79992,
                longitude: 30.271744,
                timeDistanceList: [
                    {
                        transport: 'ON_CAR',
                        time: 41,
                        distance: 39902,
                    },
                ],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '20a70a',
                description: 'очень низкая',
                level: 8,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: 'ffe424',
                description: 'выше средней',
                level: 5,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: '9ada1b',
                description: 'выше средней',
                level: 6,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: 'ffe424',
                description: 'выше среднего',
                level: 5,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '9ada1b',
                description: 'высокая',
                level: 5,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Санкт-Петербург и ЛО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 1030,
                distance: 8478,
                latitude: 59.934994,
                longitude: 30.306541,
                timeDistanceList: [
                    {
                        transport: 'ON_CAR',
                        time: 17,
                        distance: 8478,
                    },
                ],
            },
        ],
    },
    house: {
        apartments: false,
        housePart: false,
    },
    building: {
        builtYear: 2022,
        builtQuarter: 3,
        buildingState: 'UNFINISHED',
        improvements: {
            PARKING: false,
        },
        parkingType: 'OPEN',
        siteId: 549393,
        siteName: 'TARMO',
        siteDisplayName: 'ЖК «TARMO»',
        developerIds: [2725],
        houseId: '1517348',
        houseReadableName: 'Корпус 5',
        heatingType: 'UNKNOWN',
        buildingImprovementsMap: {
            PARKING: false,
        },
    },
    internal: true,
    active: true,
    vas: {
        raised: false,
        premium: false,
        placement: false,
        promoted: false,
        turboSale: false,
        raisingSale: false,
        tuzFeatured: false,
        vasAvailable: true,
    },
    dealStatus: 'PRIMARY_SALE',
    salesDepartments: [
        {
            id: 267521,
            name: 'YIT',
            isRedirectPhones: true,
            weekTimetable: [
                {
                    dayFrom: 1,
                    dayTo: 5,
                    timePattern: [
                        {
                            open: '09:00',
                            close: '19:00',
                        },
                    ],
                },
                {
                    dayFrom: 6,
                    dayTo: 6,
                    timePattern: [
                        {
                            open: '11:00',
                            close: '17:00',
                        },
                    ],
                },
            ],
            logo: image,
            statParams: '',
            encryptedPhones: ['KzcF4MHTIJ3MLDMN0NPDQR0'],
            encryptedDump: '',
        },
    ],
    uid: '313962949',
    relevance: 0,
    commissioningDateIndexValue: 20223,
    partnerInternalId: 'RU940001205A131',
    callCenter: false,
    exclusive: false,
    obsolete: false,
    withExcerpt: false,
    freeReportAccessibility: FreeReportAccessibility.FRA_NONE,
    paidReportAccessibility: PaidReportAccessibility.PPA_NOT_ALLOWED_TO_BUY,
    remoteReview: {
        onlineShow: false,
        youtubeVideoReviewUrl: '',
        virtualTour: {
            modelUrl: '',
            previewUrl: '',
        },
    },
    socialPessimization: false,
    chargeForCallsType: 'BY_CAMPAIGN',
    trustedOfferInfo: {
        isFullTrustedOwner: false,
        ownerTrustedStatus: 'NOT_LINKED_MOSRU',
        isCadastrPersonMatched: false,
    },
    yandexRent: false,
    openPlan: false,
    primarySaleV2: true,
    raised: false,
    premium: false,
    vasAvailable: true,
    placement: false,
    promoted: false,
    suspicious: false,
    shareUrl: 'https://realty.test.vertis.yandex.ru/offer/7175042308909368517',
    transactionConditionsMap: {
        MORTGAGE: true,
    },
    newBuilding: true,
    roomsTotalKey: '1',
    roomsTotalColor: '#4a85f2',
    page: 2,
    idx: 3,
    queryId: '578626e460489c2513f05301e721a989',
};

export const offerWithPriceUp = { ...baseOffer, price: { ...baseOffer.price, trend: 'INCREASED' } };

export const offerWithPriceDown = { ...baseOffer, price: { ...baseOffer.price, trend: 'DECREASED' } };

export const offerWithDistanceToMRR = {
    ...baseOffer,
    location: {
        rgid: 17385875,
        geoId: 98597,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587654,
        settlementGeoId: 1,
        address: 'Наро-Фоминский городской округ',
        geocoderAddress: 'Россия, Московская область, Наро-Фоминский городской округ',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Московская',
                    geoId: 1,
                    regionGraphId: '587654',
                    address: 'Московская область',
                    regionType: 'SUBJECT_FEDERATION',
                    queryParams: { rgid: '587654', address: 'Россия, Московская область' },
                },
                {
                    value: 'Наро-Фоминский округ',
                    geoId: 98597,
                    regionGraphId: '17385875',
                    address: 'Наро-Фоминский городской округ',
                    regionType: 'SUBJECT_FEDERATION_DISTRICT',
                    queryParams: {
                        rgid: '17385875',
                        address: 'Россия, Московская область, Наро-Фоминский городской округ',
                    },
                },
            ],
        },
        point: { latitude: 55.387775, longitude: 36.5225, precision: 'EXACT' },
        highway: { name: 'Киевское шоссе', distanceKm: 72.333 },
        airports: [
            {
                id: '878065',
                name: 'Внуково',
                timeOnCar: 4654,
                distanceOnCar: 69218,
                latitude: 55.604942,
                longitude: 37.282578,
                timeDistanceList: [{ transport: 'ON_CAR', time: 77, distance: 69218 }],
            },
            {
                id: '878042',
                name: 'Шереметьево',
                timeOnCar: 6361,
                distanceOnCar: 114204,
                latitude: 55.963852,
                longitude: 37.4169,
                timeDistanceList: [{ transport: 'ON_CAR', time: 106, distance: 114204 }],
            },
            {
                id: '858742',
                name: 'Домодедово',
                timeOnCar: 6812,
                distanceOnCar: 121196,
                latitude: 55.41435,
                longitude: 37.90048,
                timeDistanceList: [{ transport: 'ON_CAR', time: 113, distance: 121196 }],
            },
            {
                id: '878109',
                name: 'Жуковский (Раменское)',
                timeOnCar: 8454,
                distanceOnCar: 140481,
                latitude: 55.568665,
                longitude: 38.143654,
                timeDistanceList: [{ transport: 'ON_CAR', time: 140, distance: 140481 }],
            },
        ],
        routeDistances: [
            {
                geoPoint: { latitude: 55.6387, longitude: 37.459286 },
                distance: 72333,
                highway: { id: '11', name: 'Киевское шоссе' },
            },
            {
                geoPoint: { latitude: 55.713425, longitude: 37.38563 },
                distance: 78998,
                highway: { id: '32', name: 'Минское шоссе' },
            },
        ],
        subjectFederationName: 'Москва и МО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 5742,
                distance: 88765,
                latitude: 55.749058,
                longitude: 37.612267,
                timeDistanceList: [{ transport: 'ON_CAR', time: 95, distance: 88765 }],
            },
        ],
    },
};

export const offerWithSeveralBages = { ...baseOffer, yandexRent: true };

export const offerWithLongAddressName = {
    ...baseOffer,
    location: {
        ...baseOffer.location,
        address: 'Приморский район, муниципальный округ Коломяги, жилой комплекс Новоорловский',
    },
};

export const offerWith3dTour = {
    ...baseOffer,
    virtualTours: [{ enabled: true }],
};

export const houseOffer = {
    ...baseOffer,
    offerCategory: OfferCategory.HOUSE,
    house: { housePart: false, toilet: 'INSIDE', shower: 'INSIDE', houseType: 'HOUSE' },
    building: {
        builtYear: 1978,
        buildingType: 'PANEL',
        improvements: { LIFT: true, RUBBISH_CHUTE: true, GUARDED: false, SECURITY: false },
        parkingType: 'OPEN',
        buildingId: '3064409632106559109',
        flatsCount: 137,
        porchesCount: 4,
        heatingType: 'UNKNOWN',
        buildingEpoch: 'BUILDING_EPOCH_BREZHNEV',
        priceStatistics: {
            sellPricePerSquareMeter: {
                level: 0,
                maxLevel: 9,
                rgbColor: '',
                value: '0',
                regionValueFrom: '22727',
                regionValueTo: '2234148',
            },
        },
        buildingImprovementsMap: { LIFT: true, RUBBISH_CHUTE: true, GUARDED: false, SECURITY: false },
    },
    area: { value: 34, unit: 'SQUARE_METER' },
    lot: { lotArea: { unit: 'ARE', value: 33 }, lotType: 'IGS' },
    location: {
        rgid: 176187,
        geoId: 150816,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 592850,
        settlementGeoId: 21651,
        address: 'Котельники, микрорайон Белая Дача, 11',
        geocoderAddress: 'Россия, Московская область, Котельники, микрорайон Белая Дача, 11',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Московская',
                    geoId: 1,
                    regionGraphId: '587654',
                    address: 'Московская область',
                    regionType: 'SUBJECT_FEDERATION',
                    queryParams: { rgid: '587654', address: 'Россия, Московская область' },
                },
                {
                    value: 'округ Котельники',
                    geoId: 121006,
                    regionGraphId: '2305',
                    address: 'Котельники (городской округ)',
                    regionType: 'SUBJECT_FEDERATION_DISTRICT',
                    queryParams: { rgid: '2305', address: 'Россия, Московская область, Котельники (городской округ)' },
                },
                {
                    value: 'Котельники',
                    geoId: 21651,
                    regionGraphId: '592850',
                    address: 'Котельники',
                    regionType: 'CITY',
                    queryParams: {
                        rgid: '592850',
                        address: 'Россия, Московская область, Котельники (городской округ), Котельники',
                    },
                },
                {
                    value: 'Белая Дача',
                    geoId: 150816,
                    regionGraphId: '176187',
                    address: 'микрорайон Белая Дача',
                    regionType: 'NOT_ADMINISTRATIVE_DISTRICT',
                    queryParams: {
                        rgid: '176187',
                        address:
                            'Россия, Московская область, Котельники (городской округ), Котельники, микрорайон Дача',
                    },
                },
                {
                    value: '11',
                    geoId: 150816,
                    regionGraphId: '176187',
                    address: '11',
                    regionType: 'HOUSE',
                    queryParams: {
                        rgid: '176187',
                        address:
                            'Россия, Московская область, Котельники (городской округ), Котельники, микрорайон Дача, 11',
                    },
                },
            ],
        },
        point: { latitude: 55.66337, longitude: 37.84926, precision: 'EXACT' },
        metro: {
            metroGeoId: 121428,
            name: 'Котельники',
            metroTransport: 'ON_FOOT',
            timeToMetro: 18,
            latitude: 55.674137,
            longitude: 37.858643,
            minTimeToMetro: 18,
            lineColors: ['b1179a'],
            rgbColor: 'b1179a',
        },
        station: { name: 'Люберцы 1', distanceKm: 3.66 },
        streetAddress: 'микрорайон Белая Дача, 11',
        metroList: [
            {
                metroGeoId: 121428,
                name: 'Котельники',
                metroTransport: 'ON_FOOT',
                timeToMetro: 18,
                latitude: 55.674137,
                longitude: 37.858643,
                minTimeToMetro: 18,
                lineColors: ['b1179a'],
                rgbColor: 'b1179a',
            },
            {
                metroGeoId: 115038,
                name: 'Жулебино',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 21,
                latitude: 55.685135,
                longitude: 37.8558,
                minTimeToMetro: 21,
                lineColors: ['b1179a'],
                rgbColor: 'b1179a',
            },
            {
                metroGeoId: 115040,
                name: 'Лермонтовский проспект',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 25,
                latitude: 55.701702,
                longitude: 37.85238,
                minTimeToMetro: 25,
                lineColors: ['b1179a'],
                rgbColor: 'b1179a',
            },
        ],
        parks: [
            {
                parkId: '121387004',
                name: 'природно-исторический парк Кузьминки-Люблино',
                timeOnFoot: 90,
                distanceOnFoot: 126,
                latitude: 55.66399,
                longitude: 37.848976,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 1, distance: 126 }],
            },
        ],
        airports: [
            {
                id: '878109',
                name: 'Жуковский (Раменское)',
                timeOnCar: 2000,
                distanceOnCar: 26584,
                latitude: 55.568665,
                longitude: 38.143654,
                timeDistanceList: [{ transport: 'ON_CAR', time: 33, distance: 26584 }],
            },
            {
                id: '858742',
                name: 'Домодедово',
                timeOnCar: 2023,
                distanceOnCar: 35600,
                latitude: 55.41435,
                longitude: 37.90048,
                timeDistanceList: [{ transport: 'ON_CAR', time: 33, distance: 35600 }],
            },
            {
                id: '878042',
                name: 'Шереметьево',
                timeOnCar: 3112,
                distanceOnCar: 56638,
                latitude: 55.963852,
                longitude: 37.4169,
                timeDistanceList: [{ transport: 'ON_CAR', time: 51, distance: 56638 }],
            },
            {
                id: '878065',
                name: 'Внуково',
                timeOnCar: 3696,
                distanceOnCar: 50099,
                latitude: 55.604942,
                longitude: 37.282578,
                timeDistanceList: [{ transport: 'ON_CAR', time: 61, distance: 50099 }],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: 'f87c19',
                description: 'ниже среднего',
                level: 3,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: 'ffe424',
                description: 'достаточно развитая',
                level: 4,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: '128000',
                description: 'очень низкая',
                level: 9,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: '20a70a',
                description: 'очень низкая',
                level: 8,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: '20a70a',
                description: 'очень высокая',
                level: 8,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: 'f87c19',
                description: 'ниже среднего',
                level: 3,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '30ce12',
                description: 'высокая',
                level: 6,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        routeDistances: [{ geoPoint: { latitude: 55.65824, longitude: 37.83995 }, distance: 1722 }],
        subjectFederationName: 'Москва и МО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 1738,
                distance: 20903,
                latitude: 55.749893,
                longitude: 37.623425,
                timeDistanceList: [{ transport: 'ON_CAR', time: 28, distance: 20903 }],
            },
        ],
    },
    price: {
        currency: 'RUR',
        value: 340000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 10000,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 340000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 340000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 10000, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 340000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    floorsTotal: undefined,
    floorsOffered: undefined,
    livingSpace: undefined,
    kitchenSpace: undefined,
};

export const townhouseOffer = {
    ...houseOffer,
    house: { housePart: false, houseType: 'TOWNHOUSE' },
    location: {
        rgid: 190663,
        geoId: 225,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 190663,
        settlementGeoId: 117840,
        address: 'Одинцово, коттеджный поселок Довиль',
        geocoderAddress: 'Россия, М-1, новый выход на МКАД',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'М-1, новый выход на МКАД',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'М-1, новый выход на МКАД',
                    regionType: 'STREET',
                    queryParams: { rgid: '143', address: 'Россия, М-1, новый выход на МКАД' },
                },
            ],
        },
        point: { latitude: 55.65535, longitude: 37.246693, precision: 'EXACT' },
        metro: {
            metroGeoId: 218584,
            name: 'Одинцово',
            metroTransport: 'ON_TRANSPORT',
            timeToMetro: 18,
            latitude: 55.672474,
            longitude: 37.282784,
            minTimeToMetro: 18,
            lineColors: ['ed9f2d'],
            rgbColor: 'ed9f2d',
        },
        highway: { name: 'Можайское шоссе', distanceKm: 11.878 },
        station: { name: 'Отрадное', distanceKm: 1.404 },
        streetAddress: 'Одинцово, коттеджный поселок Довиль',
        metroList: [
            {
                metroGeoId: 218584,
                name: 'Одинцово',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 18,
                latitude: 55.672474,
                longitude: 37.282784,
                minTimeToMetro: 18,
                lineColors: ['ed9f2d'],
                rgbColor: 'ed9f2d',
            },
            {
                metroGeoId: 218562,
                name: 'Баковка',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 19,
                latitude: 55.682846,
                longitude: 37.315445,
                minTimeToMetro: 19,
                lineColors: ['ed9f2d'],
                rgbColor: 'ed9f2d',
            },
            {
                metroGeoId: 218545,
                name: 'Сколково',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 22,
                latitude: 55.700092,
                longitude: 37.34253,
                minTimeToMetro: 22,
                lineColors: ['ed9f2d'],
                rgbColor: 'ed9f2d',
            },
            {
                metroGeoId: 218555,
                name: 'Немчиновка',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 25,
                latitude: 55.715996,
                longitude: 37.375362,
                minTimeToMetro: 25,
                lineColors: ['ed9f2d'],
                rgbColor: 'ed9f2d',
            },
        ],
        allHeatmaps: [
            {
                name: 'carsharing',
                rgbColor: 'f87c19',
                description: 'низкая',
                level: 2,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        routeDistances: [
            {
                geoPoint: { latitude: 55.713425, longitude: 37.38563 },
                distance: 11878,
                highway: { id: '33', name: 'Можайское шоссе' },
            },
        ],
        subjectFederationName: 'Москва и МО',
    },
    village: { id: '1834189', name: 'Довиль', fullName: 'Клубный посёлок «Довиль»' },
};

export const parthouseOffer = {
    ...townhouseOffer,
    house: { housePart: true, houseType: 'PARTHOUSE' },
};

export const duplexOffer = {
    ...townhouseOffer,
    house: { housePart: false, houseType: 'DUPLEX' },
};

export const garageOffer = {
    ...baseOffer,
    offerCategory: OfferCategory.GARAGE,
    garage: { garageType: 'GARAGE', ownershipType: 'PRIVATE', garageName: 'РЕТРО-ФОНК' },
    house: { housePart: false },
    price: {
        currency: 'RUR',
        value: 2000000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 117647,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 2000000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 2000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 117647, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 2000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    building: {
        buildingType: 'FERROCONCRETE',
        improvements: { TWENTY_FOUR_SEVEN: true, SECURITY: true, CCTV: true },
        parkingType: 'OPEN',
        heatingType: 'UNKNOWN',
        buildingImprovementsMap: { TWENTY_FOUR_SEVEN: true, SECURITY: true, CCTV: true },
    },
    floorsTotal: undefined,
    floorsOffered: undefined,
    livingSpace: undefined,
    kitchenSpace: undefined,
};

export const parkingPlaceOffer = {
    ...garageOffer,
    garage: { garageType: 'PARKING_PLACE', ownershipType: 'UNKNOWN' },
    area: { value: 21, unit: 'SQUARE_METER' },
};

export const boxOffer = {
    ...garageOffer,
    garage: { garageType: 'BOX', ownershipType: 'PRIVATE' },
    area: undefined,
};

export const roomOffer = {
    ...baseOffer,
    offerCategory: OfferCategory.ROOMS,
    price: {
        currency: 'RUR',
        value: 3400000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 154545,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 3400000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 3400000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 154545, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 3400000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    building: {
        builtYear: 1914,
        buildingType: 'BRICK',
        buildingSeries: 'индивидуальный проект',
        buildingSeriesId: '1564812',
        improvements: { LIFT: true, RUBBISH_CHUTE: false, SECURITY: true },
        parkingType: 'OPEN',
        buildingId: '6403105572775699457',
        flatsCount: 120,
        porchesCount: 8,
        heatingType: 'CENTRAL',
        priceStatistics: {
            sellPricePerSquareMeter: {
                level: 0,
                maxLevel: 9,
                rgbColor: '',
                value: '0',
                regionValueFrom: '22727',
                regionValueTo: '2234148',
            },
        },
        buildingImprovementsMap: { LIFT: true, RUBBISH_CHUTE: false, SECURITY: true },
    },
    roomSpace: [{ value: 22, unit: 'SQUARE_METER' }],
    roomsOffered: 1,
    roomsTotal: 3,
};

export const lotOffer = {
    ...baseOffer,
    offerCategory: OfferCategory.LOT,
    building: { heatingType: 'UNKNOWN' },
    house: { housePart: false },
    price: {
        currency: 'RUR',
        value: 122800,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 20000,
        unitPerPart: 'ARE',
        valueForWhole: 122800,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 122800, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 20000, currency: 'RUB', priceType: 'PER_ARE', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 122800, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    area: { unit: 'ARE', value: 6.14 },
    lot: { lotArea: { unit: 'ARE', value: 6.14 }, lotType: 'IGS' },
    floorsTotal: undefined,
    floorsOffered: undefined,
    livingSpace: undefined,
    kitchenSpace: undefined,
};

export const lotOfferInKP = {
    ...lotOffer,
    lot: { lotArea: { unit: 'ARE', value: 82 } },
    location: {
        rgid: 192389,
        geoId: 159124,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 192389,
        settlementGeoId: 159124,
        address: 'Поздняково, коттеджный посёлок Никольская Слобода',
        geocoderAddress:
            'Россия, Московская область, городской округ Красногорск, коттеджный посёлок Никольская Слобода',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Московская',
                    geoId: 1,
                    regionGraphId: '587654',
                    address: 'Московская область',
                    regionType: 'SUBJECT_FEDERATION',
                    queryParams: { rgid: '587654', address: 'Россия, Московская область' },
                },
                {
                    value: 'Поздняково',
                    geoId: 159124,
                    regionGraphId: '781010',
                    address: 'Поздняково',
                    regionType: 'CITY',
                    queryParams: { rgid: '781010', address: 'Россия, Московская область, Поздняково' },
                },
                {
                    value: 'коттеджный посёлок Никольская Слобода',
                    geoId: 159124,
                    regionGraphId: '781010',
                    address: 'коттеджный посёлок Никольская Слобода',
                    regionType: 'CITY',
                    queryParams: {
                        rgid: '781010',
                        address: 'Россия, Московская область, Поздняково, коттеджный посёлок Никольская Слобода',
                    },
                },
            ],
        },
        point: { latitude: 55.79889, longitude: 37.224762, precision: 'EXACT' },
        metro: {
            metroGeoId: 218570,
            name: 'Павшино',
            metroTransport: 'ON_TRANSPORT',
            timeToMetro: 57,
            latitude: 55.815178,
            longitude: 37.341446,
            minTimeToMetro: 57,
            lineColors: ['df477c'],
            rgbColor: 'df477c',
        },
        highway: { name: 'Новорижское шоссе', distanceKm: 12.773 },
        station: { name: 'Опалиха', distanceKm: 3.048 },
        streetAddress: 'Красногорский район, коттеджный поселок Никольская Слобода',
        metroList: [
            {
                metroGeoId: 218570,
                name: 'Павшино',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 57,
                latitude: 55.815178,
                longitude: 37.341446,
                minTimeToMetro: 57,
                lineColors: ['df477c'],
                rgbColor: 'df477c',
            },
        ],
        routeDistances: [
            {
                geoPoint: { latitude: 55.789684, longitude: 37.37222 },
                distance: 12773,
                highway: { id: '20', name: 'Новорижское шоссе' },
            },
        ],
        subjectFederationName: 'Москва и МО',
    },
    village: { id: '1927150', name: 'Никольская Слобода', fullName: 'Коттеджный посёлок «Никольская Слобода»' },
};

export const rentOffer = {
    ...baseOffer,
    building: undefined,
    offerType: OfferType.RENT,
    price: {
        currency: 'RUR',
        value: 75555,
        period: 'PER_MONTH',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 635,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 75555,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 75555, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_MONTH' },
        pricePerPart: { value: 635, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'PER_MONTH' },
        priceForWhole: { value: 75555, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_MONTH' },
    },
};

export const perDayRentOffer = {
    ...rentOffer,
    price: {
        currency: 'RUR',
        value: 3500,
        period: 'PER_DAY',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 40,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 3500,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 3500, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_DAY' },
        pricePerPart: { value: 40, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'PER_DAY' },
        priceForWhole: { value: 3500, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_DAY' },
    },
};

export const offerWithPerMeterPrice = {
    ...baseOffer,
    price: {
        currency: 'RUR',
        value: 53571,
        period: 'WHOLE_LIFE',
        unit: 'SQUARE_METER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 53571,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 3000000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 53571, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 53571, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 3000000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
};

export const offerWithoutMetro = {
    ...baseOffer,
    location: {
        ...baseOffer.location,
        metro: undefined,
    },
    building: undefined,
};

export const offerWithStepToMetro = {
    ...baseOffer,
    location: {
        ...baseOffer.location,
        metro: {
            ...baseOffer.location.metro,
            timeToMetro: 20,
            metroTransport: TransportDistanceType.ON_FOOT,
        },
    },
    building: undefined,
};

export const offerFarFromMetro = {
    ...baseOffer,
    location: {
        ...baseOffer.location,
        metro: {
            ...baseOffer.location.metro,
            timeToMetro: 40,
            metroTransport: TransportDistanceType.ON_TRANSPORT,
        },
    },
    building: undefined,
};

export const baseCommercialOffer = {
    ...baseOffer,
    location: {
        rgid: 197177,
        geoId: 213,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587795,
        settlementGeoId: 213,
        address: 'Москва, Пресненская набережная, 8с1',
        geocoderAddress: 'Россия, Москва, Пресненская набережная, 8с1',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Москва',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Москва',
                    regionType: 'CITY',
                    queryParams: { rgid: '587795', address: 'Россия, Москва' },
                },
                {
                    value: 'Пресненская набережная',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Пресненская набережная',
                    regionType: 'STREET',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Пресненская набережная' },
                },
                {
                    value: '8с1',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: '8с1',
                    regionType: 'HOUSE',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, Пресненская набережная, 8с1' },
                },
            ],
        },
        point: { latitude: 55.747528, longitude: 37.538673, precision: 'EXACT' },
        metro: {
            metroGeoId: 115085,
            name: 'Деловой Центр',
            metroTransport: 'ON_FOOT',
            timeToMetro: 1,
            latitude: 55.74903,
            longitude: 37.539913,
            minTimeToMetro: 1,
            lineColors: ['6fc1ba'],
            rgbColor: '6fc1ba',
        },
        streetAddress: 'Пресненская набережная, 8с1',
        metroList: [
            {
                metroGeoId: 115085,
                name: 'Деловой Центр',
                metroTransport: 'ON_FOOT',
                timeToMetro: 1,
                latitude: 55.74903,
                longitude: 37.539913,
                minTimeToMetro: 1,
                lineColors: ['6fc1ba'],
                rgbColor: '6fc1ba',
            },
            {
                metroGeoId: 98560,
                name: 'Международная',
                metroTransport: 'ON_FOOT',
                timeToMetro: 3,
                latitude: 55.748314,
                longitude: 37.534264,
                minTimeToMetro: 3,
                lineColors: ['099dd4'],
                rgbColor: '099dd4',
            },
            {
                metroGeoId: 98559,
                name: 'Выставочная',
                metroTransport: 'ON_FOOT',
                timeToMetro: 6,
                latitude: 55.750076,
                longitude: 37.54139,
                minTimeToMetro: 6,
                lineColors: ['099dd4'],
                rgbColor: '099dd4',
            },
            {
                metroGeoId: 152947,
                name: 'Деловой Центр',
                metroTransport: 'ON_FOOT',
                timeToMetro: 7,
                latitude: 55.74709,
                longitude: 37.53209,
                minTimeToMetro: 7,
                lineColors: ['ffa8af'],
                rgbColor: 'ffa8af',
            },
            {
                metroGeoId: 218566,
                name: 'Тестовская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 15,
                latitude: 55.75415,
                longitude: 37.531693,
                minTimeToMetro: 15,
                lineColors: ['ed9f2d'],
                rgbColor: 'ed9f2d',
            },
            {
                metroGeoId: 152948,
                name: 'Шелепиха',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 8,
                latitude: 55.757122,
                longitude: 37.524075,
                minTimeToMetro: 8,
                lineColors: ['ffa8af', 'ffe400', '6fc1ba'],
                rgbColor: 'ffa8af',
            },
        ],
        parks: [
            {
                parkId: '121375314',
                name: 'Ботанический Первого Московского государственного медицинского университета имени И.М. Сеченова',
                timeOnFoot: 2711,
                distanceOnFoot: 3765,
                latitude: 55.746326,
                longitude: 37.531456,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 45, distance: 3765 }],
            },
        ],
        ponds: [
            {
                pondId: '137667589',
                name: 'река Москва',
                timeOnFoot: 120,
                distanceOnFoot: 233,
                latitude: 55.74529,
                longitude: 37.53913,
                timeDistanceList: [{ transport: 'ON_FOOT', time: 2, distance: 233 }],
            },
        ],
        airports: [
            {
                id: '878042',
                name: 'Шереметьево',
                timeOnCar: 2882,
                distanceOnCar: 36177,
                latitude: 55.963852,
                longitude: 37.4169,
                timeDistanceList: [{ transport: 'ON_CAR', time: 48, distance: 36177 }],
            },
            {
                id: '878065',
                name: 'Внуково',
                timeOnCar: 3040,
                distanceOnCar: 28915,
                latitude: 55.604942,
                longitude: 37.282578,
                timeDistanceList: [{ transport: 'ON_CAR', time: 50, distance: 28915 }],
            },
            {
                id: '858742',
                name: 'Домодедово',
                timeOnCar: 3167,
                distanceOnCar: 49358,
                latitude: 55.41435,
                longitude: 37.90048,
                timeDistanceList: [{ transport: 'ON_CAR', time: 52, distance: 49358 }],
            },
            {
                id: '878109',
                name: 'Жуковский (Раменское)',
                timeOnCar: 3496,
                distanceOnCar: 49453,
                latitude: 55.568665,
                longitude: 38.143654,
                timeDistanceList: [{ transport: 'ON_CAR', time: 58, distance: 49453 }],
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '128000',
                description: 'отличная',
                level: 8,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: '9ada1b',
                description: 'высокая доступность',
                level: 6,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '128000',
                description: 'отличная',
                level: 8,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: 'ee4613',
                description: 'очень высокая',
                level: 2,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'transport',
                rgbColor: '9ada1b',
                description: 'высокая доступность',
                level: 6,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: 'ffe424',
                description: 'выше средней',
                level: 4,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Москва и МО',
        cityCenter: [
            {
                transport: 'ON_CAR',
                time: 662,
                distance: 6991,
                latitude: 55.749058,
                longitude: 37.612267,
                timeDistanceList: [{ transport: 'ON_CAR', time: 11, distance: 6991 }],
            },
        ],
    },
    price: {
        currency: 'RUR',
        value: 124658448,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 663783,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 124658449,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 124658448, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 663783, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 124658449, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    building: {
        buildingState: 'HAND_OVER',
        improvements: { LIFT: true, ACCESS_CONTROL_SYSTEM: true, TWENTY_FOUR_SEVEN: true, SECURITY: true },
        parkingType: 'OPEN',
        siteId: 59066,
        siteName: 'Город Столиц',
        siteDisplayName: 'МФК «Город Столиц»',
        developerIds: [268706, 23314],
        officeClass: 'A_PLUS',
        houseId: '59086',
        heatingType: 'UNKNOWN',
        buildingImprovementsMap: { LIFT: true, ACCESS_CONTROL_SYSTEM: true, TWENTY_FOUR_SEVEN: true, SECURITY: true },
    },
    offerCategory: OfferCategory.COMMERCIAL,
};

export const commercialOfferOffice = {
    ...baseCommercialOffer,
    commercial: { commercialTypes: ['OFFICE'], commercialBuildingType: 'BUSINESS_CENTER' },
};

export const commercialOfferLand = {
    ...baseCommercialOffer,
    building: { parkingType: 'OPEN', heatingType: 'UNKNOWN' },
    price: {
        currency: 'RUR',
        value: 3400000,
        period: 'WHOLE_LIFE',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 1133333,
        unitPerPart: 'ARE',
        valueForWhole: 3400000,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 3400000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
        pricePerPart: { value: 1133333, currency: 'RUB', priceType: 'PER_ARE', pricingPeriod: 'WHOLE_LIFE' },
        priceForWhole: { value: 3400000, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'WHOLE_LIFE' },
    },
    location: {
        rgid: 193300,
        geoId: 213,
        subjectFederationId: 1,
        subjectFederationRgid: 741964,
        settlementRgid: 587795,
        settlementGeoId: 213,
        address: 'Москва, набережная Тараса Шевченко, 1',
        geocoderAddress: 'Россия, Москва, набережная Тараса Шевченко, 1',
        structuredAddress: {
            component: [
                {
                    value: 'Россия',
                    geoId: 225,
                    regionGraphId: '143',
                    address: 'Россия',
                    regionType: 'COUNTRY',
                    queryParams: { rgid: '143', address: 'Россия' },
                },
                {
                    value: 'Москва',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'Москва',
                    regionType: 'CITY',
                    queryParams: { rgid: '587795', address: 'Россия, Москва' },
                },
                {
                    value: 'набережная Тараса Шевченко',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: 'набережная Тараса Шевченко',
                    regionType: 'STREET',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, набережная Тараса Шевченко' },
                },
                {
                    value: '1',
                    geoId: 213,
                    regionGraphId: '587795',
                    address: '1',
                    regionType: 'HOUSE',
                    queryParams: { rgid: '587795', address: 'Россия, Москва, набережная Тараса Шевченко, 1' },
                },
            ],
        },
        point: { latitude: 55.746292, longitude: 37.57193, precision: 'EXACT' },
        metro: {
            metroGeoId: 20449,
            name: 'Киевская',
            metroTransport: 'ON_FOOT',
            timeToMetro: 6,
            latitude: 55.743927,
            longitude: 37.568108,
            minTimeToMetro: 6,
            lineColors: ['099dd4', '0042a5', '794835'],
            rgbColor: '099dd4',
        },
        streetAddress: 'набережная Тараса Шевченко, 1',
        metroList: [
            {
                metroGeoId: 20449,
                name: 'Киевская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 6,
                latitude: 55.743927,
                longitude: 37.568108,
                minTimeToMetro: 6,
                lineColors: ['099dd4', '0042a5', '794835'],
                rgbColor: '099dd4',
            },
            {
                metroGeoId: 20482,
                name: 'Смоленская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 13,
                latitude: 55.74876,
                longitude: 37.58217,
                minTimeToMetro: 11,
                lineColors: ['099dd4'],
                rgbColor: '099dd4',
            },
            {
                metroGeoId: 20495,
                name: 'Смоленская',
                metroTransport: 'ON_FOOT',
                timeToMetro: 14,
                latitude: 55.74775,
                longitude: 37.583836,
                minTimeToMetro: 11,
                lineColors: ['0042a5'],
                rgbColor: '0042a5',
            },
            {
                metroGeoId: 20461,
                name: 'Студенческая',
                metroTransport: 'ON_TRANSPORT',
                timeToMetro: 11,
                latitude: 55.738785,
                longitude: 37.548378,
                minTimeToMetro: 11,
                lineColors: ['099dd4'],
                rgbColor: '099dd4',
            },
        ],
        heatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'transport',
                rgbColor: '30ce12',
                description: 'высокая доступность',
                level: 7,
                maxLevel: 9,
                title: 'Транспорт',
            },
        ],
        allHeatmaps: [
            {
                name: 'infrastructure',
                rgbColor: '9ada1b',
                description: 'хорошо развитая',
                level: 5,
                maxLevel: 8,
                title: 'Инфраструктура',
            },
            {
                name: 'price-rent',
                rgbColor: 'f87c19',
                description: 'высокая',
                level: 3,
                maxLevel: 9,
                title: 'Цена аренды',
            },
            {
                name: 'price-sell',
                rgbColor: '620801',
                description: 'очень высокая',
                level: 1,
                maxLevel: 9,
                title: 'Цена продажи',
            },
            {
                name: 'profitability',
                rgbColor: 'ee4613',
                description: 'очень низкая',
                level: 2,
                maxLevel: 9,
                title: 'Прогноз окупаемости',
            },
            {
                name: 'transport',
                rgbColor: '30ce12',
                description: 'высокая доступность',
                level: 7,
                maxLevel: 9,
                title: 'Транспорт',
            },
            {
                name: 'carsharing',
                rgbColor: '30ce12',
                description: 'высокая',
                level: 6,
                maxLevel: 8,
                title: 'Доступность Яндекс.Драйва',
            },
        ],
        subjectFederationName: 'Москва и МО',
    },
    area: { unit: 'ARE', value: 3 },
    floorsTotal: undefined,
    floorsOffered: undefined,
    livingSpace: undefined,
    kitchenSpace: undefined,
    commercial: { commercialTypes: ['LAND'] },
};

export const commercialOfferManufacturing = {
    ...baseCommercialOffer,
    commercial: {
        commercialTypes: ['MANUFACTURING'],
        commercialBuildingType: 'BUSINESS_CENTER',
    },
};

export const commercialOfferRentOffice = {
    ...commercialOfferOffice,
    building: undefined,
    price: {
        currency: 'RUR',
        value: 330917,
        period: 'PER_MONTH',
        unit: 'WHOLE_OFFER',
        trend: 'UNCHANGED',
        hasPriceHistory: false,
        valuePerPart: 3167,
        unitPerPart: 'SQUARE_METER',
        valueForWhole: 330917,
        unitForWhole: 'WHOLE_OFFER',
        price: { value: 330917, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_MONTH' },
        pricePerPart: { value: 3167, currency: 'RUB', priceType: 'PER_METER', pricingPeriod: 'PER_MONTH' },
        priceForWhole: { value: 330917, currency: 'RUB', priceType: 'PER_OFFER', pricingPeriod: 'PER_MONTH' },
    },
    offerType: OfferType.RENT,
};

export const premiumOffer = {
    ...baseOffer,
    premium: true,
    vas: {
        ...baseOffer.vas,
        premium: true,
    },
};

export const profitOffer = {
    ...baseOffer,
    obsolete: false,
    predictions: {
        predictedPriceAdvice: {
            summary: 'LOW',
        },
    },
};

export const offerWithChat = {
    ...baseOffer,
    author: {
        ...baseOffer.author,
        allowedCommunicationChannels: ['COM_CHATS'],
    },
};

export const offerUserNote = {
    ...baseOffer,
    userNote: 'Хата огонь! Надо брать',
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const getNonCapitalOfferProps = (props: any) => ({
    ...props,
    item: {
        ...props.item,
        location: {
            address: 'Киров, ул. Украинская / ул. Чистопрудненская, д.5',
            airports: [],
            allHeatmaps: [],
            cityCenter: [],
            expectedMetroList: [],
            geoId: 46,
            heatmaps: [],
            parks: [
                {
                    distanceOnFoot: 376,
                    latitude: 58.57003,
                    longitude: 49.64284,
                    name: 'парк Молодёжный',
                    parkId: '3809656200',
                    timeDistanceList: [{ distance: 376, time: 4, transport: 'ON_FOOT' }],
                    timeOnFoot: 271,
                },
            ],
            point: {
                latitude: 58.56649,
                longitude: 49.64453,
                precision: 'EXACT',
            },
            ponds: [
                {
                    distanceOnFoot: 489,
                    latitude: 58.57069,
                    longitude: 49.643627,
                    name: 'река Мостовица',
                    pondId: '3389635825',
                    timeDistanceList: [{ distance: 489, time: 5, transport: 'ON_FOOT' }],
                    timeOnFoot: 352,
                },
            ],
            populatedRgid: 584260,
            rgid: 175563,
            schools: [],
            settlementGeoId: 46,
            settlementRgid: 584260,
            structuredAddress: {
                component: [
                    {
                        geoId: 225,
                        queryParams: { address: 'Россия', rgid: '143' },
                        regionType: 'COUNTRY',
                        rgid: '143',
                        value: 'Россия',
                        valueForAddress: 'Россия',
                    },
                    {
                        geoId: 11070,
                        queryParams: {
                            address: 'Россия, Кировская область',
                            rgid: '426967',
                        },
                        regionType: 'SUBJECT_FEDERATION',
                        rgid: '426967',
                        value: 'Кировская',
                        valueForAddress: 'Кировская область',
                    },
                    {
                        geoId: 120973,
                        queryParams: {
                            address: 'Россия, Кировская область, Киров (городской округ), Киров',
                            rgid: '584260',
                        },
                        regionType: 'SUBJECT_FEDERATION_DISTRICT',
                        rgid: '1712',
                        value: 'округ Киров',
                        valueForAddress: 'Киров (городской округ)',
                    },
                    {
                        geoId: 46,
                        queryParams: {
                            address: 'Россия, Кировская область, Киров (городской округ), Киров',
                            rgid: '584260',
                        },
                        regionType: 'CITY',
                        rgid: '584260',
                        value: 'Киров',
                        valueForAddress: 'Киров',
                    },
                    {
                        geoId: 46,
                        queryParams: {
                            address: 'Россия, Кировская область, Киров (городской округ), Киров, Мостовицкая улица',
                            rgid: '584260',
                            streetId: 29946,
                        },
                        regionType: 'STREET',
                        rgid: '584260',
                        value: 'Мостовицкая улица',
                        valueForAddress: 'Мостовицкая улица',
                    },
                    {
                        geoId: 46,
                        queryParams: {
                            address: 'Россия, Кировская область, Киров (городской округ), Киров, Мостовицкая улица, 5',
                            rgid: '584260',
                            streetId: 29946,
                        },
                        regionType: 'HOUSE',
                        rgid: '584260',
                        value: '5',
                        valueForAddress: '5',
                    },
                ],
                unifiedOneline: '',
            },
            subjectFederationId: 11070,
            subjectFederationName: 'Кировская',
            subjectFederationRgid: 426967,
        },
    },
});
