INSERT INTO {transport_p_out} (ft_id, ft_type_name, disp_class, isocode, line_type_name, uri,
  basic_icon, composite_icon, icon_line, icon_line_exit, icon_network, icon_network_exit, icon_network_line, icon_network_line_exit,
  network, line, vehicle_types, is_closed,
  name, name_lo, name_iata, p_name, composite_name, subscript,
  geom,
  tags) VALUES

-- bus stops
(1543306266, 'transport-bus-stop', 9, 'RU', NULL, NULL,
  ['bus'], ['bus'], NULL, NULL, NULL, NULL, NULL, NULL,
  '', '', [], false,
  json('{"ru_RU_LOCAL": "Шоссе Революции"}'), 'Шоссе Революции', NULL, NULL, NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(30.415876 59.958731)', 4326), 3395),
  ['transit','transit_location','transit_stop','is_unclassified_transit','bus_stop']),

(1543308889, 'transport-bus-stop', 5, 'RU', NULL, 'ymapsbm1://transit/stop?id=stop__10076602',
  ['bus'], ['bus'], NULL, NULL, NULL, NULL, NULL, NULL,
  '', '', ['bus'], false,
  json('{"ru_RU_LOCAL": "Улица Ломоносова"}'), 'Улица Ломоносова', NULL, NULL, NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(30.329796 59.931657)', 4326), 3395),
  ['transit','transit_location','transit_stop','bus_stop']),

(1746412235, 'transport-bus-stop', 5, 'RU', NULL, 'ymapsbm1://transit/stop?id=stop__10189898',
  ['tram'], ['tram'], NULL, NULL, NULL, NULL, NULL, NULL,
  '', '', ['tramway'], false,
  json('{"ru_RU_LOCAL": "Апраксин двор"}'), 'Апраксин двор', NULL, NULL, NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(30.328860 59.931335)', 4326), 3395),
  ['transit','transit_location','transit_stop','bus_stop']),

(2472242090, 'transport-bus-stop', 5, 'RU', NULL, 'ymapsbm1://transit/stop?id=stop__10075347',
  ['bus'], ['bus.tram','bus'], NULL, NULL, NULL, NULL, NULL, NULL,
  '', '', ['bus','tramway'], false,
  json('{"ru_RU_LOCAL": "Станция метро Сенная площадь"}'), 'Станция метро Сенная площадь', NULL, NULL, NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(30.320857 59.927940)', 4326), 3395),
  ['transit','transit_location','transit_stop','bus_stop']),

-- metro stations and stops
(100079104, 'transport-metro-station', 2, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858831',
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-7', 'moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-5', ['underground'],false,
  json('{"ru_RU_LOCAL":"Краснопресненская"}'), 'метро Краснопресненская', NULL, json('{"ru_RU_LOCAL":"Кольцевая линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.577218 55.760213)', 4326), 3395),
  ['transit','transit_location']),

(100079108, 'transport-metro-station', 2, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858783',
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-5','moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-7', ['underground'], false,
  json('{"ru_RU_LOCAL":"Баррикадная"}'), 'метро Баррикадная', NULL, json('{"ru_RU_LOCAL":"Таганско-Краснопресненская линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.581283 55.760819)', 4326), 3395),
  ['transit','transit_location']),

(100079120, 'transport-metro-station', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858918',
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-2', ['underground'], false,
  json('{"ru_RU_LOCAL":"Тверская"}'), 'метро Тверская', NULL, json('{"ru_RU_LOCAL":"Замоскворецкая линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.605945 55.764458)', 4326), 3395),
  ['transit','transit_location']),

(100079132, 'transport-metro-station', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858894',
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2','moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-7', ['underground'], false,
  json('{"ru_RU_LOCAL":"Пушкинская"}'), 'метро Пушкинская', NULL, json('{"ru_RU_LOCAL":"Таганско-Краснопресненская линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.603901 55.765751)', 4326), 3395),
  ['transit','transit_location']),

(100079180, 'transport-metro-station', 2, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858787',
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-2','moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-5', ['underground'], false,
  json('{"ru_RU_LOCAL":"Белорусская"}'), 'метро Белорусская', NULL, json('{"ru_RU_LOCAL":"Кольцевая линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.585256 55.776775)', 4326), 3395),
  ['transit','transit_location']),

(100079184, 'transport-metro-station', 2, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=station__9858786',
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  NULL,
  ['moscow_metro','metro'],
  NULL,
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  NULL,
  'moscow_metro', 'moscow_metro-2', ['underground'], false,
  json('{"ru_RU_LOCAL":"Белорусская"}'), 'метро Белорусская', NULL, json('{"ru_RU_LOCAL":"Замоскворецкая линия"}'), NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.582211 55.777391)', 4326), 3395),
  ['transit','transit_location']),

(100128479, 'transport-metro-exit', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=exit__22769',
  ['metro'],
  ['moscow_metro.moscow_metro-5.moscow_metro-7.exit_yellow_1','moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro-5.exit_yellow_1','moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-5.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-5', ['underground'], false,
  json('{"ru_RU_LOCAL":"Краснопресненская\\nвход 1"}'), '1', NULL, json('{"ru_RU_LOCAL":"Краснопресненская"}'), json('{"ru_RU_LOCAL":"Краснопресненская\\nБаррикадная"}'), json('{"ru_RU_LOCAL":"вход 1"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.576948 55.760380)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

(100128483, 'transport-metro-exit', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=exit__22622',
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-5.exit_yellow_2','moscow_metro.moscow_metro-7.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_2','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_2','moscow_metro.exit_yellow_2','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-7', ['underground'], false,
  json('{"ru_RU_LOCAL":"Баррикадная\\nвход 2"}'), '2', NULL, json('{"ru_RU_LOCAL":"Баррикадная"}'), json('{"ru_RU_LOCAL":"Баррикадная\\nКраснопресненская"}'), json('{"ru_RU_LOCAL":"вход 2"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.581509 55.760692)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

(100128491, 'transport-metro-exit', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=exit__22997',
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-7.exit_yellow_9','moscow_metro.moscow_metro-2.exit_yellow_9','moscow_metro.exit_yellow_9','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_9','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_9','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_9','moscow_metro.exit_yellow_9','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-2', ['underground'], false,
  json('{"ru_RU_LOCAL":"Тверская\\nвход 9"}'), '9', NULL, json('{"ru_RU_LOCAL":"Тверская"}'), json('{"ru_RU_LOCAL":"Тверская\\nПушкинская"}'), json('{"ru_RU_LOCAL":"вход 9"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.605685 55.764341)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

(100128539, 'transport-metro-exit', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=exit__22942',
  ['metro'],
  ['moscow_metro.moscow_metro-7.moscow_metro-2.exit_yellow_1','moscow_metro.moscow_metro-7.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro-7.exit_yellow_1','moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_1','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-7.exit_yellow_1','moscow_metro.exit_yellow_1','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-7', ['underground'], false,
  json('{"ru_RU_LOCAL":"Пушкинская\\nвход 1"}'), '1', NULL, json('{"ru_RU_LOCAL":"Пушкинская"}'), json('{"ru_RU_LOCAL":"Пушкинская\\nТверская"}'), json('{"ru_RU_LOCAL":"вход 1"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.604296 55.765978)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

(100128615, 'transport-metro-exit', 5, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=exit__22628',
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5','moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-2', ['underground'], false,
  json('{"ru_RU_LOCAL":"Белорусская\\nвход"}'), NULL, NULL, json('{"ru_RU_LOCAL":"Белорусская"}'), json('{"ru_RU_LOCAL":"Белорусская"}'), json('{"ru_RU_LOCAL":"вход"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.582192 55.777263)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

(3402688745, 'transport-metro-exit', 9, 'RU', 'transport-metro-line', 'ymapsbm1://transit/stop?id=3402688745',
  ['metro'],
  ['moscow_metro.moscow_metro-2.moscow_metro-5.exit_yellow_4','moscow_metro.moscow_metro-2.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro-2.exit_yellow_4','moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro','metro'],
  ['moscow_metro.exit_yellow_4','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2','moscow_metro','metro'],
  ['moscow_metro.moscow_metro-2.exit_yellow_4','moscow_metro.exit_yellow_4','moscow_metro','metro'],
  'moscow_metro', 'moscow_metro-2', ['underground'], false,
  json('{"ru_RU_LOCAL":"Белорусская\\nвыход 4"}'), '4', NULL, json('{"ru_RU_LOCAL":"Белорусская"}'), json('{"ru_RU_LOCAL":"Белорусская"}'), json('{"ru_RU_LOCAL":"выход 4"}'),
  Spatial::Transform(Spatial::GeomFromText('POINT(37.582279 55.777428)', 4326), 3395),
  ['transit','transit_location','transit_entrance']),

-- airport
(1519988663, 'transport-airport', 5, 'RU', NULL, 'ymapsbm1://org?oid=45745811341',
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  '', '', [], false,
  NULL, NULL, NULL, NULL, NULL, NULL,
  Spatial::Transform(Spatial::GeomFromText('POINT(37.900487 55.414349)', 4326), 3395),
  ['transit','transit_location','is_unclassified_transit']);
