import { NewOrderT, RouteT } from 'generate-data';

export const get14Order = (routeId: number): NewOrderT => ({
  address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
  amount: 100,
  customer_name: 'Bowser',
  lat: 60,
  lon: 31,
  number: '14',
  payment_type: 'cash',
  phone: '+70000000000',
  route_id: routeId,
  time_interval: '12:00 - 18:00',
});

export default function (route: Pick<RouteT, 'id'>): Array<NewOrderT> {
  return [
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '13',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '14',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '15',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '16',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '17',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
    {
      address: 'Россия, Санкт-Пеетербург, Пискаревский проспект, 2к2',
      amount: 100,
      customer_name: 'Bowser',
      lat: 60,
      lon: 31,
      number: '18',
      payment_type: 'cash',
      phone: '+70000000000',
      route_id: route.id,
      time_interval: '12:00 - 18:00',
    },
  ];
}
