#!/usr/bin/env bash

source /etc/yandex/yb-ar/env
exec env Y_PYTHON_ENTRY_POINT=billing.agency_rewards.src.agency_rewards.cashback.bin.main:client_testing \
    LOGGING_FILE="/var/log/yb/cashback-testing.log" \
    /usr/bin/yb-ar-cashback "$@"
