resolved_hosts = {
    '100404032': {
        'abc_prj': 'srertc',
        'dc': 'sas',
        'fqdn': 'sas5-0961.search.yandex.net',
        'hw_owners': ['sivanichkin', 'antivabo'],
        'inv': '100404032',
        'rack': '8',
        'service_owners': [],
        'switch': 'sas1-s788',
        'w_prj': 'rtc-mtn',
        'w_prj_owners': ['dldmitry',
                         'efmv',
                         'max7255',
                         'moridin',
                         'nekto0n',
                         'olegsenin',
                         'talion',
                         '@svc_rtcsupport',
                         '@svc_srertc_administration',
                         '@svc_srertc_devops'],
        'w_prj_tags': ['rtc',
                       'rtc.automation-enabled',
                       'rtc.gencfg-reserve',
                       'rtc.gpu-none',
                       'rtc.reboot_segment-gencfg',
                       'rtc.scheduler-gencfg',
                       'rtc.stage-production',
                       'rtc_network',
                       'runtime',
                       'search',
                       'skynet_installed',
                       'yasm_monitored']},
    '100404033': {'abc_prj': 'srertc',
                   'dc': 'sas',
                   'fqdn': 'sas5-4419.search.yandex.net',
                   'hw_owners': ['sivanichkin', 'antivabo'],
                   'inv': '100404033',
                   'rack': '24',
                   'service_owners': [],
                   'switch': 'sas1-s795',
                   'w_prj': 'rtc-mtn',
                   'w_prj_owners': ['dldmitry',
                                    'efmv',
                                    'max7255',
                                    'moridin',
                                    'nekto0n',
                                    'olegsenin',
                                    'talion',
                                    '@svc_rtcsupport',
                                    '@svc_srertc_administration',
                                    '@svc_srertc_devops'],
                   'w_prj_tags': ['rtc',
                                  'rtc.automation-enabled',
                                  'rtc.gencfg-reserve',
                                  'rtc.gpu-none',
                                  'rtc.reboot_segment-gencfg',
                                  'rtc.scheduler-gencfg',
                                  'rtc.stage-production',
                                  'rtc_network',
                                  'runtime',
                                  'search',
                                  'skynet_installed',
                                  'yasm_monitored']},
    '100404034': {'abc_prj': 'srertc',
                  'dc': 'sas',
                  'fqdn': 'sas5-4422.search.yandex.net',
                  'hw_owners': ['sivanichkin', 'antivabo'],
                  'inv': '100404034',
                  'rack': '9',
                  'service_owners': [],
                  'switch': 'sas1-s789',
                  'w_prj': 'rtc-mtn',
                  'w_prj_owners': ['dldmitry',
                                   'efmv',
                                   'max7255',
                                   'moridin',
                                   'nekto0n',
                                   'olegsenin',
                                   'talion',
                                   '@svc_rtcsupport',
                                   '@svc_srertc_administration',
                                   '@svc_srertc_devops'],
                  'w_prj_tags': ['rtc',
                                 'rtc.automation-enabled',
                                 'rtc.gencfg-reserve',
                                 'rtc.gpu-none',
                                 'rtc.reboot_segment-gencfg',
                                 'rtc.scheduler-gencfg',
                                 'rtc.stage-production',
                                 'rtc_network',
                                 'runtime',
                                 'search',
                                 'skynet_installed',
                                 'yasm_monitored']},
    'sas5-0961.search.yandex.net': {'abc_prj': 'srertc',
                                    'dc': 'sas',
                                    'fqdn': 'sas5-0961.search.yandex.net',
                                    'hw_owners': ['sivanichkin', 'antivabo'],
                                    'inv': '100404032',
                                    'rack': '8',
                                    'service_owners': [],
                                    'switch': 'sas1-s788',
                                    'w_prj': 'rtc-mtn',
                                    'w_prj_owners': ['dldmitry',
                                                     'efmv',
                                                     'max7255',
                                                     'moridin',
                                                     'nekto0n',
                                                     'olegsenin',
                                                     'talion',
                                                     '@svc_rtcsupport',
                                                     '@svc_srertc_administration',
                                                     '@svc_srertc_devops'],
                                    'w_prj_tags': ['rtc',
                                                   'rtc.automation-enabled',
                                                   'rtc.gencfg-reserve',
                                                   'rtc.gpu-none',
                                                   'rtc.reboot_segment-gencfg',
                                                   'rtc.scheduler-gencfg',
                                                   'rtc.stage-production',
                                                   'rtc_network',
                                                   'runtime',
                                                   'search',
                                                   'skynet_installed',
                                                   'yasm_monitored']},
    'sas5-4419.search.yandex.net': {'abc_prj': 'srertc',
                                    'dc': 'sas',
                                    'fqdn': 'sas5-4419.search.yandex.net',
                                    'hw_owners': ['sivanichkin', 'antivabo'],
                                    'inv': '100404033',
                                    'rack': '24',
                                    'service_owners': [],
                                    'switch': 'sas1-s795',
                                    'w_prj': 'rtc-mtn',
                                    'w_prj_owners': ['dldmitry',
                                                     'efmv',
                                                     'max7255',
                                                     'moridin',
                                                     'nekto0n',
                                                     'olegsenin',
                                                     'talion',
                                                     '@svc_rtcsupport',
                                                     '@svc_srertc_administration',
                                                     '@svc_srertc_devops'],
                                    'w_prj_tags': ['rtc',
                                                   'rtc.automation-enabled',
                                                   'rtc.gencfg-reserve',
                                                   'rtc.gpu-none',
                                                   'rtc.reboot_segment-gencfg',
                                                   'rtc.scheduler-gencfg',
                                                   'rtc.stage-production',
                                                   'rtc_network',
                                                   'runtime',
                                                   'search',
                                                   'skynet_installed',
                                                   'yasm_monitored']},
    'sas5-4422.search.yandex.net': {'abc_prj': 'srertc',
                                    'dc': 'sas',
                                    'fqdn': 'sas5-4422.search.yandex.net',
                                    'hw_owners': ['sivanichkin', 'antivabo'],
                                    'inv': '100404034',
                                    'rack': '9',
                                    'service_owners': [],
                                    'switch': 'sas1-s789',
                                    'w_prj': 'rtc-mtn',
                                    'w_prj_owners': ['dldmitry',
                                                     'efmv',
                                                     'max7255',
                                                     'moridin',
                                                     'nekto0n',
                                                     'olegsenin',
                                                     'talion',
                                                     '@svc_rtcsupport',
                                                     '@svc_srertc_administration',
                                                     '@svc_srertc_devops'],
                                    'w_prj_tags': ['rtc',
                                                   'rtc.automation-enabled',
                                                   'rtc.gencfg-reserve',
                                                   'rtc.gpu-none',
                                                   'rtc.reboot_segment-gencfg',
                                                   'rtc.scheduler-gencfg',
                                                   'rtc.stage-production',
                                                   'rtc_network',
                                                   'runtime',
                                                   'search',
                                                   'skynet_installed',
                                                   'yasm_monitored']},
    "vla2-1523.search.yandex.net": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283388",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1523.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "101283432": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283432",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1734.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "vla2-1734.search.yandex.net": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283432",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1734.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "101283448": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283448",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1950.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "vla2-2011.search.yandex.net": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101287675",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s25",
        "fqdn": "vla2-2011.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A07",
        "service_owners": []
    },
    "vla2-1610.search.yandex.net": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283408",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s24",
        "fqdn": "vla2-1610.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A06",
        "service_owners": []
    },
    "101287675": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101287675",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s25",
        "fqdn": "vla2-2011.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A07",
        "service_owners": []
    },
    "101283388": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283388",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1523.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "vla2-1950.search.yandex.net": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283448",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s31",
        "fqdn": "vla2-1950.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A09",
        "service_owners": []
    },
    "101283408": {
        "w_prj_owners": [
            "dldmitry",
            "efmv",
            "max7255",
            "moridin",
            "nekto0n",
            "olegsenin",
            "talion",
            "@svc_rtcsupport",
            "@svc_srertc_administration",
            "@svc_srertc_devops"
        ],
        "hw_owners": [
            "sivanichkin",
            "antivabo"
        ],
        "inv": "101283408",
        "abc_prj": "srertc",
        "dc": "vla",
        "w_prj_tags": [
            "rtc",
            "rtc.automation-enabled",
            "rtc.gencfg-reserve",
            "rtc.gpu-none",
            "rtc.reboot_segment-gencfg",
            "rtc.scheduler-gencfg",
            "rtc.stage-production",
            "rtc_network",
            "runtime",
            "search",
            "skynet_installed",
            "yasm_monitored"
        ],
        "switch": "vla2-7s24",
        "fqdn": "vla2-1610.search.yandex.net",
        "w_prj": "rtc-mtn",
        "rack": "7A06",
        "service_owners": []
    }
}
