# -*- coding: utf-8 -*-


bot_inv_notfound = '{"res":2,"msg":"not found","os":[]}'

bot_inv_msg = '{"res":2,"msg":"ololo","os":[]}'

bot_inv_100415867 = '''{
  "res": 1,
  "os": [
    {
      "instance_number": "100415867",
      "item_segment3": "NODES",
      "status_name": "OPERATION",
      "item_segment2": "XEONE5-2650V2",
      "item_segment1": "AIC/1SHV2608/DPSB0406/8xT3.5/1U/N"
    }
  ]
}'''


bot_inv_fields = '''{
  "res": 1,
  "os": [
    {
      "XXCSI_FQDN": "sas4-6617.search.yandex.net",
      "GROUP_OWNED": "YT в RTC",
      "loc_object": "SAS",
      "instance_number": "100415867",
      "loc_segment5": "4A1"
    }
  ]
}'''

bot_preorder = '''
{
    "id": 8570,
    "created_at": "2019-10-22T19:24:51+0300",
    "created_by": "robot-di-bot-prod",
    "is_deleted": false,
    "status_updated_at": "2019-10-22T19:24:51+0300",
    "current_version": {
        "id": 17985,
        "is_deleted": false,
        "is_current": true,
        "status_id": 3,
        "status_code": "approved",
        "status_display": "В закупке",
        "last_approval_name": "budget",
        "next_approval_name": null,
        "created_at": "2020-03-13T18:28:54+0300",
        "created_by": "ssudakov",
        "ticket_id": "DISPENSERREQ-3358",
        "handed_over": false,
        "big_order_config": {
            "id": 231,
            "full_name": "2020.04 (VLA, real, new)",
            "created_at": "2020-03-13T17:33:27+0300",
            "created_by": "eukho",
            "updated_at": "2020-06-02T11:03:47+0300",
            "updated_by": "ssudakov",
            "opened_at": "2020-03-13T17:33:00+0300",
            "closed_at": "2020-06-14T00:00:00+0300",
            "active": false,
            "archived": false,
            "type_id": 3,
            "type_code": "real",
            "type_display": "real",
            "units_quantity": null,
            "big_order": {
                "id": 39,
                "created_at": "2019-07-29T14:44:39+0300",
                "created_by": "keyd",
                "updated_at": null,
                "updated_by": null,
                "name": "2020.04",
                "description": null,
                "expected_give_out_at": "2020-04-30"
            },
            "location": {
                "id": 10,
                "created_at": "2016-11-14T00:00:00+0300",
                "created_by": "robot-bot-prod",
                "updated_at": null,
                "updated_by": null,
                "name": "VLA"
            },
            "description": null,
            "category_code": "new",
            "category_display": "new"
        },
        "server": {
            "id": 2962,
            "unique_id": 5536,
            "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
            "type_id": 1,
            "type_code": "server",
            "type_display": "server",
            "created_at": "2019-09-01T00:03:10+0300",
            "created_by": "andozer",
            "updated_at": null,
            "updated_by": null,
            "enabled": true,
            "recommended": false,
            "description": null
        },
        "servers_quantity": 36,
        "storage": null,
        "storages_quantity": null,
        "rams_quantity": 0,
        "drives_quantity": 0,
        "description": null,
        "customer_comment": "seneca-vla",
        "desired_at": null,
        "walle_project": null,
        "oebs_service": {
            "id": 100000227,
            "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
            "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
            "number": 37,
            "planner_id": 470,
            "start_date_active": "2014-02-24T00:00:00+0400",
            "end_date_active": null,
            "ru_description": "YT",
            "ru_long_description": null,
            "us_description": "YT",
            "us_long_description": null,
            "is_hr": true,
            "parent": {
                "id": 100002032,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                "number": 1842,
                "planner_id": 1182,
                "start_date_active": "2016-01-13T00:00:00+0300",
                "end_date_active": null,
                "ru_description": "Системы хранения и обработки данных",
                "ru_long_description": null,
                "us_description": "Системы хранения и обработки данных",
                "us_long_description": null,
                "is_hr": false,
                "parent": {
                    "id": 100000670,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                    "full_us_name": "Search Portal - Common Tech Services",
                    "number": 480,
                    "planner_id": 850,
                    "start_date_active": "2015-09-28T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Сервисы управления общих технологий",
                    "ru_long_description": null,
                    "us_description": "Common Tech Services",
                    "us_long_description": null,
                    "is_hr": true,
                    "parent": {
                        "id": 100000551,
                        "full_ru_name": "Сервисы Поискового портала",
                        "full_us_name": "Search Portal",
                        "number": 361,
                        "planner_id": 851,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы Поискового портала",
                        "ru_long_description": null,
                        "us_description": "Search Portal",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": null
                    }
                }
            }
        },
        "itdc_issue_id": null,
        "responsible": "robot-di-bot-prod",
        "components": []
    },
    "versions": [
        {
            "id": 15389,
            "is_deleted": false,
            "is_current": false,
            "status_id": 2,
            "status_code": "commited",
            "status_display": "Ждет подтверждения",
            "last_approval_name": null,
            "next_approval_name": "initial_check",
            "created_at": "2019-10-22T19:24:51+0300",
            "created_by": "robot-di-bot-prod",
            "ticket_id": "DISPENSERREQ-3358",
            "handed_over": false,
            "big_order_config": {
                "id": 186,
                "full_name": "2020.11 (VLA, forecast, new)",
                "created_at": "2019-07-29T14:47:24+0300",
                "created_by": "keyd",
                "updated_at": "2020-03-03T10:11:19+0300",
                "updated_by": "keyd",
                "opened_at": "2020-02-17T00:00:00+0300",
                "closed_at": "2020-03-03T23:59:00+0300",
                "active": true,
                "archived": false,
                "type_id": 2,
                "type_code": "forecast",
                "type_display": "forecast",
                "units_quantity": null,
                "big_order": {
                    "id": 41,
                    "created_at": "2019-07-29T14:45:22+0300",
                    "created_by": "keyd",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "2020.11",
                    "description": null,
                    "expected_give_out_at": "2020-11-30"
                },
                "location": {
                    "id": 10,
                    "created_at": "2016-11-14T00:00:00+0300",
                    "created_by": "robot-bot-prod",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "VLA"
                },
                "description": null,
                "category_code": "new",
                "category_display": "new"
            },
            "server": {
                "id": 2962,
                "unique_id": 5536,
                "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
                "type_id": 1,
                "type_code": "server",
                "type_display": "server",
                "created_at": "2019-09-01T00:03:10+0300",
                "created_by": "andozer",
                "updated_at": null,
                "updated_by": null,
                "enabled": true,
                "recommended": false,
                "description": null
            },
            "servers_quantity": 36,
            "storage": null,
            "storages_quantity": null,
            "rams_quantity": null,
            "drives_quantity": null,
            "description": null,
            "customer_comment": "seneca-vla",
            "desired_at": null,
            "walle_project": null,
            "oebs_service": {
                "id": 100000227,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
                "number": 37,
                "planner_id": 470,
                "start_date_active": "2014-02-24T00:00:00+0400",
                "end_date_active": null,
                "ru_description": "YT",
                "ru_long_description": null,
                "us_description": "YT",
                "us_long_description": null,
                "is_hr": true,
                "parent": {
                    "id": 100002032,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                    "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                    "number": 1842,
                    "planner_id": 1182,
                    "start_date_active": "2016-01-13T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Системы хранения и обработки данных",
                    "ru_long_description": null,
                    "us_description": "Системы хранения и обработки данных",
                    "us_long_description": null,
                    "is_hr": false,
                    "parent": {
                        "id": 100000670,
                        "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                        "full_us_name": "Search Portal - Common Tech Services",
                        "number": 480,
                        "planner_id": 850,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы управления общих технологий",
                        "ru_long_description": null,
                        "us_description": "Common Tech Services",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": {
                            "id": 100000551,
                            "full_ru_name": "Сервисы Поискового портала",
                            "full_us_name": "Search Portal",
                            "number": 361,
                            "planner_id": 851,
                            "start_date_active": "2015-09-28T00:00:00+0300",
                            "end_date_active": null,
                            "ru_description": "Сервисы Поискового портала",
                            "ru_long_description": null,
                            "us_description": "Search Portal",
                            "us_long_description": null,
                            "is_hr": true,
                            "parent": null
                        }
                    }
                }
            },
            "itdc_issue_id": null,
            "responsible": "robot-di-bot-prod",
            "components": []
        },
        {
            "id": 15993,
            "is_deleted": false,
            "is_current": false,
            "status_id": 2,
            "status_code": "commited",
            "status_display": "Ждет подтверждения",
            "last_approval_name": null,
            "next_approval_name": "initial_check",
            "created_at": "2019-11-27T18:03:20+0300",
            "created_by": "keyd",
            "ticket_id": "DISPENSERREQ-3358",
            "handed_over": false,
            "big_order_config": {
                "id": 182,
                "full_name": "2020.04 (VLA, forecast, new)",
                "created_at": "2019-07-29T14:46:35+0300",
                "created_by": "keyd",
                "updated_at": "2020-01-23T13:29:01+0300",
                "updated_by": "keyd",
                "opened_at": "2019-07-29T14:46:00+0300",
                "closed_at": "2019-08-31T23:00:00+0300",
                "active": false,
                "archived": false,
                "type_id": 2,
                "type_code": "forecast",
                "type_display": "forecast",
                "units_quantity": null,
                "big_order": {
                    "id": 39,
                    "created_at": "2019-07-29T14:44:39+0300",
                    "created_by": "keyd",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "2020.04",
                    "description": null,
                    "expected_give_out_at": "2020-04-30"
                },
                "location": {
                    "id": 10,
                    "created_at": "2016-11-14T00:00:00+0300",
                    "created_by": "robot-bot-prod",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "VLA"
                },
                "description": null,
                "category_code": "new",
                "category_display": "new"
            },
            "server": {
                "id": 2962,
                "unique_id": 5536,
                "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
                "type_id": 1,
                "type_code": "server",
                "type_display": "server",
                "created_at": "2019-09-01T00:03:10+0300",
                "created_by": "andozer",
                "updated_at": null,
                "updated_by": null,
                "enabled": true,
                "recommended": false,
                "description": null
            },
            "servers_quantity": 36,
            "storage": null,
            "storages_quantity": null,
            "rams_quantity": null,
            "drives_quantity": null,
            "description": null,
            "customer_comment": "seneca-vla",
            "desired_at": null,
            "walle_project": null,
            "oebs_service": {
                "id": 100000227,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
                "number": 37,
                "planner_id": 470,
                "start_date_active": "2014-02-24T00:00:00+0400",
                "end_date_active": null,
                "ru_description": "YT",
                "ru_long_description": null,
                "us_description": "YT",
                "us_long_description": null,
                "is_hr": true,
                "parent": {
                    "id": 100002032,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                    "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                    "number": 1842,
                    "planner_id": 1182,
                    "start_date_active": "2016-01-13T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Системы хранения и обработки данных",
                    "ru_long_description": null,
                    "us_description": "Системы хранения и обработки данных",
                    "us_long_description": null,
                    "is_hr": false,
                    "parent": {
                        "id": 100000670,
                        "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                        "full_us_name": "Search Portal - Common Tech Services",
                        "number": 480,
                        "planner_id": 850,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы управления общих технологий",
                        "ru_long_description": null,
                        "us_description": "Common Tech Services",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": {
                            "id": 100000551,
                            "full_ru_name": "Сервисы Поискового портала",
                            "full_us_name": "Search Portal",
                            "number": 361,
                            "planner_id": 851,
                            "start_date_active": "2015-09-28T00:00:00+0300",
                            "end_date_active": null,
                            "ru_description": "Сервисы Поискового портала",
                            "ru_long_description": null,
                            "us_description": "Search Portal",
                            "us_long_description": null,
                            "is_hr": true,
                            "parent": null
                        }
                    }
                }
            },
            "itdc_issue_id": null,
            "responsible": "robot-di-bot-prod",
            "components": []
        },
        {
            "id": 16812,
            "is_deleted": false,
            "is_current": false,
            "status_id": 2,
            "status_code": "commited",
            "status_display": "Ждет подтверждения",
            "last_approval_name": null,
            "next_approval_name": "initial_check",
            "created_at": "2019-12-10T18:49:19+0300",
            "created_by": "keyd",
            "ticket_id": "DISPENSERREQ-3358",
            "handed_over": false,
            "big_order_config": {
                "id": 182,
                "full_name": "2020.04 (VLA, forecast, new)",
                "created_at": "2019-07-29T14:46:35+0300",
                "created_by": "keyd",
                "updated_at": "2020-01-23T13:29:01+0300",
                "updated_by": "keyd",
                "opened_at": "2019-07-29T14:46:00+0300",
                "closed_at": "2019-08-31T23:00:00+0300",
                "active": false,
                "archived": false,
                "type_id": 2,
                "type_code": "forecast",
                "type_display": "forecast",
                "units_quantity": null,
                "big_order": {
                    "id": 39,
                    "created_at": "2019-07-29T14:44:39+0300",
                    "created_by": "keyd",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "2020.04",
                    "description": null,
                    "expected_give_out_at": "2020-04-30"
                },
                "location": {
                    "id": 10,
                    "created_at": "2016-11-14T00:00:00+0300",
                    "created_by": "robot-bot-prod",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "VLA"
                },
                "description": null,
                "category_code": "new",
                "category_display": "new"
            },
            "server": {
                "id": 2962,
                "unique_id": 5536,
                "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
                "type_id": 1,
                "type_code": "server",
                "type_display": "server",
                "created_at": "2019-09-01T00:03:10+0300",
                "created_by": "andozer",
                "updated_at": null,
                "updated_by": null,
                "enabled": true,
                "recommended": false,
                "description": null
            },
            "servers_quantity": 36,
            "storage": null,
            "storages_quantity": null,
            "rams_quantity": null,
            "drives_quantity": null,
            "description": null,
            "customer_comment": "seneca-vla",
            "desired_at": null,
            "walle_project": null,
            "oebs_service": {
                "id": 100000227,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
                "number": 37,
                "planner_id": 470,
                "start_date_active": "2014-02-24T00:00:00+0400",
                "end_date_active": null,
                "ru_description": "YT",
                "ru_long_description": null,
                "us_description": "YT",
                "us_long_description": null,
                "is_hr": true,
                "parent": {
                    "id": 100002032,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                    "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                    "number": 1842,
                    "planner_id": 1182,
                    "start_date_active": "2016-01-13T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Системы хранения и обработки данных",
                    "ru_long_description": null,
                    "us_description": "Системы хранения и обработки данных",
                    "us_long_description": null,
                    "is_hr": false,
                    "parent": {
                        "id": 100000670,
                        "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                        "full_us_name": "Search Portal - Common Tech Services",
                        "number": 480,
                        "planner_id": 850,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы управления общих технологий",
                        "ru_long_description": null,
                        "us_description": "Common Tech Services",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": {
                            "id": 100000551,
                            "full_ru_name": "Сервисы Поискового портала",
                            "full_us_name": "Search Portal",
                            "number": 361,
                            "planner_id": 851,
                            "start_date_active": "2015-09-28T00:00:00+0300",
                            "end_date_active": null,
                            "ru_description": "Сервисы Поискового портала",
                            "ru_long_description": null,
                            "us_description": "Search Portal",
                            "us_long_description": null,
                            "is_hr": true,
                            "parent": null
                        }
                    }
                }
            },
            "itdc_issue_id": null,
            "responsible": "robot-di-bot-prod",
            "components": []
        },
        {
            "id": 16813,
            "is_deleted": false,
            "is_current": false,
            "status_id": 3,
            "status_code": "approved",
            "status_display": "В бюджете",
            "last_approval_name": "budget",
            "next_approval_name": null,
            "created_at": "2019-12-10T18:49:19+0300",
            "created_by": "keyd",
            "ticket_id": "DISPENSERREQ-3358",
            "handed_over": false,
            "big_order_config": {
                "id": 182,
                "full_name": "2020.04 (VLA, forecast, new)",
                "created_at": "2019-07-29T14:46:35+0300",
                "created_by": "keyd",
                "updated_at": "2020-01-23T13:29:01+0300",
                "updated_by": "keyd",
                "opened_at": "2019-07-29T14:46:00+0300",
                "closed_at": "2019-08-31T23:00:00+0300",
                "active": false,
                "archived": false,
                "type_id": 2,
                "type_code": "forecast",
                "type_display": "forecast",
                "units_quantity": null,
                "big_order": {
                    "id": 39,
                    "created_at": "2019-07-29T14:44:39+0300",
                    "created_by": "keyd",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "2020.04",
                    "description": null,
                    "expected_give_out_at": "2020-04-30"
                },
                "location": {
                    "id": 10,
                    "created_at": "2016-11-14T00:00:00+0300",
                    "created_by": "robot-bot-prod",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "VLA"
                },
                "description": null,
                "category_code": "new",
                "category_display": "new"
            },
            "server": {
                "id": 2962,
                "unique_id": 5536,
                "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
                "type_id": 1,
                "type_code": "server",
                "type_display": "server",
                "created_at": "2019-09-01T00:03:10+0300",
                "created_by": "andozer",
                "updated_at": null,
                "updated_by": null,
                "enabled": true,
                "recommended": false,
                "description": null
            },
            "servers_quantity": 36,
            "storage": null,
            "storages_quantity": null,
            "rams_quantity": null,
            "drives_quantity": null,
            "description": null,
            "customer_comment": "seneca-vla",
            "desired_at": null,
            "walle_project": null,
            "oebs_service": {
                "id": 100000227,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
                "number": 37,
                "planner_id": 470,
                "start_date_active": "2014-02-24T00:00:00+0400",
                "end_date_active": null,
                "ru_description": "YT",
                "ru_long_description": null,
                "us_description": "YT",
                "us_long_description": null,
                "is_hr": true,
                "parent": {
                    "id": 100002032,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                    "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                    "number": 1842,
                    "planner_id": 1182,
                    "start_date_active": "2016-01-13T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Системы хранения и обработки данных",
                    "ru_long_description": null,
                    "us_description": "Системы хранения и обработки данных",
                    "us_long_description": null,
                    "is_hr": false,
                    "parent": {
                        "id": 100000670,
                        "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                        "full_us_name": "Search Portal - Common Tech Services",
                        "number": 480,
                        "planner_id": 850,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы управления общих технологий",
                        "ru_long_description": null,
                        "us_description": "Common Tech Services",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": {
                            "id": 100000551,
                            "full_ru_name": "Сервисы Поискового портала",
                            "full_us_name": "Search Portal",
                            "number": 361,
                            "planner_id": 851,
                            "start_date_active": "2015-09-28T00:00:00+0300",
                            "end_date_active": null,
                            "ru_description": "Сервисы Поискового портала",
                            "ru_long_description": null,
                            "us_description": "Search Portal",
                            "us_long_description": null,
                            "is_hr": true,
                            "parent": null
                        }
                    }
                }
            },
            "itdc_issue_id": null,
            "responsible": "robot-di-bot-prod",
            "components": []
        },
        {
            "id": 17985,
            "is_deleted": false,
            "is_current": true,
            "status_id": 3,
            "status_code": "approved",
            "status_display": "В закупке",
            "last_approval_name": "budget",
            "next_approval_name": null,
            "created_at": "2020-03-13T18:28:54+0300",
            "created_by": "ssudakov",
            "ticket_id": "DISPENSERREQ-3358",
            "handed_over": false,
            "big_order_config": {
                "id": 231,
                "full_name": "2020.04 (VLA, real, new)",
                "created_at": "2020-03-13T17:33:27+0300",
                "created_by": "eukho",
                "updated_at": "2020-06-02T11:03:47+0300",
                "updated_by": "ssudakov",
                "opened_at": "2020-03-13T17:33:00+0300",
                "closed_at": "2020-06-14T00:00:00+0300",
                "active": false,
                "archived": false,
                "type_id": 3,
                "type_code": "real",
                "type_display": "real",
                "units_quantity": null,
                "big_order": {
                    "id": 39,
                    "created_at": "2019-07-29T14:44:39+0300",
                    "created_by": "keyd",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "2020.04",
                    "description": null,
                    "expected_give_out_at": "2020-04-30"
                },
                "location": {
                    "id": 10,
                    "created_at": "2016-11-14T00:00:00+0300",
                    "created_by": "robot-bot-prod",
                    "updated_at": null,
                    "updated_by": null,
                    "name": "VLA"
                },
                "description": null,
                "category_code": "new",
                "category_display": "new"
            },
            "server": {
                "id": 2962,
                "unique_id": 5536,
                "full_name": "Node 3.0 / 2 × Intel Xeon 6230 / 512 GB RAM / 4 × 14 TB HDD + 4 × 3.2 TB NVMe / 25G",
                "type_id": 1,
                "type_code": "server",
                "type_display": "server",
                "created_at": "2019-09-01T00:03:10+0300",
                "created_by": "andozer",
                "updated_at": null,
                "updated_by": null,
                "enabled": true,
                "recommended": false,
                "description": null
            },
            "servers_quantity": 36,
            "storage": null,
            "storages_quantity": null,
            "rams_quantity": 0,
            "drives_quantity": 0,
            "description": null,
            "customer_comment": "seneca-vla",
            "desired_at": null,
            "walle_project": null,
            "oebs_service": {
                "id": 100000227,
                "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных - YT",
                "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных - YT",
                "number": 37,
                "planner_id": 470,
                "start_date_active": "2014-02-24T00:00:00+0400",
                "end_date_active": null,
                "ru_description": "YT",
                "ru_long_description": null,
                "us_description": "YT",
                "us_long_description": null,
                "is_hr": true,
                "parent": {
                    "id": 100002032,
                    "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий - Системы хранения и обработки данных",
                    "full_us_name": "Search Portal - Common Tech Services - Системы хранения и обработки данных",
                    "number": 1842,
                    "planner_id": 1182,
                    "start_date_active": "2016-01-13T00:00:00+0300",
                    "end_date_active": null,
                    "ru_description": "Системы хранения и обработки данных",
                    "ru_long_description": null,
                    "us_description": "Системы хранения и обработки данных",
                    "us_long_description": null,
                    "is_hr": false,
                    "parent": {
                        "id": 100000670,
                        "full_ru_name": "Сервисы Поискового портала - Сервисы управления общих технологий",
                        "full_us_name": "Search Portal - Common Tech Services",
                        "number": 480,
                        "planner_id": 850,
                        "start_date_active": "2015-09-28T00:00:00+0300",
                        "end_date_active": null,
                        "ru_description": "Сервисы управления общих технологий",
                        "ru_long_description": null,
                        "us_description": "Common Tech Services",
                        "us_long_description": null,
                        "is_hr": true,
                        "parent": {
                            "id": 100000551,
                            "full_ru_name": "Сервисы Поискового портала",
                            "full_us_name": "Search Portal",
                            "number": 361,
                            "planner_id": 851,
                            "start_date_active": "2015-09-28T00:00:00+0300",
                            "end_date_active": null,
                            "ru_description": "Сервисы Поискового портала",
                            "ru_long_description": null,
                            "us_description": "Search Portal",
                            "us_long_description": null,
                            "is_hr": true,
                            "parent": null
                        }
                    }
                }
            },
            "itdc_issue_id": null,
            "responsible": "robot-di-bot-prod",
            "components": []
        }
    ],
    "approvals": [
        {
            "id": "6a291c09-e19d-4943-9c74-33136886c21a",
            "name": "initial_check",
            "description": "Обоснование необходимости",
            "approvers": [
                "keyd",
                "aa-blokhin"
            ],
            "order": 1,
            "status": "approved",
            "status_updated_at": "2019-12-10T18:49:19+0300",
            "status_updated_by": "keyd"
        },
        {
            "id": "1897ba3a-fd62-471a-ab8f-f32044a12b0e",
            "name": "budget",
            "description": "Бюджет",
            "approvers": [
                "keyd",
                "aa-blokhin"
            ],
            "order": 2,
            "status": "approved",
            "status_updated_at": "2019-12-10T18:49:19+0300",
            "status_updated_by": "keyd"
        }
    ]
}
'''
