#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
no_color='\033[0m'

maps_branch_prefix='MAPSMOBILETEST'
newbie_branch_prefix='GEOTESTSITE'

current_branch="$(arc branch -q | grep '^\*\s.*')"
current_branch="${current_branch:2}"

hint="Используйте параметр ${green}--no-verify${no_color}, чтобы игнорировать эту проверку\n"

if [[ $current_branch != $maps_branch_prefix* ]] &&
   [[ $current_branch != $newbie_branch_prefix* ]]
then
	>&2 echo -e "\n${red} НЕКОРРЕКТНОЕ ИМЯ ЛОКАЛЬНОЙ ВЕТКИ ${no_color}\n"
	>&2 echo -e " Текущая: ${red}${current_branch} ${no_color}"
	>&2 echo -e " Разрешенные:"
	>&2 echo -e "\t${green}${maps_branch_prefix}-XXXX ${no_color}"
	>&2 echo -e "\t${green}${newbie_branch_prefix}-XXXX ${no_color}"
	>&2 echo -e "\n${hint}"
	exit 1
fi

exit 0
