{
  "receipt_content": {
    "tax_calc_method": "total",
    "agent_type": "none_agent",
    "client_email_or_phone": "firm1@yandex-team.ru",
    "firm_inn": "${firm.inn}",
    "firm_reply_email": "firm1@yandex-team.ru",
    "firm_url": "string",
    "additional_document_requisite": "string",
    "additional_user_requisite": {
      "name": "trust_id",
      "value": "06e62000-9cc1-436c-a6db-d64469fa3ab4"
    },
    "payments": [
      {
        "amount": "100",
        "payment_type": "card"
      }
    ],
    "receipt_type": "income",
    "rows": [
      {
        "payment_type_type": "full_payment_w_delivery",
        "price": "10",
        "qty": "10",
        "tax_type": "nds_20",
        "item_code": "${item_code}",
        "text": "string 666 "
      }
    ],
    "supplier_phone": "+766699944",
    "taxation_type": "OSN"
  }
}
