TAG(sb:~intel_e5645)

DISABLE_DATA_VALIDATION(
    sbr://2644393366  # CATALOGIA_DSSM_MODEL  # AUTO UPDATED RESOURCE
    sbr://2400832148  # ADV_MACHINE_ENTITY_EXTRACTOR_DATA  # AUTO UPDATED RESOURCE
)

DATA(
    sbr://2622935504  # BIGB_BUZZARD_TESTDATA  # AUTO UPDATED RESOURCE
    sbr://1150327925  # BIGB_CODECS_FOLDER  # AUTO UPDATED RESOURCE
    sbr://2621157988  # BS_YETI_SOVETNIK_DICT  # AUTO UPDATED RESOURCE
    sbr://2644393366  # CATALOGIA_DSSM_MODEL  # AUTO UPDATED RESOURCE

    sbr://3358317045  # BS_YETI_HEAVY_BASES  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2622930990  # BS_YETI_LIGHT_CONFIGS  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE
    sbr://2620413911  # BIGB_COUNTERS_IDF_BASE  # AUTO UPDATED RESOURCE  # AUTO UPDATED RESOURCE

    sbr://3281562127=bigb-bases-buzzard-daily  # BIGB_BASES buzzard_daily  # AUTO UPDATED RESOURCE
    sbr://3281371746=bigb-bases-buzzard-hourly  # BIGB_BASES buzzard_hourly  # AUTO UPDATED RESOURCE
    sbr://3281337808=bigb-bases-buzzard-every-10-minutes  # BIGB_BASES buzzard_every_10_minutes  # AUTO UPDATED RESOURCE
    sbr://3281312287=bigb-bases-common-daily  # BIGB_BASES common_daily  # AUTO UPDATED RESOURCE
    sbr://3281308281=bigb-bases-common-every-10-minutes  # BIGB_BASES common_every_10_minutes  # AUTO UPDATED RESOURCE

    sbr://2622299310  # BIGB_GEO_PERMALINK_DICT  # AUTO UPDATED RESOURCE

    sbr://179396120=used_lm_features  # USED_LM_FEATURES_BINARY_BASE  # AUTO UPDATED RESOURCE
    sbr://2622100197=robots  # YACONTEXT_ROBOTSTXT_DB_YANDEXBOT  # AUTO UPDATED RESOURCE
    sbr://2464721771=tragic  # YACONTEXT_TRAGIC_PHRASES  # AUTO UPDATED RESOURCE
    sbr://2622680656  # BS_YETI_MOBILE_APPS_BASE  # AUTO UPDATED RESOURCE
    sbr://2400832148  # ADV_MACHINE_ENTITY_EXTRACTOR_DATA  # AUTO UPDATED RESOURCE
    sbr://1767052644=incremental_dssm
    sbr://2415717987=context_dssm

    arcadia/dj/unity/projects/answers/redir_log_actions/redir_log_to_actions_bigrt_config.pbtxt
    arcadia/dj/unity/projects/market/front_events_to_actions_bigrt_config.pbtxt
    arcadia/dj/unity/projects/market/pers_history_to_actions_bigrt_config.pbtxt
)
