export const fixtures = {
    'Get tag transformer Возвращает трансформированный тег': {
        TAG_ATTRIBUTES: {
            urlPart: 'conceptcar',
            service: 'autoru',
            title: 'Концепты',
            draftTitle: 'Концепты (draft)',
            shortTitle: 'Концепты (short)',
            draftShortTitle: 'Концепты (short, draft)',
            metaDescription: 'meta description',
            metaTitle: 'meta title',
            blocks: [],
            draftBlocks: [],
            isHot: true,
            isPartnership: true,
            isArchived: true,
            partnershipImage: {
                meta: {
                    md5: '6213b6099b9bf4228b97c854d2ec2351',
                    crc64: 'F96D8F4793579ABE',
                    'orig-size': { x: 355, y: 49 },
                    processing: 'finished',
                    'orig-format': 'PNG',
                    'orig-animated': false,
                    'orig-size-bytes': 4706,
                    'orig-orientation': '0',
                    'modification-time': 1620739106,
                    processed_by_computer_vision: false,
                    processed_by_computer_vision_description: 'computer vision is disabled',
                },
                sizes: {
                    orig: {
                        path: '/get-vertis-journal/4220003/24-valo2h.png_1620739106397/orig',
                        width: 355,
                        height: 49,
                    },
                    '320х320': {
                        path: '/get-vertis-journal/4220003/24-valo2h.png_1620739106397/320х320',
                        width: 320,
                        height: 44,
                    },
                    '460х460': {
                        path: '/get-vertis-journal/4220003/24-valo2h.png_1620739106397/460х460',
                        width: 355,
                        height: 49,
                    },
                    optimize: {
                        path: '/get-vertis-journal/4220003/24-valo2h.png_1620739106397/optimize',
                        width: 355,
                        height: 49,
                    },
                    '1200х1200': {
                        path: '/get-vertis-journal/4220003/24-valo2h.png_1620739106397/1200х1200',
                        width: 355,
                        height: 49,
                    },
                },
                'group-id': 4220003,
                imagename: '24-valo2h.png_1620739106397',
            },
            partnershipLink: 'https://partnership-link.com',
            partnershipName: 'Партнер',
            partnershipBadgeName: 'Бейдж партнера',
            mmm: 'BMW,3ER',
            createdAt: '2021-06-03T16:26:11.000Z',
            lastEditedAt: '2021-06-03T16:26:11.000Z',
        },
    },
    'Get tag transformer Может возвращать трансформированный черновик тега': {
        TAG_ATTRIBUTES: {
            urlPart: 'conceptcar',
            service: 'autoru',
            title: 'Концепты',
            draftTitle: 'Концепты (draft)',
            shortTitle: 'Концепты (short)',
            draftShortTitle: 'Концепты (short, draft)',
            metaDescription: 'meta description',
            metaTitle: 'meta title',
            blocks: [],
            draftBlocks: [],
            isHot: true,
            isPartnership: true,
            isArchived: true,
            partnershipImage: null,
            partnershipLink: 'https://partnership-link.com',
            partnershipName: 'Партнер',
            partnershipBadgeName: 'Бейдж партнера',
            mmm: 'BMW,3ER',
            createdAt: '2021-06-03T16:26:11.000Z',
            lastEditedAt: '2021-06-03T16:26:11.000Z',
        },
    },
    'Get tag transformer Может возвращать тег с трансформированными блоками': {
        TAG_ATTRIBUTES: {
            urlPart: 'conceptcar',
            service: 'autoru',
            title: 'Концепты',
            draftTitle: 'Концепты (draft)',
            shortTitle: 'Концепты (short)',
            draftShortTitle: 'Концепты (short, draft)',
            metaDescription: 'meta description',
            metaTitle: 'meta title',
            blocks: [{ type: 'text', text: 'raw block' }],
            draftBlocks: [{ type: 'text', text: 'raw draft block' }],
            isHot: true,
            isPartnership: true,
            isArchived: true,
            partnershipImage: null,
            partnershipLink: 'https://partnership-link.com',
            partnershipName: 'Партнер',
            partnershipBadgeName: 'Бейдж партнера',
            mmm: 'BMW,3ER',
            createdAt: '2021-06-03T16:26:11.000Z',
            lastEditedAt: '2021-06-03T16:26:11.000Z',
        },
    },
    'Get tag transformer Может возвращает тег с трансформированными черновыми блоками': {
        TAG_ATTRIBUTES: {
            urlPart: 'conceptcar',
            service: 'autoru',
            title: 'Концепты',
            draftTitle: 'Концепты (draft)',
            shortTitle: 'Концепты (short)',
            draftShortTitle: 'Концепты (short, draft)',
            metaDescription: 'meta description',
            metaTitle: 'meta title',
            blocks: [{ type: 'text', text: 'raw block' }],
            draftBlocks: [{ type: 'text', text: 'raw draft block' }],
            isHot: true,
            isPartnership: true,
            isArchived: true,
            partnershipImage: null,
            partnershipLink: 'https://partnership-link.com',
            partnershipName: 'Партнер',
            partnershipBadgeName: 'Бейдж партнера',
            mmm: 'BMW,3ER',
            createdAt: '2021-06-03T16:26:11.000Z',
            lastEditedAt: '2021-06-03T16:26:11.000Z',
        },
    },
};
