DEPENDS(
    ads/quality/adv_machine/cm/tables_tool
    ads/quality/adv_machine/cm_robot/robot_bins
    ads/quality/adv_machine/tools/mr_utils
    ads/quality/adv_machine/cm
    ads/quality/adv_machine/mr_index
)

DATA(
    arcadia/ads/quality/adv_machine/cm
    arcadia/ads/quality/adv_machine/cm_robot/robot_bins
    arcadia/ads/quality/adv_machine/cm/tables_tool/am_cm_tables
    arcadia/ads/quality/adv_machine/cm/tables_tool/tables.json
    arcadia/ads/quality/adv_machine/config
    arcadia/ads/quality/adv_machine/config/indexer
    arcadia/ads/quality/adv_machine/mr_index/am_mr_index
    sbr://2934138772 # tables_sample
    sbr://1222678963 # small dump (tsar_difacto_models/robdrynkin_bsdev_75076_prod_v3)
    sbr://1335916818=./turbo_shop_id_2_counter_id
    sbr://1866196071 # BroadPhraseNorm.dict
)
