INSERT INTO {entrance_out} (priority, isocode, name, name_long, subscript, bld_ft_type_name, geom, tags) VALUES
(1,
 'RU',
 json('{"ru":"1","en":"1"}'),
 json('{"ru":"подъезд №\u00A01","en": "entrance 1"}'),
 json('{"ru":"кв. 1A–5A, 6–10, 11–55", "en":"apt. 1A–5A, 6–10, 11–55"}'),
 'urban-residential',
 Spatial::GeomFromText("POINT (0 5)", 3395),
 ['structure', 'building', 'entrance']),
(2,
 'RU',
 json('{"ru":"2","en":"2"}'),
 json('{"ru":"подъезд №\u00A02","en":"entrance 2"}'),
 json('{"ru":"кв. 1A", "en":"apt. 1A"}'),
 'urban-residential',
 Spatial::GeomFromText("POINT (5 0)", 3395),
 ['structure', 'building', 'entrance']),
(3,
 'RU',
 json('{"ru":"3","en":"3"}'),
 json('{"ru":"подъезд №\u00A03","en":"entrance 3"}'),
 json('{"ru":"кв. 1B","en":"apt. 1B"}'),
 'urban-residential',
 Spatial::GeomFromText("POINT (10.5 0)", 3395),
 ['structure', 'building', 'entrance']),
(4,
 'RU',
 json('{"ru":"4","en":"4"}'),
 json('{"ru":"подъезд №\u00A04","en":"entrance 4"}'),
 NULL,
 'urban-residential',
 Spatial::GeomFromText("POINT (15 15)", 3395),
 ['structure', 'building', 'entrance']),
(5,
 'RU',
 NULL,
 json('{"ru":" ","en":" "}'),
 NULL,
 'urban-residential',
 Spatial::GeomFromText("POINT (15 15)", 3395),
 ['structure', 'building', 'entrance']),
(6,
 'RU',
 json('{"ru":"6","en":"6"}'),
 json('{"ru":"6","en":"6"}'),
 NULL,
 'urban-industrial',
 Spatial::GeomFromText("POINT (25 25)", 3395),
 ['structure', 'building', 'entrance']),
(7,
 'RU',
 json('{"ru":"7","en":"7"}'),
 json('{"ru":"7","en":"7"}'),
 NULL,
 NULL,
 Spatial::GeomFromText("POINT (50 50)", 3395),
 ['structure', 'building', 'entrance']),
(8,
 'RU',
 json('{"ru":"8","en":"8"}'),
 json('{"ru":"подъезд №\u00A08","en":"entrance 8"}'),
 NULL,
 'urban-residential',
 Spatial::GeomFromText("POINT (35 35)", 3395),
 ['structure', 'building', 'entrance']),
(9,
 'RU',
 json('{"ru":"9","en":"9"}'),
 json('{"ru":"подъезд №\u00A09","en":"entrance 9"}'),
 NULL,
 'urban-residential',
 Spatial::GeomFromText("POINT (35 35)", 3395),
 ['structure', 'building', 'entrance']);
