#!/bin/sh -e

OPTIONS="pkgs.repo pkgs.cache main.repo"

CMD=$1; shift || usage

VALUES=""
if [ "$CMD" = "from_file" ]; then
    FILE=$1
    for option_name in $OPTIONS; do
        option=`git config --file "$FILE" $option_name` || die "There no option $optioname in file $FILE"
        VALUES="$VALUES $option"
    done
elif [ "$CMD" = "manual" ]; then
    VALUES=$*
fi

set -- $VALUES
git config pkgs.repo "$1"
git config pkgs.cache "$2"
git config main.repo "$3"
