// Code generated by mockery v2.9.3. DO NOT EDIT.

package mocks

import (
	staff "github.com/YandexClassifieds/h2p/common/staff"
	mock "github.com/stretchr/testify/mock"
)

// IStaff is an autogenerated mock type for the IStaff type
type IStaff struct {
	mock.Mock
}

// CheckLogin provides a mock function with given fields: login
func (_m *IStaff) CheckLogin(login string) error {
	ret := _m.Called(login)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGroupId provides a mock function with given fields: groupUrl
func (_m *IStaff) GetGroupId(groupUrl string) (string, error) {
	ret := _m.Called(groupUrl)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(groupUrl)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupUrl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKeys provides a mock function with given fields: login
func (_m *IStaff) GetKeys(login string) ([]staff.Key, error) {
	ret := _m.Called(login)

	var r0 []staff.Key
	if rf, ok := ret.Get(0).(func(string) []staff.Key); ok {
		r0 = rf(login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]staff.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
