import datetime
from collections import defaultdict

data_crm_api = {
    'welcome': [
        {
            "id": 410315,
            "role": "welcome",
            "location": "hd_msk",
            "author": "nslus",
            "application": "нужен usb otg",
            "resolution": "заказываю на складе",
            "dateOpen": 1556032866,
            "dateClose": 'null',
            "owner": "waltz",
            "status": "CLOSE",
            "type": "consumption"
        },
        {
            "id": 410317,
            "role": "welcome",
            "location": "hd_msk",
            "author": "pavelgur",
            "application": "Вздулся аккумулятор",
            "resolution": "Замена тушки",
            "dateOpen": 1556033290,
            "dateClose": 1556033739,
            "owner": "sing1etone",
            "status": "CLOSE",
            "type": "help"
        },
        {
            "id": 410333,
            "role": "welcome",
            "location": "hd_msk",
            "author": "dmitriydragan",
            "application": "за докой",
            "resolution": "выдал",
            "dateOpen": 1556035019,
            "dateClose": 'null',
            "owner": "waltz",
            "status": "CLOSE",
            "type": "consumption"
        },
        {
            "id": 410341,
            "role": "welcome",
            "location": "hd_msk",
            "author": "nbatyukova",
            "application": "Ноут не выходит изсна",
            "resolution": "замена тушки",
            "dateOpen": 1556035955,
            "dateClose": 1556039762,
            "owner": "sing1etone",
            "status": "CLOSE",
            "type": "help"
        },
        {
            "id": 410348,
            "role": "welcome",
            "location": "hd_avrora",
            "author": "bryancev",
            "application": "Принять заявление на оплату ремонта",
            "resolution": "Принял",
            "dateOpen": 1556036994,
            "dateClose": 1556037179,
            "owner": "maxim-shanti",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410381,
            "role": "welcome",
            "location": "hd_msk",
            "author": "zienag",
            "application": "Возврат",
            "resolution": "Принял 101398891",
            "dateOpen": 1556040647,
            "dateClose": 1556040969,
            "owner": "sing1etone",
            "status": "CLOSE",
            "type": "take"
        }
    ],
    'st': [
        {
            "id": 130609,
            "role": "st",
            "location": "hd_msk",
            "author": "swan",
            "application": "reset pw",
            "resolution": "reset",
            "dateOpen": 1476443752,
            "dateClose": 'null',
            "owner": "orange13",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 130631,
            "role": "st",
            "location": "hd_msk",
            "author": "robot-bot-prod",
            "application": "Нужно сбросить пароль",
            "resolution": "настройка завершена",
            "dateOpen": 1476447045,
            "dateClose": 'null',
            "owner": "horus",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 130641,
            "role": "st",
            "location": "hd_msk",
            "author": "eye",
            "application": "-",
            "resolution": "-",
            "dateOpen": 1476449582,
            "dateClose": 'null',
            "owner": "eye",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 130674,
            "role": "st",
            "location": "hd_msk",
            "author": "rudeshko",
            "application": "Оторвать лицензию",
            "resolution": "доне",
            "dateOpen": 1476456166,
            "dateClose": 'null',
            "owner": "spellanser",
            "status": "CLOSE",
            "type": 'null'
        }
    ],
    'income': [
        {
            "id": 410316,
            "role": "income",
            "location": "hd_msk",
            "author": "gibzer",
            "application": "Закончился картридж в 420 принтере Аврова 10 этаж",
            "resolution": "создал тикет",
            "dateOpen": 1556032979,
            "dateClose": 1556033060,
            "owner": "denisyurkin",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410319,
            "role": "income",
            "location": "hd_msk",
            "author": "perova",
            "application": "Переустановка КриптоПро",
            "resolution": "Отписался в связном тикете",
            "dateOpen": 1556033820,
            "dateClose": 1556034178,
            "owner": "denisyurkin",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410334,
            "role": "income",
            "location": "hd_msk",
            "author": "dchusov",
            "application": "apitomtsev@: у меня в Outlook было две учетки, но одну я случайно удалил. как ее вернуть и почему их две?",
            "resolution": "рассказал в общих чертах об imap и exchange. Настроить учетную запись и ознакомится с различиями можно по инструкции https://wiki.yandex-team.ru/diy/Windows/Mail/ \r\nУправлять своими почтовыми рассылками можно тут https://ml.yandex-team.ru/",
            "dateOpen": 1556035046,
            "dateClose": 'null',
            "owner": "waltz",
            "status": "CLOSE",
            "type": 'null'
        }
    ],
    'tlg': [
        {
            "id": 410180,
            "role": "tlg",
            "location": 'null',
            "author": "mkurepov",
            "application": "ну у меня есть токен. Настроить его просто?; Здравствуйте! Недавно я запрашивал сброс пароля к почте. Сейчас мне пришла смс о том, что пароль сброшен, но как теперь зайти в почту всё ещё непонятно",
            "resolution": "Да, по https://download.yandex.ru/wiki/EXT/winopenvpnrutocken.htm",
            "dateOpen": 1556024080,
            "dateClose": 1556035173,
            "owner": "shimchenko",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410186,
            "role": "tlg",
            "location": 'null',
            "author": "ninaost86",
            "application": "Не могу установить токен на мак",
            "resolution": "Статус заявки: необходимо обновить macOS до последней версии Mojave. После этого проверить в Настройках безопасности что Yandex LLC можно разблокировать и повторить попытку подключения через бета-версию Tunnelblick (соединить Yandex на значке Tunnelblick в меню)",
            "dateOpen": 1556024472,
            "dateClose": 1556038159,
            "owner": "shimchenko",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410332,
            "role": "tlg",
            "location": 'null',
            "author": "hatter",
            "application": "На лестнице что-то прошили и кажется надо помыть. Лестница между 4-5 этажами Аврора корпус а; *пролили",
            "resolution": "Передам коллегам в supply",
            "dateOpen": 1556034948,
            "dateClose": 1556036582,
            "owner": "fn-555",
            "status": "CLOSE",
            "type": 'null'
        },
        {
            "id": 410340,
            "role": "tlg",
            "location": 'null',
            "author": "yanadem",
            "application": "всё в порядке. спасибо большое!",
            "resolution": "Ок, прошу ещё раз прощение за задержку.",
            "dateOpen": 1556035955,
            "dateClose": 1556036524,
            "owner": "fn-555",
            "status": "CLOSE",
            "type": 'null'
        }
    ]
}

data_stat_crm_api = [
    (
        'welcome',
        'h',
        [defaultdict(int, {'all': 3, 'hd_msk': 3, 'consumption': 2,
                           'hd_msk_consumption': 2, 'help': 1, 'hd_msk_help': 1,
                           'fielddate': '2019-04-23 18:00:00'}),
         defaultdict(int, {'all': 2, 'hd_msk': 1, 'help': 1, 'hd_msk_help': 1,
                           'hd_avrora': 1, 'null': 1, 'hd_avrora_null': 1,
                           'fielddate': '2019-04-23 19:00:00'}),
         defaultdict(int, {'all': 1, 'hd_msk': 1, 'take': 1, 'hd_msk_take': 1,
                           'fielddate': '2019-04-23 20:00:00'})]
    ),
    (
        'st',
        'd',
        [defaultdict(int, {'all': 4, 'hd_msk': 4, 'fielddate': '2016-10-14'})]
    ),
    (
        'income',
        'd',
        [defaultdict(int, {'all': 3, 'hd_msk': 3, 'fielddate': '2019-04-23'})]
    ),
    (
        'tlg',
        'd',
        [defaultdict(int, {'all': 4, 'null': 4, 'fielddate': '2019-04-23'})]
    )
]

EQ_STOCK_MONITORING = {'yt_data': [
    {'loc_segment2': 'MOW', 'segment1': 'Kingston - KTD-L3B/4G'},
    {'loc_segment2': 'MOW', 'segment1': 'Kingston - KTA-MB1066/4G'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-KITPLUS-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-KITPLUS-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-CODEC-PL-NR-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-TOUCH10'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-TOUCH10'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-CODEC-PL-NR-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-KIT-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-TOUCH10'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-KIT-K7'},
    {'loc_segment2': 'SPB', 'segment1': 'Cisco - CS-TOUCH10'},
    {'loc_segment2': 'SPB', 'segment1': 'iPad 6 WiFi (A1893)'},
    {'loc_segment2': 'SPB', 'segment1': 'iPad 6 WiFi (A1893)'},
    {'loc_segment2': 'SPB', 'segment1': 'iPad 6 WiFi (A1893)'},
    {'loc_segment2': 'SPB', 'segment1': 'iPad 6 WiFi (A1893)'},
    {'loc_segment2': 'MOW', 'segment1': 'E6230'},
    {'loc_segment2': 'MOW', 'segment1': 'E4310'},
    {'loc_segment2': 'MOW', 'segment1': 'E4310'},
    {'loc_segment2': 'MOW', 'segment1': 'E4310'},
    {'loc_segment2': 'SIMF', 'segment1': 'E7440'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'SPB', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MOW', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'SMR', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9Q2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'MYT', 'segment1': 'MR9R2RU/A'},
    {'loc_segment2': 'SIMF', 'segment1': 'MD231UA/A'}],
    'models_result':
        {'MR9Q2RU/A': {'MYT': 111}, 'MB Pro 13 Touch': {'sum': 151},
         'MR9R2RU/A': {'MYT': 37, 'SPB': 1, 'MOW': 1, 'OTHER': 1},
         'Z0UN000F7': {}, 'Z0V7000L7': {}, 'Z0WQ000DJ': {},
         'MB Pro 15 Touch': {'sum': 0}, 'Z0SG000DQ': {}, 'Z0UB0002R': {},
         'Z0V0000NW': {}, 'Z0WV00069': {}, 'XPS': {'sum': 0},
         '9570 4K Touch': {}, '9570 FHD': {}, 'LENOVO': {'sum': 0},
         'T580 (20LASV0Y00)': {}, 'X1 Carbon 6th Gen (20KGS6PC00)': {},
         'T580 (20LAS5V100)': {}, 'X1 Carbon 6th Gen (20KGSBUL00)': {},
         'AQUARIUS': {'sum': 0}, 'Pro P30 K15': {}, 'Pro G40 S58': {},
         'INTEL': {'sum': 0}, 'NUC7i3DNHE': {}, 'LENOVO-MONITORS': {'sum': 0},
         'P24h-10 (F16238QP1)': {}, 'P27u-10 (A16270UP0)': {},
         'VOIP': {'sum': 0}, 'Cisco - CP-7821': {}}
    ,
    'csv_result': 'Отчет сформирован в {}\r\nModel,SPB,MYT,MOW,EKB,MSQ,NNOV,NVB,SIMF,SOCHI,OTHER,Sum\r\nMB Pro 13 Touch,,,,,,,,,, ,151\r\nMR9Q2RU/A,,111,,,,,,,,,111\r\nMR9R2RU/A,1,37,1,,,,,,,1,40\r\nZ0UN000F7,,,,,,,,,,,0\r\nZ0V7000L7,,,,,,,,,,,0\r\nZ0WQ000DJ,,,,,,,,,,,0\r\nMB Pro 15 Touch,,,,,,,,,, ,0\r\nZ0SG000DQ,,,,,,,,,,,0\r\nZ0UB0002R,,,,,,,,,,,0\r\nZ0V0000NW,,,,,,,,,,,0\r\nZ0WV00069,,,,,,,,,,,0\r\nXPS,,,,,,,,,, ,0\r\n9570 4K Touch,,,,,,,,,,,0\r\n9570 FHD,,,,,,,,,,,0\r\nLENOVO,,,,,,,,,, ,0\r\nT580 (20LASV0Y00),,,,,,,,,,,0\r\nX1 Carbon 6th Gen (20KGS6PC00),,,,,,,,,,,0\r\nT580 (20LAS5V100),,,,,,,,,,,0\r\nX1 Carbon 6th Gen (20KGSBUL00),,,,,,,,,,,0\r\nAQUARIUS,,,,,,,,,, ,0\r\nPro P30 K15,,,,,,,,,,,0\r\nPro G40 S58,,,,,,,,,,,0\r\nINTEL,,,,,,,,,, ,0\r\nNUC7i3DNHE,,,,,,,,,,,0\r\nLENOVO-MONITORS,,,,,,,,,, ,0\r\nP24h-10 (F16238QP1),,,,,,,,,,,0\r\nP27u-10 (A16270UP0),,,,,,,,,,,0\r\nVOIP,,,,,,,,,, ,0\r\nCisco - CP-7821,,,,,,,,,,,0\r\n"OTHER локация включает в себя ALA,AMS,ASTANA,BERLIN,BKU,CHELYABINSK,HERZLIYA,INNOPOLIS,IST,IVA,IZHEVSK,KHUTOR_LENINA,KIEV,KRASNODAR,KYA,KZN,LCN,MANTSALA,NEWBURYPORT,ODS,OMSK,PAO,PERM,RND,RZN,SAS,SHANGHAI,SJC,SMR,TJM,TOMILINO,UFA,VLADIMIR,VOLGOGRAD,VORONEZH,VVK,ZRH"\r\n'.format(
        (datetime.datetime.now().strftime('%Y-%m-%d %H:%M')))
}
