// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM parcelize.ts >>>

import Foundation

fileprivate class A: Parcelable {
  public func f() -> Void {
    fatalError("Must be overridden in subclasses")
  }

}

fileprivate class B: A {
  public override func f() -> Void {
  }

}

fileprivate class Foo: Parcelable {
  public func f() -> Void {
  }

}

