// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM parcelize.ts >>>

package com.yandex.xplat

import com.yandex.ys.*

private abstract class A: Parcelable {
    abstract fun f(): Unit
}

@Parcelize
private open class B: A() {
    open override fun f(): Unit {
    }

}

@Parcelize
private open class Foo: Parcelable {
    open fun f(): Unit {
    }

}

