// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM sandbox.ts >>>

import Foundation

fileprivate func f() -> Void {
}

fileprivate class A {
  @discardableResult
  private func m1() -> Bool! {
    f()
    return 1 > 0 ? true : false
  }

}

fileprivate protocol I {
  func m1() -> Void
  @discardableResult
  func m2() -> Bool
}

