// <<< AUTOGENERATED BY YANDEX.SCRIPT FROM sandbox.ts >>>

package com.yandex.xplat

import com.yandex.ys.*

private fun f(): Unit {
}

private open class A {
    private fun m1(): Boolean? {
        f()
        return if (1 > 0) true else false
    }

}

private interface I {
    fun m1(): Unit
    fun m2(): Boolean
}

