#pragma once

#include <util/generic/string.h>

static const TString SIGN_KEYS_STRING = "aR3zxenEu6+rgV84g2qoHQ==\n"
    "ayFVMGPqmKf4pZ0rnsGMGQ==\n"
    "24ntBqnEvWw3jHAvnKJEvA==\n"
    "hqYz6+YZIl4AfHzMUGl/xA==\n"
    "YesPFJdHJwAECaqFelNVTw==\n"
    "W50/PxLsdRldOKXKklW4Ng==\n"
    "WHiJLfjkTpzeaMP65r1Gnw==\n"
    "eEyd0ZW5Mpma9X9/8/MvIw==\n"
    "RruX5oob0hJiwwjiZsX9xg==\n"
    "FrWYBOOTWYsr+mTFZd1lHA==\n"
    "yyf/T+rhLFnEOmw1Xxnjhg==\n"
    "JsONbaMTM6whc5BrvVakUg==\n"
    "iVR/KzErTBb4F0rQXBh48g==\n"
    "ap94v+rJUKjDCIZRiF2cGg==\n"
    "tfGqrPhSbRvNnL4ZtHh5Gg==\n"
    "jQm9NqfREKGKRNgHSGLV1A==\n"
    "mNVy8DPGI+9jzjxpWqJa/w==\n"
    "pSACYtk06Czfuh4ZtnDUqw==\n"
    "b5GXVlqker8fysGncnnYRA==\n"
    "RPnjGO2M6HoSyOaofBXftg==\n"
    "8bp70jeSYVz8VqEcgZpD3w==\n"
    "A8C7bbzc2H5dOLWTguX/bQ==\n"
    "XK7N3MS6qs6as+xKNNdxUQ==\n"
    "Jzn2EHfGl+uNK0LHLOrgZQ==\n"
    "/v0GVpoAXSvj6v6gsW7rzg==\n"
    "IvDkIwdmNCKtI1B/MNaOFQ==\n"
    "nl3eeeUJ7JV3PSrEJ3KIhQ==\n"
    "uwMlJ04iauFxEscgDrVM5A==\n"
    "MKjOJq3A0WtU/nqxqk9OUA==\n"
    "8pDPGNUpXFxUVonVs3NW1A==\n"
    "oJW+MlU7IOS2Ud/SbEQaYw==\n"
    "qcsvSB+bbHR9ym0BpYOGEA==\n"
    "VeTzOyeD1xh7KwrUi5K0rQ==\n"
    "Ep6pBa6wq+6Q5tTSADYe5A==\n"
    "6bCYUFnaa99RWC1FElRjtw==\n"
    "qH36vMUejVh5D7LHe2ENwA==\n"
    "RhVl6QmK442T49kvNTfTdA==\n"
    "qE/6dNgbmVnFyr49d/zZbQ==";
