// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	check_statuses "github.com/YandexClassifieds/cms/pb/cms/domains/check_statuses"

	mock "github.com/stretchr/testify/mock"
)

// ICheck is an autogenerated mock type for the ICheck type
type ICheck struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *ICheck) Run() (check_statuses.Status, string) {
	ret := _m.Called()

	var r0 check_statuses.Status
	if rf, ok := ret.Get(0).(func() check_statuses.Status); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(check_statuses.Status)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}
