const {formats} = require('@yandex-int/palmsync');
const dotenv = require('dotenv');
const commonConfig = require('../../../common/.common.palmsync.conf.js')

dotenv.config();

module.exports = {
    ...commonConfig,

    project: process.env.TESTPALM_PROJECT,
    testpalmToken: process.env.TESTPALM_OAUTH_TOKEN,

    schemeExtension: [
        // custom names
        {
            name: "components",
            meta: true,
            mergeable: true,
            format: formats.isEnum(
                '3d_touch',
                'ad',
                'ad_pin',
                'ad_unlogin',
                'alice',
                'alternatives',
                'alternatives_mobile_maps',
                'android_notification',
                'android_auto',
                'annotation',
                'audio',
                'audio_zsb',
                'auth',
                'auto_card',
                'baloon',
                'billboard_card',
                'blizzard',
                'burger_king',
                'burn_in_protection',
                'cargo_navigation',
                'carplay',
                'carplay_and_android_auto',
                'cars_autocode',
                'carsharing',
                'cashe',
                'ckad',
                'create_route',
                'cta',
                'cursor',
                'dka',
                'eda',
                'fast_settings',
                'fine',
                'foreground_guidance',
                'free_drive',
                'gas_by_alice',
                'gas_card_col',
                'gas_card_org',
                'gas_food',
                'gas_layer',
                'gas_notification',
                'gas_payment',
                'gas_promo',
                'gas_tr',
                'gas_station_at_route',
                'gas_taximeter',
                'gas_attendant',
                'geoproduct',
                'gps',
                'home_plus',
                'headsup_notification',
                'hu_buttons',
                'icons',
                'intent',
                'introscreeen',
                'jams',
                'js_api',
                'longtap_menu',
                'main_menu_card',
                'map',
                'map_search',
                'menu',
                'more_fast_route',
                'motion',
                'multicar',
                'music',
                'my_place',
                'myspin',
                'navikittestapp',
                'naviprovider',
                'navigation',
                'network',
                'new_road_events',
                'new_start_menu',
                'new_tab_and_notifications',
                'offer_menu',
                'offline_routes',
                'offline_search',
                'organization_card',
                'osago',
                'overview',
                'parking',
                'parking_widget',
                'permissions',
                'poi',
                'pointers',
                'promolib',
                'provisioning',
                'push',
                'rate_us',
                'real_road_test',
                'revocable_companies',
                'road_events',
                'route',
                'route_guidance_search',
                'search',
                'search_result',
                'search_screen',
                'send_route',
                'settings',
                'setting_foreground_guidance',
                'share',
                'smoke',
                'snippet',
                'speccial_project',
                'speechkit',
                'speedlimit',
                'splashscreen',
                'stability',
                'suggest',
                'synchronization',
                'taxi',
                'taxi_on_alternative_route',
                'tgo',
                'toponym_card',
                'ui',
                'update',
                'updater',
                'via_points',
                'voices',
                'voice_search',
                'waitcursor',
                'weather',
                'widget',
                'zsb',
                'cpaa_bookmarks',
                'cpaa_access',
                'cpaa_foreground',
                'cpaa_connection',
                'cpaa_driving',
                'cpaa_map',
                'cpaa_network',
                'cpaa_plus',
                'cpaa_search',
                'cpaa_stability',
                'cpaa_real_road_test',
                'cpaa_settings',
                'cpaa_interrupt',
                'cpaa_routes',
                'cpaa_route_guidance',
                'cp_dashboard',
                'zsb_webview',
                'zsb_regular',
                'zsb_pixel',
                'zsb_pixel_2',
                'zsb_cta',
                'zsb_appinstall',
                'zsb_yas_direct',
                'cpaa_push',
                'cpaa_assessors_env',
                'cpaa_audiosession',
                'assessors_ch',
                'geoad_appinstall',
                'geoad_direct',
                'geoad_end_point',
                'geoad_pixel_end_point',
                'geoad_pixel',
                'geoad_pixel_2',
                'geoad_regular',
                'geoad_webview',
                'geoad_yas',
                'booking',
                'data_reading',
                'migrations'
            )
        },
        {
            name: "integration_run",
            meta: true,
            mergeable: true,
            format: formats.isArrayOfEnums(
                'alice',
                'am_sdk',
                'android_auto',
                'annotation',
                'app_metrica',
                'audiosession',
                'carplay',
                'localization',
                'mapkit',
                'music_sdk',
                'myspin',
                'new_tab_and_notifications',
                'parking_pay',
                'push',
                'search',
                'searchlib',
                'speechkit',
                'tanker_sdk',
                'map_search',
                'fine',
                'promolib',
                'payment_sdk'
            )
        },
        {
            name: "testing",
            meta: true,
            mergeable: true,
            format: formats.isArrayOfEnums(
                'real_road_test',
                'regress',
                'acceptance_navi',
                'smoke_navi',
                'lite_acceptance_maps',
                'acceptance_maps',
                'smoke_myspin'
            )
        },
        {
            name: "platforms",
            mergeable: true,
            meta: true,
            format: formats.isArrayOfEnums(
                'android',
                'android_auto',
                'autochip',
                'carsharing_t3',
                'carplay',
                'first_run_hu',
                'geely',
                'honda',
                'ios',
                'mitsubishi_oem',
                'motrex',
                'myspin',
                'nissan',
                'renault',
                'second_run_hu',
                't3am',
                'vaz'
            )
        },
        {
            name: "tags",
            meta: true,
            mergeable: true,
            format: formats.isArrayOfEnums(
                'bt_headset',
                'mobile_internet',
                'not_suitable_for_farm',
                'assessors',
                'both_myspin',
                'android_4',
                'mapkit_ready',
                'metric',
                'not_gp',
                'sd_card',
                'samsung',
                'migration',
                'parity'
            )
        },
        {
            name: "casetype",
            mergeable: true,
            meta: true,
            format: formats.isArrayOfEnums('ch')
        },
        // Временные меры, что бы не плодили старые ключи (про assessors / need_debug / platform / component)
        // Тот кто столкнлся с ошибкой валиидации на список ключей ниже - вы ввели тот ключ, который нельзя использоать
        {
            name: "assessors",
            mergeable: true,
            meta: true,
            format: formats.isEnum('')
        },
        {
            name: "platform",
            mergeable: true,
            meta: true,
            format: formats.isEnum('')
        },
        {
            name: "need_debug",
            mergeable: true,
            meta: true,
            format: formats.isEnum('')
        },
        {
            name: "componnt",
            mergeable: true,
            meta: true,
            format: formats.isEnum('')
        },

        // system names
        {
            name: "hermioneTitle",
            required: false,
            meta: true,
        },
        {
            name: "palmsync_synchronization_errors",
            required: false,
            meta: true,
        },
        {
            name: "browsers",
            required: false,
            meta: true,
        },
        {
            name: "filepath",
            required: false,
            meta: true,
        },
        {
            name: "scenarioType",
            required: false,
            meta: true,
        },
        {
            name: "feature",
            required: false,
            meta: true,
        }
    ]
};
