#!/bin/sh -e

color=$1
shift

case "$color" in
    blue)
        color='34;1'
        ;;
    green)
        color='32;1'
        ;;

    red)
        color='31;1'
        ;;
    bold)
        color=1
        ;;
    *)
        echo "Unknown color ${color}" >&2
        exit 1
esac

echo -ne "\033[${color}m"
echo "$@"
echo -ne "\033[0m"
