OWNER(g:awacs)
PY3TEST()
TEST_SRCS(
    test_awacslet.py
    util.py
)
DATA(
    arcadia/infra/awacs/awacslet/test/testdata
)
PEERDIR(
    contrib/python/requests
)
DEPENDS(
    balancer/daemons/balancer
    infra/awacs/awacslet/test/sdstub
    infra/awacs/awacslet/cmd/awacslet
)
REQUIREMENTS(ram:32)

END()
