// Code generated by mockery v2.6.0. DO NOT EDIT.

package _switch

import mock "github.com/stretchr/testify/mock"

// ISwitchSystem is an autogenerated mock type for the ISwitchSystem type
type ISwitchSystem struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *ISwitchSystem) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Switch provides a mock function with given fields: from
func (_m *ISwitchSystem) Switch(from string) error {
	ret := _m.Called(from)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(from)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
