# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _test_case_for_parse_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import test_awacs_field_schema_pb2 as test__awacs__field__schema__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='_test_case_for_parse_request.proto',
  package='test_case_for_parse_request',
  syntax='proto2',
  serialized_pb=_b('\n\"_test_case_for_parse_request.proto\x12\x1btest_case_for_parse_request\x1a\x1dtest_awacs_field_schema.proto\"x\n\x0c\x45mbeddedTest\x12\x11\n\tint_field\x18\x01 \x01(\x05\x12\x13\n\x0b\x66loat_field\x18\x02 \x01(\x02\x12\x14\n\x0cstring_field\x18\x03 \x01(\t\x12\x12\n\nbool_field\x18\x04 \x01(\x08\x12\x16\n\x0erepeated_field\x18\x05 \x03(\x05\"\xb3\x01\n\x05Test1\x12\x11\n\tint_field\x18\x01 \x01(\x05\x12\x13\n\x0b\x66loat_field\x18\x02 \x01(\x02\x12\x14\n\x0cstring_field\x18\x03 \x01(\t\x12\x12\n\nbool_field\x18\x04 \x01(\x08\x12\x16\n\x0erepeated_field\x18\x05 \x03(\x05\x12@\n\rmessage_field\x18\x06 \x01(\x0b\x32).test_case_for_parse_request.EmbeddedTest\"\x87\x01\n\x16ValidationEmbeddedTest\x12\x1b\n\tint_field\x18\x01 \x01(\x05\x42\x08\x88\xa6\x1d\x00\x90\xa6\x1d\x64\x12\x1d\n\x0b\x66loat_field\x18\x02 \x01(\x02\x42\x08\x88\xa6\x1d\x00\x90\xa6\x1d\x64\x12\x31\n\x0cstring_field\x18\x03 \x01(\t:\x01\x30\x42\x18\x98\xa6\x1d\x02\xa0\xa6\x1d\n\xaa\xa6\x1d\x0c[0-9]{1,10}$\"\x9a\x02\n\x0eValidationTest\x12\x44\n\x07message\x18\x01 \x01(\x0b\x32\x33.test_case_for_parse_request.ValidationEmbeddedTest\x12\x1e\n\x0crepeated_int\x18\x02 \x03(\x05\x42\x08\x88\xa6\x1d\x00\x90\xa6\x1d\x64\x12 \n\x0erepeated_float\x18\x03 \x03(\x02\x42\x08\x88\xa6\x1d\x00\x90\xa6\x1d\x64\x12\x31\n\x0frepeated_string\x18\x04 \x03(\tB\x18\x98\xa6\x1d\x02\xa0\xa6\x1d\n\xaa\xa6\x1d\x0c[0-9]{1,10}$\x12M\n\x10repeated_message\x18\x05 \x03(\x0b\x32\x33.test_case_for_parse_request.ValidationEmbeddedTest')
  ,
  dependencies=[test__awacs__field__schema__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMBEDDEDTEST = _descriptor.Descriptor(
  name='EmbeddedTest',
  full_name='test_case_for_parse_request.EmbeddedTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_field', full_name='test_case_for_parse_request.EmbeddedTest.int_field', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_field', full_name='test_case_for_parse_request.EmbeddedTest.float_field', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_field', full_name='test_case_for_parse_request.EmbeddedTest.string_field', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_field', full_name='test_case_for_parse_request.EmbeddedTest.bool_field', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeated_field', full_name='test_case_for_parse_request.EmbeddedTest.repeated_field', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=218,
)


_TEST1 = _descriptor.Descriptor(
  name='Test1',
  full_name='test_case_for_parse_request.Test1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_field', full_name='test_case_for_parse_request.Test1.int_field', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_field', full_name='test_case_for_parse_request.Test1.float_field', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string_field', full_name='test_case_for_parse_request.Test1.string_field', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool_field', full_name='test_case_for_parse_request.Test1.bool_field', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeated_field', full_name='test_case_for_parse_request.Test1.repeated_field', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_field', full_name='test_case_for_parse_request.Test1.message_field', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=400,
)


_VALIDATIONEMBEDDEDTEST = _descriptor.Descriptor(
  name='ValidationEmbeddedTest',
  full_name='test_case_for_parse_request.ValidationEmbeddedTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_field', full_name='test_case_for_parse_request.ValidationEmbeddedTest.int_field', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))),
    _descriptor.FieldDescriptor(
      name='float_field', full_name='test_case_for_parse_request.ValidationEmbeddedTest.float_field', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))),
    _descriptor.FieldDescriptor(
      name='string_field', full_name='test_case_for_parse_request.ValidationEmbeddedTest.string_field', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("0").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\246\035\002\240\246\035\n\252\246\035\014[0-9]{1,10}$'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=538,
)


_VALIDATIONTEST = _descriptor.Descriptor(
  name='ValidationTest',
  full_name='test_case_for_parse_request.ValidationTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='test_case_for_parse_request.ValidationTest.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='repeated_int', full_name='test_case_for_parse_request.ValidationTest.repeated_int', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))),
    _descriptor.FieldDescriptor(
      name='repeated_float', full_name='test_case_for_parse_request.ValidationTest.repeated_float', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))),
    _descriptor.FieldDescriptor(
      name='repeated_string', full_name='test_case_for_parse_request.ValidationTest.repeated_string', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\246\035\002\240\246\035\n\252\246\035\014[0-9]{1,10}$'))),
    _descriptor.FieldDescriptor(
      name='repeated_message', full_name='test_case_for_parse_request.ValidationTest.repeated_message', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=823,
)

_TEST1.fields_by_name['message_field'].message_type = _EMBEDDEDTEST
_VALIDATIONTEST.fields_by_name['message'].message_type = _VALIDATIONEMBEDDEDTEST
_VALIDATIONTEST.fields_by_name['repeated_message'].message_type = _VALIDATIONEMBEDDEDTEST
DESCRIPTOR.message_types_by_name['EmbeddedTest'] = _EMBEDDEDTEST
DESCRIPTOR.message_types_by_name['Test1'] = _TEST1
DESCRIPTOR.message_types_by_name['ValidationEmbeddedTest'] = _VALIDATIONEMBEDDEDTEST
DESCRIPTOR.message_types_by_name['ValidationTest'] = _VALIDATIONTEST

EmbeddedTest = _reflection.GeneratedProtocolMessageType('EmbeddedTest', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDEDTEST,
  __module__ = '_test_case_for_parse_request_pb2'
  # @@protoc_insertion_point(class_scope:test_case_for_parse_request.EmbeddedTest)
  ))
_sym_db.RegisterMessage(EmbeddedTest)

Test1 = _reflection.GeneratedProtocolMessageType('Test1', (_message.Message,), dict(
  DESCRIPTOR = _TEST1,
  __module__ = '_test_case_for_parse_request_pb2'
  # @@protoc_insertion_point(class_scope:test_case_for_parse_request.Test1)
  ))
_sym_db.RegisterMessage(Test1)

ValidationEmbeddedTest = _reflection.GeneratedProtocolMessageType('ValidationEmbeddedTest', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATIONEMBEDDEDTEST,
  __module__ = '_test_case_for_parse_request_pb2'
  # @@protoc_insertion_point(class_scope:test_case_for_parse_request.ValidationEmbeddedTest)
  ))
_sym_db.RegisterMessage(ValidationEmbeddedTest)

ValidationTest = _reflection.GeneratedProtocolMessageType('ValidationTest', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATIONTEST,
  __module__ = '_test_case_for_parse_request_pb2'
  # @@protoc_insertion_point(class_scope:test_case_for_parse_request.ValidationTest)
  ))
_sym_db.RegisterMessage(ValidationTest)


_VALIDATIONEMBEDDEDTEST.fields_by_name['int_field'].has_options = True
_VALIDATIONEMBEDDEDTEST.fields_by_name['int_field']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))
_VALIDATIONEMBEDDEDTEST.fields_by_name['float_field'].has_options = True
_VALIDATIONEMBEDDEDTEST.fields_by_name['float_field']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))
_VALIDATIONEMBEDDEDTEST.fields_by_name['string_field'].has_options = True
_VALIDATIONEMBEDDEDTEST.fields_by_name['string_field']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\246\035\002\240\246\035\n\252\246\035\014[0-9]{1,10}$'))
_VALIDATIONTEST.fields_by_name['repeated_int'].has_options = True
_VALIDATIONTEST.fields_by_name['repeated_int']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))
_VALIDATIONTEST.fields_by_name['repeated_float'].has_options = True
_VALIDATIONTEST.fields_by_name['repeated_float']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\210\246\035\000\220\246\035d'))
_VALIDATIONTEST.fields_by_name['repeated_string'].has_options = True
_VALIDATIONTEST.fields_by_name['repeated_string']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\230\246\035\002\240\246\035\n\252\246\035\014[0-9]{1,10}$'))
# @@protoc_insertion_point(module_scope)
