# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_awacs_field_schema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_awacs_field_schema.proto',
  package='test_awacs_field_schema',
  syntax='proto3',
  serialized_pb=_b('\n\x1dtest_awacs_field_schema.proto\x12\x17test_awacs_field_schema\x1a google/protobuf/descriptor.proto:0\n\x07minimum\x12\x1d.google.protobuf.FieldOptions\x18\xe1\xd4\x03 \x01(\x05:0\n\x07maximum\x12\x1d.google.protobuf.FieldOptions\x18\xe2\xd4\x03 \x01(\x05:2\n\tminLength\x12\x1d.google.protobuf.FieldOptions\x18\xe3\xd4\x03 \x01(\x05:2\n\tmaxLength\x12\x1d.google.protobuf.FieldOptions\x18\xe4\xd4\x03 \x01(\x05:0\n\x07pattern\x12\x1d.google.protobuf.FieldOptions\x18\xe5\xd4\x03 \x01(\t:1\n\x08required\x12\x1d.google.protobuf.FieldOptions\x18\xe6\xd4\x03 \x01(\x08:.\n\x05title\x12\x1d.google.protobuf.FieldOptions\x18\xca\xd5\x03 \x01(\t:4\n\x0b\x64\x65scription\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xd5\x03 \x01(\tb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


MINIMUM_FIELD_NUMBER = 60001
minimum = _descriptor.FieldDescriptor(
  name='minimum', full_name='test_awacs_field_schema.minimum', index=0,
  number=60001, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MAXIMUM_FIELD_NUMBER = 60002
maximum = _descriptor.FieldDescriptor(
  name='maximum', full_name='test_awacs_field_schema.maximum', index=1,
  number=60002, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MINLENGTH_FIELD_NUMBER = 60003
minLength = _descriptor.FieldDescriptor(
  name='minLength', full_name='test_awacs_field_schema.minLength', index=2,
  number=60003, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MAXLENGTH_FIELD_NUMBER = 60004
maxLength = _descriptor.FieldDescriptor(
  name='maxLength', full_name='test_awacs_field_schema.maxLength', index=3,
  number=60004, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
PATTERN_FIELD_NUMBER = 60005
pattern = _descriptor.FieldDescriptor(
  name='pattern', full_name='test_awacs_field_schema.pattern', index=4,
  number=60005, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
REQUIRED_FIELD_NUMBER = 60006
required = _descriptor.FieldDescriptor(
  name='required', full_name='test_awacs_field_schema.required', index=5,
  number=60006, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
TITLE_FIELD_NUMBER = 60106
title = _descriptor.FieldDescriptor(
  name='title', full_name='test_awacs_field_schema.title', index=6,
  number=60106, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
DESCRIPTION_FIELD_NUMBER = 60107
description = _descriptor.FieldDescriptor(
  name='description', full_name='test_awacs_field_schema.description', index=7,
  number=60107, type=9, cpp_type=9, label=1,
  has_default_value=False, default_value=_b("").decode('utf-8'),
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['minimum'] = minimum
DESCRIPTOR.extensions_by_name['maximum'] = maximum
DESCRIPTOR.extensions_by_name['minLength'] = minLength
DESCRIPTOR.extensions_by_name['maxLength'] = maxLength
DESCRIPTOR.extensions_by_name['pattern'] = pattern
DESCRIPTOR.extensions_by_name['required'] = required
DESCRIPTOR.extensions_by_name['title'] = title
DESCRIPTOR.extensions_by_name['description'] = description

google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(minimum)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(maximum)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(minLength)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(maxLength)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(pattern)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(required)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(title)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(description)

# @@protoc_insertion_point(module_scope)
