# This Dockerfile creates an debian image with xfstests-bld build environment
#
# This Dockerfile file is useful for building the xfstests.tar.gz file
# in a Docker environment, for continuous build testing.  It can also
# be useful for testing whatever the file system environemnt is
# provided in the Docker environment, without requiring any special
# privileges.
#
# VERSION 0.1
FROM debian:stretch

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
	autoconf \
	autoconf2.64 \
	automake \
	autopoint \
	bison \
	build-essential \
	ca-certificates \
	debootstrap \
	e2fslibs-dev \
	ed \
	fakechroot \
	gettext \
	git \
	golang-1.8-go \
	libdbus-1-3 \
	libgdbm-dev \
	libkeyutils-dev \
	libssl-dev \
	libtool-bin \
	pkg-config \
	qemu-utils \
	symlinks \
	sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
       /usr/share/doc /usr/share/doc-base \
       /usr/share/man /usr/share/locale /usr/share/zoneinfo
