# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from models.method_options import MethodOptions  # noqa: E501
from solomon_client.rest import ApiException


class TestMethodOptions(unittest.TestCase):
    """MethodOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMethodOptions(self):
        """Test MethodOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = solomon_client.models.method_options.MethodOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
