# coding: utf-8

"""
    Yasm alert api client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ps-admin@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yasm_alert
from yasm_alert.models.body import Body  # noqa: E501
from yasm_alert.rest import ApiException


class TestBody(unittest.TestCase):
    """Body unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody(self):
        """Test Body"""
        # FIXME: construct object with mandatory attributes with example values
        # model = yasm_alert.models.body.Body()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
