# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from api.services_api import ServicesApi  # noqa: E501
from solomon_client.rest import ApiException


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self):
        self.api = api.services_api.ServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_service_using_post(self):
        """Test case for create_service_using_post

        create service  # noqa: E501
        """
        pass

    def test_delete_service_using_delete(self):
        """Test case for delete_service_using_delete

        delete service  # noqa: E501
        """
        pass

    def test_get_all_using_get3(self):
        """Test case for get_all_using_get3

        list available services  # noqa: E501
        """
        pass

    def test_get_service_clusters_using_get(self):
        """Test case for get_service_clusters_using_get

        associated clusters  # noqa: E501
        """
        pass

    def test_get_service_using_get(self):
        """Test case for get_service_using_get

        read one service  # noqa: E501
        """
        pass

    def test_update_service_using_put(self):
        """Test case for update_service_using_put

        update service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
