# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from models.enum_value_options import EnumValueOptions  # noqa: E501
from solomon_client.rest import ApiException


class TestEnumValueOptions(unittest.TestCase):
    """EnumValueOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnumValueOptions(self):
        """Test EnumValueOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = solomon_client.models.enum_value_options.EnumValueOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
