# coding: utf-8

"""
    Yasm alert api client

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: ps-admin@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import yasm_alert
from yasm_alert.api.default_api import DefaultApi  # noqa: E501
from yasm_alert.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = yasm_alert.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bind_check(self):
        """Test case for bind_check

        Bind yasm alert to juggler check  # noqa: E501
        """
        pass

    def test_create_alert(self):
        """Test case for create_alert

        Create new alert  # noqa: E501
        """
        pass

    def test_delete_alert(self):
        """Test case for delete_alert

        Delete one alert  # noqa: E501
        """
        pass

    def test_get_alert(self):
        """Test case for get_alert

        Get one alert  # noqa: E501
        """
        pass

    def test_list_alerts(self):
        """Test case for list_alerts

        Get checks by filter  # noqa: E501
        """
        pass

    def test_replace_alerts(self):
        """Test case for replace_alerts

        Replace alerts with prefix  # noqa: E501
        """
        pass

    def test_unbind_check(self):
        """Test case for unbind_check

        Remove binding between yasm alert and juggler check  # noqa: E501
        """
        pass

    def test_update_alert(self):
        """Test case for update_alert

        Update one alert  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
