# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from api.push_api import PushApi  # noqa: E501
from solomon_client.rest import ApiException


class TestPushApi(unittest.TestCase):
    """PushApi unit test stubs"""

    def setUp(self):
        self.api = api.push_api.PushApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_push_using_post(self):
        """Test case for push_using_post

        Push sensors data  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
