# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from api.shards_api import ShardsApi  # noqa: E501
from solomon_client.rest import ApiException


class TestShardsApi(unittest.TestCase):
    """ShardsApi unit test stubs"""

    def setUp(self):
        self.api = api.shards_api.ShardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_shard_using_post(self):
        """Test case for create_shard_using_post

        create shard  # noqa: E501
        """
        pass

    def test_delete_shard_using_delete(self):
        """Test case for delete_shard_using_delete

        delete shard  # noqa: E501
        """
        pass

    def test_get_all_using_get4(self):
        """Test case for get_all_using_get4

        list available shards  # noqa: E501
        """
        pass

    def test_get_shard_using_get(self):
        """Test case for get_shard_using_get

        read one shard  # noqa: E501
        """
        pass

    def test_targets_status_using_get(self):
        """Test case for targets_status_using_get

        get shard targets statuses  # noqa: E501
        """
        pass

    def test_update_shard_using_put(self):
        """Test case for update_shard_using_put

        update shard  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
