# coding: utf-8

"""
    Solomon API v2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: solomon@yandex-team.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import solomon_client
from api.clusters_api import ClustersApi  # noqa: E501
from solomon_client.rest import ApiException


class TestClustersApi(unittest.TestCase):
    """ClustersApi unit test stubs"""

    def setUp(self):
        self.api = api.clusters_api.ClustersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_cluster_using_post(self):
        """Test case for create_cluster_using_post

        create cluster  # noqa: E501
        """
        pass

    def test_delete_cluster_using_delete(self):
        """Test case for delete_cluster_using_delete

        delete cluster  # noqa: E501
        """
        pass

    def test_get_all_using_get(self):
        """Test case for get_all_using_get

        list available clusters  # noqa: E501
        """
        pass

    def test_get_cluster_services_using_get(self):
        """Test case for get_cluster_services_using_get

        associated services  # noqa: E501
        """
        pass

    def test_get_cluster_using_get(self):
        """Test case for get_cluster_using_get

        read one cluster  # noqa: E501
        """
        pass

    def test_update_cluster_using_put(self):
        """Test case for update_cluster_using_put

        update cluster  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
