PY3TEST()

STYLE_PYTHON()

OWNER(g:walle)

TEST_SRCS(
    automation_plot_api/test_add.py
    automation_plot_api/test_delete.py
    automation_plot_api/test_enable_or_disable_check.py
    automation_plot_api/test_get.py
    automation_plot_api/test_update.py
    automation_plot_api/test_validate_checks.py
    box_api/test_get.py
    host_api/conftest.py
    host_api/test_add.py
    host_api/test_agent_api.py
    host_api/test_cancel_task.py
    host_api/test_check_dns.py
    host_api/test_debug_trace_decision_maker.py
    host_api/test_debug_update_bot_platform.py
    host_api/test_delete.py
    host_api/test_deploy_log.py
    host_api/test_errors.py
    host_api/test_fdqn_deinvalidation.py
    host_api/test_force_status.py
    host_api/test_get.py
    host_api/test_handle_failure.py
    host_api/test_host_network_api.py
    host_api/test_info.py
    host_api/test_maintenance.py
    host_api/test_modify_extra_vlans.py
    host_api/test_power_off.py
    host_api/test_power_on.py
    host_api/test_power_status.py
    host_api/test_prepare.py
    host_api/test_profile.py
    host_api/test_profile_log.py
    host_api/test_kexec_reboot.py
    host_api/test_reboot.py
    host_api/test_redeploy.py
    host_api/test_release_host.py
    host_api/test_render_deploy_config.py
    host_api/test_set_assigned.py
    host_api/test_switch_project.py
    host_api/test_switch_vlans.py
    host_api/test_update.py
    iam_permissions/conftest.py
    iam_permissions/test_agent_report.py
    iam_permissions/test_projects.py
    iam_permissions/test_hosts.py
    iam_permissions/test_automation_plot.py
    iam_permissions/test_logs.py
    iam_permissions/test_other.py
    maintenance_plot_api/test_create.py
    maintenance_plot_api/test_delete.py
    maintenance_plot_api/test_get.py
    maintenance_plot_api/test_modify.py
    preorder_api/test_add.py
    preorder_api/test_delete.py
    preorder_api/test_get.py
    preorder_api/test_restart.py
    project_api/conftest.py
    project_api/test_add.py
    project_api/test_clone.py
    project_api/test_common.py
    project_api/test_delete.py
    project_api/test_fsm_handbrake.py
    project_api/test_get.py
    project_api/test_manually_disabled_checks.py
    project_api/test_modify.py
    project_api/test_modify_automation_limits.py
    project_api/test_modify_automation_plot.py
    project_api/test_modify_automation_settings.py
    project_api/test_modify_bot_project_id.py
    project_api/test_modify_cms_settings.py
    project_api/test_modify_dns_domain.py
    project_api/test_modify_hbf_project_id.py
    project_api/test_modify_host_limits.py
    project_api/test_modify_hostname_template.py
    project_api/test_modify_maintenance_plot.py
    project_api/test_modify_notifications.py
    project_api/test_modify_owned_vlans.py
    project_api/test_modify_owners.py
    project_api/test_modify_repair_request_severity.py
    project_api/test_modify_report_settings.py
    project_api/test_modify_tags.py
    project_api/test_modify_tier.py
    project_api/test_modify_vlan_scheme.py
    project_api/test_project_roles.py
    project_api/test_toggle_ssh_reboot.py
    project_api/test_validators.py
    scenario_api/test_add.py
    scenario_api/test_add_with_maintenance_plot_checks.py
    scenario_api/test_cancel.py
    scenario_api/test_snapshot.py
    scenario_api/test_get_scenario.py
    scenario_api/test_get_scenarios.py
    scenario_api/test_get_scenarios_by_labels.py
    scenario_api/test_itdc_maintenance_api.py
    scenario_api/test_modify.py
    scenario_api/test_noc_api.py
    scenario_api/test_pause.py
    scenario_api/test_specific_scenario_handlers.py
    scenario_api/test_start.py
    scenario_api/test_utils.py
    settings_api/test_settings_api.py
    settings_api/test_global_limit_override.py
    conftest.py
    test_api.py
    test_audit_log_api.py
    test_authorization.py
    test_cauth_api.py
    test_cms_api.py
    test_constants_api.py
    test_dc_shortnames.py
    test_deploy_config_api.py
    test_dns_api.py
    test_health_check_api.py
    test_helpers.py
    test_idm_api.py
    test_metrics_api.py
    test_operation_log_api.py
    test_physical_location_api.py
    test_third_party_api.py
    test_tickets_api.py
    test_token_api.py
    test_user_api.py
)

PY_SRCS(
    NAMESPACE tests.api
    common.py
    iam_permissions/mocks.py
    maintenance_plot_api/mocks.py
    scenario_api/utils.py
)

INCLUDE(${ARCADIA_ROOT}/infra/walle/server/recipes/mongodb/recipe.inc)

SIZE(MEDIUM)

TAG(sb:LINUX_XENIAL)

IF (NOT NO_FORK_TESTS)
    FORK_SUBTESTS(MODULO)
    SPLIT_FACTOR(6)
ENDIF()

PEERDIR(
    contrib/python/deepdiff
    contrib/python/mock
    infra/walle/server/walle
    infra/walle/server/tests/lib
)

NO_DOCTESTS()

END()
