#! /usr/bin/env python
import sys
import time
import signal


if __name__ == '__main__':
    _, time_to_sleep, file_to_write = sys.argv

    def handler(signo, stack_frame):
        with open(file_to_write, 'w') as fd:
            fd.write(str(signo))

    signal.signal(signal.SIGTERM, handler)
    time.sleep(float(time_to_sleep))


