TEST_RAIL_RESULTS_RESPONSE = {
    'search_id': '04T4.04T40000.1.0.0.ru.2000000.2034137.25052022.0.24',
    'total': 20,
    'offset': 10,
    'limit': 10,
    'search': {
        'adult': 1,
        'child': 0,
        'infant': 0,
        'date': '25-05-2022',
        'time_from': 0,
        'time_to': 24,
        'from_code': 2000000,
        'to_code': 2034137,
        'from_country': 'RU',
        'from': 'Москва',
        'to_country': 'RU',
        'to': 'Владивосток',
    },
    'allowed_document_types': {
        'chd': {
            'ru': ['B', 'P'],
            'other': ['A'],
        },
        'chd+': {
            'ru': ['B', 'C', 'P'],
            'other': ['A'],
        },
        'inf': {
            'ru': ['B', 'P'],
            'other': ['A'],
        },
        'adt': {
            'ru': ['C', 'P', 'M', 'S', 'ВЖ'],
            'other': ['A'],
        },
        'yth': {
            'ru': ['C', 'P'],
            'other': ['A'],
        },
    },
    'items': [
        {
            'is_sale_forbidden': False,
            'has_electronic_registration': True,
            'has_two_storey_cars': False,
            'carriers': ['ФПК'],
            'train_number': '002Э',
            'search_train_number': '002Э',
            'display_train_number': '002Э',
            'train_category': 'Скорый',
            'departure_station_name': 'Москва Ярославская',
            'arrival_station_name': 'Владивосток',
            'passenger_departure_station': 'Москва Ярославская',
            'passenger_arrival_station': 'Владивосток',
            'local_departure_date_time': '25.05.2022 01:35',
            'local_arrival_date_times': ['01.06.2022 01:03'],
            'days_on_the_way': 5,
            'arrival_date_times': ['31.05.2022 23:03'],
            'departure_date_from_forming_station': '25.05.2022 00:00',
            'departure_date_time': '25.05.2022 00:35',
            'trip_duration': '9988',
            'train_name': 'Россия',
            'car_groups': [
                {
                    'car_type': 'ReservedSeat',
                    'car_type_code': 'П',
                    'car_type_name': 'ПЛАЦ',
                    'total_place_quantity': 303,
                    'lower_place_quantity': 103,
                    'upper_place_quantity': 104,
                    'lower_side_place_quantity': 48,
                    'upper_side_place_quantity': 48,
                    'min_ticket_price': 10376.4,
                    'max_ticket_price': 10386.4,
                    'has_gender_cabins': False,
                    'carriers': ['ФПК'],
                    'travel_policy': {
                        'is_violated': False,
                        'notices': ['AAAAAA'],
                        'reason_codes': [],
                    },
                    'has_non_refundable_tariff': False,
                },
            ],
            'number_to_get_route': '002Э',
        },
    ],
}

TEST_RAIL_DETAIL_RESPONSE = {
    'route_policy': 'Internal',
    'items': [
        {
            'available_tariffs': [
                {'code': 1, 'type': 'Full'},
                {'code': 3, 'type': 'FreeChild'},
                {'code': 2, 'type': 'Child'},
                {'code': 6, 'type': 'Junior'},
                {'code': 4, 'type': 'Senior'},
                {'code': 23, 'type': 'RoundTrip'},
            ],
            'car_description': '',
            'car_id': '112Л',
            'car_number': '11',
            'car_schema': '66К',
            'car_schema_id': 39,
            'car_type': 'Compartment',
            'car_type_code': 'К',
            'car_type_name': 'КУПЕ',
            'carrier': 'ТВЕРСК',
            'has_electronic_registration': True,
            'has_gender_cabins': False,
            'has_no_interchange': False,
            'has_non_refundable_tariff': False,
            'is_bedding_selection_possible': False,
            'is_two_storey': False,
            'required_places_on_booking': True,
            'arrival_date_time': '29.05.2022 08:59',
            'arrival_station_name': 'Санкт-Петербург-Главн.',
            'local_arrival_date_time': '29.05.2022 08:59',
            'road': 'РЖД/ОКТ',
            'loyalty_cards': [],
            'service_class': '2Л',
            'service_class_description': '4-х местные купе. В стоимость',
            'service_class_international': '',
            'service_class_name': '',
            'travel_policy': {
                'is_violated': True,
                'notices': [
                    'Превышение длительности пребывания',
                ],
                'reason_codes': [
                    'reason2022',
                ],
            },
            'min_ticket_price': 2940.1,
            'max_ticket_price': 2950.1,
            'min_fare': 2940.1,
            'max_fare': 2940.1,
            'pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
            'max_pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
            'service_cost': 100,
            'place_reservation_type': 'Usual',
            'place_count': 1,
            'total_place_quantity': 2,
            'lower_place_quantity': 0,
            'lower_side_place_quantity': 0,
            'upper_place_quantity': 1,
            'upper_side_place_quantity': 0,
            'services': {
                'AirConditioning': 'Кондиционер',
                'Bedclothes': 'Постельное белье',
                'BioToilet': 'Биотуалет',
                'InfotainmentService': 'Мультимедийный портал (кинотеатр, книги, музыка)',
                'RestaurantCarOrBuffet': 'Вагон-ресторан или купе-буфет',
                'Socket220V': 'Розетка 220В',
                'Wifi': 'Wifi',
            },
            'places': [
                {
                    'compartment_number': 3,
                    'max_fare': 2940.1,
                    'max_price': 2980.1,
                    'max_pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
                    'min_fare': 2940.1,
                    'min_price': 2930.1,
                    'min_pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
                    'place': '10С',
                    'type': 'Upper',
                    'type_description': 'Верхнее',
                },
            ],
        },
    ],
}

TEST_HOTEL_RESULTS_RESPONSE = {
    'search_id': 'some_id',
    'search': {
        'adults': 1,
        'children': [],
        'rooms': [{'guests': [{'age': 30, 'is_child': False, 'citizenship': 'ru'}]}],
        'check_in': '26.06.2022',
        'check_out': '01.07.2022',
        'city': 6308866,
        'hotel_id': None,
        'location': {
            'iata': 6308866,
            'country': 'Россия',
            'type': 'City',
            'type_description': 'Город',
            'typeRu': 'Город',
            'name': 'Белогорск, Россия',
        },
    },
    'hotels': [
        {
            'id': '925157',
            'name': 'Тестотель (Островок)',
            'phone': None,
            'email': None,
            'photos': [
                {
                    'url': 'some_url',
                    'thumb': 'some_thumb',
                },
            ],
            'description': 'Плата за доступ в номерах',
            'policy': None,
            'facilities': [{'name': 'Питание и напитки', 'list': ['Ресторан', 'Бар']}],
            'city': 'Белогорск',
            'country': 'Россия',
            'location': {'latitude': 50.921287, 'longitude': 128.473881},
            'stars': 2,
            'category_name': 'Hotel',
            'rating': [],
            'address': 'Белогорск, Ордос 1',
            'trip_advisor_rating': None,
            'check_in_time': '14:00',
            'check_out_time': '12:00',
            'max_check_in_time': None,
            'max_check_out_time': None,
            'important_information': None,
            'min_fare': 487,
            'min_fares': {'RUB': 487},
            'min_price': 487,
            'min_prices': {'RUB': 487},
            'price_details': {'RUB': {'aac_fee': 0}},
            'liked': False,
            'has_free_cancellation': True,
            'travel_policy': {'is_violated': False, 'notices': [], 'reason_codes': []},
            'search_id': 'some_hotel_id',
            'contract': None,
            'is_contract_only': False,
            'is_provider_contract': False,
        },
    ],
    'total': 2,
    'offset': 0,
    'limit': 20,
    'is_completed': True,
}

TEST_HOTEL_DETAIL_RESPONSE = {
    'hotel': {
        'id': '924838',
        'name': 'Домик Спанч Боба test',
        'phone': None,
        'email': None,
        'photos': [
            {
                'url': 'http://some.url',
                'thumb': 'http://some.thumb',
            },
        ],
        'description': 'a description',
        'policy': None,
        'facilities': [
            {
                'name': 'Общие',
                'list': [
                    'Парковка',
                    'Допускается размещение домашних животных',
                    'Wi-Fi доступен на всей территории',
                    'Номера для курящих',
                ],
            },
            {'name': 'Питание и напитки', 'list': ['Ресторан', 'Кафе']},
            {'name': 'Разное', 'list': ['Номера для некурящих']},
            {'name': 'Услуги уборки', 'list': ['Прачечная']},
            {
                'name': 'Стойка регистрации',
                'list': [
                    'Обмен валюты',
                    'Камера хранения багажа',
                    'Банкомат на территории отеля',
                    'Депозит при заселении',
                ],
            },
        ],
        'city': 'Белогорск',
        'country': 'Россия',
        'location': {'latitude': 38.5907739013, 'longitude': 4.1785051625},
        'stars': 0,
        'category_name': 'Hotel',
        'rating': [],
        'address': 'Белогорск, Набережная ул., 4',
        'trip_advisor_rating': None,
        'check_in_time': '10:00',
        'check_out_time': '14:00',
        'max_check_in_time': None,
        'max_check_out_time': None,
        'important_information': None,
        'rooms': [
            {
                'rate_id': 'rate-id',
                'is_non_refundable': True,
                'price': 5822,
                'prices': {'RUB': 5822},
                'vendor': '',
                'type': '',
                'name': 'Без категории, тип кровати может измениться',
                'description': '',
                'fare_sum': 5822,
                'fare_sums': {'RUB': 5822},
                'meal_type': 'Континентальный завтрак',
                'meal_type_code': 'continentalBreakfast',
                'cancellation_rules': [
                    {
                        'is_possible': True,
                        'amount': 4823,
                        'date_from': '29.06.2022 15:00',
                        'date_to': '03.07.2022 09:30',
                        'fare': None,
                    },
                    {
                        'is_possible': True,
                        'amount': 5822,
                        'date_from': '03.07.2022 09:00',
                        'date_to': '04.07.2022 10:00',
                        'fare': None,
                    },
                ],
                'surcharges': [],
                'data': [],
                'price_details': {'RUB': {'aac_fee': 0}},
                'is_contract': False,
                'travel_policy': [],
                'rates': [{'guest_ages': [30], 'rate_id': 'some-rate-id'}],
                'available_room_count': None,
                'has_vat': False,
            },
        ],
        'min_fare': 5822,
        'min_fares': {'RUB': 5822},
        'min_price': 5822,
        'min_prices': {'RUB': 5822},
        'currencies_rates': [],
        'price_details': {'RUB': {'aac_fee': 0}},
        'search_id': '04T4.04T40000.0:30::ru.04072022.09072022.6308866.924838',
        'contract': None,
        'is_contract_only': False,
        'liked': False,
    },
    'search': {
        'adults': 1,
        'children': [],
        'rooms': [{'guests': [{'age': 30, 'is_child': False, 'citizenship': 'ru'}]}],
        'check_in': '04.07.2022',
        'check_out': '09.07.2022',
        'city': 6308866,
        'hotel_id': '924838',
    },
    'location_search_id': '04T4.04T40000.0:30::ru.04072022.09072022.6308866.',
    'is_completed': True,
}


TEST_AVIA_RESULTS_RESPONSE = {
    'search': {
        'adt': 1,
        'channel': '04T40000',
        'chd': 0,
        'class': 'E',
        'inf': 0,
        'partner': '04T4',
        'segments': [
            {
                'from': {
                    'name': 'Москва',
                    'iata': 'MOW',
                    'country': {'name': 'Россия', 'iata': 'RU'},
                    'city': {'name': 'Москва', 'iata': 'MOW'},
                    'region': '---',
                },
                'to': {
                    'name': 'Санкт-Петербург, Пулково',
                    'iata': 'LED',
                    'country': {'name': 'Россия', 'iata': 'RU'},
                    'city': {'name': 'Санкт-Петербург', 'iata': 'LED'},
                    'region': '---',
                },
                'date': '26.06.2022'
            },
        ],
        'airlines': [],
        'src': 0,
        'token': '04T40000RTE1000010090MOWLED20220626LEDMOW20220701',
        'type': 'rt',
        'yth': 0,
        'is_direct_only': False,
        'is_inner_flight': True,
    },
    'flights': [
        {
            'id': 'some_id',
            'rid': 'some_rid',
            'tariff_type': None,
            'fare_family_type': 'SMARTLIGHT',
            'fare_family_flag': True,
            'segments_count': 2,
            'type': 'regular',
            'is_inner_flight': True,
            'is_baggage': True,
            'is_refund': False,
            'is_subsidized': False,
            'citizenships': None,
            'is_vtrip': False,
            'office_id': '8308',
            'provider': {
                'gds': 4,
                'name': 'TUA',
                'supplier': {'id': 1080, 'code': '5N', 'title': 'Смартавиа'},
            },
            'price': {'RUB': {'fare': 240, 'fee': 0, 'taxes': 200, 'amount': 440}},
            'extra_baggage': [],
            'segments': [
                {
                    'arrival': {
                        'date': '26.06.2022',
                        'time': '13:40',
                        'datetime': '26.06.2022 13:40:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1656240000,
                        'terminal': '1',
                        'airport': {
                            'id': 80431, 'title': 'Пулково',
                            'short_title': '',
                            'code': 'LED',
                        },
                        'city': {'id': 7069620, 'code': 'LED', 'title': 'Санкт-Петербург'},
                        'region': {'id': None, 'code': None, 'title': None},
                        'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                    },
                    'departure': {
                        'date': '26.06.2022',
                        'time': '12:00',
                        'datetime': '26.06.2022 12:00:00',
                        'timezone': 'Europe/Moscow',
                        'timezone_offset': '3',
                        'timestamp': 1656234000,
                        'terminal': '',
                        'airport': {
                            'id': 80750,
                            'title': 'Домодедово',
                            'short_title': '',
                            'code': 'DME',
                        },
                        'city': {'id': 64192, 'code': 'MOW', 'title': 'Москва'},
                        'region': {'id': None, 'code': None, 'title': None},
                        'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                    },
                    'seats': 9,
                    'flight_number': '295',
                    'direction': 0,
                    'duration': {'flight': {'common': 100, 'hour': 1, 'minute': 40}},
                    'route_duration': 110,
                    'is_baggage': True,
                    'baggage': {'piece': 0, 'weight': None},
                    'comment': 'this is a comment',
                    'cbaggage': {'piece': 1, 'weight': 10, 'dimensions': None},
                    'is_refund': False,
                    'is_change': True,
                    'class': {'type_id': 1, 'name': 'E', 'service': 'R'},
                    'is_first': True,
                    'is_last': True,
                    'fare_code': 'RLTOW',
                    'carrier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                    'aircraft': {'code': '738', 'title': 'Boeing 737-800'},
                    'stops': [],
                    'provider': {
                        'gds': 4,
                        'name': 'TUA',
                        'supplier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                    },
                    'type': 'regular',
                    'trip_id': None,
                },
            ],
            'segments_direction': [[0]],
            'pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
            'discount_rule': None,
            'booking_with_partial_data_allowed': False,
            'booking_actualization_from_gds_allowed': True,
            'discount': None,
            'online_registration': {
                'price': 600,
                'is_available': True,
            }
        },
    ],
    'travel_policy': {
        'some_id': {'is_violated': False, 'notices': [], 'reason_codes': []},
    },
    'total': 265,
    'offset': 0,
    'limit': 20,
    'is_completed': True,
    'post_filter_values': {
        'carriers': [
            {'code': '5N', 'name': 'Smartavia'},
            {'code': '4G', 'name': 'Gazprom Avia'},
        ],
        'from': [
            {'code': 'DME', 'name': 'Домодедово'},
            {'code': 'LED', 'name': 'Пулково'},
        ],
    },
}

avia_moscow = {
    'name': 'Москва',
    'iata': 'MOW',
    'country': {'name': 'Россия', 'iata': 'RU'},
    'city': {'name': 'Москва', 'iata': 'MOW'},
    'region': '---',
}

avia_spb = {
    'name': 'Санкт-Петербург, Пулково',
    'iata': 'LED',
    'country': {'name': 'Россия', 'iata': 'RU'},
    'city': {'name': 'Санкт-Петербург', 'iata': 'LED'},
    'region': '---',
}

TEST_AVIA_DETAIL_RESPONSE = {
    'search': {
        'adt': 1,
        'channel': '04T40000',
        'chd': 0,
        'class': 'E',
        'inf': 0,
        'partner': '04T4',
        'segments': [
            {
                'from': avia_moscow,
                'to': avia_spb,
                'date': '02.07.2022',
            },
            {
                'from': avia_spb,
                'to': avia_moscow,
                'date': '07.07.2022',
            },
        ],
        'airlines': [],
        'src': 0,
        'token': '04T40000RTE1000010090MOWLED20220702LEDMOW20220707',
        'type': 'rt',
        'yth': 0,
        'is_direct_only': False,
        'is_inner_flight': True,
    },
    'flight': {
        'id': 'SOME.FLIGHT.ID',
        'rid': 'SOME.RID',
        'tariff_type': None,
        'fare_family_type': 'SMARTLIGHT',
        'fare_family_flag': True,
        'segments_count': 2,
        'type': 'regular',
        'is_inner_flight': True,
        'is_baggage': True,
        'is_refund': False,
        'is_subsidized': False,
        'citizenships': None,
        'is_vtrip': False,
        'office_id': '8308',
        'provider': {
            'gds': 4,
            'name': 'TUA',
            'supplier': {'id': 1080, 'code': '5N', 'title': 'Смартавиа'},
        },
        'price': {'RUB': {'fare': 240, 'fee': 0, 'taxes': 200, 'amount': 440}},
        'extra_baggage': [],
        'segments': [
            {
                'arrival': {
                    'date': '02.07.2022',
                    'time': '13:40',
                    'datetime': '02.07.2022 13:40:00',
                    'timezone': 'Europe/Moscow',
                    'timezone_offset': '3',
                    'timestamp': 1656758400,
                    'terminal': '1',
                    'airport': {
                        'id': 80431,
                        'title': 'Пулково',
                        'short_title': '',
                        'code': 'LED',
                    },
                    'city': {'id': 7069620, 'code': 'LED', 'title': 'Санкт-Петербург'},
                    'region': {'id': None, 'code': None, 'title': None},
                    'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                },
                'departure': {
                    'date': '02.07.2022',
                    'time': '12:00',
                    'datetime': '02.07.2022 12:00:00',
                    'timezone': 'Europe/Moscow',
                    'timezone_offset': '3',
                    'timestamp': 1656752400,
                    'terminal': '',
                    'airport': {
                        'id': 80750,
                        'title': 'Домодедово',
                        'short_title': '',
                        'code': 'DME',
                    },
                    'city': {'id': 64192, 'code': 'MOW', 'title': 'Москва'},
                    'region': {'id': None, 'code': None, 'title': None},
                    'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                },
                'seats': 9,
                'flight_number': '295',
                'direction': 0,
                'duration': {'flight': {'common': 100, 'hour': 1, 'minute': 40}},
                'route_duration': 100,
                'is_baggage': True,
                'baggage': {'piece': 0, 'weight': None},
                'comment': 'this is a comment',
                'cbaggage': {'piece': 1, 'weight': 10, 'dimensions': None},
                'is_refund': False,
                'is_change': True,
                'class': {'type_id': 1, 'name': 'E', 'service': 'R'},
                'is_first': True,
                'is_last': True,
                'fare_code': 'RLTOW',
                'carrier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                'aircraft': {'code': '738', 'title': 'Boeing 737-800'},
                'stops': [],
                'provider': {
                    'gds': 4,
                    'name': 'TUA',
                    'supplier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                },
                'type': 'regular',
                'trip_id': None,
            },
            {
                'arrival': {
                    'date': '07.07.2022',
                    'time': '16:20',
                    'datetime': '07.07.2022 16:20:00',
                    'timezone': 'Europe/Moscow',
                    'timezone_offset': '3',
                    'timestamp': 1657200000,
                    'terminal': '',
                    'airport': {
                        'id': 80750,
                        'title': 'Домодедово',
                        'short_title': '',
                        'code': 'DME',
                    },
                    'city': {'id': 64192, 'code': 'MOW', 'title': 'Москва'},
                    'region': {'id': None, 'code': None, 'title': None},
                    'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                },
                'departure': {
                    'date': '07.07.2022',
                    'time': '14:40',
                    'datetime': '07.07.2022 14:40:00',
                    'timezone': 'Europe/Moscow',
                    'timezone_offset': '3',
                    'timestamp': 1657194000,
                    'terminal': '1',
                    'airport': {
                        'id': 80431,
                        'title': 'Пулково',
                        'short_title': '',
                        'code': 'LED',
                    },
                    'city': {'id': 7069620, 'code': 'LED', 'title': 'Санкт-Петербург'},
                    'region': {'id': None, 'code': None, 'title': None},
                    'country': {'id': 191, 'code': 'RU', 'title': 'Россия'},
                },
                'seats': 9,
                'flight_number': '296',
                'direction': 1,
                'duration': {'flight': {'common': 100, 'hour': 1, 'minute': 40}},
                'route_duration': 100,
                'is_baggage': False,
                'baggage': {'piece': 0, 'weight': None},
                'comment': 'this is some other comment',
                'cbaggage': {'piece': 0, 'weight': None, 'dimensions': None},
                'is_refund': False,
                'is_change': True,
                'class': {'type_id': 1, 'name': 'E', 'service': 'R'},
                'is_first': True,
                'is_last': True,
                'fare_code': 'RLTOW',
                'carrier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                'aircraft': {'code': '738', 'title': 'Boeing 737-800'},
                'stops': [],
                'provider': {
                    'gds': 4,
                    'name': 'TUA',
                    'supplier': {'id': 1080, 'title': 'Smartavia', 'code': '5N'},
                },
                'type': 'regular',
                'trip_id': None,
            },
        ],
        'segments_direction': [[0], [1]],
        'pricer_info': {'RUB': {'aac_fee': 0, 'provider_fee': 0}},
        'discount_rule': None,
        'booking_with_partial_data_allowed': False,
        'booking_actualization_from_gds_allowed': True,
        'discount': None,
        'online_registration': {'price': 600, 'is_available': True},
    },
    'products': {
        'insurances': {
            'rules': [],
            'currency_rates': {'EUR': '55.964', 'UAH': '1.80589', 'USD': '53.3234'},
            'auto_select': False,
        },
    },
    'travel_policy': None,
    'available_documents': {
        'chd': {'ru': ['B', 'P'], 'other': ['A']},
        'inf': {'ru': ['B', 'P'], 'other': ['A']},
        'teen': {'ru': ['B', 'P'], 'other': ['A']},
        'adt': {'ru': ['C', 'P', 'M', 'S'], 'other': ['A']},
        'src': {'ru': ['C', 'P']},
        'yth': {'ru': ['C', 'P']},
    },
}
