# -*- coding: utf-8 -*-


VALID_INN_10 = 7879679858
VALID_INN_12 = 583500693804

person_validator_spendable_mandatory_fields_map = {
    'ph': {
        'type': 'ph',  # Русский физик
        'is_partner': '1',  # получает деньги
        'fname': 'Элеонора',  # Имя
        'lname': 'Елисеева',  # Фамилия
        'mname': 'Батьковна',  # Отчество, пока обязательно
        'email': 'example@yandex-team.ru',
        'phone': '+7 812 9164191',
        'birthday': '1987-01-09 ',  # Дата рождения
        'passport_code': '123-456',  # Код подразделения
        'passport_d': '1997-09-23',  # Когда выдан
        'passport_e': 'ОВД Замоскворечье',  # Кем выдан
        'passport_n': '123456',  # Паспорт номер
        'passport_s': '7777',  # Паспорт серия
        'passport_birthplace': 'г. Москва',  # Место рождения
        'legaladdress': 'г. Москва, ул. Строителей д.9',  # Прописка
        'country_id': '225',  # Резиденство (Россия по геобазе)
        'city': 'г. Москва',  # Адрес доставки документов - город
        'street': 'ул. Льва Толстого',  # Адрес доставки документов - улица
        'postcode': '456010',  # Адрес доставки документов - индекс
        'postsuffix': 'дом 10',  # Адрес доставки документов - дом
        'inn': '784149383059',  # ИНН
        'pfr': '366-255-894 18',  # ПФР
        'bank_type': '1',  # Тип банка 1 = сбербанк
        'person_account': '12345',  # Номер счета
        # 'bank_inn': '3358359869',  # ИНН Банка
        # 'bik': '044525225',  # БИК банка
        # 'payment_purpose': 'Перевод по договору, НДС не облагается'  # Добавочное назначение платежа
    }}

mandatory_fields_map = {
    'ur': {"postaddress": u"а/я Кладр 0",
           "email": "m-SC@qCWF.rKU",
           "longname": u"000 WBXG",
           "legaladdress": "Avenue 5",
           "inn": "7879679858",
           "postcode": "191025",
           "kpp": "767726208",
           "phone": "+7 812 3990776",
           "name": u"Юр. лицо или ПБОЮЛqdZd",
           "country_id": "225",
           "legal_address_postcode": "666666"
           },
    'ph': {"fname": "Test1",  # Физ.лицо РФ
           "lname": "Test2",
           "mname": "Test3",
           "phone": "+7 905 1234567",
           "email": "testagpi2@yandex.ru",
           },
    'yt': {"email": "xTW9@fOJz.XcJ",
           "phone": "+7 812 5389048",
           "address": u"Улица 4",
           "name": "YT_MTL",
           },
    'ytph': {"fname": "Test1",  # Физ.лицо-нерезидент РФ
             "lname": "Test2",
             "phone": "+7 905 1234567",
             "email": "testagpi2@yandex.ru"
             },
    'yt_kzu': {"name": "Python yt_kzu",  # нерезиденты казахстан ЮЛ
               "iik": "KZ838560000000463517",
               "bik": "kzkzkzk",
               "phone": "+7 905 1234567",
               "email": "test-balance-notify@yandex-team.ru",
               "city": "citygKZ",
               "postaddress": "Py_Street 5",
               "kz-in": "892849352919",
               },
    'yt_kzp': {"lname": u"Жапбасбай",  # нерезиденты казахстан ФЛ
               "fname": u"Бекет",
               "email": "usp@email.com",
               "phone": "+1 650 5173548",
               "postaddress": "Py_Street 5",
               "city": "py_city",
               "kz-in": "892849352919",
               },
    'kzp': {"lname": u"Жапбасбай",
            "fname": u"Бекет",
            "email": "usp@email.com",
            "phone": "+1 650 5173548",
            "postaddress": "Py_Street 5",
            "city": "py_city",
            "kz-in": "892849352919",
            },
    'kzu': {"name": "KZ firm",
            "phone": "+7 727 1732223",
            "email": "usp@email.kz",
            "city": "py_city",
            "postaddress": "Py_Street 5",
            "bik": "kzkzkzkz",
            "iik": "KZ838560000000463517",
            "kz-in": "892849352919",
            "kbe": '18',
            },
    'usp': {"lname": "MTL Doh",
            "fname": "MTL John",
            "email": "usp@email.com",
            "phone": "+1 650 5173548",
            "postaddress": "Py_Street 5",
            "city": "py_city",
            "postcode": "98411",
            "us-state": "CA",
            },
    'usu': {"name": "MTL John",
            "phone": "+1 650 5173548",
            "email": "usp@email.com",
            "postaddress": "Py_Street 5",
            "city": "py_city",
            "us-state": "CA",
            "postcode": "98411"
            },
    'byp': {"fname": "Test1",
            "lname": "Test2",
            "mname": "Test3",
            "phone": "+1 650 5173548",
            "email": "usp@email.com",
            "organization": "Yandex",
            'postcode': "323",
            'city': 'vvv',
            'postaddress': '12323'
            },
    'byu': {"name": "LTD, Belarus",
            "longname": "Long LTD BELARUS",
            "city": "city Kdt",
            "email": "E'Na@EsKd.FxY",
            "phone": "+41 32 5617074",
            "inn": "339293",
            "postcode": "81070",
            "legaladdress": "Avenue 4",
            "postaddress": "Street 4",
            },
    'by_ytph': {"fname": "Test1",
                "lname": "Test2",
                "phone": "+375 29 0601336",
                "email": "E'Na@EsKd.FxY",
                "city": "city Kdt",
                "postaddress": "Py_Street 5",
                },
    'eu_yt': {"email": "0^$-@rNcG.QdG",
              "phone": "+41 32 2304106",
              "postcode": "43857",
              "postaddress": u"Улица 5",
              "name": u"Test BV !",
              },
    'sw_ph': {"fname": "MTL_sw_ph",
              "email": "P!iY@DMII.umZ",
              "lname": "Individual, SwitzerlandPide",
              "phone": "+41 32 1020210",
              },
    'sw_ytph': {"fname": "MTL_sw_ytph",
                "email": "Hc`F@lmsS.Sta",
                "lname": u"Физ. лицо-нерезидент, Швейцарияzbey",
                "phone": "+41 32 9126742",
                },
    'hk_ytph': {"fname": "Test",
                "email": "1@1.com",
                "lname": u"Физ. лицо-нерезидент, Гонконг",
                "phone": "+41 32 4567890",
                },
    'sw_ur': {"email": "E'Na@EsKd.FxY",
              "phone": "+41 32 5617074",
              "postcode": "81070",
              "postaddress": "Street 4",
              "name": "Legal entity, SwitzerlandRpo",
              },
    'sw_yt': {"email": "0^$-@rNcG.QdG",
              "phone": "+41 32 2304106",
              "postcode": "43857",
              "postaddress": u"Улица 5",
              "name": u"Нерезидент, ШвейцарияAMY"},
    'de_ur': {"email": "E'Na@EsKd.FxY",
              "phone": "+41 32 5617074",
              "postaddress": "Street 4",
              "name": "Legal entity, GermanyRpo",
              "longname": "Long Legal entity, GermanyRpo",
              "inn": "111111111",
              "country-id": '96',
              "legaladdress": "Putina street 666",
              },
    'de_ph': {"fname": "MTL_sw_ph",
              "email": "P!iY@DMII.umZ",
              "lname": "Individual, SwitzerlandPide",
              "phone": "+41 32 1020210",
              'country-id': '96',
              },
    'de_yt': {"email": "0^$-@rNcG.QdG",
              "phone": "+41 32 2304106",
              "postcode": "43857",
              "postaddress": u"Улица 5",
              "name": u"Нерезидент, ГерманияAMY"},
    'de_ytph': {"fname": "MTL_de_ytph",
                "email": "Hc`F@lmsS.Sta",
                "lname": u"Физ. лицо-нерезидент, Германияzbey",
                "phone": "+41 32 9126742",
                },
    # 'trp': {"fname": "Test1",  # ФЛ Турция
    #         "lname": "Test2",
    #         "email": "testagpi2@yandex.ru",
    #         "phone": "+90 537 565810",
    #         },
    # 'tru': {"name": "LTD TurName",  # ЮЛ Турция
    #         "inn": "99999",
    #         "email": "testagpi2@yandex.ru",
    #         "phone": "+90 537 851753",
    #         "postcode": "12345",
    #         "postaddress": "Tur addr",
    #         },
    'am_jp': {"name": "am_jp_name",  # ЮЛ Армения
              "postaddress": "ARM addr",
              "longname": "am_jp_name_longname",
              "legaladdress": "am_jp_name_legaladdress",
              "phone": "+90 537 851753",
              "inn": "999854459",
              "account": "223",
              "ben-bank": 'bank_name_am',
              "swift": "jtsbjpjt",
              "email": "testagpi2@yandex.ru",
              "postcode": "1235",
              },
    'am_np': {"fname": 'AM_fname',  # ФЛ Армения
              "lname": 'AM_lname',
              "phone": '34344',
              'email': 'reerg@erg.rr',
              "postcode": '5677',
              "city": 'Erevan',
              "postaddress": 'AM_postadress'
              },
    'az_ur': {"email": "E'Na@EsKd.FxY",
              "phone": "+41 32 5617074",
              "postcode": "81070",
              "postaddress": "Street 4",
              "name": "Legal entity, SwitzerlandRpo",
              },
    'fr_ur': {"email": "E'Na@EsKd.FxY",
              "legaladdress": "fr_ur_legaladdress",
              "postaddress": "Street 4",
              "name": "Legal entity",
              "inn": "999854459",
              },
    'kg_ur': {"email": "E'Na@EsKd.FxY",
              "legaladdress": "kg_ur_legaladdress",
              "postaddress": "Street 4",
              "name": "Legal entity",
              "inn": "999854459",
              },
    'srb_ur': {"name": "Legal entity",
               "longname": "Legal entity longname",
               "country-id": "180",
               "legaladdress": "srb_ur_legaladdress",
               "postaddress": "Street 4",
               "email": "E'Na@EsKd.FxY",
               "phone": "+7 499 6660666",
               },
    'gb_ur': {"email": "E'Na@EsKd.FxY_GB_UR",
              "legaladdress": "gb_ur_legaladdress",
              "postaddress": "Street 4 gb_ur",
              "name": "Legal entity GB_UR delit ltimed",
              "inn": "999854459",
              },
    'ur_ytkz': {"email": "0^$-@rNcG.QdG",
                "phone": "+7 499 6660666",
                "postcode": "105082",
                "postaddress": u"Улица ur_ytkz5",
                "name": u"Test ur_ytkz !",
                },
    'hk_ur': {
        "email": "E'Na@EsKd.FxY",
        "phone": "+99999999999",
        "postcode": "81070",
        "postaddress": "Street 4",
        "name": "Legal entity,Hong Kong",
    },
    'us_yt': {
        "name": "Legal entity, US non-resident",
        "phone": "+11111111111",
        "email": "E'Na@EsKd.FxY",
        "postaddress": "2 N Rotary Rd, Arlington, VA, US",
        "postcode": "22202",
    },
    'us_ytph': {
        "fname": 'us_ytph_fname',
        "lname": 'us_ytph_lname',
        "phone": '34344',
        "email": 'us_ytph@fakegmail.com',
    },
    'il_ph': {"fname": "MTL_il_ph",
              "email": "P!iY@DMII.umZ",
              "lname": "Individual, Esrail",
              "phone": "+66 32 1020210",
              },
    'cl_ur': {"email": "hola@amigO.olo",
              "legaladdress": "cl_ur_legaladdress",
              "name": "Chile Legal entity",
              "phone": "+90 537 851753",
              "inn": "77.506.936-8",
              # "account": "123123123",
              # "bik": "044525440",
              "city": "Santiago",
              # "bank": "bank_name",
              },
    'uzb_ur': {
        "email": "uzbekskii@chai.uz",
        "legaladdress": "uzb_ur_legaladdress",
        "name": "Uzbekistan Legal entity",
        "phone": "+998 66 5557535",
        "inn": "999999999",
        "city": "Samarkand",
    },
}

additional_fields_map = {
    'ur': {"delivery-type": "4",
           "bik": "044525440",
           "live-signature": "1",
           "invalid-bankprops": "0",
           "delivery-city": "NSK",
           "authority-doc-details": "g",
           "fax": "+7 812 5696286",
           "invalid-address": "1",
           "vip": "1",
           "representative": "tPLLK",
           "ogrn": "379956466494603",
           "address": u"Улица 4",
           "revise-act-period-type": "",
           "authority-doc-type": u"Свидетельство о регистрации",
           "s_signer-position-name": "President",
           "signer_person_gender": "W",
           "account": "40702810437116329435",
           "signer_person_name": "Signer RR"},

    'fr_ur': {"TVA-number": "FRXX999999999"},
    'gb_ur': {"VAT-number": "GBXX999999999"},
    'kg_ur': {"rnn-kg": "RNNKG999999999"},
}


def get_full_person_defaults(person_type):
    full_defaults = additional_fields_map[person_type]
    full_defaults.update(mandatory_fields_map[person_type])
    return full_defaults


swift_examples = {
    'too_short': 'aaaaaaa',
    'too_long': 'aaaaaaaaaaaa',
    'non_existing': 'aaaaaaaa',
    'existing': 'tecnby22',
    'empty': '',
}
