INSERT INTO {rd_nm_tmp_out} (rd_id, name, name_lo, name_ll) VALUES
(0,
 json('{"ru_RU_LOCAL": "Р-254", "ru-Latn_RU_LOCAL": "R-254 Irtysh"}'),
 'Р-254 Иртыш',
 'Р-254'),
(1,
 json('{"en_FR": "Blvd Saint-Germain", "fr_FR": "Boulevard Saint-Germain", "ru_FR": "бульв. Сен-Жермен"}'),
 null,
 null),
(2,
 json('{"en_US": "7th St"}'),
 null,
 null),
(3,
 json('{"en_UK": "Fore St Ave"}'),
 null,
 null),
-- Skip by article tests
(4,
 json('{"en_NZ": "The Avenue"}'),
 null,
 null),
(5,
 json('{"en_NZ": "7th The Avenue"}'),
 null,
 null),
(6,
 json('{"en_NZ": "the Avenue"}'),
 null,
 null),
(7,
 json('{"en_NZ": "Hythe Ave"}'),
 null,
 null),
(8,
 json('{"ru_RU": "улица Зеленая аллея"}'),
 null,
 null);
