package ru.yandex.market.test.allure

class Functionality {

    companion object {

        const val APP_GRAPH = "Граф зависимостей приложения"
        const val IDENTIFIERS = "Идентификаторы"
        const val KM = "КМ"
        const val CART = "Корзина"
        const val SEARCH_RESULT = "Выдача"
        const val MY_ORDERS = "Мои заказы"
        const val ORDER_CHANGE_FIO = "Изменение ФИО"
        const val CATALOG = "Каталог"
        const val PROMO = "Морда"
        const val CHECKOUT = "Чекаут"
        const val RATE_ME = "RateMe"
        const val WISHLIST = "Вишлист"
        const val ANALOGS = "Аналоги"
        const val SEARCH_REQUEST = "Поиск"
        const val SMART_COINS = "Беру Бонусы"
        const val DEEPLINKS = "Deeplinks"
        const val CHARACTERISTICS = "Характеристики"
        const val REVIEWS_PAGE = "Страница отзывов"
        const val CATEGORY_RESULT = "Категорийная выдача"
        const val PRICE_DROP = "Скидки Price Drop"
        const val UPDATING = "Обновление"
        const val REGION = "Регион"
        const val PROFILE = "Личный кабинет"
        const val PROFILE_FUN = "Профиль"
        const val ORDER_CHANGE_DELIVERY_DATE = "Изменение даты доставки"
        const val PROBLEM_REPORT = "Сообщение о проблеме"
        const val LOYALTY_DEGRADATION = "Деградация лоялти"
        const val ORDER_CHANGE_PAYMENT_METHOD = "Изменение предоплаты"
        const val TABS = "Табы"
        const val EFIM = "ЕФИМ"
        const val COMPARISON = "Сравнение"
        const val CASHBACK = "Кэшбэк"
        const val RECENT_PURCHASE = "Ранее купленные товары"
        const val DSBS = "DSBS"
        const val STORIES = "Сториз"
        const val REFERRAL_PROGRAM = "Реферальная программа"
        const val ORDER_SUCCESS = "Спасибо за заказ"
        const val REVIEW_SUCCESS = "Спасибо за отзыв"
        const val EXPRESS_DELIVERY = "Экспресс-доставка"
        const val EXPERIMENTS = "Эксперименты"
        const val LAVKET = "Лавка на Маркете"
        const val RETAIL = "Еда на Маркете"
        const val GROWING_CASHBACK = "Растуищй кэшбэк"
        const val MULTILANDING = "Мультилендинг"
        const val FITTING = "Примерка"
    }
}
