// Code generated by mockery v2.13.1. DO NOT EDIT.

package st

import mock "github.com/stretchr/testify/mock"

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// CreateTicket provides a mock function with given fields: summary, description
func (_m *IClient) CreateTicket(summary string, description string) (string, error) {
	ret := _m.Called(summary, description)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(summary, description)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(summary, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t mockConstructorTestingTNewIClient) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
