SRCPKG = yandex-maps-grcat-config-boost-test
PKG    = $(SRCPKG)
DESC   = Generic colourizer configuration for Boost.Test output

$(PKG): DEPENDS += \
	grc \

$(PKG): FILES = \
	/usr/share/grc/conf.bt \

include /usr/share/yandex/maps/build/build.mk
