default_platform :ios

platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  desc "Runs all the tests"
  lane :test do
    cocoapods
    if is_ci
      scan(skip_slack: false)
    else
      scan
    end
  end

  error do |lane, exception|
    if is_ci
      slack(
        message: exception.message,
        success: false
      )
    end
  end

end
