import {HermionePerformCommand} from '@yandex-int/tests-to-testpalm/out/types/hermione';

/* eslint-disable @typescript-eslint/no-unused-vars */
import addStyles from '../commands/add-styles';
import checkStandError from '../commands/check-stand-error';
import openPage from '../commands/open-page';
import openWebview from '../commands/open-webview';
import scrollIntoView from '../commands/scroll-into-view';
import waitAndClick from '../commands/wait-and-click';
import waitAndDoubleClick from '../commands/wait-and-double-click';
import waitForUrlContains from '../commands/wait-for-url-contains';
import simulateClick from '../commands/simulate-click';
import simulateDoubleClick from '../commands/simulate-double-click';
import simulateGeoClick from '../commands/simulate-geo-click';
import simulateGeoHover from '../commands/simulate-geo-hover';
import simulateGeoDrag from '../commands/simulate-geo-drag';
import logout from '../commands/logout';
import getMapCenter from '../commands/get-map-center';
import setValueToInput from '../commands/set-value-to-input';
import getViewportVisibility from '../commands/get-viewport-visibility';
import verifyRequestId from '../commands/verify-request-id';
import dragPointer from '../commands/drag-pointer';
import movePointer from '../commands/move-pointer';
import openYMaps3 from '../commands/open-y-maps3';
import openMetroPage from '../commands/open-metro-page';
import openMapWidgetPage from '../commands/open-map-widget-page';
import openPageWithCustomViewport from '../commands/open-page-with-custom-viewport';
import openCustomMobilePage from '../commands/open-custom-mobile-page';
import verifyAttribute from '../commands/verify-attribute';
import verifyTitle from '../commands/verify-title';
import waitAndClickInCenter from '../commands/wait-and-click-in-center';
import waitAndClickPlacemark from '../commands/wait-and-click-placemark';
import waitAndHover from '../commands/wait-and-hover';
import verifyLdJson from '../commands/verify-ld-json';
import verifyMetroSnippetTimeEqualWithDetails from '../commands/verify-metro-snippet-time-equal-with-details';
import waitAndVerifyLink from '../commands/wait-and-verify-link';
import waitAndVerifyScreenshot from '../commands/wait-and-verify-screenshot';
import waitAndVerifyMapScreenshot from '../commands/wait-and-verify-map-screenshot';
import waitAndVerifyPanoramaScreenshot from '../commands/wait-and-verify-panorama-screenshot';
import waitForViewportVisibility from '../commands/wait-for-viewport-visibility';
import waitForLoadedAdvert from '../commands/wait-for-loaded-advert';
import waitForHiddenAdvert from '../commands/wait-for-hidden-advert';
import waitForVisibleAdvert from '../commands/wait-for-visible-advert';
import waitForExist from '../commands/wait-for-exist';
import waitForVisible from '../commands/wait-for-visible';
import waitForHidden from '../commands/wait-for-hidden';
import waitForNotAppear from '../commands/wait-for-not-appear';
import submitSearch from '../commands/submit-search';
import verifyUrl from '../commands/verify-url';
import tap from '../commands/tap';
import clickInMap from '../commands/click-in-map';
import dragPointerFromCenter from '../commands/drag-pointer-from-center';
import getLocalStorage from '../commands/get-local-storage';
import setLocalStorage from '../commands/set-local-storage';
import clearLocalStorage from '../commands/clear-local-storage';
import waitAndCheckValue from '../commands/wait-and-check-value';
import waitForElementsCount from '../commands/wait-for-elements-count';
import retrieveLogs from '../commands/retrieve-logs';
import getMapGeoOptions from '../commands/get-map-geo-options';
import swipeShutter from '../commands/swipe-shutter';
import uploadImage from '../commands/upload-image';
import waitAndDragAndDrop from '../commands/wait-and-drag-and-drop';
import addClass from '../commands/add-class';
import zoom from '../commands/zoom';
import longtapMap from '../commands/longtap-map';
import getElementCenter from '../commands/get-element-center';
import checkMapState from '../commands/check-map-state';
import setRequestListener from '../commands/set-request-listener';
import setResponseListener from '../commands/set-response-listener';
import addWebviewApi from '../commands/add-webview-api';
import waitForMapTilted from '../commands/wait-for-map-tilted';
import waitForMapNotTilted from '../commands/wait-for-map-not-tilted';
import waitForMapRotated from '../commands/wait-for-map-rotated';
import waitForMapNotRotated from '../commands/wait-for-map-not-rotated';
import twoFingersSwipe from '../commands/two-fingers-swipe';
import twoFingersMapRotate from '../commands/two-fingers-map-rotate';
import crashWebgl from '../commands/crash-webgl';
import checkTileState from '../commands/check-tile-state';
import checkCameraState from '../commands/check-camera-state';

declare global {
    namespace WebdriverIO {
        interface Browser {
            addStyles: typeof addStyles;
            checkStandError: typeof checkStandError;
            openPage: typeof openPage;
            openWebview: typeof openWebview;
            scrollIntoView: typeof scrollIntoView;
            waitAndClick: typeof waitAndClick;
            waitAndDoubleClick: typeof waitAndDoubleClick;
            waitForUrlContains: typeof waitForUrlContains;
            simulateClick: typeof simulateClick;
            simulateDoubleClick: typeof simulateDoubleClick;
            simulateGeoClick: typeof simulateGeoClick;
            simulateGeoHover: typeof simulateGeoHover;
            simulateGeoDrag: typeof simulateGeoDrag;
            logout: typeof logout;
            getMapCenter: typeof getMapCenter;
            setValueToInput: typeof setValueToInput;
            getViewportVisibility: typeof getViewportVisibility;
            verifyRequestId: typeof verifyRequestId;
            dragPointer: typeof dragPointer;
            movePointer: typeof movePointer;
            openYMaps3: typeof openYMaps3;
            openMetroPage: typeof openMetroPage;
            openMapWidgetPage: typeof openMapWidgetPage;
            checkMapState: typeof checkMapState;
            openPageWithCustomViewport: typeof openPageWithCustomViewport;
            openCustomMobilePage: typeof openCustomMobilePage;
            verifyAttribute: typeof verifyAttribute;
            verifyTitle: typeof verifyTitle;
            waitAndClickInCenter: typeof waitAndClickInCenter;
            waitAndClickPlacemark: typeof waitAndClickPlacemark;
            waitAndHover: typeof waitAndHover;
            verifyLdJson: typeof verifyLdJson;
            waitAndVerifyLink: typeof waitAndVerifyLink;
            verifyMetroSnippetTimeEqualWithDetails: typeof verifyMetroSnippetTimeEqualWithDetails;
            waitAndVerifyScreenshot: typeof waitAndVerifyScreenshot;
            waitAndVerifyMapScreenshot: typeof waitAndVerifyMapScreenshot;
            waitAndVerifyPanoramaScreenshot: typeof waitAndVerifyPanoramaScreenshot;
            waitForViewportVisibility: typeof waitForViewportVisibility;
            waitForLoadedAdvert: typeof waitForLoadedAdvert;
            waitForHiddenAdvert: typeof waitForHiddenAdvert;
            waitForVisibleAdvert: typeof waitForVisibleAdvert;
            waitForExist: typeof waitForExist;
            waitForVisible: typeof waitForVisible;
            waitForHidden: typeof waitForHidden;
            waitForNotAppear: typeof waitForNotAppear;
            submitSearch: typeof submitSearch;
            verifyUrl: typeof verifyUrl;
            tap: typeof tap;
            clickInMap: typeof clickInMap;
            perform: HermionePerformCommand;
            dragPointerFromCenter: typeof dragPointerFromCenter;
            getLocalStorage: typeof getLocalStorage;
            setLocalStorage: typeof setLocalStorage;
            clearLocalStorage: typeof clearLocalStorage;
            waitAndCheckValue: typeof waitAndCheckValue;
            waitForElementsCount: typeof waitForElementsCount;
            retrieveLogs: typeof retrieveLogs;
            getMapGeoOptions: typeof getMapGeoOptions;
            swipeShutter: typeof swipeShutter;
            uploadImage: typeof uploadImage;
            waitAndDragAndDrop: typeof waitAndDragAndDrop;
            addClass: typeof addClass;
            zoom: typeof zoom;
            longtapMap: typeof longtapMap;
            getElementCenter: typeof getElementCenter;
            setRequestListener: typeof setRequestListener;
            setResponseListener: typeof setResponseListener;
            addWebviewApi: typeof addWebviewApi;
            waitForMapTilted: typeof waitForMapTilted;
            waitForMapNotTilted: typeof waitForMapNotTilted;
            waitForMapRotated: typeof waitForMapRotated;
            waitForMapNotRotated: typeof waitForMapNotRotated;
            twoFingersSwipe: typeof twoFingersSwipe;
            twoFingersMapRotate: typeof twoFingersMapRotate;
            crashWebgl: typeof crashWebgl;
            checkTileState: typeof checkTileState;
            checkCameraState: typeof checkCameraState;
        }
    }
}
