// Code generated by mockery v2.14.0. DO NOT EDIT.

package cms

import mock "github.com/stretchr/testify/mock"

// IClient is an autogenerated mock type for the IClient type
type IClient struct {
	mock.Mock
}

// Disable provides a mock function with given fields: layer, dc
func (_m *IClient) Disable(layer string, dc string) error {
	ret := _m.Called(layer, dc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(layer, dc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Enable provides a mock function with given fields: layer, dc
func (_m *IClient) Enable(layer string, dc string) error {
	ret := _m.Called(layer, dc)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(layer, dc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewIClient creates a new instance of IClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIClient(t mockConstructorTestingTNewIClient) *IClient {
	mock := &IClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
